.TH "app Directory Reference" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.c\fP"
.br
.ti -1c
.RI "file \fBinterface\&.c\fP"
.br
.ti -1c
.RI "file \fBnetconfig\&.c\fP"
.br
.ti -1c
.RI "file \fBpbxconfig\&.c\fP"
.br
.ti -1c
.RI "file \fBprivate\&.h\fP"
.br
.ti -1c
.RI "file \fBtesting\&.c\fP"
.br
.ti -1c
.RI "file \fBtoolbar\&.cpp\fP"
.br
.ti -1c
.RI "file \fBwizard\&.c\fP"
.br
.RI "\fIWizard Interface\&. \fP"
.ti -1c
.RI "file \fBwxforms\&.c\fP"
.br
.RI "\fIMain application file\&. \fP"
.in -1c
