.TH "src Directory Reference" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinclude\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcxxapi\&.cpp\fP"
.br
.RI "\fIC++ Functions exported to C API\&. \fP"
.ti -1c
.RI "file \fBDTSApp\&.cpp\fP"
.br
.RI "\fICore Application Class implementation\&. \fP"
.ti -1c
.RI "file \fBDTSFrame\&.cpp\fP"
.br
.RI "\fICore application frame class\&. \fP"
.ti -1c
.RI "file \fBDTSListView\&.cpp\fP"
.br
.RI "\fIData Store/View/Control model for tree window\&. \fP"
.ti -1c
.RI "file \fBDTSPanel\&.cpp\fP"
.br
.RI "\fIImplementation of core panel classes and event handler\&. \fP"
.ti -1c
.RI "file \fBDTSTreeWindow\&.cpp\fP"
.br
.RI "\fIImplementation of Tree and Tab view and event handlers\&. \fP"
.ti -1c
.RI "file \fBDTSWizard\&.cpp\fP"
.br
.RI "\fIImplementation of wizard classes\&. \fP"
.ti -1c
.RI "file \fBDTSXMLComboBox\&.cpp\fP"
.br
.RI "\fICombo box that populates list from the XML returned in XML Post\&. \fP"
.ti -1c
.RI "file \fBevdata\&.cpp\fP"
.br
.RI "\fIImplementation of panel event classes\&. \fP"
.ti -1c
.RI "file \fBpitems\&.cpp\fP"
.br
.RI "\fIImplementation of Panel Items\&. \fP"
.ti -1c
.RI "file \fBwrapper\&.cpp\fP"
.br
.RI "\fIWrapper functions exported to C to allow interfacing with C++\&. \fP"
.in -1c
