.TH "app_data" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app_data \- 
.PP
Application data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct xml_doc * \fBxmldoc\fP"
.br
.RI "\fIXML Document been edited\&. \fP"
.ti -1c
.RI "const char * \fBdatadir\fP"
.br
.RI "\fIShared datadir\&. \fP"
.ti -1c
.RI "const char * \fBopenconf\fP"
.br
.RI "\fIActive configuration\&. \fP"
.ti -1c
.RI "\fBdtsgui_menuitem\fP \fBn_wiz\fP"
.br
.RI "\fINew system configuration menu item\&. \fP"
.ti -1c
.RI "\fBdtsgui_menuitem\fP \fBe_wiz\fP"
.br
.RI "\fIExisting system configuration menu item\&. \fP"
.ti -1c
.RI "\fBdtsgui_menuitem\fP \fBc_open\fP"
.br
.RI "\fIOpen configuration menu item\&. \fP"
.ti -1c
.RI "\fBdtsgui_menu\fP \fBcfg_menu\fP"
.br
.RI "\fIConfiguration menu\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Application data structure\&. 
.PP
Definition at line 69 of file private\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBdtsgui_menuitem\fP app_data::c_open"

.PP
Open configuration menu item\&. 
.PP
Definition at line 81 of file private\&.h\&.
.PP
Referenced by file_menu(), open_config(), and save_config()\&.
.SS "\fBdtsgui_menu\fP app_data::cfg_menu"

.PP
Configuration menu\&. 
.PP
Definition at line 83 of file private\&.h\&.
.PP
Referenced by config_menu(), open_config(), and save_config()\&.
.SS "const char* app_data::datadir"

.PP
Shared datadir\&. 
.PP
Definition at line 73 of file private\&.h\&.
.PP
Referenced by export_config(), free_appdata(), main(), newsys_wizard(), and view_config_conf()\&.
.SS "\fBdtsgui_menuitem\fP app_data::e_wiz"

.PP
Existing system configuration menu item\&. 
.PP
Definition at line 79 of file private\&.h\&.
.PP
Referenced by file_menu(), open_config(), and save_config()\&.
.SS "\fBdtsgui_menuitem\fP app_data::n_wiz"

.PP
New system configuration menu item\&. 
.PP
Definition at line 77 of file private\&.h\&.
.PP
Referenced by file_menu(), open_config(), and save_config()\&.
.SS "const char* app_data::openconf"

.PP
Active configuration\&. 
.PP
Definition at line 75 of file private\&.h\&.
.SS "struct xml_doc* app_data::xmldoc"

.PP
XML Document been edited\&. 
.PP
Definition at line 71 of file private\&.h\&.
.PP
Referenced by app_getxmldoc(), free_appdata(), open_config(), and save_config()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
