C API Wizard Interface
NAME
C API Wizard Interface -
C API Wizard Management.
Functions
struct dtsgui_wizard * DTS_C_API::dtsgui_newwizard (struct dtsgui *dtsgui, const char *title)
Create a new wizard.
dtsgui_pane DTS_C_API::dtsgui_wizard_addpage (struct dtsgui_wizard *dtswiz, const char *title, void *userdata, struct xml_doc *xmldoc)
Create a panel appended to the wizard.
int DTS_C_API::dtsgui_runwizard (struct dtsgui_wizard *dtswiz)
Run the wizard.
Detailed Description
C API Wizard Management.
Remarks:
Resources controlling and manipulating wizards in the C API.
Function Documentation
struct dtsgui_wizard* DTS_C_API::dtsgui_newwizard (struct dtsgui *dtsgui, const char *title) [read]
Create a new wizard. A wizard consists of multiple panels linked with back/next controls each panel will need to be procesed on completion.
See Also:
dtsgui_wizard
Parameters:
dtsgui Aplication data ptr.
title Title shown on title bar of wizard pop up.
Returns:
New wizard that needs pages added too and run.
Definition at line 928 of file wrapper.cpp.
References dtsgui::GetFrame().
Referenced by system_wizard().
int DTS_C_API::dtsgui_runwizard (struct dtsgui_wizard *dtswiz)
Run the wizard. Pop up the wizard window and open first page on success its required that the panels information be processed. When the wizard is un refferenced the panels are deleted.
See Also:
dtsgui_wizard::RunWizard()
Parameters:
dtswiz Wizard too run.
Returns:
non Zero on success.
Definition at line 957 of file wrapper.cpp.
References dtsgui_wizard::RunWizard().
Referenced by system_wizard().
dtsgui_pane DTS_C_API::dtsgui_wizard_addpage (struct dtsgui_wizard *dtswiz, const char *title, void *userdata, struct xml_doc *xmldoc)
Create a panel appended to the wizard. See Also:
dtsgui_wizard::AddPage()
Parameters:
dtswiz Wizard to add page too.
title Title of the new panel.
userdata Userdata to be referenced and stored on the panel.
xmldoc Optional XML Doc to be referenced and stored on the panel.
Returns:
New panel that will need to be configured and processed after completion.
Definition at line 942 of file wrapper.cpp.
References dtsgui_wizard::AddPage().
Referenced by system_wizard().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.