Progress dialog interface.
NAME
Progress dialog interface. -
Popup dialog containing a progress bar and posible cancel button.
Functions
int DTS_C_API::dtsgui_progress_start (struct dtsgui *dtsgui, const char *text, int maxval, int quit)
Initialise the progress dialog Pop up a dialog box that can be updated to showprogress with a optional cancel button.
int DTS_C_API::dtsgui_progress_update (struct dtsgui *dtsgui, int newval, const char *newtext)
Update the progress bar counter This function updates the current progress value and optionally allows setting new displayed text.
int DTS_C_API::dtsgui_progress_increment (struct dtsgui *dtsgui, int ival, const char *newtext)
Increments the counter by adding to it not setting it.
void DTS_C_API::dtsgui_progress_end (struct dtsgui *dtsgui)
Disable the progress bar.
Detailed Description
Popup dialog containing a progress bar and posible cancel button.
Todo
Allow multiple instances of progress dialog not only the single interface at present.
Function Documentation
void DTS_C_API::dtsgui_progress_end (struct dtsgui *dtsgui)
Disable the progress bar. See Also:
DTSFrame::EndProgress()
Parameters:
dtsgui Application data ptr.
Definition at line 1057 of file wrapper.cpp.
References DTSFrame::EndProgress(), and dtsgui::GetFrame().
int DTS_C_API::dtsgui_progress_increment (struct dtsgui *dtsgui, intival, const char *newtext)
Increments the counter by adding to it not setting it. See Also:
DTSFrame::IncProgress()
Parameters:
dtsgui Application data ptr.
ival Value to increment progress bar.
newtext Text displayed in the popup box.
Returns:
0 on success may fail when the user presses cancel.
Definition at line 1048 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::IncProgress().
int DTS_C_API::dtsgui_progress_start (struct dtsgui *dtsgui, const char *text, intmaxval, intquit)
Initialise the progress dialog Pop up a dialog box that can be updated to showprogress with a optional cancel button. See Also:
DTSFrame::StartProgress()
Parameters:
dtsgui Application data ptr.
text Text displayed in the popup box.
maxval the maximum expected value to update.
quit Disable the cancel button if quit is zero.
Returns:
zero on failure
Definition at line 1021 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::StartProgress().
int DTS_C_API::dtsgui_progress_update (struct dtsgui *dtsgui, intnewval, const char *newtext)
Update the progress bar counter This function updates the current progress value and optionally allows setting new displayed text. See Also:
DTSFrame::UpdateProgress()
Parameters:
dtsgui Application data ptr.
newval Update the counter with this value.
newtext Text displayed in the popup box.
Returns:
0 on success may fail when the user presses cancel.
Definition at line 1036 of file wrapper.cpp.
References dtsgui::GetFrame(), and DTSFrame::UpdateProgress().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.