C API Common Dialog Boxes
NAME
C API Common Dialog Boxes -
C API for managing user interface dialogs.
Functions
void DTS_C_API::dtsgui_alert (struct dtsgui *dtsgui, const char *text)
Alert the user and expect a confirmation.
int DTS_C_API::dtsgui_confirm (struct dtsgui *dtsgui, const char *text)
Request Yes/No Confirmation from the user.
const char * DTS_C_API::dtsgui_filesave (struct dtsgui *dtsgui, const char *title, const char *path, const char *name, const char *filter)
Open file save dialog box.
const char * DTS_C_API::dtsgui_fileopen (struct dtsgui *dtsgui, const char *title, const char *path, const char *name, const char *filter)
Open file open dialog box.
struct basic_auth * DTS_C_API::dtsgui_pwdialog (const char *user, const char *passwd, void *data)
Return basic auth reference from a password dialog box. A dialog box requesting the user name and password is presented to the user. The initial values may be supplied.
Detailed Description
C API for managing user interface dialogs.
Remarks:
Simple dialog boxes for user interfacing (Alert/Confirm/File/Password)
remark All implementations of the wxFileDialog provide a wildcard filter. Typing a filename containing wildcards (*, ?) in the filename text item, and clicking on Ok, will result in only those files matching the pattern being displayed. The wildcard may be a specification for multiple types of file with a description for each, such as:
"BMP and GIF files (*.bmp;*.gif)|*.bmp;*.gif|PNG files (*.png)|*.png"
Function Documentation
void DTS_C_API::dtsgui_alert (struct dtsgui *dtsgui, const char *text)
Alert the user and expect a confirmation. See Also:
DTSFrame::Alert()
Parameters:
dtsgui Application data ptr.
text Text to supply in the alert.
Definition at line 1093 of file wrapper.cpp.
References DTSFrame::Alert(), and dtsgui::GetFrame().
Referenced by advanced_config(), editsys_wizard(), export_config(), handle_test(), DTSAPPToolBar::HandleEvent(), newsys_wizard(), open_config(), post_items(), and view_config_conf().
int DTS_C_API::dtsgui_confirm (struct dtsgui *dtsgui, const char *text)
Request Yes/No Confirmation from the user. See Also:
DTSFrame::Confirm()
Parameters:
dtsgui Application data ptr.
text Text to supply in the alert.
Returns:
Non zero if the user affirmed.
Definition at line 1104 of file wrapper.cpp.
References DTSFrame::Confirm(), and dtsgui::GetFrame().
Referenced by system_wizard().
const char* DTS_C_API::dtsgui_fileopen (struct dtsgui *dtsgui, const char *title, const char *path, const char *name, const char *filter)
Open file open dialog box. See Also:
DTSFrame::FileDialog()
dtsgui_fileopen()
Parameters:
dtsgui Application data ptr.
title Title of the file dialog.
path Original path to open dialog in.
name Suggested name to open.
filter File namr filter.
Returns:
Reference to the filename that must be unreferenced.
Definition at line 1134 of file wrapper.cpp.
References DTSFrame::FileDialog(), and dtsgui::GetFrame().
Referenced by editsys_wizard(), and open_config().
const char* DTS_C_API::dtsgui_filesave (struct dtsgui *dtsgui, const char *title, const char *path, const char *name, const char *filter)
Open file save dialog box. See Also:
DTSFrame::FileDialog()
Parameters:
dtsgui Application data ptr.
title Title of the file dialog.
path Original path to open dialog in.
name Suggested name to save as.
filter File namr filter.
Returns:
Reference to the filename that must be unreferenced.
Definition at line 1118 of file wrapper.cpp.
References DTSFrame::FileDialog(), and dtsgui::GetFrame().
Referenced by export_config(), and system_wizard().
struct basic_auth* DTS_C_API::dtsgui_pwdialog (const char *user, const char *passwd, void *data) [read]
Return basic auth reference from a password dialog box. A dialog box requesting the user name and password is presented to the user. The initial values may be supplied. Remarks:
This function is used as a callback for CURL.
See Also:
DTSFrame::Passwd()
Parameters:
user initial username entered into the box.
passwd the initial password.
data this will always be the application data ptr.
Returns:
Basic auth reference.
Definition at line 1149 of file wrapper.cpp.
References DTSFrame::Passwd().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.