Basic Elements.
NAME
Basic Elements. -
Elements consisting Name/Value/Data.
Functions
void DTS_C_API::dtsgui_textbox (dtsgui_pane pane, const char *title, const char *name, const char *value, void *data)
Place a text element on the panel.
void DTS_C_API::dtsgui_textbox_multi (dtsgui_pane pane, const char *title, const char *name, const char *value, void *data)
Place a multi line text element on the panel.
void DTS_C_API::dtsgui_passwdbox (dtsgui_pane pane, const char *title, const char *name, const char *value, void *data)
Place a password element on the panel.
void DTS_C_API::dtsgui_checkbox (dtsgui_pane pane, const char *title, const char *name, const char *checkval, const char *uncheck, int ischecked, void *data)
Place a checkbox element on the panel.
struct form_item * DTS_C_API::dtsgui_listbox (dtsgui_pane pane, const char *title, const char *name, void *data)
Place a listbox element on the panel.
struct form_item * DTS_C_API::dtsgui_combobox (dtsgui_pane pane, const char *title, const char *name, void *data)
Place a combobox element on the panel.
Detailed Description
Elements consisting Name/Value/Data.
Note:
The data is a reference to a referenced object.
Function Documentation
void DTS_C_API::dtsgui_checkbox (dtsgui_panepane, const char *title, const char *name, const char *checkval, const char *uncheck, intischecked, void *data)
Place a checkbox element on the panel. See Also:
DTSPanel::CheckBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
checkval Value of item when checked.
uncheck Value of item when unchecked.
ischecked Set to non zero if item is initially checked.
data User data to hold a reference of.
Definition at line 1294 of file wrapper.cpp.
References DTSPanel::CheckBox(), and DTSGUI_FORM_DATA_PTR.
Referenced by network_config_dns_domain_new(), and testpanel().
                                                                                                                                                         {
    DTSPanel *p = (DTSPanel *)pane;
    p->CheckBox(title, name, ischecked, checkval, uncheck, data, DTSGUI_FORM_DATA_PTR);
}
struct form_item* DTS_C_API::dtsgui_combobox (dtsgui_panepane, const char *title, const char *name, void *data) [read]
Place a combobox element on the panel. See Also:
DTSPanel::ComboBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
data User data to hold a reference of.
Returns:
Form item that can be used to add values this must be unreferenced
Definition at line 1320 of file wrapper.cpp.
References DTSPanel::ComboBox(), and DTSGUI_FORM_DATA_PTR.
Referenced by testpanel().
                                                                                                            {
    DTSPanel *p = (DTSPanel *)pane;
    return p->ComboBox(title, name, NULL, data, DTSGUI_FORM_DATA_PTR);
}
struct form_item* DTS_C_API::dtsgui_listbox (dtsgui_panepane, const char *title, const char *name, void *data) [read]
Place a listbox element on the panel. See Also:
DTSPanel::ListBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
data User data to hold a reference of.
Returns:
Form item that can be used to add values this must be unreferenced
Definition at line 1307 of file wrapper.cpp.
References DTSGUI_FORM_DATA_PTR, and DTSPanel::ListBox().
Referenced by network_adsl_link_new(), network_newwifi(), network_tos_new(), and testpanel().
                                                                                                           {
    DTSPanel *p = (DTSPanel *)pane;
    return p->ListBox(title, name, NULL, data, DTSGUI_FORM_DATA_PTR);
}
void DTS_C_API::dtsgui_passwdbox (dtsgui_panepane, const char *title, const char *name, const char *value, void *data)
Place a password element on the panel. See Also:
DTSPanel::TextBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
value Initial value of element.
data User data to hold a reference of.
Definition at line 1279 of file wrapper.cpp.
References DTSGUI_FORM_DATA_PTR, and DTSPanel::TextBox().
                                                                                                                   {
    DTSPanel *p = (DTSPanel *)pane;
    p->TextBox(title, name, value, wxTE_PASSWORD | wxTE_PROCESS_ENTER, 1, data, DTSGUI_FORM_DATA_PTR);
}
void DTS_C_API::dtsgui_textbox (dtsgui_panepane, const char *title, const char *name, const char *value, void *data)
Place a text element on the panel. See Also:
DTSPanel::TextBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
value Initial value of element.
data User data to hold a reference of.
Definition at line 1253 of file wrapper.cpp.
References DTSGUI_FORM_DATA_PTR, and DTSPanel::TextBox().
Referenced by network_adsl_link_new(), network_adsl_user_new(), network_config_dns_domain_new(), network_config_dns_domain_server_new(), network_config_dns_host_new(), network_iface_new_pane(), network_newroute(), network_newwan(), network_newwifi(), network_tos_new(), and testpanel().
                                                                                                                 {
    DTSPanel *p = (DTSPanel *)pane;
    p->TextBox(title, name, value, wxTE_LEFT | wxTE_PROCESS_ENTER, 1, data, DTSGUI_FORM_DATA_PTR);
}
void DTS_C_API::dtsgui_textbox_multi (dtsgui_panepane, const char *title, const char *name, const char *value, void *data)
Place a multi line text element on the panel. See Also:
DTSPanel::TextBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
value Initial value of element.
data User data to hold a reference of.
Definition at line 1266 of file wrapper.cpp.
References DTSGUI_FORM_DATA_PTR, and DTSPanel::TextBox().
Referenced by testpanel().
                                                                                                                       {
    DTSPanel *p = (DTSPanel *)pane;
    p->TextBox(title, name, value, wxTE_MULTILINE, 5, data, DTSGUI_FORM_DATA_PTR);
}
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.