.TH "C API Common Dialog Boxes" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C API Common Dialog Boxes \- 
.PP
C API for managing user interface dialogs\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDTS_C_API::dtsgui_alert\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *text)"
.br
.RI "\fIAlert the user and expect a confirmation\&. \fP"
.ti -1c
.RI "int \fBDTS_C_API::dtsgui_confirm\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *text)"
.br
.RI "\fIRequest Yes/No Confirmation from the user\&. \fP"
.ti -1c
.RI "const char * \fBDTS_C_API::dtsgui_filesave\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, const char *path, const char *name, const char *filter)"
.br
.RI "\fIOpen file save dialog box\&. \fP"
.ti -1c
.RI "const char * \fBDTS_C_API::dtsgui_fileopen\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, const char *path, const char *name, const char *filter)"
.br
.RI "\fIOpen file open dialog box\&. \fP"
.ti -1c
.RI "struct basic_auth * \fBDTS_C_API::dtsgui_pwdialog\fP (const char *user, const char *passwd, void *data)"
.br
.RI "\fIReturn basic auth reference from a password dialog box\&. A dialog box requesting the user name and password is presented to the user\&. The initial values may be supplied\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
C API for managing user interface dialogs\&. 

\fBRemarks:\fP
.RS 4
Simple dialog boxes for user interfacing (Alert/Confirm/File/Password)
.RE
.PP
remark All implementations of the wxFileDialog provide a wildcard filter\&. Typing a filename containing wildcards (*, ?) in the filename text item, and clicking on Ok, will result in only those files matching the pattern being displayed\&. The wildcard may be a specification for multiple types of file with a description for each, such as: 
.PP
.nf
"BMP and GIF files (*.bmp;*.gif)|*.bmp;*.gif|PNG files (*.png)|*.png"
.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "void DTS_C_API::dtsgui_alert (struct \fBdtsgui\fP *dtsgui, const char *text)"

.PP
Alert the user and expect a confirmation\&. \fBSee Also:\fP
.RS 4
\fBDTSFrame::Alert()\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdtsgui\fP Application data ptr\&. 
.br
\fItext\fP Text to supply in the alert\&. 
.RE
.PP

.PP
Definition at line 1093 of file wrapper\&.cpp\&.
.PP
References DTSFrame::Alert(), and dtsgui::GetFrame()\&.
.PP
Referenced by advanced_config(), editsys_wizard(), export_config(), handle_test(), DTSAPPToolBar::HandleEvent(), newsys_wizard(), open_config(), post_items(), and view_config_conf()\&.
.SS "int DTS_C_API::dtsgui_confirm (struct \fBdtsgui\fP *dtsgui, const char *text)"

.PP
Request Yes/No Confirmation from the user\&. \fBSee Also:\fP
.RS 4
\fBDTSFrame::Confirm()\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdtsgui\fP Application data ptr\&. 
.br
\fItext\fP Text to supply in the alert\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Non zero if the user affirmed\&. 
.RE
.PP

.PP
Definition at line 1104 of file wrapper\&.cpp\&.
.PP
References DTSFrame::Confirm(), and dtsgui::GetFrame()\&.
.PP
Referenced by system_wizard()\&.
.SS "const char* DTS_C_API::dtsgui_fileopen (struct \fBdtsgui\fP *dtsgui, const char *title, const char *path, const char *name, const char *filter)"

.PP
Open file open dialog box\&. \fBSee Also:\fP
.RS 4
\fBDTSFrame::FileDialog()\fP 
.PP
\fBdtsgui_fileopen()\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdtsgui\fP Application data ptr\&. 
.br
\fItitle\fP Title of the file dialog\&. 
.br
\fIpath\fP Original path to open dialog in\&. 
.br
\fIname\fP Suggested name to open\&. 
.br
\fIfilter\fP File namr filter\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Reference to the filename that must be unreferenced\&. 
.RE
.PP

.PP
Definition at line 1134 of file wrapper\&.cpp\&.
.PP
References DTSFrame::FileDialog(), and dtsgui::GetFrame()\&.
.PP
Referenced by editsys_wizard(), and open_config()\&.
.SS "const char* DTS_C_API::dtsgui_filesave (struct \fBdtsgui\fP *dtsgui, const char *title, const char *path, const char *name, const char *filter)"

.PP
Open file save dialog box\&. \fBSee Also:\fP
.RS 4
\fBDTSFrame::FileDialog()\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdtsgui\fP Application data ptr\&. 
.br
\fItitle\fP Title of the file dialog\&. 
.br
\fIpath\fP Original path to open dialog in\&. 
.br
\fIname\fP Suggested name to save as\&. 
.br
\fIfilter\fP File namr filter\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Reference to the filename that must be unreferenced\&. 
.RE
.PP

.PP
Definition at line 1118 of file wrapper\&.cpp\&.
.PP
References DTSFrame::FileDialog(), and dtsgui::GetFrame()\&.
.PP
Referenced by export_config(), and system_wizard()\&.
.SS "struct basic_auth* DTS_C_API::dtsgui_pwdialog (const char *user, const char *passwd, void *data)\fC [read]\fP"

.PP
Return basic auth reference from a password dialog box\&. A dialog box requesting the user name and password is presented to the user\&. The initial values may be supplied\&. \fBRemarks:\fP
.RS 4
This function is used as a callback for CURL\&. 
.RE
.PP
\fBSee Also:\fP
.RS 4
\fBDTSFrame::Passwd()\fP 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIuser\fP initial username entered into the box\&. 
.br
\fIpasswd\fP the initial password\&. 
.br
\fIdata\fP this will always be the application data ptr\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Basic auth reference\&. 
.RE
.PP

.PP
Definition at line 1149 of file wrapper\&.cpp\&.
.PP
References DTSFrame::Passwd()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
