Tree view panel interface.
NAME
Tree view panel interface. -
A tree view is a split window with a tree in the left window and display area on right.
Functions
dtsgui_pane DTS_C_API::dtsgui_treepane (dtsgui_treeview tv, const char *name, int butmask, void *userdata, struct xml_doc *xmldoc)
Create a panel owned by the tree.
dtsgui_pane DTS_C_API::dtsgui_treepane_default (dtsgui_treeview tv, dtsgui_treenode node)
Create a panel owned by the tree configured from the specified node.
dtsgui_treenode DTS_C_API::dtsgui_treecont (dtsgui_treeview tree, dtsgui_treenode node, const char *title, int can_edit, int can_sort, int can_del, int nodeid, dtsgui_treeviewpanel_cb p_cb, void *data)
Create a container in the tree view.
dtsgui_treenode DTS_C_API::dtsgui_treeitem (dtsgui_treeview tree, dtsgui_treenode node, const char *title, int can_edit, int can_sort, int can_del, int nodeid, dtsgui_treeviewpanel_cb p_cb, void *data)
Create a item in a container in the tree view.
void DTS_C_API::dtsgui_newxmltreenode (dtsgui_treeview tree, dtsgui_pane p, dtsgui_treenode tn, const char *xpath, const char *node, const char *vitem, const char *tattr, int nid, int flags, dtsgui_xmltreenode_cb node_cb, void *data, dtsgui_treeviewpanel_cb p_cb)
Helper function to handle 'Adding' a new node from a existing node.
int DTS_C_API::dtsgui_treenodeid (dtsgui_treenode tn)
Get the node id of a tree node.
const char * DTS_C_API::dtsgui_treenodeparent (dtsgui_treenode tn)
Get the name of the nodes parent.
void DTS_C_API::dtsgui_treenodesetxml (dtsgui_treenode tn, struct xml_node *xn, const char *tattr)
Add a XML node to the tree node.
struct xml_node * DTS_C_API::dtsgui_treenodegetxml (dtsgui_treenode tn, char **buf)
Return the XML node reference held by the tree node.
void DTS_C_API::dtsgui_nodesetxml (dtsgui_treeview tree, dtsgui_treenode node, const char *newname)
Update the XML Node or title attribute with a new name.
void * DTS_C_API::dtsgui_treenodegetdata (dtsgui_treenode tn)
Get reference for the user data of node.
Detailed Description
A tree view is a split window with a tree in the left window and display area on right.
Remarks:
The tree can contain branches (folder containers) and leaf nodes each node when clicked will create and place a panel in the display area.
The tree window supports sorting and deletion via a menu displayed when right clicking.
Todo
Allow for the deletion of branch/container/folder nodes.
Function Documentation
void DTS_C_API::dtsgui_newxmltreenode (dtsgui_treeviewtree, dtsgui_panep, dtsgui_treenodetn, const char *xpath, const char *node, const char *vitem, const char *tattr, intnid, intflags, dtsgui_xmltreenode_cbnode_cb, void *data, dtsgui_treeviewpanel_cbp_cb)
Helper function to handle 'Adding' a new node from a existing node. This implements the concept of the New button a new node will be created from the data filled in on the pane this callback is attached too. A new XML node is created and the panel created from this node.
See Also:
tree_newnode_flags
Note:
this callback helper is rather complex.
Parameters:
tree Tree view the new panel will be added too.
p The panel this callback is attached too.
tn Root treenode to add too.
xpath the path of the new node.
node the name of the XML node to create in the xpath.
vitem the item in the panel to be used to create the value of the new node.
tattr the attribute to be used too create the title in the new pane.
nid Node id for newly created node.
flags Option flags combined from tree_newnode_flags.
node_cb Callback called to configure the node.
data Referenced Object passed to the callbacks.
p_cb Callback called to configure the panel when it is selected.
Returns:
Nothing is returned the callback is registered on the panel.
Definition at line 762 of file wrapper.cpp.
References tree_newnode::handle_newtreenode_cb(), and tree_newnode::tree_newnode().
Referenced by network_adsl_link_new(), network_adsl_user_new(), network_config_dns_domain_new(), network_config_dns_domain_server_new(), network_config_dns_host_new(), network_newiface(), network_newroute(), network_newwan(), network_newwifi(), and network_tos_new().
                                                                                                                         {
    class tree_newnode *nn = new tree_newnode(tree, tn, xpath, node, vitem, tattr, nid, flags, node_cb, data, p_cb);
    static_cast<DTSPanel*>(p)->SetEventCallback(&tree_newnode::handle_newtreenode_cb, nn, true);
}
void DTS_C_API::dtsgui_nodesetxml (dtsgui_treeviewtree, dtsgui_treenodenode, const char *newname)
Update the XML Node or title attribute with a new name. This helper function will update the node's XML after a edit event.
See Also:
DTSTreeWindow::UpdateNodeXML()
Parameters:
tree Treeview node is part of.
node TreeNode to update.
newname Name to update XML node with.
Definition at line 825 of file wrapper.cpp.
References DTSTreeWindow::UpdateNodeXML().
                                                                                        {
    DTSTreeWindow *tw = (DTSTreeWindow*)tree;
    tw->UpdateNodeXML(wxDataViewItem(node), newname);
}
dtsgui_treenode DTS_C_API::dtsgui_treecont (dtsgui_treeviewtree, dtsgui_treenodenode, const char *title, intcan_edit, intcan_sort, intcan_del, intnodeid, dtsgui_treeviewpanel_cbp_cb, void *data)
Create a container in the tree view. Create and insert a new folder/container in the tree view with properties / call back. A panel will be created and supplied to the callback too implement on selection.
Note:
The root node is NULL this is the initial container.
See Also:
DTSTreeWindow::AppendContainer
dtsgui_treeviewpanel_cb
Parameters:
tree The tree view to add the node too.
node The parent node or NULL to create root node.
title The label shown on the tree.
can_edit Allow editing of this node the XML node will be updated.
can_sort Allow sorting of this node the XML node will be updated.
can_del Not yet implemented for containers but will allow right click menu to delete.
nodeid A value passed to the callback as convinence can be any value -1 will cause a blank panel.
p_cb Callback to pass panel for configuration on selection of the item.
data Referenced object passed too callbacks.
Definition at line 708 of file wrapper.cpp.
References DTSDVMCtrl::AppendContainer(), and DTSTreeWindow::GetTreeCtrl().
Referenced by network_config_dns_domain_node(), and network_tree_setup().
                                                                      {
    DTSTreeWindow *tw = (DTSTreeWindow*)tree;
    return tw->GetTreeCtrl()->AppendContainer(wxDataViewItem(node), title, can_edit, can_sort, can_del, nodeid, p_cb, data).GetID();
}
dtsgui_treenode DTS_C_API::dtsgui_treeitem (dtsgui_treeviewtree, dtsgui_treenodenode, const char *title, intcan_edit, intcan_sort, intcan_del, intnodeid, dtsgui_treeviewpanel_cbp_cb, void *data)
Create a item in a container in the tree view. Create and insert a new item in the tree view in the node specified with properties / call back. A panel will be created and supplied to the callback too implement on selection.
See Also:
DTSTreeWindow::AppendItem
dtsgui_treeviewpanel_cb
Parameters:
tree The tree view to add the node too.
node The parent node or NULL to create root node.
title The label shown on the tree.
can_edit Allow editing of this node the XML node will be updated.
can_sort Allow sorting of this node the XML node will be updated.
can_del Allow right click menu to delete.
nodeid A value passed to the callback as convinence can be any value -1 will cause a blank panel.
p_cb Callback to pass panel for configuration on selection of the item.
data Referenced object passed too callbacks.
Definition at line 732 of file wrapper.cpp.
References DTSDVMCtrl::AppendItem(), and DTSTreeWindow::GetTreeCtrl().
Referenced by network_tree_setup().
                                                          {
    DTSTreeWindow *tw = (DTSTreeWindow*)tree;
    return tw->GetTreeCtrl()->AppendItem(wxDataViewItem(node), title, can_edit, can_sort, can_del, nodeid, p_cb, data).GetID();
}
void* DTS_C_API::dtsgui_treenodegetdata (dtsgui_treenodetn)
Get reference for the user data of node. See Also:
DTSDVMListStore::GetUserData()
Note:
This needs to be unreferenced.
Parameters:
tn Tree node.
Returns:
Reference to user data
Definition at line 836 of file wrapper.cpp.
References DTSDVMListStore::GetUserData().
Referenced by network_config_dns_domain_server().
                                                 {
    DTSDVMListStore *ls = (DTSDVMListStore*)tn;
    return ls->GetUserData();
}
struct xml_node* DTS_C_API::dtsgui_treenodegetxml (dtsgui_treenodetn, char **buf) [read]
Return the XML node reference held by the tree node. Returns the XML node of the node and optionally the title attribute.
Note:
The reference to the buffer and node needs to be droped.
Parameters:
tn Tree node to obtain XML node from.
buf a pointer to a buffer that will be set to the title attribute (Optional).
Returns:
Reference to the XML node stored in the tree node.
Definition at line 810 of file wrapper.cpp.
References DTSDVMListStore::GetXMLData().
Referenced by network_adsl_link(), network_adsl_user(), network_config_dns_domain(), network_config_dns_domain_server(), network_config_dns_host(), network_iface(), network_route(), network_tos(), network_wan(), and network_wifi().
                                                                       {
    DTSDVMListStore *ls = (DTSDVMListStore*)tn;
    return ls->GetXMLData(buf);
}
int DTS_C_API::dtsgui_treenodeid (dtsgui_treenodetn)
Get the node id of a tree node. See Also:
DTSDVMListStore::GetNodeID()
Parameters:
tn Tree Node to get the node of.
Returns:
the user defined tree node ID
Definition at line 775 of file wrapper.cpp.
References DTSDVMListStore::GetNodeID().
                                          {
    DTSDVMListStore *ls = (DTSDVMListStore*)tn;
    return ls->GetNodeID();
}
const char* DTS_C_API::dtsgui_treenodeparent (dtsgui_treenodetn)
Get the name of the nodes parent. See Also:
DTSDVMListStore::GetParentTitle()
Parameters:
tn Tree node
Returns:
Name og the nodes parentI
Definition at line 785 of file wrapper.cpp.
References DTSDVMListStore::GetParentTitle().
Referenced by network_config_dns_domain_server_new().
                                                      {
    DTSDVMListStore *entry = (DTSDVMListStore*)tn;
    return strdup(entry->GetParentTitle().ToUTF8());
}
void DTS_C_API::dtsgui_treenodesetxml (dtsgui_treenodetn, struct xml_node *xn, const char *tattr)
Add a XML node to the tree node. See Also:
DTSDVMListStore::SetXMLData
Parameters:
tn Tree node to set.
xn XML Node to reference.
tattr Attribute in the XN that represents the title NULL if the value is the title.
Definition at line 796 of file wrapper.cpp.
References DTSDVMListStore::SetXMLData().
Referenced by network_tree_setup().
                                                                                      {
    DTSDVMListStore *ls = (DTSDVMListStore*)tn;
    return ls->SetXMLData(xn, tattr);
}
dtsgui_pane DTS_C_API::dtsgui_treepane (dtsgui_treeviewtv, const char *name, intbutmask, void *userdata, struct xml_doc *xmldoc)
Create a panel owned by the tree. This will seldom be needed as panels are created and supplied in callbacks.
See Also:
DTSTreeWindow::CreatePane()
panel_buttons
Note:
Panels used in tree views must be created as children of the tree.
Parameters:
tv Tree view.
name Title placed on the panel top/center
butmask A mask of buttons to be placed on the panel.
userdata Referenced object available in event callbacks.
xmldoc XML doc reference used for updating XML elements.
Returns:
New Tree Pane.
Definition at line 665 of file wrapper.cpp.
References DTSTreeWindow::CreatePane().
                                                                                                                              {
    DTSTreeWindow *tw = (DTSTreeWindow*)tv;
    return tw->CreatePane(name, butmask, userdata, xmldoc);
}
dtsgui_pane DTS_C_API::dtsgui_treepane_default (dtsgui_treeviewtv, dtsgui_treenodenode)
Create a panel owned by the tree configured from the specified node. Create a pane from information obtained from node. Name of node is used for the panel title and a Accept/Undo button.
Note:
if node id is -1 no name/buttons are added the page is blank.
See Also:
DTSTreeWindow::CreatePane()
Parameters:
tv Tree view.
node used as template for panel.
Returns:
New Tree Pane.
Definition at line 683 of file wrapper.cpp.
References DTSTreeWindow::CreatePane().
                                                                              {
    DTSTreeWindow *tw = (DTSTreeWindow*)tv;
    return tw->CreatePane(wxDataViewItem(node));
}
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.