XML Elements
NAME
XML Elements -
Elements derived from a XML node.
Functions
void DTS_C_API::dtsgui_xmltextbox (dtsgui_pane pane, const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Place a XML text element on the panel.
void DTS_C_API::dtsgui_xmltextbox_multi (dtsgui_pane pane, const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Place a XML multi line text element on the panel.
void DTS_C_API::dtsgui_xmlpasswdbox (dtsgui_pane pane, const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Place a XML password element on the panel.
void DTS_C_API::dtsgui_xmlcheckbox (dtsgui_pane pane, const char *title, const char *name, const char *checkval, const char *uncheckval, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Place a XML checkbox element on the panel.
struct form_item * DTS_C_API::dtsgui_xmllistbox (dtsgui_pane pane, const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Place a XML listbox element on the panel.
struct form_item * DTS_C_API::dtsgui_xmlcombobox (dtsgui_pane pane, const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Place a XML combobox element on the panel.
Detailed Description
Elements derived from a XML node.
See Also:
DTSPanel::GetNode()
Todo
Adding functions to work from a search path will be better than the current interface that alloacates a new search for each element.
Remarks:
XML elements require a xpath to the parent , node name , filter attribute , filter value and attribute name to derive the value from.
If a node name is supplied a XML node will be attempted to be created.
If no XML node is found or can be created the element will be disabled.
the resulting path will be
XPATH/Node<[<Filter attribute|.> = 'Filter Value']>
Note:
node, filter attribute, filter value and attribute may be NULL.
If the node name is not supplied a node will not be created.
If the attribute is NULL the value of the node will be used for value.
If no filter value is supplied the filter attribute is ignored
Function Documentation
void DTS_C_API::dtsgui_xmlcheckbox (dtsgui_panepane, const char *title, const char *name, const char *checkval, const char *uncheckval, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Place a XML checkbox element on the panel. See Also:
DTSPanel::XMLCheckBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
checkval The value will be set to this if checked.
uncheckval The value will be set to this if unchecked.
xpath Xpath of the element.
node Node to create in path if it does not exist.
fattr Attribute to create a filter on.
fval Value to equate to filter attr in filter.
attr Attribute in the node to assign value of.
Definition at line 1386 of file wrapper.cpp.
References DTSPanel::XMLCheckBox().
Referenced by network_config_dns(), network_config_dns_domain(), network_config_dns_dyn(), network_config_dns_serv(), network_modem_adv(), network_modem_ana(), pbxconf_autoadd(), pbxconf_default(), pbxconf_e1(), pbxconf_global(), pbxconf_incoming(), pbxconf_mfcr2(), pbxconf_misdn(), pbxconf_topts(), wizz_acd(), wizz_exten(), wizz_location(), wizz_network(), wizz_samba(), wizz_trunk(), and wizz_voip().
                                                                                                                                                                                                                                {
    DTSPanel *p = (DTSPanel *)pane;
    p->XMLCheckBox(title, name, checkval, uncheckval, xpath, node, fattr, fval, attr);
}
struct form_item* DTS_C_API::dtsgui_xmlcombobox (dtsgui_panepane, const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr) [read]
Place a XML combobox element on the panel. See Also:
DTSPanel::XMLComboBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
xpath Xpath of the element.
node Node to create in path if it does not exist.
fattr Attribute to create a filter on.
fval Value to equate to filter attr in filter.
attr Attribute in the node to assign value of.
Returns:
Form item that can be used to add values this must be unreferenced
Definition at line 1420 of file wrapper.cpp.
References DTSPanel::XMLComboBox().
Referenced by network_wifi(), and wizz_network().
                                                                                                                                                                                        {
    DTSPanel *p = (DTSPanel *)pane;
    return p->XMLComboBox(title, name, xpath, node, fattr, fval, attr);
}
struct form_item* DTS_C_API::dtsgui_xmllistbox (dtsgui_panepane, const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr) [read]
Place a XML listbox element on the panel. See Also:
DTSPanel::XMLListBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
xpath Xpath of the element.
node Node to create in path if it does not exist.
fattr Attribute to create a filter on.
fval Value to equate to filter attr in filter.
attr Attribute in the node to assign value of.
Returns:
Form item that can be used to add values this must be unreferenced
Definition at line 1403 of file wrapper.cpp.
References DTSPanel::XMLListBox().
Referenced by network_adsl_link(), network_config(), network_modem(), network_modem_ana(), network_tos(), pbxconf_default(), pbxconf_e1(), pbxconf_global(), pbxconf_incoming(), pbxconf_mfcr2(), pbxconf_trunk(), wizz_exten(), wizz_location(), wizz_trunk(), and wizz_voip().
                                                                                                                                                                                       {
    DTSPanel *p = (DTSPanel *)pane;
    return p->XMLListBox(title, name, xpath, node, fattr, fval, attr);
}
void DTS_C_API::dtsgui_xmlpasswdbox (dtsgui_panepane, const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Place a XML password element on the panel. See Also:
DTSPanel::XMLPasswdBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
xpath Xpath of the element.
node Node to create in path if it does not exist.
fattr Attribute to create a filter on.
fval Value to equate to filter attr in filter.
attr Attribute in the node to assign value of.
Definition at line 1368 of file wrapper.cpp.
References DTSPanel::XMLPasswdBox().
Referenced by pbxconf_global().
                                                                                                                                                                                   {
    DTSPanel *p = (DTSPanel *)pane;
    p->XMLPasswdBox(title, name, xpath, node, fattr, fval, attr, wxTE_LEFT | wxTE_PROCESS_ENTER);
}
void DTS_C_API::dtsgui_xmltextbox (dtsgui_panepane, const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Place a XML text element on the panel. See Also:
DTSPanel::XMLTextBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
xpath Xpath of the element.
node Node to create in path if it does not exist.
fattr Attribute to create a filter on.
fval Value to equate to filter attr in filter.
attr Attribute in the node to assign value of.
Definition at line 1336 of file wrapper.cpp.
References DTSPanel::XMLTextBox().
Referenced by network_adsl_link(), network_adsl_user(), network_config(), network_config_dns(), network_config_dns_domain(), network_config_dns_domain_server(), network_config_dns_dyn(), network_config_dns_host(), network_config_dns_serv(), network_config_dns_zone(), network_iface_pane(), network_iface_pane_cb(), network_modem(), network_modem_adv(), network_modem_ana(), network_route(), network_tos(), network_wan(), network_wifi(), pbxconf_acd(), pbxconf_autoadd(), pbxconf_default(), pbxconf_global(), pbxconf_location(), pbxconf_mfcr2(), pbxconf_misdn(), pbxconf_numplan(), pbxconf_topts(), pbxconf_trunk(), wizz_acd(), wizz_custinfo(), wizz_dnsinfo(), wizz_dyndns(), wizz_exten(), wizz_location(), wizz_netinfo(), wizz_network(), wizz_samba(), wizz_trunk(), and wizz_x509().
                                                                                                                                                                                 {
    DTSPanel *p = (DTSPanel *)pane;
    p->XMLTextBox(title, name, xpath, node, fattr, fval, attr, wxTE_LEFT | wxTE_PROCESS_ENTER, 1);
}
void DTS_C_API::dtsgui_xmltextbox_multi (dtsgui_panepane, const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Place a XML multi line text element on the panel. See Also:
DTSPanel::XMLTextBox()
Parameters:
pane Panel to place element on.
title Title of element.
name Name of element.
xpath Xpath of the element.
node Node to create in path if it does not exist.
fattr Attribute to create a filter on.
fval Value to equate to filter attr in filter.
attr Attribute in the node to assign value of.
Definition at line 1352 of file wrapper.cpp.
References DTSPanel::XMLTextBox().
Referenced by wizz_custinfo().
                                                                                                                                                                                       {
    DTSPanel *p = (DTSPanel *)pane;
    p->XMLTextBox(title, name, xpath, node, fattr, fval, attr, wxTE_MULTILINE, 5);
}
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.