.TH "C API Form Element Interface" 3 "Thu Oct 10 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C API Form Element Interface \- 
.PP
C API for managing elements of a panel\&.
.PP
Element items include Text / Password / Check / List / Combo boxes\&.  
C API for managing elements of a panel\&.
.PP
Element items include Text / Password / Check / List / Combo boxes\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
