Panel element interface.
NAME
Panel element interface. -
Interface for creating and placing elements on the panel.
Modules
Basic Elements.
Elements consisting Name/Value/Data.
XML Elements
Elements derived from a XML node.
Functions
void DTS_C_API::dtsgui_listbox_add (struct form_item *listbox, const char *text, const char *value)
Add a name / value to the list box for selection.
void DTS_C_API::dtsgui_listbox_set (struct form_item *listbox, int idx)
Set the selected item on a list box or combobox to the index.
void DTS_C_API::dtsgui_listbox_addxml (struct form_item *lb, struct xml_doc *xmldoc, const char *xpath, const char *nattr, const char *vattr)
Populate a listbox or combobox from a XML path. A entry is added for each node found using the supplied attributes for displayed text and value.
Detailed Description
Interface for creating and placing elements on the panel.
Todo
Add a JSON API
See Also:
Panel item interface.
Remarks:
Element items include Text / Password / Check / List / Combo boxes.
They are placed with the title on the left and element on the right.
Elements are accessed via the item interface.
There multiple API's for managing elements but a common interface for controling list and combo boxes.
Function Documentation
void DTS_C_API::dtsgui_listbox_add (struct form_item *listbox, const char *text, const char *value)
Add a name / value to the list box for selection. See Also:
form_item::Append()
Parameters:
listbox A form item containing a listbox or combobox.
text The text appearing on the drop down box.
value The value set when this item is selected.
Definition at line 1213 of file wrapper.cpp.
References form_item::Append().
Referenced by network_config(), network_modem(), network_modem_ana(), network_newwifi(), network_tos(), network_tos_new(), network_wifi(), pbxconf_default(), pbxconf_e1(), pbxconf_global(), pbxconf_incoming(), pbxconf_mfcr2(), pbxconf_trunk(), testpanel(), wizz_exten(), wizz_location(), wizz_network(), wizz_trunk(), and wizz_voip().
void DTS_C_API::dtsgui_listbox_addxml (struct form_item *lb, struct xml_doc *xmldoc, const char *xpath, const char *nattr, const char *vattr)
Populate a listbox or combobox from a XML path. A entry is added for each node found using the supplied attributes for displayed text and value. Remarks:
passing NULL as either or both of the attributes will use the value of the node.
Parameters:
lb A form item containing a listbox or combobox.
xmldoc XML Document to search.
xpath XML search path.
nattr Attribute whoose value will be used for name on list.
vattr Attribute whoose value will be used for value.
Definition at line 1234 of file wrapper.cpp.
References form_item::AppendXML().
Referenced by network_adsl_link(), network_adsl_link_new(), network_config(), and network_newwifi().
void DTS_C_API::dtsgui_listbox_set (struct form_item *listbox, intidx)
Set the selected item on a list box or combobox to the index. Parameters:
listbox A form item containing a listbox or combobox.
idx the index to set as the selected value.
Definition at line 1221 of file wrapper.cpp.
References form_item::SetSelection().
Referenced by network_newwifi().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.