app/config.c
NAME
app/config.c -
SYNOPSIS
#include <stdlib.h>
#include <limits.h>
#include <stdio.h>
#include 'dtsgui.h'
#include 'private.h'
Functions
dtsgui_pane open_config (struct dtsgui *dtsgui, const char *title, void *data)
dtsgui_pane save_config (struct dtsgui *dtsgui, const char *title, void *data)
dtsgui_pane view_config_xml (struct dtsgui *dtsgui, const char *title, void *data)
dtsgui_pane view_config_conf (struct dtsgui *dtsgui, const char *title, void *data)
dtsgui_pane export_config (struct dtsgui *dtsgui, const char *title, void *data)
void config_menu (struct dtsgui *dtsgui)
Function Documentation
void config_menu (struct dtsgui *dtsgui)
Definition at line 189 of file config.c.
References advanced_config(), app_data::cfg_menu, dtsgui_menuenable(), dtsgui_menusep(), dtsgui_newmenu(), dtsgui_newmenucb(), dtsgui_userdata(), export_config(), iface_config(), pbx_settings(), reconfig_wizard(), save_config(), view_config_conf(), and view_config_xml().
Referenced by guiconfig_cb().
dtsgui_pane export_config (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 150 of file config.c.
References app_getxmldoc(), app_data::datadir, dtsgui_alert(), dtsgui_filesave(), and dtsgui_userdata().
Referenced by config_menu().
dtsgui_pane open_config (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 27 of file config.c.
References app_data::c_open, app_data::cfg_menu, dtsgui_alert(), dtsgui_fileopen(), dtsgui_menuenable(), dtsgui_menuitemenable(), dtsgui_sendevent(), dtsgui_set_toolbar(), dtsgui_titleappend(), dtsgui_userdata(), app_data::e_wiz, app_data::n_wiz, and app_data::xmldoc.
Referenced by file_menu().
dtsgui_pane save_config (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 69 of file config.c.
References app_data::c_open, app_data::cfg_menu, dtsgui_menuenable(), dtsgui_menuitemenable(), dtsgui_set_toolbar(), dtsgui_titleappend(), dtsgui_userdata(), app_data::e_wiz, app_data::n_wiz, and app_data::xmldoc.
Referenced by config_menu().
dtsgui_pane view_config_conf (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 112 of file config.c.
References app_getxmldoc(), app_data::datadir, dtsgui_alert(), dtsgui_textpane(), and dtsgui_userdata().
Referenced by config_menu().
dtsgui_pane view_config_xml (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 94 of file config.c.
References app_getxmldoc(), and dtsgui_textpane().
Referenced by config_menu().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.