.TH "app/config.c" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/config.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'private\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdtsgui_pane\fP \fBopen_config\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.ti -1c
.RI "\fBdtsgui_pane\fP \fBsave_config\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.ti -1c
.RI "\fBdtsgui_pane\fP \fBview_config_xml\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.ti -1c
.RI "\fBdtsgui_pane\fP \fBview_config_conf\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.ti -1c
.RI "\fBdtsgui_pane\fP \fBexport_config\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.ti -1c
.RI "void \fBconfig_menu\fP (struct \fBdtsgui\fP *\fBdtsgui\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void config_menu (struct \fBdtsgui\fP *dtsgui)"

.PP
Definition at line 189 of file config\&.c\&.
.SS "\fBdtsgui_pane\fP export_config (struct \fBdtsgui\fP *dtsgui, const char *title, void *data)"

.PP
Definition at line 150 of file config\&.c\&.
.SS "\fBdtsgui_pane\fP open_config (struct \fBdtsgui\fP *dtsgui, const char *title, void *data)"

.PP
Definition at line 27 of file config\&.c\&.
.SS "\fBdtsgui_pane\fP save_config (struct \fBdtsgui\fP *dtsgui, const char *title, void *data)"

.PP
Definition at line 69 of file config\&.c\&.
.SS "\fBdtsgui_pane\fP view_config_conf (struct \fBdtsgui\fP *dtsgui, const char *title, void *data)"

.PP
Definition at line 112 of file config\&.c\&.
.SS "\fBdtsgui_pane\fP view_config_xml (struct \fBdtsgui\fP *dtsgui, const char *title, void *data)"

.PP
Definition at line 94 of file config\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
