.TH "mingw/config.h" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mingw/config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAVE_DLFCN_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMORY_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDLIB_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRINGS_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_STAT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNISTD_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE__BOOL\fP   1"
.br
.ti -1c
.RI "#define \fBLT_OBJDIR\fP   '\&.libs/'"
.br
.ti -1c
.RI "#define \fBPACKAGE\fP   'dtsguiapp'"
.br
.ti -1c
.RI "#define \fBPACKAGE_BUGREPORT\fP   'gregory@distrotech\&.co\&.za'"
.br
.ti -1c
.RI "#define \fBPACKAGE_NAME\fP   'dtsguiapp'"
.br
.ti -1c
.RI "#define \fBPACKAGE_STRING\fP   'dtsguiapp 0\&.1'"
.br
.ti -1c
.RI "#define \fBPACKAGE_TARNAME\fP   'dtsguiapp'"
.br
.ti -1c
.RI "#define \fBPACKAGE_URL\fP   ''"
.br
.ti -1c
.RI "#define \fBPACKAGE_VERSION\fP   '0\&.1'"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBVERSION\fP   '0\&.1'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HAVE__BOOL   1"

.PP
Definition at line 35 of file config\&.h\&.
.SS "#define HAVE_DLFCN_H   1"

.PP
Definition at line 5 of file config\&.h\&.
.SS "#define HAVE_INTTYPES_H   1"

.PP
Definition at line 8 of file config\&.h\&.
.SS "#define HAVE_MEMORY_H   1"

.PP
Definition at line 11 of file config\&.h\&.
.SS "#define HAVE_STDINT_H   1"

.PP
Definition at line 14 of file config\&.h\&.
.SS "#define HAVE_STDLIB_H   1"

.PP
Definition at line 17 of file config\&.h\&.
.SS "#define HAVE_STRING_H   1"

.PP
Definition at line 23 of file config\&.h\&.
.SS "#define HAVE_STRINGS_H   1"

.PP
Definition at line 20 of file config\&.h\&.
.SS "#define HAVE_SYS_STAT_H   1"

.PP
Definition at line 26 of file config\&.h\&.
.SS "#define HAVE_SYS_TYPES_H   1"

.PP
Definition at line 29 of file config\&.h\&.
.SS "#define HAVE_UNISTD_H   1"

.PP
Definition at line 32 of file config\&.h\&.
.SS "#define LT_OBJDIR   '\&.libs/'"

.PP
Definition at line 39 of file config\&.h\&.
.SS "#define PACKAGE   'dtsguiapp'"

.PP
Definition at line 45 of file config\&.h\&.
.SS "#define PACKAGE_BUGREPORT   'gregory@distrotech\&.co\&.za'"

.PP
Definition at line 48 of file config\&.h\&.
.SS "#define PACKAGE_NAME   'dtsguiapp'"

.PP
Definition at line 51 of file config\&.h\&.
.SS "#define PACKAGE_STRING   'dtsguiapp 0\&.1'"

.PP
Definition at line 54 of file config\&.h\&.
.SS "#define PACKAGE_TARNAME   'dtsguiapp'"

.PP
Definition at line 57 of file config\&.h\&.
.SS "#define PACKAGE_URL   ''"

.PP
Definition at line 60 of file config\&.h\&.
.SS "#define PACKAGE_VERSION   '0\&.1'"

.PP
Definition at line 63 of file config\&.h\&.
.SS "#define STDC_HEADERS   1"

.PP
Definition at line 66 of file config\&.h\&.
.SS "#define VERSION   '0\&.1'"

.PP
Definition at line 69 of file config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
