.TH "Panel item classes" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Panel item classes \- 
.PP
Implementation of Panel Items\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBpitems\&.cpp\fP"
.br
.RI "\fIImplementation of Panel Items\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of Panel Items\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
