.TH "Application frame." 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Application frame. \- 
.PP
Core application frame class\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDTSFrame\&.cpp\fP"
.br
.RI "\fICore application frame class\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Core application frame class\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
