.TH "XML combination box." 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XML combination box. \- 
.PP
Combo box that populates list from the XML returned in XML Post\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDTSXMLComboBox\&.cpp\fP"
.br
.RI "\fICombo box that populates list from the XML returned in XML Post\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Combo box that populates list from the XML returned in XML Post\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
