.TH "Panel event handler classes." 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Panel event handler classes. \- 
.PP
Implementation of panel event classes\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBevdata\&.cpp\fP"
.br
.RI "\fIImplementation of panel event classes\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of panel event classes\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
