.TH "Native C++ API" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Native C++ API \- 
.PP
C++ Interface\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBApplication frame\&.\fP"
.br
.RI "\fICore application frame class\&. \fP"
.ti -1c
.RI "\fBCore panel classes\fP"
.br
.RI "\fIImplementation of core panel clases and event handler\&. \fP"
.ti -1c
.RI "\fBWizard Classes\fP"
.br
.RI "\fIImplementation of wizard classes\&. \fP"
.ti -1c
.RI "\fBXML combination box\&.\fP"
.br
.RI "\fICombo box that populates list from the XML returned in XML Post\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDTSApp\&.cpp\fP"
.br
.RI "\fICore Application Class implementation\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwxDEFINE_EVENT\fP (DTS_APP_EVENT, wxCommandEvent)"
.br
.RI "\fIDefine event type used for application events\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
C++ Interface\&. 


.SH "Function Documentation"
.PP 
.SS "wxDEFINE_EVENT (DTS_APP_EVENT, wxCommandEvent)"

.PP
Define event type used for application events\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
