.TH "curl_progress" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
curl_progress \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSApp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTS_OJBREF_CLASS\fP (\fBcurl_progress\fP)"
.br
.ti -1c
.RI "\fBcurl_progress\fP (class \fBdtsgui_curl\fP *dc)"
.br
.ti -1c
.RI "\fBDTSFrame\fP * \fBGetFrame\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBpd\fP"
.br
.ti -1c
.RI "int \fBpause\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file DTSApp\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "curl_progress::curl_progress (class \fBdtsgui_curl\fP *dc)"

.PP
Definition at line 219 of file DTSApp\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "curl_progress::DTS_OJBREF_CLASS (\fBcurl_progress\fP)"

.SS "\fBDTSFrame\fP * curl_progress::GetFrame (void)"

.PP
Definition at line 235 of file DTSApp\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "int curl_progress::pause"

.PP
Definition at line 63 of file DTSApp\&.h\&.
.SS "int curl_progress::pd"

.PP
Definition at line 62 of file DTSApp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
