.TH "src/cxxapi.cpp" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/cxxapi.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/menu\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDTS_C_API\fP"
.br
.RI "\fINamespace containing exported functions used by C\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__DTS_C_API\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDTS_C_API::dtsgui_menuenable\fP (\fBdtsgui_menu\fP dm, int enable)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __DTS_C_API"

.PP
Definition at line 19 of file cxxapi\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
