PBX Configuration
NAME
PBX Configuration -
PBX Configuration.
Files
file pbxconfig.c
PBX Configuration panel.
Functions
void pbxconf_trunk (dtsgui_pane pg, void *data)
Configuration callback for tunk panel.
void pbxconf_topts (dtsgui_pane pg, void *data)
Configuration callback for trunk options panel.
void pbxconf_misdn (dtsgui_pane pg, void *data)
Configuration callback for mISDN panel.
void pbxconf_e1 (dtsgui_pane pg, void *data)
Configuration callback for E1/T1 panel.
void pbxconf_mfcr2 (dtsgui_pane pg, void *data)
Configuration callback for MFC/R2 panel.
void pbxconf_global (dtsgui_pane pg, void *data)
Configuration callback for global settings panel.
void pbxconf_acd (dtsgui_pane pg, void *data)
Configuration callback for ACD options panel.
void pbxconf_default (dtsgui_pane pg, void *data)
Configuration callback for extension default panel.
void pbxconf_location (dtsgui_pane pg, void *data)
Configuration callback for location panel.
void pbxconf_incoming (dtsgui_pane pg, void *data)
Configuration callback for incoming panel.
void pbxconf_numplan (dtsgui_pane pg, void *data)
Configuration callback for number plan panel.
void pbxconf_autoadd (dtsgui_pane pg, void *data)
Configuration callback for auto add panel.
dtsgui_pane pbx_settings (struct dtsgui *dtsgui, const char *title, void *data)
Configure and return the PBX configuration tab view.
Detailed Description
PBX Configuration.
Function Documentation
dtsgui_pane pbx_settings (struct dtsgui *dtsgui, const char *title, void *data)
Configure and return the PBX configuration tab view. Parameters:
dtsgui Application data ptr.
title Title of menuitem.
data Reference of data associated with menu item.
Definition at line 374 of file pbxconfig.c.
References app_getxmldoc(), dtsgui_newtabpage(), dtsgui_tabwindow(), pbxconf_acd(), pbxconf_autoadd(), pbxconf_default(), pbxconf_e1(), pbxconf_global(), pbxconf_incoming(), pbxconf_location(), pbxconf_mfcr2(), pbxconf_misdn(), pbxconf_numplan(), pbxconf_topts(), pbxconf_trunk(), and wx_PANEL_BUTTON_ACTION.
Referenced by config_menu().
void pbxconf_acd (dtsgui_panepg, void *data)
Configuration callback for ACD options panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 244 of file pbxconfig.c.
References dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_autoadd (dtsgui_panepg, void *data)
Configuration callback for auto add panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 360 of file pbxconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_default (dtsgui_panepg, void *data)
Configuration callback for extension default panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 253 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), dtsgui_xmltextbox(), form_item::name, and form_item::value.
Referenced by pbx_settings().
void pbxconf_e1 (dtsgui_panepg, void *data)
Configuration callback for E1/T1 panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 155 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), and dtsgui_xmllistbox().
Referenced by pbx_settings().
void pbxconf_global (dtsgui_panepg, void *data)
Configuration callback for global settings panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 222 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), dtsgui_xmlpasswdbox(), and dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_incoming (dtsgui_panepg, void *data)
Configuration callback for incoming panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 318 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), and dtsgui_xmllistbox().
Referenced by pbx_settings().
void pbxconf_location (dtsgui_panepg, void *data)
Configuration callback for location panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 304 of file pbxconfig.c.
References dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_mfcr2 (dtsgui_panepg, void *data)
Configuration callback for MFC/R2 panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 185 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), and dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_misdn (dtsgui_panepg, void *data)
Configuration callback for mISDN panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 139 of file pbxconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_numplan (dtsgui_panepg, void *data)
Configuration callback for number plan panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 343 of file pbxconfig.c.
References dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_topts (dtsgui_panepg, void *data)
Configuration callback for trunk options panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 122 of file pbxconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_trunk (dtsgui_panepg, void *data)
Configuration callback for tunk panel. Parameters:
pg Panel to be configured.
data data Reference to data held by callback.
Definition at line 37 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmllistbox(), dtsgui_xmltextbox(), form_item::name, and form_item::value.
Referenced by pbx_settings().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.