Interface configuration tab view
NAME
Interface configuration tab view -
Tab view panel allowing configuration and addition of interfaces.
Files
file interface.c
Interface configuration panel.
Classes
struct new_iface_data
Structure containing treeview and xmldoc for creating new tab.
struct iface_cdata
Pretty pointless structure holding interface name.
Functions
void free_iface_cdata (void *data)
Relase references held by structure before free.
struct iface_cdata * get_iface_cdata (const char *val)
Allocate new iface_cdata structure.
void free_newiface_data (void *data)
Release references held by structure before free.
struct new_iface_data * get_newiface_data (dtsgui_tabview tv, struct xml_doc *xmldoc)
Allocate and return a new_iface_data structure.
void handle_newxmltabpane (struct xml_doc *xmldoc, struct xml_node *xn, void *tdata, void **cdata, int *last)
Configure panel configuration data.
int handle_updatetabpane (struct dtsgui *dtsgui, dtsgui_pane p, int type, int event, void *data)
Event handler callback that will only check the interface name and pass handling to default handler.
void network_iface_pane_cb (dtsgui_pane p, void *data)
Callback called to configure a interface pane.
void network_iface_new_pane_cb (dtsgui_pane p, void *data)
Callback called for the 'New' interface pane.
dtsgui_pane iface_config (struct dtsgui *dtsgui, const char *title, void *data)
Callback called when the interface configuration link is selected.
Detailed Description
Tab view panel allowing configuration and addition of interfaces.
Function Documentation
void free_iface_cdata (void *data)
Relase references held by structure before free. Parameters:
data Reference to iface_cdata that is about to be freed
Definition at line 52 of file interface.c.
References iface_cdata::name.
Referenced by get_iface_cdata().
                                  {
    struct iface_cdata *cdata = data;
    if (cdata->name) {
        free((void*)cdata->name);
    }
}
void free_newiface_data (void *data)
Release references held by structure before free. Parameters:
data Reference to new_iface_data that is about to be freed
Definition at line 75 of file interface.c.
References new_iface_data::xmldoc.
Referenced by get_newiface_data().
                                    {
    struct new_iface_data *nd = data;
    if (nd->xmldoc) {
        objunref(nd->xmldoc);
    }
}
struct iface_cdata* get_iface_cdata (const char *val) [read]
Allocate new iface_cdata structure. Parameters:
val Name of interface.
Definition at line 62 of file interface.c.
References free_iface_cdata(), and iface_cdata::name.
Referenced by handle_newxmltabpane(), and iface_config().
                                                     {
    struct iface_cdata *cd;
    if (!(cd = objalloc(sizeof(*cd), free_iface_cdata))) {
        return NULL;
    }
    ALLOC_CONST(cd->name, val);
    return cd;
}
struct new_iface_data* get_newiface_data (dtsgui_tabviewtv, struct xml_doc *xmldoc) [read]
Allocate and return a new_iface_data structure. This structure is used to create and insert a new tab in the treeview.
Parameters:
tv Tabview to allocate new tab too.
xmldoc XML Document to create new node in.
Returns:
Reference to new new_iface_data structure
Definition at line 90 of file interface.c.
References free_newiface_data(), new_iface_data::tv, and new_iface_data::xmldoc.
Referenced by iface_config().
                                                                                    {
    struct new_iface_data *nd;
    if (!(nd = objalloc(sizeof(*nd), free_newiface_data))) {
        return NULL;
    }
    if (xmldoc && objref(xmldoc)) {
        nd->xmldoc = xmldoc;
    }
    nd->tv = tv;
    return nd;
}
void handle_newxmltabpane (struct xml_doc *xmldoc, struct xml_node *xn, void *tdata, void **cdata, int *last)
Configure panel configuration data. As the new interface name is not known till creation time the configuration data needs to be configured.
See Also:
dtsgui_tabpane_newdata_cb
Definition at line 109 of file interface.c.
References get_iface_cdata().
Referenced by network_iface_new_pane_cb().
                                                                                                                    {
    struct iface_cdata *ndat = NULL;
    if (xn->value && (ndat = get_iface_cdata(xn->value))) {
        cdata[0] = ndat;
    }
}
int handle_updatetabpane (struct dtsgui *dtsgui, dtsgui_panep, inttype, intevent, void *data)
Event handler callback that will only check the interface name and pass handling to default handler. Parameters:
dtsgui Application data ptr.
p Panel generating the event.
type Event type.
event Event id.
data Reference to data passed to event handler.
Returns:
0 on error 1 will allow the event to be handled by default handler.
Definition at line 124 of file interface.c.
References dtsgui_findvalue(), dtsgui_setstatus(), iface_cdata::name, wx_PANEL_EVENT_BUTTON, wx_PANEL_EVENT_BUTTON_NO, and wx_PANEL_EVENT_BUTTON_YES.
Referenced by network_iface_pane_cb().
                                                                                                       {
    struct iface_cdata *cdata = data;
    const char *name;
    if (type != wx_PANEL_EVENT_BUTTON) {
        return 1;
    }
    switch(event) {
        case wx_PANEL_EVENT_BUTTON_YES:
            break;
        case wx_PANEL_EVENT_BUTTON_NO:
            return 1;
        default:
            return 1;
    }
    if (!cdata || !(name = dtsgui_findvalue(p, 'iface'))) {
        return 0;
    }
    objlock(cdata);
    if (cdata->name) {
        free((void*)cdata->name);
        cdata->name = NULL;
    }
    ALLOC_CONST(cdata->name, name);
    objunlock(cdata);
    if ((name = dtsgui_findvalue(p, 'name'))) {
        dtsgui_setstatus(p, name);
        free((void*)name);
    }
    return 1;
}
dtsgui_pane iface_config (struct dtsgui *dtsgui, const char *title, void *data)
Callback called when the interface configuration link is selected. Parameters:
dtsgui Application data ptr.
title Name assigned to the menu item (not name in menubar).
data Userdata referenced in menuitem.
Returns:
Tabview panel to display to configure interface cards.
Definition at line 197 of file interface.c.
References app_getxmldoc(), dtsgui_newtabpage(), dtsgui_tabwindow(), get_iface_cdata(), get_newiface_data(), network_iface_new_pane_cb(), network_iface_pane_cb(), and wx_PANEL_BUTTON_ACTION.
Referenced by config_menu().
                                                                               {
    dtsgui_tabview tabv;
    struct new_iface_data *nd;
    struct xml_doc *xmldoc;
    struct xml_search *xp;
    struct xml_node *xn;
    const char *name;
    struct iface_cdata *cdata;
    void *iter = NULL;
    if (!(xmldoc = app_getxmldoc(dtsgui))) {
        return NULL;
    }
    if (!(xp = xml_xpath(xmldoc, '/config/IP/Interfaces/Interface', 'name'))) {
        objunref(xmldoc);
        return NULL;
    }
    tabv = dtsgui_tabwindow(dtsgui, title, NULL);
    for(xn = xml_getfirstnode(xp, &iter); xn; xn = xml_getnextnode(iter)) {
        name = xml_getattr(xn, 'name');
        cdata = get_iface_cdata(xn->value);
        dtsgui_newtabpage(tabv, name, wx_PANEL_BUTTON_ACTION, NULL, xmldoc, network_iface_pane_cb, cdata);
        objunref(cdata);
        objunref(xn);
    }
    nd = get_newiface_data(tabv, xmldoc);
    dtsgui_newtabpage(tabv, 'Add', wx_PANEL_BUTTON_ACTION, NULL, xmldoc, network_iface_new_pane_cb, nd);
    objunref(nd);
    if (iter) {
        objunref(iter);
    }
    objunref(xp);
    objunref(xmldoc);
    return tabv;
}
void network_iface_new_pane_cb (dtsgui_panep, void *data)
Callback called for the 'New' interface pane. Parameters:
p Panel to configure.
data Reference to configuration data new_iface_data.
Remarks:
use dtsgui_newxmltabpane() helper to atach a callback that will create a new panel
See Also:
handle_newxmltabpane()
network_iface_pane_cb()
Definition at line 181 of file interface.c.
References dtsgui_newxmltabpane(), handle_newxmltabpane(), network_iface_new_pane(), network_iface_pane_cb(), new_iface_data::tv, and new_iface_data::xmldoc.
Referenced by iface_config().
                                                          {
    struct new_iface_data *nd = data;
    network_iface_new_pane(p);
    dtsgui_newxmltabpane(nd->tv, p, '/config/IP/Interfaces', 'Interface', 'iface', 'name', handle_newxmltabpane, network_iface_pane_cb, NULL, nd->xmldoc, nd);
}
void network_iface_pane_cb (dtsgui_panep, void *data)
Callback called to configure a interface pane. Parameters:
p Panel to configure.
data Reference to configuration data iface_cdata.
Definition at line 164 of file interface.c.
References dtsgui_setevcallback(), dtsgui_xmltextbox(), handle_updatetabpane(), iface_cdata::name, and network_iface_pane().
Referenced by iface_config(), and network_iface_new_pane_cb().
                                                      {
    struct iface_cdata *cdata = data;
    const char *iface;
    const char *xpre = '/config/IP/Interfaces';
    objlock(cdata);
    iface = cdata->name;
    objunlock(cdata);
    dtsgui_xmltextbox(p, 'Name', 'name', xpre, 'Interface', NULL, iface, 'name');
    network_iface_pane(p, xpre, iface);
    dtsgui_setevcallback(p, handle_updatetabpane, cdata);
}
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.