.TH "Distrotech Server Configuration Application" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Distrotech Server Configuration Application \- 
.PP
Multi platform GUI server management application\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBDistrotech Application Wizard Interface\fP"
.br
.RI "\fISystem configuration wizard\&. \fP"
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBwxforms\&.c\fP"
.br
.RI "\fIMain application file\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBxml_config\fP (struct xml_doc *xmldoc)"
.br
.ti -1c
.RI "struct xml_doc * \fBapp_getxmldoc\fP (struct \fBdtsgui\fP *\fBdtsgui\fP)"
.br
.ti -1c
.RI "void \fBfile_menu\fP (struct \fBdtsgui\fP *\fBdtsgui\fP)"
.br
.ti -1c
.RI "void \fBhelp_menu\fP (struct \fBdtsgui\fP *\fBdtsgui\fP)"
.br
.ti -1c
.RI "int \fBguiconfig_cb\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, void *data)"
.br
.ti -1c
.RI "void \fBfree_appdata\fP (void *data)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Multi platform GUI server management application\&. 


.SH "Function Documentation"
.PP 
.SS "struct xml_doc* app_getxmldoc (struct \fBdtsgui\fP *dtsgui)\fC [read]\fP"

.PP
Definition at line 48 of file wxforms\&.c\&.
.PP
References dtsgui_userdata(), and app_data::xmldoc\&.
.PP
Referenced by advanced_config(), export_config(), iface_config(), pbx_settings(), reconfig_wizard(), view_config_conf(), and view_config_xml()\&.
.SS "void file_menu (struct \fBdtsgui\fP *dtsgui)"

.PP
Definition at line 69 of file wxforms\&.c\&.
.PP
References app_data::c_open, dtsgui_close(), dtsgui_exit(), dtsgui_menusep(), dtsgui_newmenu(), dtsgui_newmenucb(), dtsgui_userdata(), app_data::e_wiz, editsys_wizard(), app_data::n_wiz, newsys_wizard(), and open_config()\&.
.PP
Referenced by guiconfig_cb()\&.
.SS "void free_appdata (void *data)"

.PP
Definition at line 125 of file wxforms\&.c\&.
.PP
References app_data::datadir, and app_data::xmldoc\&.
.PP
Referenced by main()\&.
.SS "int guiconfig_cb (struct \fBdtsgui\fP *dtsgui, void *data)"

.PP
Definition at line 110 of file wxforms\&.c\&.
.PP
References app_toolbar(), config_menu(), dtsgui_setuptoolbar(), file_menu(), and help_menu()\&.
.PP
Referenced by main()\&.
.SS "void help_menu (struct \fBdtsgui\fP *dtsgui)"

.PP
Definition at line 94 of file wxforms\&.c\&.
.PP
References dtsgui_about(), dtsgui_menusep(), dtsgui_newmenu(), dtsgui_newmenuitem(), dtsgui_textpane(), and test_menu()\&.
.PP
Referenced by guiconfig_cb()\&.
.SS "int main (intargc, char **argv)"

.PP
Definition at line 137 of file wxforms\&.c\&.
.PP
References DATA_DIR, app_data::datadir, dtsgui_config(), dtsgui_run(), free_appdata(), and guiconfig_cb()\&.
.SS "void xml_config (struct xml_doc *xmldoc)"

.PP
Definition at line 40 of file wxforms\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
