.TH "Configuration menu functions" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Configuration menu functions \- 
.PP
Configuration menu functions\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.c\fP"
.br
.RI "\fIConfiguration menu functions\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdtsgui_pane\fP \fBopen_config\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.RI "\fIOpen XML configuration file callback\&. \fP"
.ti -1c
.RI "\fBdtsgui_pane\fP \fBsave_config\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.RI "\fIClose/Save menu option call back\&. \fP"
.ti -1c
.RI "\fBdtsgui_pane\fP \fBview_config_xml\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.RI "\fIDisplay XML document formated in text display\&. \fP"
.ti -1c
.RI "\fBdtsgui_pane\fP \fBview_config_conf\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.RI "\fIDisplay XML document formated in text display as a dot conf\&. \fP"
.ti -1c
.RI "\fBdtsgui_pane\fP \fBexport_config\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.RI "\fIExport XML document as a \&.conf file\&. \fP"
.ti -1c
.RI "void \fBconfig_menu\fP (struct \fBdtsgui\fP *\fBdtsgui\fP)"
.br
.RI "\fIAdd the configure menu to the menu bar and add options\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Configuration menu functions\&. 


.SH "Function Documentation"
.PP 
.SS "void config_menu (struct \fBdtsgui\fP *dtsgui)"

.PP
Add the configure menu to the menu bar and add options\&. \fBParameters:\fP
.RS 4
\fIdtsgui\fP Application data ptr\&. 
.RE
.PP

.PP
Definition at line 240 of file config\&.c\&.
.PP
References advanced_config(), app_data::cfg_menu, dtsgui_menuenable(), dtsgui_menusep(), dtsgui_newmenu(), dtsgui_newmenucb(), dtsgui_userdata(), export_config(), iface_config(), pbx_settings(), reconfig_wizard(), save_config(), view_config_conf(), and view_config_xml()\&.
.PP
Referenced by guiconfig_cb()\&.
.SS "\fBdtsgui_pane\fP export_config (struct \fBdtsgui\fP *dtsgui, const char *title, void *data)"

.PP
Export XML document as a \&.conf file\&. Openand apply the XSLT xml2conf\&.xsl and save the result to a file selected in a file dialog\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdtsgui\fP Application data ptr\&. 
.br
\fItitle\fP Name supplied to menuitem\&. 
.br
\fIdata\fP Reference to data held by menu callback\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
NULL as no panel is displayed\&. 
.RE
.PP

.PP
Definition at line 198 of file config\&.c\&.
.PP
References app_getxmldoc(), app_data::datadir, dtsgui_alert(), dtsgui_filesave(), and dtsgui_userdata()\&.
.PP
Referenced by config_menu()\&.
.SS "\fBdtsgui_pane\fP open_config (struct \fBdtsgui\fP *dtsgui, const char *title, void *data)"

.PP
Open XML configuration file callback\&. Present a file open dialog to the user let them select a configuration file on success enable config menu options and disable file menu options\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdtsgui\fP Application data ptr\&. 
.br
\fItitle\fP Name supplied to menuitem\&. 
.br
\fIdata\fP Reference to data held by menu callback\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
NULL as no pane is displayed\&. 
.RE
.PP

.PP
Definition at line 44 of file config\&.c\&.
.PP
References app_data::c_open, app_data::cfg_menu, dtsgui_alert(), dtsgui_fileopen(), dtsgui_menuenable(), dtsgui_menuitemenable(), dtsgui_sendevent(), dtsgui_set_toolbar(), dtsgui_titleappend(), dtsgui_userdata(), app_data::e_wiz, app_data::n_wiz, and app_data::xmldoc\&.
.PP
Referenced by file_menu()\&.
.SS "\fBdtsgui_pane\fP save_config (struct \fBdtsgui\fP *dtsgui, const char *title, void *data)"

.PP
Close/Save menu option call back\&. This function re enables the file menu items And disables the config menu\&. 
.PP
\fBTodo\fP
.RS 4
Actually save the config 
.RE
.PP
\fBParameters:\fP
.RS 4
\fIdtsgui\fP Application data ptr\&. 
.br
\fItitle\fP Name supplied to menuitem\&. 
.br
\fIdata\fP Reference to data held by menu callback\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
NULL as no pane is displayed\&. 
.RE
.PP

.PP
Definition at line 95 of file config\&.c\&.
.PP
References app_data::c_open, app_data::cfg_menu, dtsgui_menuenable(), dtsgui_menuitemenable(), dtsgui_set_toolbar(), dtsgui_titleappend(), dtsgui_userdata(), app_data::e_wiz, app_data::n_wiz, and app_data::xmldoc\&.
.PP
Referenced by config_menu()\&.
.SS "\fBdtsgui_pane\fP view_config_conf (struct \fBdtsgui\fP *dtsgui, const char *title, void *data)"

.PP
Display XML document formated in text display as a dot conf\&. Open the XSLT file to transform to \&.conf and apply it to the XML document placing the output in a text panel\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdtsgui\fP Application data ptr\&. 
.br
\fItitle\fP Name supplied to menuitem\&. 
.br
\fIdata\fP Reference to data held by menu callback\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Text Panel\&. 
.RE
.PP

.PP
Definition at line 152 of file config\&.c\&.
.PP
References app_getxmldoc(), app_data::datadir, dtsgui_alert(), dtsgui_textpane(), and dtsgui_userdata()\&.
.PP
Referenced by config_menu()\&.
.SS "\fBdtsgui_pane\fP view_config_xml (struct \fBdtsgui\fP *dtsgui, const char *title, void *data)"

.PP
Display XML document formated in text display\&. \fBParameters:\fP
.RS 4
\fIdtsgui\fP Application data ptr\&. 
.br
\fItitle\fP Name supplied to menuitem\&. 
.br
\fIdata\fP Reference to data held by menu callback\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Text Panel\&. 
.RE
.PP

.PP
Definition at line 126 of file config\&.c\&.
.PP
References app_getxmldoc(), and dtsgui_textpane()\&.
.PP
Referenced by config_menu()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
