Advanced configuration tree
NAME
Advanced configuration tree -
wAdvanced configuration tree
Files
file netconfig.c
Advanced configuration panel.
Functions
void network_config_dns_domain_server_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (New Hosted Domain Server)
void customer_info (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (Customer Info)
void network_config (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (Network Configuration)
void network_config_dns (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (DNS Configuration)
void network_config_dns_dyn (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (Dynamic DNS)
void network_config_dns_serv (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (DNS Server)
void network_config_dns_zone (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (DNS Zone Defaults)
void network_config_dns_host (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (DNS Hosts)
void network_config_dns_host_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (New DNS Host)
void network_config_dns_domain_node (dtsgui_treeview tv, dtsgui_treenode tn, struct xml_node *xn, void *data)
Add a container for servers to newly added domain.
void network_config_dns_domain (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (Hosted Domain)
void network_config_dns_domain_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (New Hosted Domain)
void network_config_dns_domain_server (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (Hosted Domain Server)
void network_iface_pane (dtsgui_pane p, const char *xpre, const char *iface)
Network interface stub shared with interface config.
void network_iface (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (Network Interface)
void network_iface_new_pane (dtsgui_pane p)
Network interface stub shared with interface config.
void network_newiface (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (New Network Interface)
void network_wifi (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (WiFi Interface)
void network_newwifi (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (New WiFi Interface)
void network_wan (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (WAN Route)
void network_newwan (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (New Wan Route)
void network_route (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (Static Route)
void network_newroute (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (New Static Route)
void network_modem (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (Modem Config)
void network_modem_adv (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (Advanced Modem Config)
void network_modem_ana (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (Analogue Modem Config)
void network_adsl_link (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (DSL Links)
void network_adsl_link_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (New DSL Link)
void network_adsl_user (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (DSL User)
void network_adsl_user_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (New DSL User)
void network_tos (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (TOS Config)
void network_tos_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
Tree pane configuration call back (New TOS Config)
void network_tree_setup (dtsgui_treeview tree, struct xml_doc *xmldoc)
Configure the networking noded on the tree.
dtsgui_pane advanced_config (struct dtsgui *dtsgui, const char *title, void *data)
Advanced configuration menu callback.
Variables
static const char * protocols [] = {'TCP', 'UDP', 'GRE', 'ESP', 'AH', 'OSPF', 'ALL'}
Array of network protocols.
Detailed Description
wAdvanced configuration tree
Function Documentation
dtsgui_pane advanced_config (struct dtsgui *dtsgui, const char *title, void *data)
Advanced configuration menu callback. Parameters:
dtsgui Application data ptr.
title Menuitem name.
data Reference to data held by menuitem.
Definition at line 912 of file netconfig.c.
References app_getxmldoc(), dtsgui_treewindow(), and network_tree_setup().
Referenced by config_menu().
                                                                                  {
    dtsgui_treeview tree;
    struct xml_doc *xmldoc;
    struct app_data *appdata;
    char defconf[PATH_MAX];
    if (!(xmldoc = app_getxmldoc(dtsgui))) {
        return NULL;
    }
    tree = dtsgui_treewindow(dtsgui, title, NULL, data, xmldoc);
    network_tree_setup(tree, xmldoc);
    objunref(xmldoc);
    return tree;
}
void customer_info (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (Customer Info) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 47 of file netconfig.c.
References wizz_custinfo().
Referenced by network_tree_setup().
                                                                                          {
    wizz_custinfo(p);
}
void network_adsl_link (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (DSL Links) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 586 of file netconfig.c.
References dtsgui_listbox_addxml(), dtsgui_panelxml(), dtsgui_treenodegetxml(), dtsgui_xmllistbox(), and dtsgui_xmltextbox().
Referenced by network_adsl_link_new(), and network_tree_setup().
                                                                                              {
    const char *xpre = '/config/IP/ADSL/Links';
    struct xml_node *xn;
    struct xml_doc *xmldoc;
    struct form_item *elb;
    if (!(xn = dtsgui_treenodegetxml(node, NULL))) {
        return;
    }
    if (!(xmldoc = dtsgui_panelxml(p))) {
        objunref(xn);
        return;
    }
    if ((elb = dtsgui_xmllistbox(p, 'Interface', 'interface', xpre, 'Link', NULL, xn->value, 'interface'))) {
        dtsgui_listbox_addxml(elb, xmldoc, '/config/IP/Interfaces/Interface', 'name', NULL);
        objunref(elb);
    }
    dtsgui_xmltextbox(p, 'PPPoE Service (AC/Service)', 'service', xpre, 'Link', NULL, xn->value, 'service');
    dtsgui_xmltextbox(p, 'Username', 'username', xpre, 'Link', NULL, xn->value, 'username');
    dtsgui_xmltextbox(p, 'Password', 'password', xpre, 'Link', NULL, xn->value, 'password');
    dtsgui_xmltextbox(p, 'Bandwidth In', 'bwin', xpre, 'Link', NULL, xn->value, 'bwin');
    dtsgui_xmltextbox(p, 'Bandwidth Out', 'bwout', xpre, 'Link', NULL, xn->value, 'bwout');
    dtsgui_xmltextbox(p, 'TOS Match', 'tos', xpre, 'Link', NULL, xn->value, 'tos');
    dtsgui_xmltextbox(p, 'Virtual IP', 'virtip', xpre, 'Link', NULL, xn->value, 'virtip');
    dtsgui_xmltextbox(p, 'Remote IP', 'remip', xpre, 'Link', NULL, xn->value, 'remip');
    objunref(xn);
    objunref(xmldoc);
}
void network_adsl_link_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (New DSL Link) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 624 of file netconfig.c.
References DTS_NODE_NETWORK_ADSL_LINK, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_listbox(), dtsgui_listbox_addxml(), dtsgui_newxmltreenode(), dtsgui_panelxml(), dtsgui_textbox(), and network_adsl_link().
Referenced by network_tree_setup().
                                                                                                  {
    struct xml_doc *xmldoc = dtsgui_panelxml(p);
    struct form_item *elb;
    int flg;
    dtsgui_textbox(p, 'Link Name', 'name', '', NULL);
    if ((elb = dtsgui_listbox(p, 'Interface', 'interface', NULL))) {
        dtsgui_listbox_addxml(elb, xmldoc, '/config/IP/Interfaces/Interface', 'name', NULL);
        objunref(elb);
    }
    dtsgui_textbox(p, 'PPPoE Service (AC/Service)', 'service', '', NULL);
    dtsgui_textbox(p, 'Username', 'username', '', NULL);
    dtsgui_textbox(p, 'Password', 'password', '', NULL);
    dtsgui_textbox(p, 'Bandwidth In', 'bwin', '', NULL);
    dtsgui_textbox(p, 'Bandwidth Out', 'bwout', '', NULL);
    dtsgui_textbox(p, 'TOS Match', 'tos', '', NULL);
    dtsgui_textbox(p, 'Virtual IP', 'virtip', '', NULL);
    dtsgui_textbox(p, 'Remote IP', 'remip', '', NULL);
    flg = DTS_TREE_NEW_NODE_DELETE | DTS_TREE_NEW_NODE_EDIT | DTS_TREE_NEW_NODE_SORT;
    dtsgui_newxmltreenode(self, p, node, '/config/IP/ADSL/Links', 'Link', 'name', NULL, DTS_NODE_NETWORK_ADSL_LINK,
                                flg, NULL, NULL, network_adsl_link);
    objunref(xmldoc);
}
void network_adsl_user (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (DSL User) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 654 of file netconfig.c.
References dtsgui_treenodegetxml(), and dtsgui_xmltextbox().
Referenced by network_adsl_user_new(), and network_tree_setup().
                                                                                              {
    const char *xpre = '/config/IP/ADSL/Users';
    struct xml_node *xn = dtsgui_treenodegetxml(node, NULL);
    dtsgui_xmltextbox(p, 'Password', 'password', xpre, 'User', NULL, xn->value , 'password');
    objunref(xn);
}
void network_adsl_user_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (New DSL User) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 668 of file netconfig.c.
References DTS_NODE_NETWORK_ADSL_USER, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), dtsgui_textbox(), and network_adsl_user().
Referenced by network_tree_setup().
                                                                                                  {
    int flg;
    dtsgui_textbox(p, 'Username', 'username', '', NULL);
    dtsgui_textbox(p, 'Password', 'password', '', NULL);
    flg = DTS_TREE_NEW_NODE_DELETE | DTS_TREE_NEW_NODE_EDIT | DTS_TREE_NEW_NODE_SORT;
    dtsgui_newxmltreenode(self, p, node, '/config/IP/ADSL/Users', 'User', 'username', NULL, DTS_NODE_NETWORK_ADSL_USER,
                                flg, NULL, NULL, network_adsl_user);
}
void network_config (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (Network Configuration) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 56 of file netconfig.c.
References dtsgui_item_value(), dtsgui_listbox_add(), dtsgui_listbox_addxml(), dtsgui_panelxml(), dtsgui_xmllistbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
                                                                                           {
    struct xml_doc *xmldoc = dtsgui_panelxml(p);
    struct form_item *lb, *elb;
    const char *extint = NULL;
    /*XXX LDAP Settings server/DN*/
    if ((lb = dtsgui_xmllistbox(p, 'Internal Interface', 'Internal', '/config/IP/SysConf', 'Option', 'option', 'Internal', NULL))) {
        dtsgui_listbox_addxml(lb, xmldoc, '/config/IP/Interfaces/Interface', 'name', NULL);
        objunref(lb);
    }
    if ((elb = dtsgui_xmllistbox(p, 'External Interface', 'External', '/config/IP/SysConf', 'Option', 'option', 'External', NULL))) {
        dtsgui_listbox_add(elb, 'Modem', 'Dialup');
        dtsgui_listbox_addxml(elb, xmldoc, '/config/IP/Interfaces/Interface', 'name', NULL);
        extint = dtsgui_item_value(elb);
        objunref(elb);
    }
    if ((lb = dtsgui_xmllistbox(p, 'External OVPN Interface', 'OVPNNet', '/config/IP/SysConf', 'Option', 'option', 'OVPNNet', NULL))) {
        dtsgui_listbox_add(lb, 'Modem', 'Dialup');
        dtsgui_listbox_addxml(lb, xmldoc, '/config/IP/Interfaces/Interface', 'name', NULL);
        objunref(lb);
    }
    if (extint) {
        free((void*)extint);
    }
    dtsgui_xmltextbox(p, 'Gateway Address', 'Nexthop', '/config/IP/SysConf', 'Option', 'option', 'Nexthop', NULL);
    dtsgui_xmltextbox(p, 'External (Natted IP)', 'NattedIP', '/config/IP/SysConf', 'Option', 'option', 'NattedIP', NULL);
    dtsgui_xmltextbox(p, 'IPSEC VPN Access', 'VPNNet', '/config/IP/SysConf', 'Option', 'option', 'VPNNet', NULL);
    dtsgui_xmltextbox(p, 'Open VPN Access', 'OVPNNet', '/config/IP/SysConf', 'Option', 'option', 'OVPNNet', NULL);
    dtsgui_xmltextbox(p, 'L2TP VPN Access', 'L2TPNet', '/config/IP/SysConf', 'Option', 'option', 'L2TPNet', NULL);
    dtsgui_xmltextbox(p, 'NTP Server[s]', 'NTPServer', '/config/IP/SysConf', 'Option', 'option', 'NTPServer', NULL);
    dtsgui_xmltextbox(p, 'Bridge Interfaces', 'Bridge', '/config/IP/SysConf', 'Option', 'option', 'Bridge', NULL);
    dtsgui_xmltextbox(p, 'Incoming Traffic Limit', 'Ingress','/config/IP/SysConf', 'Option', 'option', 'Ingress', NULL);
    dtsgui_xmltextbox(p, 'Outgoing Traffic Limit', 'Egress', '/config/IP/SysConf', 'Option', 'option', 'Egress', NULL);
    objunref(xmldoc);
}
void network_config_dns (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (DNS Configuration) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 100 of file netconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
                                                                                               {
    dtsgui_xmltextbox(p, 'Hostname', 'Hostname', '/config/DNS/Config', 'Option', 'option', 'Hostname', NULL);
    dtsgui_xmltextbox(p, 'Domain', 'Domain', '/config/DNS/Config', 'Option', 'option', 'Domain', NULL);
    dtsgui_xmltextbox(p, 'Aditional Search Domains', 'Search', '/config/DNS/Config', 'Option', 'option', 'Search', NULL);
    dtsgui_xmltextbox(p, 'Primary DNS', 'PrimaryDns', '/config/IP/SysConf', 'Option', 'option', 'PrimaryDns', NULL);
    dtsgui_xmltextbox(p, 'Secondary DNS', 'SecondaryDns', '/config/IP/SysConf', 'Option', 'option', 'SecondaryDns', NULL);
    dtsgui_xmltextbox(p, 'Primary WINS', 'PrimaryWins', '/config/IP/SysConf', 'Option', 'option', 'PrimaryWins', NULL);
    dtsgui_xmltextbox(p, 'Secondary WINS', 'SecondaryWins', '/config/IP/SysConf', 'Option', 'option', 'SecondaryWins', NULL);
    dtsgui_xmltextbox(p, 'DHCP Lease', 'DHCPLease', '/config/IP/SysConf', 'Option', 'option', 'DHCPLease', NULL);
    dtsgui_xmltextbox(p, 'DHCP Max Lease', 'DHCPLease', '/config/IP/SysConf', 'Option', 'option', 'DHCPMaxLease', NULL);
    dtsgui_xmlcheckbox(p, 'Use Internal Interface For DNS First', 'IntFirst', 'true', '', '/config/DNS/Config', 'Option', 'option', 'IntFirst', NULL);
}
void network_config_dns_domain (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (Hosted Domain) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 197 of file netconfig.c.
References dtsgui_treenodegetxml(), dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by network_config_dns_domain_new(), and network_tree_setup().
                                                                                                      {
    const char *xpre = '/config/DNS/Hosted';
    const char *domain;
    struct xml_node *xn = dtsgui_treenodegetxml(node, NULL);
    domain = xml_getattr(xn, 'domain');
    dtsgui_xmltextbox(p, 'TSIG Key [Master]', 'key', xpre, 'Domain', 'domain', domain, 'key');
    dtsgui_xmlcheckbox(p, 'Internal Domain', 'internal', 'true', '', xpre, 'Domain', 'domain', domain, 'internal');
    objunref(xn);
}
void network_config_dns_domain_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (New Hosted Domain) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 215 of file netconfig.c.
References DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN, DTS_TREE_NEW_NODE_CONTAINER, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_checkbox(), dtsgui_newxmltreenode(), dtsgui_textbox(), network_config_dns_domain(), and network_config_dns_domain_node().
Referenced by network_tree_setup().
                                                                                                          {
    int flg;
    dtsgui_textbox(p, 'Domain', 'domain', '', NULL);
    dtsgui_textbox(p, 'TSIG Key [Master]', 'key', '', NULL);
    dtsgui_checkbox(p, 'Internal Domain', 'internal', 'true', '', 0, NULL);
    flg = DTS_TREE_NEW_NODE_CONTAINER | DTS_TREE_NEW_NODE_DELETE | DTS_TREE_NEW_NODE_EDIT | DTS_TREE_NEW_NODE_SORT;
    dtsgui_newxmltreenode(self, p, node, '/config/DNS/Hosted', 'Domain', NULL, 'domain', DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN, flg,
                            network_config_dns_domain_node, NULL, network_config_dns_domain);
}
void network_config_dns_domain_node (dtsgui_treeviewtv, dtsgui_treenodetn, struct xml_node *xn, void *data)
Add a container for servers to newly added domain. Parameters:
tv Treeview.
tn New treenode added.
xn XML node reference held by new node.
data reference to data held by node
Definition at line 188 of file netconfig.c.
References DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER_NEW, dtsgui_treecont(), and network_config_dns_domain_server_new().
Referenced by network_config_dns_domain_new().
                                                                                                             {
    dtsgui_treecont(tv, tn, 'Servers', 0, 1, 0, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER_NEW, network_config_dns_domain_server_new, NULL);
}
void network_config_dns_domain_server (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (Hosted Domain Server) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 232 of file netconfig.c.
References dtsgui_treenodegetdata(), dtsgui_treenodegetxml(), and dtsgui_xmltextbox().
Referenced by network_config_dns_domain_server_new().
                                                                                                             {
    const char *xpre;
    struct xml_node *xn = dtsgui_treenodegetxml(node, NULL);
    if (!(xpre = dtsgui_treenodegetdata(node))) {
        objunref(xn);
        return;
    }
    dtsgui_xmltextbox(p, 'Name Server IP Address', 'master', xpre, 'NameServer', NULL, xn->value, NULL);
    objunref((void*)xpre);
    objunref(xn);
}
void network_config_dns_domain_server_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (New Hosted Domain Server) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 251 of file netconfig.c.
References DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), dtsgui_textbox(), dtsgui_treenodeparent(), and network_config_dns_domain_server().
Referenced by network_config_dns_domain_node().
                                                                                                                 {
    const char *domain;
    char xpath[PATH_MAX];
    int len, flg;
    if (!(domain = dtsgui_treenodeparent(node))) {
        return;
    }
    snprintf(xpath, PATH_MAX, '/config/DNS/Hosted/Domain[@domain = '%s']', domain);
    free((void*)domain);
    len = strlen(xpath)+1;
    domain = objalloc(len, NULL);
    memcpy((void*)domain, xpath, len);
    dtsgui_textbox(p, 'Name Server IP Address', 'master', '', NULL);
    flg = DTS_TREE_NEW_NODE_DELETE | DTS_TREE_NEW_NODE_SORT;
    dtsgui_newxmltreenode(self, p, node, xpath, 'NameServer', 'master', 'master', DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER,
                            flg, NULL, (void*)domain, network_config_dns_domain_server);
    objunref((void*)domain);
}
void network_config_dns_dyn (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (Dynamic DNS) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 118 of file netconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
                                                                                                   {
    dtsgui_xmltextbox(p, 'Dynamic DNS Domain', 'DynZone', '/config/DNS/Config', 'Option', 'option', 'DynZone', NULL);
    dtsgui_xmltextbox(p, 'Dynamic DNS Server', 'DynServ', '/config/DNS/Config', 'Option', 'option', 'DynServ', NULL);
    dtsgui_xmltextbox(p, 'Dynamic DNS Secret', 'DynKey', '/config/DNS/Config', 'Option', 'option', 'DynKey', NULL);
    dtsgui_xmltextbox(p, 'Dynamic Zone TTL', 'DynamicTTL', '/config/DNS/Config', 'Option', 'option', 'DynamicTTL', NULL);
    dtsgui_xmlcheckbox(p, 'Add CNAME For host', 'DynamicCNAME', 'true', '', '/config/DNS/Config', 'Option', 'option', 'DynamicCNAME', NULL);
}
void network_config_dns_host (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (DNS Hosts) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 159 of file netconfig.c.
References dtsgui_treenodegetxml(), and dtsgui_xmltextbox().
Referenced by network_config_dns_host_new(), and network_tree_setup().
                                                                                                    {
    const char *xpre = '/config/DNS/Hosts';
    struct xml_node *xn = dtsgui_treenodegetxml(node, NULL);
    dtsgui_xmltextbox(p, 'IP Address', 'ipaddr', xpre, 'Host', NULL, xn->value, 'ipaddr');
    dtsgui_xmltextbox(p, 'MAC Address', 'macaddr', xpre, 'Host', NULL, xn->value, 'macaddr');
    objunref(xn);
}
void network_config_dns_host_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (New DNS Host) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 174 of file netconfig.c.
References DTS_NODE_NETWORK_CONFIG_DNS_HOST, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), dtsgui_textbox(), and network_config_dns_host().
Referenced by network_tree_setup().
                                                                                                        {
    dtsgui_textbox(p, 'Hostame', 'host', '', NULL);
    dtsgui_textbox(p, 'IP Address', 'ipaddr', '', NULL);
    dtsgui_textbox(p, 'Mac Address', 'macaddr', '', NULL);
    dtsgui_newxmltreenode(self, p, node, '/config/DNS/Hosts', 'Host', 'host', 'host', DTS_NODE_NETWORK_CONFIG_DNS_HOST,
                            DTS_TREE_NEW_NODE_DELETE | DTS_TREE_NEW_NODE_EDIT | DTS_TREE_NEW_NODE_SORT, NULL, NULL, network_config_dns_host);
}
void network_config_dns_serv (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (DNS Server) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 131 of file netconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
                                                                                                    {
    dtsgui_xmltextbox(p, 'Shared Secret For Domain Updates', 'SmartKey', '/config/DNS/Config', 'Option', 'option', 'SmartKey', NULL);
    dtsgui_xmlcheckbox(p, 'Backup Zone Files', 'Backup', 'true', '', '/config/DNS/Config', 'Option', 'option', 'Backup', NULL);
    dtsgui_xmlcheckbox(p, 'Authorotive [Internal]', 'Auth', 'true', '', '/config/DNS/Config', 'Option', 'option', 'Auth', NULL);
    dtsgui_xmlcheckbox(p, 'Authorotive [External]', 'AuthX', 'true', '','/config/DNS/Config', 'Option', 'option', 'AuthX', NULL);
    dtsgui_xmlcheckbox(p, 'Use DNS Servers Obtained From PPP', 'Usepeer', 'true', '', '/config/DNS/Config', 'Option', 'option', 'Usepeer', NULL);
    dtsgui_xmlcheckbox(p, 'Allow Recursive Lookup Externally', 'ExtServ', 'true', '', '/config/DNS/Config', 'Option', 'option', 'ExtServ', NULL);
}
void network_config_dns_zone (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (DNS Zone Defaults) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 146 of file netconfig.c.
References dtsgui_xmltextbox().
Referenced by network_tree_setup().
                                                                                                    {
    dtsgui_xmltextbox(p, 'SOA Serial', 'Serial', '/config/DNS/Config', 'Option', 'option', 'Serial', NULL);
    dtsgui_xmltextbox(p, 'SOA Refresh', 'Refresh', '/config/DNS/Config', 'Option', 'option', 'Refresh', NULL);
    dtsgui_xmltextbox(p, 'SOA Retry', 'Retry', '/config/DNS/Config', 'Option', 'option', 'Retry', NULL);
    dtsgui_xmltextbox(p, 'SOA Expire', 'Expire', '/config/DNS/Config', 'Option', 'option', 'Expire', NULL);
    dtsgui_xmltextbox(p, 'Default TTL', 'DefaultTTL', '/config/DNS/Config', 'Option', 'option', 'DefaultTTL', NULL);
}
void network_iface (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (Network Interface) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 296 of file netconfig.c.
References dtsgui_treenodegetxml(), and network_iface_pane().
Referenced by network_newiface(), and network_tree_setup().
                                                                                          {
    struct xml_node *xn = dtsgui_treenodegetxml(node, NULL);
    const char *xpre = '/config/IP/Interfaces';
    const char *iface = data;
    network_iface_pane(p, xpre, iface);
    objunref(xn);
}
void network_iface_new_pane (dtsgui_panep)
Network interface stub shared with interface config. Parameters:
p Panel been configured.
Definition at line 307 of file netconfig.c.
References dtsgui_textbox().
Referenced by network_iface_new_pane_cb(), and network_newiface().
                                           {
    dtsgui_textbox(p, 'Name', 'name', '', NULL);
    dtsgui_textbox(p, 'Interface', 'iface', '', NULL);
    dtsgui_textbox(p, 'IP Address', 'ipaddr', '0', NULL);
    dtsgui_textbox(p, 'IP Subnet Bits', 'subnet', '32', NULL);
    dtsgui_textbox(p, 'DHCP Gateway', 'gateway', '', NULL);
    dtsgui_textbox(p, 'MAC Address', 'macaddr', '00:00:00:00:00:00', NULL);
    dtsgui_textbox(p, 'DHCP Start Address', 'dhcpstart', '-', NULL);
    dtsgui_textbox(p, 'DHCP End Address', 'dhcpend', '-', NULL);
    dtsgui_textbox(p, 'Bandwidth In', 'bwin', '', NULL);
    dtsgui_textbox(p, 'Bandwidth Out', 'bwout', '', NULL);
}
void network_iface_pane (dtsgui_panep, const char *xpre, const char *iface)
Network interface stub shared with interface config. Parameters:
p Panel been configured.
xpre Xpath for this interface.
iface Interface name.
Definition at line 279 of file netconfig.c.
References dtsgui_xmltextbox().
Referenced by network_iface(), and network_iface_pane_cb().
                                                                            {
    dtsgui_xmltextbox(p, 'Interface', 'iface', xpre, 'Interface', NULL, iface, NULL);
    dtsgui_xmltextbox(p, 'IP Address', 'ipaddr', xpre, 'Interface', NULL, iface, 'ipaddr');
    dtsgui_xmltextbox(p, 'IP Subnet Bits', 'subnet', xpre, 'Interface', NULL, iface, 'subnet');
    dtsgui_xmltextbox(p, 'DHCP Gateway', 'gateway', xpre, 'Interface', NULL, iface, 'gateway');
    dtsgui_xmltextbox(p, 'MAC Address', 'macaddr', xpre, 'Interface', NULL, iface, 'macaddr');
    dtsgui_xmltextbox(p, 'DHCP Start Address', 'dhcpstart', xpre, 'Interface', NULL, iface, 'dhcpstart');
    dtsgui_xmltextbox(p, 'DHCP End Address', 'dhcpend', xpre, 'Interface', NULL, iface, 'dhcpend');
    dtsgui_xmltextbox(p, 'Bandwidth In', 'bwin', xpre, 'Interface', NULL, iface, 'bwin');
    dtsgui_xmltextbox(p, 'Bandwidth Out', 'bwout', xpre, 'Interface', NULL, iface, 'bwout');
}
void network_modem (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (Modem Config) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 497 of file netconfig.c.
References dtsgui_listbox_add(), dtsgui_xmllistbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
                                                                                          {
    struct form_item *lb;
    /*XXX LDAP Settings server/DN*/
    if ((lb = dtsgui_xmllistbox(p, 'Connection Type', 'Connection', '/config/IP/Dialup', 'Option', 'option', 'Connection', NULL))) {
        dtsgui_listbox_add(lb, 'Dialup', 'Dialup');
        dtsgui_listbox_add(lb, 'Leased', 'Leased');
        dtsgui_listbox_add(lb, 'ADSL', 'ADSL');
        dtsgui_listbox_add(lb, '3G', '3G');
        dtsgui_listbox_add(lb, '3GIPW', '3GIPW');
        objunref(lb);
    }
    dtsgui_xmltextbox(p, 'Number/Service ID/APN', 'Number', '/config/IP/Dialup', 'Option', 'option', 'Number', NULL);
    dtsgui_xmltextbox(p, 'Username', 'Username', '/config/IP/Dialup', 'Option', 'option', 'Username', NULL);
    dtsgui_xmltextbox(p, 'Password', 'Password', '/config/IP/Dialup', 'Option', 'option', 'Password', NULL);
}
void network_modem_adv (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (Advanced Modem Config) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 520 of file netconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
                                                                                              {
    dtsgui_xmltextbox(p, 'Holdoff Time', 'Holdoff', '/config/IP/Dialup', 'Option', 'option', 'Holdoff', NULL);
    dtsgui_xmltextbox(p, 'MTU/MRU', 'MTU', '/config/IP/Dialup', 'Option', 'option', 'MTU', NULL);
    dtsgui_xmltextbox(p, 'Idle Timeout', 'IdleTimeout', '/config/IP/Dialup', 'Option', 'option', 'IdleTimeout', NULL);
    dtsgui_xmltextbox(p, 'Fail Limit', 'MaxFail', '/config/IP/Dialup', 'Option', 'option', 'MaxFail', NULL);
    dtsgui_xmltextbox(p, 'Connect Dely', 'ConnectDelay', '/config/IP/Dialup', 'Option', 'option', 'ConnectDelay', NULL);
    dtsgui_xmlcheckbox(p, 'BSD Compression', 'BSD', 'true', '', '/config/IP/Dialup', 'Option', 'option', 'BSD', NULL);
    dtsgui_xmlcheckbox(p, 'Deflate Compression', 'Deflate', 'true', '', '/config/IP/Dialup', 'Option', 'option', 'Deflate', NULL);
}
void network_modem_ana (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (Analogue Modem Config) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 536 of file netconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
                                                                                              {
    struct form_item *lb;
    if ((lb = dtsgui_xmllistbox(p, 'Comm Port ', 'ComPort', '/config/IP/Dialup', 'Option', 'option', 'ComPort', NULL))) {
        dtsgui_listbox_add(lb, 'COM1', 'COM1');
        dtsgui_listbox_add(lb, 'COM2', 'COM2');
        dtsgui_listbox_add(lb, 'COM3', 'COM3');
        dtsgui_listbox_add(lb, 'COM4', 'COM4');
        dtsgui_listbox_add(lb, 'USB0', 'USB0');
        dtsgui_listbox_add(lb, 'USB1', 'USB1');
        dtsgui_listbox_add(lb, 'USB2', 'USB2');
        dtsgui_listbox_add(lb, 'USB3', 'USB3');
        objunref(lb);
    }
    if ((lb = dtsgui_xmllistbox(p, 'Port Speed', 'Speed', '/config/IP/Dialup', 'Option', 'option', 'Speed', NULL))) {
        dtsgui_listbox_add(lb, '115200', '115200');
        dtsgui_listbox_add(lb, '57600', '57600');
        dtsgui_listbox_add(lb, '38400', '38400');
        dtsgui_listbox_add(lb, '19200', '19200');
        dtsgui_listbox_add(lb, '9600', '9600');
        objunref(lb);
    }
    if ((lb = dtsgui_xmllistbox(p, 'Flow Control ', 'FlowControl', '/config/IP/Dialup', 'Option', 'option', 'FlowControl', NULL))) {
        dtsgui_listbox_add(lb, 'Hardware (RTS/CTS)', 'crtscts');
        dtsgui_listbox_add(lb, 'Software (Xon/Xoff)', 'xonxoff');
        dtsgui_listbox_add(lb, 'Hardware (DTR/CTS)', 'cdtrcts');
        dtsgui_listbox_add(lb, 'None', '');
        objunref(lb);
    }
    dtsgui_xmltextbox(p, 'Local Address', 'Address', '/config/IP/Dialup', 'Option', 'option', 'Address', NULL);
    dtsgui_xmltextbox(p, 'Remote Address', 'Gateway', '/config/IP/Dialup', 'Option', 'option', 'Gateway', NULL);
    dtsgui_xmltextbox(p, 'Init String 1', 'Init1', '/config/IP/Dialup', 'Option', 'option', 'Init1', NULL);
    dtsgui_xmltextbox(p, 'Init String 2', 'Init2', '/config/IP/Dialup', 'Option', 'option', 'Init2', NULL);
    dtsgui_xmltextbox(p, 'Dial String', 'DialString', '/config/IP/Dialup', 'Option', 'option', 'DialString', NULL);
    dtsgui_xmlcheckbox(p, 'Abort On No Carrier', 'NoCarrier', 'true', '','/config/IP/Dialup', 'Option', 'option', 'NoCarrier', NULL);
    dtsgui_xmlcheckbox(p, 'Abort On No Dialtone', 'NoDialtone', 'true', '', '/config/IP/Dialup', 'Option', 'option', 'NoDialtone', NULL);
    dtsgui_xmlcheckbox(p, 'Abort On Error', 'Error', 'true', '', '/config/IP/Dialup', 'Option', 'option', 'Error', NULL);
    dtsgui_xmlcheckbox(p, 'Abort On Busy', 'Busy', 'true', '', '/config/IP/Dialup', 'Option', 'option', 'Busy', NULL);
}
void network_newiface (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (New Network Interface) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 325 of file netconfig.c.
References DTS_NODE_NETWORK_IFACE, DTS_TREE_NEW_NODE_CONTAINER, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), network_iface(), and network_iface_new_pane().
Referenced by network_tree_setup().
                                                                                             {
    int flg;
    network_iface_new_pane(p);
    flg = DTS_TREE_NEW_NODE_CONTAINER | DTS_TREE_NEW_NODE_DELETE | DTS_TREE_NEW_NODE_EDIT | DTS_TREE_NEW_NODE_SORT;
    dtsgui_newxmltreenode(self, p, node, '/config/IP/Interfaces', 'Interface', 'iface', 'name', DTS_NODE_NETWORK_IFACE,
                            flg, NULL, NULL, network_iface);
}
void network_newroute (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (New Static Route) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 479 of file netconfig.c.
References DTS_NODE_NETWORK_ROUTE, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), dtsgui_textbox(), and network_route().
Referenced by network_tree_setup().
                                                                                             {
    int flg;
    dtsgui_textbox(p, 'Description', 'descrip', '', NULL);
    dtsgui_textbox(p, 'Network', 'network', '', NULL);
    dtsgui_textbox(p, 'Subnet Bits', 'subnet', '', NULL);
    dtsgui_textbox(p, 'Gateway', 'gateway', '', NULL);
    flg = DTS_TREE_NEW_NODE_DELETE | DTS_TREE_NEW_NODE_EDIT | DTS_TREE_NEW_NODE_SORT;
    dtsgui_newxmltreenode(self, p, node, '/config/IP/GenRoutes', 'Route', 'descrip', NULL, DTS_NODE_NETWORK_ROUTE,
                                flg, NULL, NULL, network_route);
}
void network_newwan (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (New Wan Route) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 443 of file netconfig.c.
References DTS_NODE_NETWORK_WAN, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), dtsgui_textbox(), and network_wan().
Referenced by network_tree_setup().
                                                                                           {
    int flg;
    dtsgui_textbox(p, 'Description', 'descrip', '', NULL);
    dtsgui_textbox(p, 'Network', 'network', '', NULL);
    dtsgui_textbox(p, 'Subnet Bits', 'subnet', '', NULL);
    dtsgui_textbox(p, 'Gateway [Local]', 'gateway', '', NULL);
    dtsgui_textbox(p, 'DHCP Start Address', 'dhcpstart', '', NULL);
    dtsgui_textbox(p, 'DHCP End Address', 'dhcpend', '', NULL);
    dtsgui_textbox(p, 'Gateway [Remote]', 'remote', '', NULL);
    flg = DTS_TREE_NEW_NODE_DELETE | DTS_TREE_NEW_NODE_EDIT | DTS_TREE_NEW_NODE_SORT;
    dtsgui_newxmltreenode(self, p, node, '/config/IP/Routes', 'Route', 'descrip', NULL, DTS_NODE_NETWORK_WAN,
                            flg, NULL, NULL, network_wan);
}
void network_newwifi (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (New WiFi Interface) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 377 of file netconfig.c.
References DTS_NODE_NETWORK_WIFI, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_SORT, dtsgui_listbox(), dtsgui_listbox_add(), dtsgui_listbox_addxml(), dtsgui_listbox_set(), dtsgui_newxmltreenode(), dtsgui_panelxml(), dtsgui_textbox(), and network_wifi().
Referenced by network_tree_setup().
                                                                                            {
    struct xml_doc *xmldoc = dtsgui_panelxml(p);
    struct form_item *lb;
    int flg;
    lb = dtsgui_listbox(p, 'WiFi Interface', 'iface', NULL);
    dtsgui_listbox_addxml(lb, xmldoc, '/config/IP/Interfaces/Interface', 'name', NULL);
    objunref(lb);
    lb = dtsgui_listbox(p, 'WiFi Configuration', 'type', NULL);
    dtsgui_listbox_add(lb, 'Access Point', 'AP');
    dtsgui_listbox_add(lb, 'WiFi Client', 'Client');
    dtsgui_listbox_add(lb, 'Hotspot', 'Hotspot');
    dtsgui_listbox_set(lb, 0);
    objunref(lb);
    lb = dtsgui_listbox(p, 'WiFi Mode', 'mode', NULL);
    dtsgui_listbox_add(lb, '802.11a', '0');
    dtsgui_listbox_add(lb, '802.11b [ch 1/6/11/14]', '1');
    dtsgui_listbox_add(lb, '802.11g [ch 1/5/9/13]', '2');
    dtsgui_listbox_add(lb, '802.11n 20Mhz [ch 1/5/9/13]', '3');
    dtsgui_listbox_add(lb, '802.11n 40Mhz [ch 3/11]', '4');
    dtsgui_listbox_set(lb, 2);
    objunref(lb);
    lb = dtsgui_listbox(p, 'WiFi Auth Type', 'auth', NULL);
    dtsgui_listbox_add(lb, 'WiFi Protected Access', 'WPA');
    dtsgui_listbox_add(lb, 'Extensible Authentication Protocol', 'EAP');
    dtsgui_listbox_add(lb, 'None', 'None');
    dtsgui_listbox_set(lb, 0);
    objunref(lb);
    dtsgui_textbox(p, 'Channel', 'channel', '', NULL);
    dtsgui_textbox(p, 'Key (WPA)', 'key', '', NULL);
    dtsgui_textbox(p, 'Regulatory Domain', 'regdom', 'ZA', NULL);
    dtsgui_textbox(p, 'TX Power', 'txpower', '25', NULL);
    flg = DTS_TREE_NEW_NODE_DELETE | DTS_TREE_NEW_NODE_SORT;
    dtsgui_newxmltreenode(self, p, node, '/config/IP', 'WiFi', 'iface', NULL, DTS_NODE_NETWORK_WIFI,
                            flg, NULL, NULL, network_wifi);
    objunref(xmldoc);
}
void network_route (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (Static Route) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 464 of file netconfig.c.
References dtsgui_treenodegetxml(), and dtsgui_xmltextbox().
Referenced by network_newroute(), and network_tree_setup().
                                                                                          {
    const char *xpre = '/config/IP/GenRoutes';
    struct xml_node *xn = dtsgui_treenodegetxml(node, NULL);
    dtsgui_xmltextbox(p, 'Network', 'network', xpre, 'Route', NULL, xn->value, 'network');
    dtsgui_xmltextbox(p, 'Subnet Bits', 'subnet', xpre, 'Route', NULL, xn->value, 'subnet');
    dtsgui_xmltextbox(p, 'Gateway', 'gateway', xpre, 'Route', NULL, xn->value, 'gateway');
    objunref(xn);
}
void network_tos (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (TOS Config) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 684 of file netconfig.c.
References dtsgui_listbox_add(), dtsgui_treenodegetxml(), dtsgui_xmllistbox(), dtsgui_xmltextbox(), form_item::name, and protocols.
Referenced by network_tos_new(), and network_tree_setup().
                                                                                        {
    struct form_item *lb;
    int pcnt, i;
    const char *xpre = '/config/IP/QOS';
    const char *name;
    struct xml_node *xn;
    if (!(xn = dtsgui_treenodegetxml(node, NULL))) {
        return;
    }
    name = xml_getattr(xn, 'name');
    dtsgui_xmltextbox(p, 'Destination Address', 'ipaddr', xpre, 'TOS', 'name', name, 'ipaddr');
    lb = dtsgui_xmllistbox(p, 'Protocol', 'protocol', xpre, 'TOS', 'name', name, 'protocol');
    pcnt = sizeof(protocols)/sizeof(protocols[0]);
    for(i = 0;i < pcnt;i ++) {
        dtsgui_listbox_add(lb, protocols[i], protocols[i]);
    }
    objunref(lb);
    dtsgui_xmltextbox(p, 'Destination Port', 'dport', xpre, 'TOS', 'name', name, 'dport');
    dtsgui_xmltextbox(p, 'Source Port', 'sport', xpre, 'TOS', 'name', name, 'sport');
    lb = dtsgui_xmllistbox(p, 'TOS Setting', 'tos', xpre, 'TOS', 'name', name, NULL);
    dtsgui_listbox_add(lb, 'Normal-Service', 'Normal-Service');
    dtsgui_listbox_add(lb, 'Minimize-Cost', 'Minimize-Cost');
    dtsgui_listbox_add(lb, 'Maximize-Reliability', 'Maximize-Reliability');
    dtsgui_listbox_add(lb, 'Maximize-Throughput', 'Maximize-Throughput');
    dtsgui_listbox_add(lb, 'Minimize-Delay', 'Minimize-Delay');
    objunref(lb);
    lb = dtsgui_xmllistbox(p, 'Priority', 'priority', xpre, 'TOS', 'name', name, 'priority');
    dtsgui_listbox_add(lb, 'High', 'High');
    dtsgui_listbox_add(lb, 'Med', 'Med');
    dtsgui_listbox_add(lb, 'Low', 'Low');
    objunref(lb);
    objunref(xn);
}
void network_tos_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (New TOS Config) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 730 of file netconfig.c.
References DTS_NODE_NETWORK_TOS, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_listbox(), dtsgui_listbox_add(), dtsgui_newxmltreenode(), dtsgui_textbox(), network_tos(), and protocols.
Referenced by network_tree_setup().
                                                                                            {
    struct form_item *lb;
    int pcnt, i, flg;
    dtsgui_textbox(p, 'Description', 'name', '', NULL);
    dtsgui_textbox(p, 'Destination Address', 'ipaddr', '', NULL);
    lb = dtsgui_listbox(p, 'Protocol', 'protocol', NULL);
    pcnt = sizeof(protocols)/sizeof(protocols[0]);
    for(i = 0;i < pcnt;i ++) {
        dtsgui_listbox_add(lb, protocols[i], protocols[i]);
    }
    objunref(lb);
    dtsgui_textbox(p, 'Destination Address', 'ipaddr', '', NULL);
    dtsgui_textbox(p, 'Destination Port', 'dport', '', NULL);
    dtsgui_textbox(p, 'Source Port', 'sport', '1024:65535', NULL);
    lb = dtsgui_listbox(p, 'TOS Setting', 'tos', NULL);
    dtsgui_listbox_add(lb, 'Normal-Service', 'Normal-Service');
    dtsgui_listbox_add(lb, 'Minimize-Cost', 'Minimize-Cost');
    dtsgui_listbox_add(lb, 'Maximize-Reliability', 'Maximize-Reliability');
    dtsgui_listbox_add(lb, 'Maximize-Throughput', 'Maximize-Throughput');
    dtsgui_listbox_add(lb, 'Minimize-Delay', 'Minimize-Delay');
    objunref(lb);
    lb = dtsgui_listbox(p, 'Priority', 'priority', NULL);
    dtsgui_listbox_add(lb, 'High', 'High');
    dtsgui_listbox_add(lb, 'Med', 'Med');
    dtsgui_listbox_add(lb, 'Low', 'Low');
    objunref(lb);
    flg = DTS_TREE_NEW_NODE_DELETE | DTS_TREE_NEW_NODE_EDIT | DTS_TREE_NEW_NODE_SORT;
    dtsgui_newxmltreenode(self, p, node, '/config/IP/QOS', 'TOS', 'name', NULL, DTS_NODE_NETWORK_TOS,
                                flg, NULL, NULL, network_tos);
}
void network_tree_setup (dtsgui_treeviewtree, struct xml_doc *xmldoc)
Configure the networking noded on the tree. Parameters:
tree Treeview to add nodes too.
xmldoc XML document to configure nodes from.
Definition at line 770 of file netconfig.c.
References customer_info(), DTS_NODE_CUSTOMER, DTS_NODE_NETWORK_ADSL_LINK, DTS_NODE_NETWORK_ADSL_LINK_NEW, DTS_NODE_NETWORK_ADSL_USER, DTS_NODE_NETWORK_ADSL_USER_NEW, DTS_NODE_NETWORK_CONFIG, DTS_NODE_NETWORK_CONFIG_DNS, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_NEW, DTS_NODE_NETWORK_CONFIG_DNS_DYN, DTS_NODE_NETWORK_CONFIG_DNS_HOST, DTS_NODE_NETWORK_CONFIG_DNS_HOST_NEW, DTS_NODE_NETWORK_CONFIG_DNS_SERV, DTS_NODE_NETWORK_CONFIG_DNS_ZONE, DTS_NODE_NETWORK_IFACE, DTS_NODE_NETWORK_IFACE_NEW, DTS_NODE_NETWORK_MODEM, DTS_NODE_NETWORK_MODEM_ADV, DTS_NODE_NETWORK_MODEM_ANA, DTS_NODE_NETWORK_ROUTE_NEW, DTS_NODE_NETWORK_TOS, DTS_NODE_NETWORK_TOS_NEW, DTS_NODE_NETWORK_WAN, DTS_NODE_NETWORK_WAN_NEW, DTS_NODE_NETWORK_WIFI, DTS_NODE_NETWORK_WIFI_NEW, dtsgui_treecont(), dtsgui_treeitem(), dtsgui_treenodesetxml(), network_adsl_link(), network_adsl_link_new(), network_adsl_user(), network_adsl_user_new(), network_config(), network_config_dns(), network_config_dns_domain(), network_config_dns_domain_new(), network_config_dns_dyn(), network_config_dns_host(), network_config_dns_host_new(), network_config_dns_serv(), network_config_dns_zone(), network_iface(), network_modem(), network_modem_adv(), network_modem_ana(), network_newiface(), network_newroute(), network_newwan(), network_newwifi(), network_route(), network_tos(), network_tos_new(), network_wan(), and network_wifi().
Referenced by advanced_config().
                                                                      {
    dtsgui_treenode cust, ipconf, tmp, tmp2, tln/*, tmp3*/;
    struct xml_search *xp;
    struct xml_node *xn;
    void *iter = NULL;
    cust = dtsgui_treecont(tree, NULL, 'Customer Information', 0, 0, 0, DTS_NODE_CUSTOMER, customer_info, NULL);
    ipconf = dtsgui_treecont(tree, cust, 'Global IP Settings', 0, 0, 0, DTS_NODE_NETWORK_CONFIG, network_config, NULL);
    tln = dtsgui_treecont(tree, ipconf, 'DNS/DHCP Settings', 0, 0, 0, DTS_NODE_NETWORK_CONFIG_DNS, network_config_dns, NULL);
    dtsgui_treeitem(tree, tln, 'Dynamic DNS', 0, 0, 0, DTS_NODE_NETWORK_CONFIG_DNS_DYN, network_config_dns_dyn, NULL);
    dtsgui_treeitem(tree, tln, 'DNS Server Options', 0, 0, 0, DTS_NODE_NETWORK_CONFIG_DNS_SERV, network_config_dns_serv, NULL);
    dtsgui_treeitem(tree, tln, 'DNS Zone Defaults', 0, 0, 0, DTS_NODE_NETWORK_CONFIG_DNS_ZONE, network_config_dns_zone, NULL);
    tmp = dtsgui_treecont(tree, tln, 'Static Hosts', 0, 1, 0, DTS_NODE_NETWORK_CONFIG_DNS_HOST_NEW, network_config_dns_host_new, NULL);
    xp = xml_xpath(xmldoc, '/config/DNS/Hosts/Host', NULL);
    for(xn = xml_getfirstnode(xp, &iter); xn; xn = xml_getnextnode(iter)) {
        tmp2 = dtsgui_treeitem(tree, tmp, xn->value, 1, 1, 1, DTS_NODE_NETWORK_CONFIG_DNS_HOST, network_config_dns_host, NULL);
        dtsgui_treenodesetxml(tmp2, xn, NULL);
        objunref(xn);
    }
    objunref(xp);
    objunref(iter);
    iter = NULL;
    dtsgui_treecont(tree, tln, 'Hosted Domains', 0, 1, 0, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_NEW, network_config_dns_domain_new, NULL);
    xp = xml_xpath(xmldoc, '/config/DNS/Hosted/Domain', NULL);
    for(xn = xml_getfirstnode(xp, &iter); xn; xn = xml_getnextnode(iter)) {
        tmp2 = dtsgui_treeitem(tree, tmp, xn->value, 1, 1, 1, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN, network_config_dns_domain, NULL);
        dtsgui_treenodesetxml(tmp2, xn, NULL);
/* xp2 = xml_xpath(xmldoc, '/config/DNS/Hosted/Domain', NULL);
        for(xn = xml_getfirstnode(xp2, &iter); xn2; xn2 = xml_getnextnode(iter2)) {
            tmp3 = dtsgui_treeitem(tree, tmp2, xn2->value, 1, 1, 1, DTS_NODE_NETWORK_CONFIG_DNS_HOST, NULL);
            dtsgui_treenodesetxml(tree, tmp3, xn2, NULL);
            objunref(xn2);
        }
        objunref(xp2);*/
        objunref(xn);
    }
    objunref(xp);
    objunref(iter);
    iter = NULL;
    tln = dtsgui_treecont(tree, ipconf, 'Network Interfaces', 0, 0, 0, -1, NULL, NULL);
    tmp = dtsgui_treecont(tree, tln, 'Ethernet Interfaces', 0, 1, 0, DTS_NODE_NETWORK_IFACE_NEW, network_newiface, NULL);
    xp = xml_xpath(xmldoc, '/config/IP/Interfaces/Interface', 'name');
    for(xn = xml_getfirstnode(xp, &iter); xn; xn = xml_getnextnode(iter)) {
        tmp2 = dtsgui_treecont(tree, tmp, xml_getattr(xn, 'name'), 1, 1, 1, DTS_NODE_NETWORK_IFACE, network_iface, NULL);
        dtsgui_treenodesetxml(tmp2, xn, 'name');
        objunref(xn);
    }
    objunref(xp);
    objunref(iter);
    iter = NULL;
    tmp = dtsgui_treecont(tree, tln, 'Wireless Config', 0, 1, 0, DTS_NODE_NETWORK_WIFI_NEW, network_newwifi, NULL);
    xp = xml_xpath(xmldoc, '/config/IP/WiFi', NULL);
    for(xn = xml_getfirstnode(xp, &iter); xn; xn = xml_getnextnode(iter)) {
        tmp2 = dtsgui_treeitem(tree, tmp, xn->value, 0, 1, 1, DTS_NODE_NETWORK_WIFI, network_wifi, NULL);
        dtsgui_treenodesetxml(tmp2, xn, NULL);
        objunref(xn);
    }
    objunref(xp);
    objunref(iter);
    iter = NULL;
    tln = dtsgui_treecont(tree, ipconf, 'Static Routes', 0, 0, 0, -1, NULL, NULL);
    tmp = dtsgui_treecont(tree, tln, 'Wan Routing/Nodes', 0, 1, 0, DTS_NODE_NETWORK_WAN_NEW, network_newwan, NULL);
    xp = xml_xpath(xmldoc, '/config/IP/Routes/Route', NULL);
    for(xn = xml_getfirstnode(xp, &iter); xn; xn = xml_getnextnode(iter)) {
        tmp2 = dtsgui_treeitem(tree, tmp, xn->value, 1, 1, 1, DTS_NODE_NETWORK_WAN, network_wan, NULL);
        dtsgui_treenodesetxml(tmp2, xn, NULL);
        objunref(xn);
    }
    objunref(xp);
    objunref(iter);
    iter = NULL;
    tmp = dtsgui_treecont(tree, tln, 'Other Routes', 0, 1, 0, DTS_NODE_NETWORK_ROUTE_NEW, network_newroute, NULL);
    xp = xml_xpath(xmldoc, '/config/IP/GenRoutes/Route', NULL);
    for(xn = xml_getfirstnode(xp, &iter); xn; xn = xml_getnextnode(iter)) {
        tmp2 = dtsgui_treeitem(tree, tmp, xn->value, 1, 1, 1, DTS_NODE_NETWORK_WAN, network_route, NULL);
        dtsgui_treenodesetxml(tmp2, xn, NULL);
        objunref(xn);
    }
    objunref(xp);
    objunref(iter);
    iter = NULL;
    tln = dtsgui_treecont(tree, ipconf, 'PPP Config (DSL/3G)', 0, 0, 0, DTS_NODE_NETWORK_MODEM, network_modem, NULL);
    dtsgui_treeitem(tree, tln, 'Advanced Settings', 0, 0, 0, DTS_NODE_NETWORK_MODEM_ADV, network_modem_adv, NULL);
    dtsgui_treeitem(tree, tln, 'Dialup/Leased', 0, 0, 0, DTS_NODE_NETWORK_MODEM_ANA, network_modem_ana, NULL);
    dtsgui_treecont(tree, tln, 'Modem Firewall Rules', 0, 1, 0, -1, NULL, NULL);
    tmp = dtsgui_treecont(tree, tln, 'Additional ADSL Links', 0, 1, 0, DTS_NODE_NETWORK_ADSL_LINK_NEW, network_adsl_link_new, NULL);
    xp = xml_xpath(xmldoc, '/config/IP/ADSL/Links/Link', NULL);
    for(xn = xml_getfirstnode(xp, &iter); xn; xn = xml_getnextnode(iter)) {
        tmp2 = dtsgui_treeitem(tree, tmp, xn->value, 1, 1, 1, DTS_NODE_NETWORK_ADSL_LINK, network_adsl_link, NULL);
        dtsgui_treenodesetxml(tmp2, xn, NULL);
        objunref(xn);
    }
    objunref(xp);
    objunref(iter);
    iter = NULL;
    tmp = dtsgui_treecont(tree, tln, 'ADSL Accounts', 0, 1, 0, DTS_NODE_NETWORK_ADSL_USER_NEW, network_adsl_user_new, NULL);
    xp = xml_xpath(xmldoc, '/config/IP/ADSL/Users/User', NULL);
    for(xn = xml_getfirstnode(xp, &iter); xn; xn = xml_getnextnode(iter)) {
        tmp2 = dtsgui_treeitem(tree, tmp, xn->value, 1, 1, 1, DTS_NODE_NETWORK_ADSL_USER, network_adsl_user, NULL);
        dtsgui_treenodesetxml(tmp2, xn, NULL);
        objunref(xn);
    }
    objunref(xp);
    objunref(iter);
    iter = NULL;
    tmp = dtsgui_treecont(tree, ipconf, 'Default TOS', 0, 1, 0, DTS_NODE_NETWORK_TOS_NEW, network_tos_new, NULL);
    xp = xml_xpath(xmldoc, '/config/IP/QOS/TOS', NULL);
    for(xn = xml_getfirstnode(xp, &iter); xn; xn = xml_getnextnode(iter)) {
        tmp2 = dtsgui_treeitem(tree, tmp, xml_getattr(xn, 'name'), 1, 1, 1, DTS_NODE_NETWORK_TOS, network_tos, NULL);
        dtsgui_treenodesetxml(tmp2, xn, NULL);
        objunref(xn);
    }
    objunref(xp);
    objunref(iter);
    iter = NULL;
    tln = dtsgui_treecont(tree, ipconf, 'VPN Configuration', 0, 0, 0, -1, NULL, NULL);
    dtsgui_treecont(tree, tln, 'GRE VPN Tunnels', 0, 1, 0, -1, NULL, NULL);
    dtsgui_treecont(tree, tln, 'ESP VPN Tunnels', 0, 1, 0, -1, NULL, NULL);
    dtsgui_treecont(tree, tln, 'ESP Remote Access', 0, 1, 0, -1, NULL, NULL);
    tln = dtsgui_treecont(tree, ipconf, 'Voice & FAX Over IP', 0, 0, 0, -1, NULL, NULL);
    dtsgui_treecont(tree, tln, 'VOIP Registrations', 0, 0, 0, -1, NULL, NULL);
    dtsgui_treecont(tree, tln, 'FAX Config', 0, 0, 0, -1, NULL, NULL);
    dtsgui_treecont(tree, ipconf, 'Secuity Certificate Config', 0, 0, 0, -1, NULL, NULL);
}
void network_wan (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (WAN Route) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 425 of file netconfig.c.
References dtsgui_treenodegetxml(), and dtsgui_xmltextbox().
Referenced by network_newwan(), and network_tree_setup().
                                                                                        {
    const char *xpre = '/config/IP/Routes';
    struct xml_node *xn = dtsgui_treenodegetxml(node, NULL);
    dtsgui_xmltextbox(p, 'Network', 'network', xpre, 'Route', NULL, xn->value, 'network');
    dtsgui_xmltextbox(p, 'Subnet Bits', 'subnet', xpre, 'Route', NULL, xn->value, 'subnet');
    dtsgui_xmltextbox(p, 'Gateway [Local]', 'gateway', xpre, 'Route', NULL, xn->value, 'gateway');
    dtsgui_xmltextbox(p, 'DHCP Start Address', 'dhcpstart', xpre, 'Route', NULL, xn->value, 'dhcpstart');
    dtsgui_xmltextbox(p, 'DHCP End Address', 'dhcpend', xpre, 'Route', NULL, xn->value, 'dhcpend');
    dtsgui_xmltextbox(p, 'Gateway [Remote]', 'remote', xpre, 'Route', NULL, xn->value, 'remote');
    objunref(xn);
}
void network_wifi (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Tree pane configuration call back (WiFi Interface) Parameters:
p panel to be configured.
self Tree view.
node Active tree node.
data reference to data held by node
Definition at line 340 of file netconfig.c.
References dtsgui_listbox_add(), dtsgui_treenodegetxml(), dtsgui_xmlcombobox(), and dtsgui_xmltextbox().
Referenced by network_newwifi(), and network_tree_setup().
                                                                                         {
    const char *xpre = '/config/IP';
    struct form_item *lb;
    struct xml_node *xn = dtsgui_treenodegetxml(node, NULL);
    lb = dtsgui_xmlcombobox(p, 'WiFi Configuration', 'type', xpre, 'WiFi', NULL, xn->value, 'type');
    dtsgui_listbox_add(lb, 'Access Point', 'AP');
    dtsgui_listbox_add(lb, 'WiFi Client', 'Client');
    dtsgui_listbox_add(lb, 'Hotspot', 'Hotspot');
    objunref(lb);
    lb = dtsgui_xmlcombobox(p, 'WiFi Mode', 'mode', xpre, 'WiFi', NULL, xn->value, 'mode');
    dtsgui_listbox_add(lb, '802.11a', '0');
    dtsgui_listbox_add(lb, '802.11b [ch 1/6/11/14]', '1');
    dtsgui_listbox_add(lb, '802.11g [ch 1/5/9/13]', '2');
    dtsgui_listbox_add(lb, '802.11n 20Mhz [ch 1/5/9/13]', '3');
    dtsgui_listbox_add(lb, '802.11n 40Mhz [ch 3/11]', '4');
    objunref(lb);
    lb = dtsgui_xmlcombobox(p, 'WiFi Auth Type', 'auth', xpre, 'WiFi', NULL, xn->value, 'auth');
    dtsgui_listbox_add(lb, 'WiFi Protected Access', 'WPA');
    dtsgui_listbox_add(lb, 'Extensible Authentication Protocol', 'EAP');
    dtsgui_listbox_add(lb, 'None', 'None');
    objunref(lb);
    dtsgui_xmltextbox(p, 'Channel', 'channel', xpre, 'WiFi', NULL, xn->value, 'channel');
    dtsgui_xmltextbox(p, 'Key (WPA)', 'key', xpre, 'WiFi', NULL, xn->value, 'key');
    dtsgui_xmltextbox(p, 'Regulatory Domain', 'regdom', xpre, 'WiFi', NULL, xn->value, 'regdom');
    dtsgui_xmltextbox(p, 'TX Power', 'txpower', xpre, 'WiFi', NULL, xn->value, 'txpower');
    objunref(xn);
}
Variable Documentation
const char* protocols[] = {'TCP', 'UDP', 'GRE', 'ESP', 'AH', 'OSPF', 'ALL'} [static]
Array of network protocols.
Definition at line 40 of file netconfig.c.
Referenced by network_tos(), and network_tos_new().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.