Application test panel
NAME
Application test panel -
Static window with standard elements that will post to a URL and pop up the result.
Files
file testing.c
Test panel.
Functions
void post_items (struct dtsgui *dtsgui, dtsgui_pane p)
Create a curl post object and submit to url.
int handle_test (struct dtsgui *dtsgui, dtsgui_pane p, int type, int event, void *data)
panel event handler.
void testpanel (dtsgui_pane p)
Configure a panel with test elements.
void test_menu (struct dtsgui *dtsgui, dtsgui_menu menu, const char *url)
Add test option to menu.
Detailed Description
Static window with standard elements that will post to a URL and pop up the result.
This is for testing the basic features and curl integration.
Function Documentation
int handle_test (struct dtsgui *dtsgui, dtsgui_panep, inttype, intevent, void *data)
panel event handler. Filter all but button events and on Apply/Yes post the panel to URL. Other butons pressed will pop up a alert box with the button pressed.
Parameters:
dtsgui Application data ptr.
p The panel generating the events.
type Type of event generated.
event The event generated.
data Reference to userdata set with eventhandler.
Returns:
0 to mark the event as handled or non zero to pass handling on.
Definition at line 70 of file testing.c.
References dtsgui_alert(), post_items(), wx_PANEL_EVENT_BUTTON, wx_PANEL_EVENT_BUTTON_BACK, wx_PANEL_EVENT_BUTTON_FIRST, wx_PANEL_EVENT_BUTTON_FWD, wx_PANEL_EVENT_BUTTON_LAST, wx_PANEL_EVENT_BUTTON_NO, and wx_PANEL_EVENT_BUTTON_YES.
Referenced by test_menu().
                                                                                       {
    if (type != wx_PANEL_EVENT_BUTTON) {
        return 1;
    }
    switch(event) {
        case wx_PANEL_EVENT_BUTTON_YES:
            post_items(dtsgui, p);
            break;
        case wx_PANEL_EVENT_BUTTON_NO:
            dtsgui_alert(dtsgui, 'Undo');
            break;
        case wx_PANEL_EVENT_BUTTON_FIRST:
            dtsgui_alert(dtsgui, 'First');
            break;
        case wx_PANEL_EVENT_BUTTON_LAST:
            dtsgui_alert(dtsgui, 'Last');
            break;
        case wx_PANEL_EVENT_BUTTON_BACK:
            dtsgui_alert(dtsgui, 'Back');
            break;
        case wx_PANEL_EVENT_BUTTON_FWD:
            dtsgui_alert(dtsgui, 'Forward');
            break;
    }
    return 1;
}
void post_items (struct dtsgui *dtsgui, dtsgui_panep)
Create a curl post object and submit to url. The panel data contains the URL
Parameters:
dtsgui Application data ptr.
p panel to be posted.
Returns:
Nothing is returned a alert box is popped up on success.
Definition at line 41 of file testing.c.
References dtsgui_alert(), dtsgui_pane2post(), and dtsgui_paneldata().
Referenced by handle_test().
                                                      {
    struct curl_post *post;
    struct curlbuf *cbuf;
    const char *url;
    url = dtsgui_paneldata(p);
    post = dtsgui_pane2post(p);
    cbuf = curl_posturl(url, NULL, post, NULL, NULL);
    if (cbuf && cbuf->body) {
        dtsgui_alert(dtsgui, (char*)cbuf->body);
    }
    if (cbuf) {
        objunref(cbuf);
    }
    objunref((void*)url);
}
void test_menu (struct dtsgui *dtsgui, dtsgui_menumenu, const char *url)
Add test option to menu. Parameters:
dtsgui Application data ptr.
menu Menu to append new item too.
url URL to post the panel too.
Definition at line 128 of file testing.c.
References dtsgui_newmenuitem(), dtsgui_panel(), dtsgui_setevcallback(), handle_test(), testpanel(), and wx_PANEL_BUTTON_ALL.
Referenced by help_menu().
                                                                         {
    void *purl;
    dtsgui_pane p;
    purl = objchar(url);
    p = dtsgui_panel(dtsgui, 'Test Panel', 'Test Panel', wx_PANEL_BUTTON_ALL, 1, purl);
    objunref(purl);
    testpanel(p);
    dtsgui_setevcallback(p, handle_test, NULL);
    dtsgui_newmenuitem(menu, dtsgui, '&Test', p);
}
void testpanel (dtsgui_panep)
Configure a panel with test elements. Parameters:
p Panel to configure
Definition at line 100 of file testing.c.
References dtsgui_checkbox(), dtsgui_combobox(), dtsgui_listbox(), dtsgui_listbox_add(), dtsgui_textbox(), and dtsgui_textbox_multi().
Referenced by test_menu().
                              {
    struct form_item *l;
    dtsgui_textbox(p, 'TextBox', 'text', 'Text', NULL);
    dtsgui_textbox_multi(p, 'Multi Line', 'multi', 'L\nL\n', NULL);
    dtsgui_checkbox(p, 'Checkbox', 'check', '1', '0', 1, NULL);
    l = dtsgui_combobox(p, 'ComboBox', 'combo', NULL);
    dtsgui_listbox_add(l, 'Test1', NULL);
    dtsgui_listbox_add(l, 'Test2', NULL);
    dtsgui_listbox_add(l, 'Test3', NULL);
    dtsgui_listbox_add(l, 'Alt Test3', NULL);
    objunref(l);
    l = dtsgui_listbox(p, 'ListBox', 'list', NULL);
    dtsgui_listbox_add(l, 'Test1', NULL);
    dtsgui_listbox_add(l, 'Test2', NULL);
    dtsgui_listbox_add(l, 'Test3', NULL);
    dtsgui_listbox_add(l, 'Alt Test3', NULL);
    objunref(l);
}
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.