.TH "DTSApp" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSApp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSApp\&.h>\fP
.PP
Inherits wxApp\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSApp\fP (\fBdtsgui_configcb\fP confcallback_cb, void *data, struct \fBpoint\fP wsize, struct \fBpoint\fP wpos, const char *title, const char *status)"
.br
.ti -1c
.RI "\fB~DTSApp\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBOnInit\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "class \fBdtsgui\fP * \fBdtsgui\fP"
.br
.ti -1c
.RI "class \fBdtsgui_curl\fP * \fBcurl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file DTSApp\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSApp::DTSApp (\fBdtsgui_configcb\fPconfcallback_cb, void *data, struct \fBpoint\fPwsize, struct \fBpoint\fPwpos, const char *title, const char *status)"

.PP
Definition at line 247 of file DTSApp\&.cpp\&.
.SS "DTSApp::~DTSApp ()"

.PP
Definition at line 251 of file DTSApp\&.cpp\&.
.PP
References dtsgui_curl::curl\&.
.SH "Member Function Documentation"
.PP 
.SS "bool DTSApp::OnInit ()\fC [private]\fP, \fC [virtual]\fP"

.PP
Definition at line 262 of file DTSApp\&.cpp\&.
.PP
References dtsgui_curl::curl, and dtsgui::SetupAPPFrame()\&.
.SH "Member Data Documentation"
.PP 
.SS "class \fBdtsgui_curl\fP* DTSApp::curl\fC [private]\fP"

.PP
Definition at line 75 of file DTSApp\&.h\&.
.SS "class \fBdtsgui\fP* DTSApp::dtsgui\fC [private]\fP"

.PP
Definition at line 74 of file DTSApp\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
