.TH "DTSAPPToolBar" 3 "Thu Oct 10 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSAPPToolBar \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits wxToolBar\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSAPPToolBar\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, \fBwxWindow\fP *parent, long style, wxWindowID id, wxString name, void *data)"
.br
.ti -1c
.RI "\fB~DTSAPPToolBar\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static struct curl_post * \fBGetPostInfo\fP (const wxString &val)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBHandleEvent\fP (wxCommandEvent &event)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBitemid\fP"
.br
.ti -1c
.RI "\fBDTSXMLComboBox\fP * \fBserver\fP"
.br
.ti -1c
.RI "\fBwxComboBox\fP * \fBproto\fP"
.br
.ti -1c
.RI "struct \fBdtsgui\fP * \fBdtsgui\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file toolbar\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSAPPToolBar::DTSAPPToolBar (struct \fBdtsgui\fP *dtsgui, \fBwxWindow\fP *parent, longstyle, wxWindowIDid, wxStringname, void *data)"

.PP
Definition at line 44 of file toolbar\&.cpp\&.
.PP
References GetPostInfo(), HandleEvent(), itemid, proto, and server\&.
.SS "DTSAPPToolBar::~DTSAPPToolBar ()"

.PP
Definition at line 79 of file toolbar\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "struct curl_post * DTSAPPToolBar::GetPostInfo (const wxString &val)\fC [static]\fP, \fC [read]\fP"

.PP
Definition at line 85 of file toolbar\&.cpp\&.
.PP
Referenced by DTSAPPToolBar()\&.
.SS "void DTSAPPToolBar::HandleEvent (wxCommandEvent &event)\fC [private]\fP"

.PP
Definition at line 95 of file toolbar\&.cpp\&.
.PP
References DTS_C_API::dtsgui_alert(), DTSXMLComboBox::HasXMLList(), and server\&.
.PP
Referenced by DTSAPPToolBar()\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBdtsgui\fP* DTSAPPToolBar::dtsgui\fC [private]\fP"

.PP
Definition at line 40 of file toolbar\&.cpp\&.
.SS "int DTSAPPToolBar::itemid\fC [private]\fP"

.PP
Definition at line 36 of file toolbar\&.cpp\&.
.PP
Referenced by DTSAPPToolBar()\&.
.SS "\fBwxComboBox\fP* DTSAPPToolBar::proto\fC [private]\fP"

.PP
Definition at line 39 of file toolbar\&.cpp\&.
.PP
Referenced by DTSAPPToolBar()\&.
.SS "\fBDTSXMLComboBox\fP* DTSAPPToolBar::server\fC [private]\fP"

.PP
Definition at line 38 of file toolbar\&.cpp\&.
.PP
Referenced by DTSAPPToolBar(), and HandleEvent()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
