.TH "DTSApp" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSApp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSApp\&.h>\fP
.PP
Inherits wxApp\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSApp\fP (\fBdtsgui_configcb\fP confcallback_cb, void *data, struct \fBpoint\fP wsize, struct \fBpoint\fP wpos, const char *title, const char *status)"
.br
.ti -1c
.RI "\fB~DTSApp\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file DTSApp\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSApp::DTSApp (\fBdtsgui_configcb\fPconfcallback_cb, void *data, struct \fBpoint\fPwsize, struct \fBpoint\fPwpos, const char *title, const char *status)"

.PP
Definition at line 239 of file DTSApp\&.cpp\&.
.SS "DTSApp::~DTSApp ()"

.PP
Definition at line 243 of file DTSApp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
