.TH "src/DTSApp.cpp" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/DTSApp.cpp \- 
.PP
Core Application Class implementation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <wx/toolbar\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'DTSApp\&.h'\fP
.br
\fC#include 'DTSFrame\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwxDEFINE_EVENT\fP (DTS_APP_EVENT, wxCommandEvent)"
.br
.RI "\fIDefine event type used for application events\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Core Application Class implementation\&. 


.PP
Definition in file \fBDTSApp\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
