DTSAPPToolBar
NAME
DTSAPPToolBar -
Application toolbar class.
SYNOPSIS
Inherits wxToolBar.
Public Member Functions
DTSAPPToolBar (struct dtsgui *dtsgui, wxWindow *parent, long style, wxWindowID id, wxString name, void *data)
Application toolbar.
~DTSAPPToolBar ()
Release references held.
Static Public Member Functions
static struct curl_post * GetPostInfo (const wxString &val)
Callback from DTSXMLComboBox.
Private Member Functions
void HandleEvent (wxCommandEvent &event)
Toolbar event handler callback.
Private Attributes
int itemid
Item id incremented for each item added to toolbar.
DTSXMLComboBox * server
URL Combo box that will populate list based on XML.
wxComboBox * proto
Protocol listbox.
struct dtsgui * dtsgui
Reference to application data ptr.
Detailed Description
Application toolbar class.
Derived from wxToolbar.
Definition at line 45 of file toolbar.cpp.
Constructor & Destructor Documentation
DTSAPPToolBar::DTSAPPToolBar (struct dtsgui *dtsgui, wxWindow *parent, longstyle, wxWindowIDid, wxStringname, void *data)
Application toolbar. Parameters:
dtsgui Application data ptr.
parent Parent window.
style Toolbar Style.
id Toolbar ID.
name Toolbar name.
data Hold reference to this user data.
Definition at line 98 of file toolbar.cpp.
References GetPostInfo(), HandleEvent(), itemid, proto, and server.
                                                                                                                          {
    int servid;
    if (dtsgui && objref(dtsgui)) {
        this->dtsgui = (struct dtsgui*)dtsgui;
    } else {
        this->dtsgui = NULL;
    }
    itemid = wxID_AUTO_LOWEST;
    Create(parent, id, wxDefaultPosition, wxDefaultSize, style, name);
    proto = new wxComboBox(this, itemid++, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0, NULL, wxCB_READONLY);
    servid = itemid++;
    server = new DTSXMLComboBox(this, servid, 'https://sip1.speakezi.co.za:666/auth/test.php', '/servers/Server', &DTSAPPToolBar::GetPostInfo, 3);
    server->SetSize(wxSize(300,-1));
    wxStaticText *text2 = new wxStaticText(this, wxID_ANY, '://');
    wxStaticText *text = new wxStaticText(this, wxID_ANY, 'Server ');
    AddControl(text);
    proto->Append('http');
    proto->Append('https');
    proto->Append('https [:666]');
    proto->SetSelection(2);
    AddControl(proto);
    AddControl(text2);
    AddControl(server);
    AddStretchableSpace();
    Bind(wxEVT_TEXT_ENTER, &DTSAPPToolBar::HandleEvent, this, servid, servid, NULL);
    Bind(wxEVT_COMBOBOX, &DTSAPPToolBar::HandleEvent, this, servid, servid, NULL);
    Bind(wxEVT_COMBOBOX_DROPDOWN, &DTSAPPToolBar::HandleEvent, this, servid, servid, NULL);
}
DTSAPPToolBar::~DTSAPPToolBar ()
Release references held.
Definition at line 133 of file toolbar.cpp.
                              {
    if (dtsgui) {
        objunref(dtsgui);
    }
}
Member Function Documentation
struct curl_post * DTSAPPToolBar::GetPostInfo (const wxString &val) [static], [read]
Callback from DTSXMLComboBox. Parameters:
val Value used to create a curl_post structure.
Returns:
curl_post structure to send in XML request.
Definition at line 139 of file toolbar.cpp.
Referenced by DTSAPPToolBar().
                                                                {
    struct curl_post *post;
    post = curl_newpost();
    curl_postitem(post, 'function', 'getcust');
    curl_postitem(post, 'search', val);
    return post;
}
void DTSAPPToolBar::HandleEvent (wxCommandEvent &event) [private]
Toolbar event handler callback. Parameters:
event Event emited by the toolbar.
Definition at line 149 of file toolbar.cpp.
References DTS_C_API::dtsgui_alert(), DTSXMLComboBox::HasXMLList(), and server.
Referenced by DTSAPPToolBar().
                                                     {
    int etype = event.GetEventType(), idx;
    struct xml_node *xn;
    idx = server->GetSelection();
    if (etype == wxEVT_TEXT_ENTER) {
        DTS_C_API::dtsgui_alert(dtsgui, 'Got Me Some URL ARRRRGh');
    } else if (etype == wxEVT_COMBOBOX) {
        xn = (struct xml_node*)server->GetClientData(idx);
        DTS_C_API::dtsgui_alert(dtsgui, wxString('Selected IP ').Append(xml_getattr(xn, 'ipaddr')));
    } else if ((etype == wxEVT_COMBOBOX_DROPDOWN) && !server->HasXMLList()) {
        DTS_C_API::dtsgui_alert(dtsgui, 'Please enter 3 or more characters to search !');
    }
}
Member Data Documentation
struct dtsgui* DTSAPPToolBar::dtsgui [private]
Reference to application data ptr.
Definition at line 75 of file toolbar.cpp.
int DTSAPPToolBar::itemid [private]
Item id incremented for each item added to toolbar.
Definition at line 66 of file toolbar.cpp.
Referenced by DTSAPPToolBar().
wxComboBox* DTSAPPToolBar::proto [private]
Protocol listbox.
Definition at line 73 of file toolbar.cpp.
Referenced by DTSAPPToolBar().
DTSXMLComboBox* DTSAPPToolBar::server [private]
URL Combo box that will populate list based on XML. The XML is returned from a HTTP post using the contents of the comobo box as search key.
Definition at line 71 of file toolbar.cpp.
Referenced by DTSAPPToolBar(), and HandleEvent().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.