DTSDVMCtrl
NAME
DTSDVMCtrl -
SYNOPSIS
#include <DTSListView.h>
Inherits wxDataViewCtrl.
Public Member Functions
DTSDVMCtrl ()
DTSDVMCtrl (wxWindow *parent, wxWindowID id=wxID_ANY, DTSDVMListView *model=NULL, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDV_ROW_LINES, const wxValidator &validator=wxDefaultValidator)
~DTSDVMCtrl ()
virtual bool AssociateModel (DTSDVMListView *model)
void Sort (const wxDataViewItem &parent)
DTSDVMListView * GetStore ()
wxDataViewItem AppendItem (wxDataViewItem parent, const wxString &title, bool can_edit=true, bool can_sort=true, bool can_del=false, int nodeid=-1, dtsgui_treeviewpanel_cb p_cb=NULL, void *userdata=NULL)
wxDataViewItem AppendContainer (wxDataViewItem parent, const wxString &title, bool can_edit=true, bool can_sort=true, bool can_del=false, int nodeid=-1, dtsgui_treeviewpanel_cb p_cb=NULL, void *userdata=NULL)
Private Member Functions
wxDataViewItem AppendNode (wxDataViewItem parent, const wxString &title, bool iscont, bool can_edit=true, bool can_sort=true, bool can_del=false, int nodeid=-1, dtsgui_treeviewpanel_cb p_cb=NULL, void *userdata=NULL)
Private Attributes
DTSDVMListView * model
Detailed Description
Definition at line 105 of file DTSListView.h.
Constructor & Destructor Documentation
DTSDVMCtrl::DTSDVMCtrl ()
Definition at line 551 of file DTSListView.cpp.
References model.
                       {
    model = NULL;
}
DTSDVMCtrl::DTSDVMCtrl (wxWindow *parent, wxWindowIDid = wxID_ANY, DTSDVMListView *model = NULL, const wxPoint &pos = wxDefaultPosition, const wxSize &size = wxDefaultSize, longstyle = wxDV_ROW_LINES, const wxValidator &validator = wxDefaultValidator)
Definition at line 555 of file DTSListView.cpp.
References AssociateModel().
                                                                                                                                                               {
    wxDataViewTextRenderer *col0_r;
    wxDataViewColumn *col0;
    this->model = NULL;
    Create(parent, id, pos, size, style, validator);
    if (model) {
        AssociateModel(model);
    }
    col0_r = new wxDataViewTextRenderer('string', wxDATAVIEW_CELL_EDITABLE);
#ifndef _WIN32
    col0_r->DisableEllipsize();
#endif //_WIN32
    col0 = new wxDataViewColumn('Title', col0_r, 0);
#ifndef _WIN32
    col0->SetWidth(wxCOL_WIDTH_AUTOSIZE);
#endif // _WIN32
    col0->SetFlags(wxCOL_RESIZABLE | wxCOL_REORDERABLE);
    col0->SetReorderable(true);
    col0->SetAlignment(wxALIGN_LEFT);
    AppendColumn(col0);
#ifdef _WIN32
    SetRowHeight(17);
#endif // _WIN32
}
DTSDVMCtrl::~DTSDVMCtrl ()
Definition at line 582 of file DTSListView.cpp.
References DTSDVMListView::DeleteAll(), and model.
                        {
    model->DeleteAll();
}
Member Function Documentation
wxDataViewItem DTSDVMCtrl::AppendContainer (wxDataViewItemparent, const wxString &title, boolcan_edit = true, boolcan_sort = true, boolcan_del = false, intnodeid = -1, dtsgui_treeviewpanel_cbp_cb = NULL, void *userdata = NULL)
Definition at line 612 of file DTSListView.cpp.
References AppendNode().
Referenced by DTS_C_API::dtsgui_treecont(), and tree_newnode::handle_newtreenode().
                                                                                                                                                                                             {
    return AppendNode(parent, title, true, can_edit, can_sort, can_del, nodeid, p_cb, userdata);
}
wxDataViewItem DTSDVMCtrl::AppendItem (wxDataViewItemparent, const wxString &title, boolcan_edit = true, boolcan_sort = true, boolcan_del = false, intnodeid = -1, dtsgui_treeviewpanel_cbp_cb = NULL, void *userdata = NULL)
Definition at line 608 of file DTSListView.cpp.
References AppendNode().
Referenced by DTS_C_API::dtsgui_treeitem(), and tree_newnode::handle_newtreenode().
                                                                                                                                                                                        {
    return AppendNode(parent, title, false, can_edit, can_sort, can_del, nodeid, p_cb, userdata);
}
wxDataViewItem DTSDVMCtrl::AppendNode (wxDataViewItemparent, const wxString &title, booliscont, boolcan_edit = true, boolcan_sort = true, boolcan_del = false, intnodeid = -1, dtsgui_treeviewpanel_cbp_cb = NULL, void *userdata = NULL) [private]
Definition at line 616 of file DTSListView.cpp.
References DTSDVMListStore::Append(), DTSDVMListStore::can_delete, DTSDVMListStore::can_edit, DTSDVMListStore::can_sort, DTSDVMListView::GetRoot(), model, and DTSDVMListView::SetRoot().
Referenced by AppendContainer(), and AppendItem().
                                                                                                                                                                                                     {
    DTSDVMListStore *li, *node;
    wxDataViewItem dvi;
    if (!parent.IsOk() && !model->GetRoot()) {
        li = model->SetRoot(title, nodeid, p_cb, userdata);
    } else if (!(node = (DTSDVMListStore*)parent.GetID())) {
        return wxDataViewItem(NULL);
    } else {
        li= new DTSDVMListStore(node, iscont, title, nodeid, p_cb, userdata);
        node->Append(li);
    }
    li->can_delete = can_del;
    li->can_edit = can_edit;
    li->can_sort = can_sort;
    dvi = wxDataViewItem(li);
    model->ItemAdded(parent, dvi);
    return dvi;
}
bool DTSDVMCtrl::AssociateModel (DTSDVMListView *model) [virtual]
Definition at line 586 of file DTSListView.cpp.
References DTSDVMListView::DeleteAll(), and model.
Referenced by DTSDVMCtrl().
                                                     {
    bool res;
    res = wxDataViewCtrl::AssociateModel(model);
    if (res) {
        if (this->model) {
            model->DeleteAll();
        }
        this->model = model;
        model->DecRef();
    }
    return res;
}
DTSDVMListView * DTSDVMCtrl::GetStore ()
Definition at line 604 of file DTSListView.cpp.
References model.
Referenced by DTSTreeWindowEvent::DTSTreeWindowEvent(), and DTSTreeWindow::Show().
                                     {
    return model;
}
void DTSDVMCtrl::Sort (const wxDataViewItem &parent)
Definition at line 600 of file DTSListView.cpp.
References model, and DTSDVMListView::SortChildren().
                                                  {
    model->SortChildren(parent);
}
Member Data Documentation
DTSDVMListView* DTSDVMCtrl::model [private]
Definition at line 118 of file DTSListView.h.
Referenced by AppendNode(), AssociateModel(), DTSDVMCtrl(), GetStore(), Sort(), and ~DTSDVMCtrl().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.