DTSDVMListView
NAME
DTSDVMListView -
SYNOPSIS
#include <DTSListView.h>
Inherits wxDataViewModel.
Public Member Functions
DTSDVMListView (int cols=1, bool cont_cols=true)
~DTSDVMListView ()
virtual bool IsContainer (const wxDataViewItem &item) const
virtual wxDataViewItem GetParent (const wxDataViewItem &item) const
virtual unsigned int GetChildren (const wxDataViewItem &parent, wxDataViewItemArray &items) const
virtual unsigned int GetColumnCount () const
virtual bool HasContainerColumns (const wxDataViewItem &item) const
virtual wxString GetColumnType (unsigned int col) const
virtual void GetValue (wxVariant &variant, const wxDataViewItem &item, unsigned int col) const
virtual bool SetValue (const wxVariant &variant, const wxDataViewItem &item, unsigned int col)
DTSDVMListStore * GetRoot ()
DTSDVMListStore * SetRoot (const wxString &title, int nodeid=-1, dtsgui_treeviewpanel_cb p_cb=NULL, void *userdata=NULL)
void Delete (const wxDataViewItem &item)
void DeleteAll (void)
void SortChildren (const wxDataViewItem &parent)
int GetChildCount (wxDataViewItem &parent)
wxDataViewItem GetNthChild (wxDataViewItem &parent, size_t idx)
void SetExpanded (const wxDataViewItem &node, bool expanded=true)
virtual unsigned int GetContainers (const wxDataViewItem &parent, wxDataViewItemArray &items, bool exonly=false) const
void MoveChildUp (const wxDataViewItem &node)
void MoveChildDown (const wxDataViewItem &node)
void * GetUserData (const wxDataViewItem &node)
int GetNodeID (const wxDataViewItem &node)
void SetXMLData (const wxDataViewItem &node, struct xml_node *xnode, const char *tattr)
struct xml_node * GetXMLData (const wxDataViewItem &node, char **buff)
const wxString GetTitle (const wxDataViewItem &node)
Protected Attributes
DTSDVMListStore * root
bool hascontcol
int colcnt
Detailed Description
Definition at line 69 of file DTSListView.h.
Constructor & Destructor Documentation
DTSDVMListView::DTSDVMListView (intcols = 1, boolcont_cols = true)
Definition at line 247 of file DTSListView.cpp.
References colcnt, hascontcol, and root.
                                                       {
    hascontcol = cont_cols;
    root = NULL;
    colcnt = cols;
}
DTSDVMListView::~DTSDVMListView ()
Definition at line 253 of file DTSListView.cpp.
References DeleteAll().
                                {
    DeleteAll();
}
Member Function Documentation
void DTSDVMListView::Delete (const wxDataViewItem &item)
Definition at line 341 of file DTSListView.cpp.
References DeleteAll(), DTSDVMListStore::GetParent(), DTSDVMListStore::GetXMLData(), and DTSDVMListStore::RemoveChildReference().
Referenced by DTSTreeWindowEvent::MenuEvent().
                                                      {
    DTSDVMListStore *node;
    wxDataViewItem parent;
    struct xml_node *xn;
    node = (DTSDVMListStore*)item.GetID();
    if (!node) {
        return;
    }
    parent = wxDataViewItem(node->GetParent());
    if (!parent.IsOk()) {
        DeleteAll();
        return;
    }
    if ((xn = node->GetXMLData(NULL))) {
        xml_delete(xn);
        objunref(xn);
    }
    node->GetParent()->RemoveChildReference(node);
    delete node;
    ItemDeleted(parent, item);
}
void DTSDVMListView::DeleteAll (void)
Definition at line 367 of file DTSListView.cpp.
References root.
Referenced by DTSDVMCtrl::AssociateModel(), Delete(), DTSDVMCtrl::~DTSDVMCtrl(), and ~DTSDVMListView().
                                   {
    if (!root) {
        return;
    }
    delete root;
    root = NULL;
    Cleared();
}
int DTSDVMListView::GetChildCount (wxDataViewItem &parent)
Definition at line 391 of file DTSListView.cpp.
References DTSDVMListStore::GetChildCount(), and root.
Referenced by DTSTreeWindowEvent::TreeEvent().
                                                        {
    DTSDVMListStore *entry;
    bool nok;
    nok = parent.IsOk();
    if (nok && (entry = (DTSDVMListStore*)parent.GetID())) {
        return entry->GetChildCount();
    } else if (root && !nok) {
        return root->GetChildCount();
    } else {
        return 0;
    }
}
unsigned int DTSDVMListView::GetChildren (const wxDataViewItem &parent, wxDataViewItemArray &items) const [virtual]
Definition at line 281 of file DTSListView.cpp.
References DTSDVMListStore::GetChildren(), and root.
Referenced by MoveChildDown(), MoveChildUp(), and SortChildren().
                                                                                                       {
    DTSDVMListStore *node;
    bool nok;
    nok = parent.IsOk();
    node = (DTSDVMListStore*)parent.GetID();
    if (!nok && !node) {
        if (root) {
            items.Add(wxDataViewItem((void*)root));
            return 1;
        } else {
            return 0;
        }
    } else {
        return node->GetChildren(items);
    }
}
unsigned int DTSDVMListView::GetColumnCount () const [virtual]
Definition at line 300 of file DTSListView.cpp.
References colcnt.
                                                  {
    return colcnt;
}
wxString DTSDVMListView::GetColumnType (unsigned intcol) const [virtual]
Definition at line 308 of file DTSListView.cpp.
                                                             {
    return wxT('string');
}
unsigned int DTSDVMListView::GetContainers (const wxDataViewItem &parent, wxDataViewItemArray &items, boolexonly = false) const [virtual]
Definition at line 436 of file DTSListView.cpp.
References DTSDVMListStore::GetContainers(), and root.
Referenced by DTSTreeWindowEvent::SortParent().
                                                                                                                      {
    DTSDVMListStore *node;
    bool nok;
    nok = parent.IsOk();
    node = (DTSDVMListStore*)parent.GetID();
    if (!nok && !node) {
        if (root) {
            items.Add(wxDataViewItem((void*)root));
            return 1;
        } else {
            return 0;
        }
    } else {
        return node->GetContainers(items, exonly);
    }
}
int DTSDVMListView::GetNodeID (const wxDataViewItem &node)
Definition at line 507 of file DTSListView.cpp.
References DTSDVMListStore::GetNodeID(), and root.
Referenced by DTSTreeWindow::CreatePane(), and DTSTreeWindowEvent::TreeEvent().
                                                        {
    DTSDVMListStore *data;
    if (!node.IsOk() && root) {
        return root->GetNodeID();
    } else if ((data = (DTSDVMListStore*)node.GetID())) {
        return data->GetNodeID();
    } else {
        return -1;
    }
}
wxDataViewItem DTSDVMListView::GetNthChild (wxDataViewItem &parent, size_tidx)
Definition at line 405 of file DTSListView.cpp.
References DTSDVMListStore::GetNthChild(), and root.
Referenced by DTSTreeWindowEvent::TreeEvent().
                                                                             {
    DTSDVMListStore *entry, *li;
    bool nok;
    nok = parent.IsOk();
    entry = (DTSDVMListStore*)parent.GetID();
    if (nok && entry) {
        li = entry->GetNthChild(idx);
    } else if (!nok && root) {
        li = root->GetNthChild(idx);
    } else {
        li = NULL;
    }
    return wxDataViewItem(li);
}
wxDataViewItem DTSDVMListView::GetParent (const wxDataViewItem &item) const [virtual]
Definition at line 266 of file DTSListView.cpp.
References DTSDVMListStore::GetParent(), and root.
Referenced by DTSTreeWindowEvent::MenuEvent(), and DTSTreeWindowEvent::TreeEvent().
                                                                         {
    DTSDVMListStore *node;
    if (!item.IsOk()) {
        return wxDataViewItem(NULL);
    }
    node = (DTSDVMListStore*)item.GetID();
    if (!node || (node == root)){
        return wxDataViewItem(NULL);
    }
    return wxDataViewItem((void*)node->GetParent());
}
DTSDVMListStore * DTSDVMListView::GetRoot ()
Definition at line 332 of file DTSListView.cpp.
References root.
Referenced by DTSDVMCtrl::AppendNode(), and DTSTreeWindow::Show().
                                         {
    return root;
}
const wxString DTSDVMListView::GetTitle (const wxDataViewItem &node)
Definition at line 540 of file DTSListView.cpp.
References DTSDVMListStore::GetTitle(), and root.
Referenced by DTSTreeWindow::CreatePane().
                                                                  {
    DTSDVMListStore *data;
    if (!node.IsOk() && root) {
        return root->GetTitle();
    } else if ((data = (DTSDVMListStore*)node.GetID())) {
        return data->GetTitle();
    }
    return wxEmptyString;
}
void * DTSDVMListView::GetUserData (const wxDataViewItem &node)
Definition at line 495 of file DTSListView.cpp.
References DTSDVMListStore::GetUserData(), and root.
                                                            {
    DTSDVMListStore *data;
    if (!node.IsOk() && root) {
        return root->GetUserData();
    } else if ((data = (DTSDVMListStore*)node.GetID())) {
        return data->GetUserData();
    } else {
        return NULL;
    }
}
void DTSDVMListView::GetValue (wxVariant &variant, const wxDataViewItem &item, unsigned intcol) const [virtual]
Definition at line 312 of file DTSListView.cpp.
References DTSDVMListStore::GetTitle().
                                                                                                    {
    DTSDVMListStore *node = (DTSDVMListStore*)item.GetID();
    if (col == 0) {
        variant = node->GetTitle();
    }
}
struct xml_node * DTSDVMListView::GetXMLData (const wxDataViewItem &node, char **buff) [read]
Definition at line 529 of file DTSListView.cpp.
References DTSDVMListStore::GetXMLData(), and root.
Referenced by DTSTreeWindow::UpdateNodeXML().
                                                                                  {
    DTSDVMListStore *data;
    if (!node.IsOk() && root) {
        return root->GetXMLData(buf);
    } else if ((data = (DTSDVMListStore*)node.GetID())) {
        return data->GetXMLData(buf);
    }
    return NULL;
}
bool DTSDVMListView::HasContainerColumns (const wxDataViewItem &item) const [virtual]
Definition at line 304 of file DTSListView.cpp.
References hascontcol.
                                                                         {
    return hascontcol;
}
bool DTSDVMListView::IsContainer (const wxDataViewItem &item) const [virtual]
Definition at line 257 of file DTSListView.cpp.
References DTSDVMListStore::IsContainer().
Referenced by DTSTreeWindow::Select(), and DTSTreeWindowEvent::TreeEvent().
                                                                 {
    if (!item.IsOk()) {
        return true;
    }
    DTSDVMListStore *node = (DTSDVMListStore*)item.GetID();
    return node->IsContainer();
}
void DTSDVMListView::MoveChildDown (const wxDataViewItem &node)
Definition at line 475 of file DTSListView.cpp.
References DTSDVMListStore::GetChildIndex(), GetChildren(), DTSDVMListStore::GetParent(), and DTSDVMListStore::MoveChildDown().
Referenced by DTSTreeWindowEvent::SortParent().
                                                             {
    DTSDVMListStore *data, *parent;
    wxDataViewItem pnode;
    wxDataViewItemArray items;
    data = (DTSDVMListStore*)node.GetID();
    if (!data || !node.IsOk()) {
        return;
    }
    parent = data->GetParent();
    pnode = wxDataViewItem(parent);
    if (parent) {
        parent->MoveChildDown(parent->GetChildIndex(data));
        GetChildren(pnode, items);
        ItemsDeleted(pnode, items);
        ItemsAdded(pnode, items);
    }
}
void DTSDVMListView::MoveChildUp (const wxDataViewItem &node)
Definition at line 455 of file DTSListView.cpp.
References DTSDVMListStore::GetChildIndex(), GetChildren(), DTSDVMListStore::GetParent(), and DTSDVMListStore::MoveChildUp().
Referenced by DTSTreeWindowEvent::SortParent().
                                                           {
    DTSDVMListStore *data, *parent;
    wxDataViewItem pnode;
    wxDataViewItemArray items;
    data = (DTSDVMListStore*)node.GetID();
    if (!data || !node.IsOk()) {
        return;
    }
    parent = data->GetParent();
    pnode = wxDataViewItem(parent);
    if (parent) {
        parent->MoveChildUp(parent->GetChildIndex(data));
        GetChildren(pnode, items);
        ItemsDeleted(pnode, items);
        ItemsAdded(pnode, items);
    }
}
void DTSDVMListView::SetExpanded (const wxDataViewItem &node, boolexpanded = true)
Definition at line 422 of file DTSListView.cpp.
References root, and DTSDVMListStore::SetExpanded().
Referenced by DTSTreeWindowEvent::SortParent().
                                                                          {
    DTSDVMListStore *entry;
    bool nok;
    nok = node.IsOk();
    entry = (DTSDVMListStore*)node.GetID();
    if (nok && entry) {
        entry->SetExpanded(expanded);
    } else if (!nok && root) {
        root->SetExpanded();
    }
}
DTSDVMListStore * DTSDVMListView::SetRoot (const wxString &title, intnodeid = -1, dtsgui_treeviewpanel_cbp_cb = NULL, void *userdata = NULL)
Definition at line 336 of file DTSListView.cpp.
References root.
Referenced by DTSDVMCtrl::AppendNode().
                                                                                                                        {
    root = new DTSDVMListStore(NULL, true, title, nodeid, p_cb, userdata);
    return root;
}
bool DTSDVMListView::SetValue (const wxVariant &variant, const wxDataViewItem &item, unsigned intcol) [virtual]
Definition at line 320 of file DTSListView.cpp.
References DTSDVMListStore::SetTitle().
                                                                                                    {
    assert(item.IsOk());
    DTSDVMListStore *node = (DTSDVMListStore*) item.GetID();
    if (col == 0) {
        node->SetTitle(variant.GetString());
        return true;
    }
    return false;
}
void DTSDVMListView::SetXMLData (const wxDataViewItem &node, struct xml_node *xnode, const char *tattr)
Definition at line 519 of file DTSListView.cpp.
References root, and DTSDVMListStore::SetXMLData().
                                                                                                     {
    DTSDVMListStore *data;
    if (!node.IsOk() && root) {
        root->SetXMLData(xnode, tattr);
    } else if ((data = (DTSDVMListStore*)node.GetID())) {
        data->SetXMLData(xnode, tattr);
    }
}
void DTSDVMListView::SortChildren (const wxDataViewItem &parent)
Definition at line 377 of file DTSListView.cpp.
References GetChildren(), and DTSDVMListStore::SortChildren().
Referenced by DTSDVMCtrl::Sort(), and DTSTreeWindowEvent::SortParent().
                                                              {
    DTSDVMListStore *node = (DTSDVMListStore*)parent.GetID();
    wxDataViewItemArray items;
    if (!node) {
        return;
    }
    node->SortChildren();
    GetChildren(parent, items);
    ItemsDeleted(parent, items);
    ItemsAdded(parent, items);
}
Member Data Documentation
int DTSDVMListView::colcnt [protected]
Definition at line 102 of file DTSListView.h.
Referenced by DTSDVMListView(), and GetColumnCount().
bool DTSDVMListView::hascontcol [protected]
Definition at line 101 of file DTSListView.h.
Referenced by DTSDVMListView(), and HasContainerColumns().
DTSDVMListStore* DTSDVMListView::root [protected]
Definition at line 100 of file DTSListView.h.
Referenced by DeleteAll(), DTSDVMListView(), GetChildCount(), GetChildren(), GetContainers(), GetNodeID(), GetNthChild(), GetParent(), GetRoot(), GetTitle(), GetUserData(), GetXMLData(), SetExpanded(), SetRoot(), and SetXMLData().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.