DTSDialog
NAME
DTSDialog -
SYNOPSIS
#include <DTSPanel.h>
Inherits DTSStaticPanel.
Public Member Functions
DTSDialog (DTSFrame *=NULL, wxString=wxEmptyString, int=wx_PANEL_BUTTON_ACTION)
~DTSDialog ()
bool Show (bool=true)
void RunDialog (event_callback evcb, void *data)
Private Attributes
wxBoxSizer * sizer
wxDialog * dialog
Additional Inherited Members
Detailed Description
Definition at line 161 of file DTSPanel.h.
Constructor & Destructor Documentation
DTSDialog::DTSDialog (DTSFrame *frame = NULL, wxStringname = wxEmptyString, intbutmask = wx_PANEL_BUTTON_ACTION)
Definition at line 1048 of file DTSPanel.cpp.
References DTSPanel::button_mask, DTSObject::buttons, dialog, DTSObject::dtsevthandler, DTSPanelEvent::OnDialog(), DTSObject::panel, DTSPanel::SetupWin(), sizer, DTSObject::type, and wx_DTSPANEL_DIALOG.
DTSDialog::~DTSDialog ()
Definition at line 1069 of file DTSPanel.cpp.
Member Function Documentation
void DTSDialog::RunDialog (event_callbackevcb, void *data)
Definition at line 1077 of file DTSPanel.cpp.
References dialog, DTSObject::panel, DTSPanel::SetEventCallback(), Show(), and sizer.
Referenced by DTS_C_API::dtsgui_rundialog(), and DTSFrame::Passwd().
bool DTSDialog::Show (boolshow = true) [virtual]
Reimplemented from DTSStaticPanel.
Definition at line 1072 of file DTSPanel.cpp.
References DTSPanel::ShowPanel().
Referenced by RunDialog().
Member Data Documentation
wxDialog* DTSDialog::dialog [private]
Definition at line 169 of file DTSPanel.h.
Referenced by DTSDialog(), and RunDialog().
wxBoxSizer* DTSDialog::sizer [private]
Definition at line 168 of file DTSPanel.h.
Referenced by DTSDialog(), and RunDialog().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.