.TH "DTSDVMListStore" 3 "Thu Oct 10 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSDVMListStore \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSListView\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSDVMListStore\fP (\fBDTSDVMListStore\fP *\fBparent\fP, bool \fBis_container\fP, const wxString &\fBtitle\fP, int \fBnodeid\fP=-1, \fBdtsgui_treeviewpanel_cb\fP \fBp_cb\fP=NULL, void *userdata=NULL)"
.br
.ti -1c
.RI "\fB~DTSDVMListStore\fP ()"
.br
.ti -1c
.RI "bool \fBIsContainer\fP () const "
.br
.ti -1c
.RI "\fBDTSDVMListStore\fP * \fBGetParent\fP ()"
.br
.ti -1c
.RI "const wxString \fBGetParentTitle\fP ()"
.br
.ti -1c
.RI "size_t \fBGetChildCount\fP ()"
.br
.ti -1c
.RI "void \fBAppend\fP (\fBDTSDVMListStore\fP *child)"
.br
.ti -1c
.RI "void \fBInsert\fP (\fBDTSDVMListStore\fP *child, size_t idx)"
.br
.ti -1c
.RI "\fBDTSDVMListStore\fP * \fBGetNthChild\fP (size_t idx)"
.br
.ti -1c
.RI "size_t \fBGetChildIndex\fP (\fBDTSDVMListStore\fP *child)"
.br
.ti -1c
.RI "void \fBRemoveChildReference\fP (\fBDTSDVMListStore\fP *child)"
.br
.ti -1c
.RI "const wxString \fBGetTitle\fP ()"
.br
.ti -1c
.RI "void \fBSetTitle\fP (const wxString &value)"
.br
.ti -1c
.RI "void \fBSortChildren\fP ()"
.br
.ti -1c
.RI "void \fBSetExpanded\fP (bool \fBexpanded\fP=true)"
.br
.ti -1c
.RI "unsigned int \fBGetChildren\fP (wxDataViewItemArray &items)"
.br
.ti -1c
.RI "unsigned int \fBGetContainers\fP (wxDataViewItemArray &items, bool exonly=false)"
.br
.ti -1c
.RI "bool \fBIsExpanded\fP ()"
.br
.ti -1c
.RI "bool \fBMoveChildUp\fP (size_t idx)"
.br
.ti -1c
.RI "bool \fBMoveChildDown\fP (size_t idx)"
.br
.ti -1c
.RI "void * \fBGetUserData\fP ()"
.br
.ti -1c
.RI "int \fBGetNodeID\fP ()"
.br
.ti -1c
.RI "void \fBSetXMLData\fP (struct xml_node *xnode, const char *\fBtattr\fP)"
.br
.ti -1c
.RI "struct xml_node * \fBGetXMLData\fP (char **buff)"
.br
.ti -1c
.RI "void \fBConfigPanel\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP tw)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBcmp_title\fP (\fBDTSDVMListStore\fP *c1, \fBDTSDVMListStore\fP *c2)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBcan_edit\fP"
.br
.ti -1c
.RI "bool \fBcan_sort\fP"
.br
.ti -1c
.RI "bool \fBcan_delete\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBDTSDVMListStore\fP * > \fBchildren\fP"
.br
.ti -1c
.RI "\fBdtsgui_treeviewpanel_cb\fP \fBp_cb\fP"
.br
.ti -1c
.RI "\fBDTSDVMListStore\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct xml_node * \fBxml\fP"
.br
.ti -1c
.RI "const char * \fBtattr\fP"
.br
.ti -1c
.RI "bool \fBis_container\fP"
.br
.ti -1c
.RI "wxString \fBtitle\fP"
.br
.ti -1c
.RI "bool \fBexpanded\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "int \fBnodeid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file DTSListView\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSDVMListStore::DTSDVMListStore (\fBDTSDVMListStore\fP *parent, boolis_container, const wxString &title, intnodeid = \fC-1\fP, \fBdtsgui_treeviewpanel_cb\fPp_cb = \fCNULL\fP, void *userdata = \fCNULL\fP)"

.PP
Definition at line 39 of file DTSListView\&.cpp\&.
.PP
References data, is_container, nodeid, p_cb, parent, tattr, title, and xml\&.
.SS "DTSDVMListStore::~DTSDVMListStore ()"

.PP
Definition at line 54 of file DTSListView\&.cpp\&.
.PP
References children, data, tattr, and xml\&.
.SH "Member Function Documentation"
.PP 
.SS "void DTSDVMListStore::Append (\fBDTSDVMListStore\fP *child)"

.PP
Definition at line 88 of file DTSListView\&.cpp\&.
.PP
References children\&.
.PP
Referenced by DTSDVMCtrl::AppendNode()\&.
.SS "bool DTSDVMListStore::cmp_title (\fBDTSDVMListStore\fP *c1, \fBDTSDVMListStore\fP *c2)\fC [static]\fP"

.PP
Definition at line 30 of file DTSListView\&.cpp\&.
.PP
References GetTitle()\&.
.PP
Referenced by SortChildren()\&.
.SS "void DTSDVMListStore::ConfigPanel (\fBdtsgui_pane\fPp, \fBdtsgui_treeview\fPtw)"

.PP
Definition at line 232 of file DTSListView\&.cpp\&.
.PP
References data, and p_cb\&.
.PP
Referenced by DTSTreeWindowEvent::TreeCallback()\&.
.SS "size_t DTSDVMListStore::GetChildCount ()"

.PP
Definition at line 84 of file DTSListView\&.cpp\&.
.PP
References children\&.
.PP
Referenced by DTSDVMListView::GetChildCount()\&.
.SS "size_t DTSDVMListStore::GetChildIndex (\fBDTSDVMListStore\fP *child)"

.PP
Definition at line 110 of file DTSListView\&.cpp\&.
.PP
References children\&.
.PP
Referenced by DTSDVMListView::MoveChildDown(), DTSDVMListView::MoveChildUp(), and RemoveChildReference()\&.
.SS "unsigned int DTSDVMListStore::GetChildren (wxDataViewItemArray &items)"

.PP
Definition at line 146 of file DTSListView\&.cpp\&.
.PP
References children\&.
.PP
Referenced by DTSDVMListView::GetChildren()\&.
.SS "unsigned int DTSDVMListStore::GetContainers (wxDataViewItemArray &items, boolexonly = \fCfalse\fP)"

.PP
Definition at line 157 of file DTSListView\&.cpp\&.
.PP
References children, expanded, and is_container\&.
.PP
Referenced by DTSDVMListView::GetContainers()\&.
.SS "int DTSDVMListStore::GetNodeID ()"

.PP
Definition at line 207 of file DTSListView\&.cpp\&.
.PP
References nodeid\&.
.PP
Referenced by DTS_C_API::dtsgui_treenodeid(), and DTSDVMListView::GetNodeID()\&.
.SS "\fBDTSDVMListStore\fP * DTSDVMListStore::GetNthChild (size_tidx)"

.PP
Definition at line 102 of file DTSListView\&.cpp\&.
.PP
References children\&.
.PP
Referenced by DTSDVMListView::GetNthChild()\&.
.SS "\fBDTSDVMListStore\fP * DTSDVMListStore::GetParent ()"

.PP
Definition at line 75 of file DTSListView\&.cpp\&.
.PP
References parent\&.
.PP
Referenced by DTSDVMListView::Delete(), DTSDVMListView::GetParent(), GetParentTitle(), DTSDVMListView::MoveChildDown(), and DTSDVMListView::MoveChildUp()\&.
.SS "const wxString DTSDVMListStore::GetParentTitle ()"

.PP
Definition at line 79 of file DTSListView\&.cpp\&.
.PP
References GetParent(), GetTitle(), and parent\&.
.PP
Referenced by DTS_C_API::dtsgui_treenodeparent()\&.
.SS "const wxString DTSDVMListStore::GetTitle ()"

.PP
Definition at line 130 of file DTSListView\&.cpp\&.
.PP
References title\&.
.PP
Referenced by cmp_title(), GetParentTitle(), DTSDVMListView::GetTitle(), DTSDVMListView::GetValue(), DTSTreeWindowEvent::TreeCallback(), and DTSTreeWindowEvent::TreeEvent()\&.
.SS "void * DTSDVMListStore::GetUserData (void)"

.PP
Definition at line 200 of file DTSListView\&.cpp\&.
.PP
References data\&.
.PP
Referenced by DTS_C_API::dtsgui_treenodegetdata(), and DTSDVMListView::GetUserData()\&.
.SS "struct xml_node * DTSDVMListStore::GetXMLData (char **buff)\fC [read]\fP"

.PP
Definition at line 220 of file DTSListView\&.cpp\&.
.PP
References tattr, and xml\&.
.PP
Referenced by DTSDVMListView::Delete(), DTS_C_API::dtsgui_treenodegetxml(), and DTSDVMListView::GetXMLData()\&.
.SS "void DTSDVMListStore::Insert (\fBDTSDVMListStore\fP *child, size_tidx)"

.PP
Definition at line 92 of file DTSListView\&.cpp\&.
.PP
References children\&.
.SS "bool DTSDVMListStore::IsContainer () const"

.PP
Definition at line 71 of file DTSListView\&.cpp\&.
.PP
References is_container\&.
.PP
Referenced by DTSDVMListView::IsContainer(), and DTSTreeWindowEvent::TreeEvent()\&.
.SS "bool DTSDVMListStore::IsExpanded ()"

.PP
Definition at line 172 of file DTSListView\&.cpp\&.
.PP
References expanded\&.
.PP
Referenced by DTSTreeWindowEvent::SortParent()\&.
.SS "bool DTSDVMListStore::MoveChildDown (size_tidx)"

.PP
Definition at line 188 of file DTSListView\&.cpp\&.
.PP
References children\&.
.PP
Referenced by DTSDVMListView::MoveChildDown()\&.
.SS "bool DTSDVMListStore::MoveChildUp (size_tidx)"

.PP
Definition at line 176 of file DTSListView\&.cpp\&.
.PP
References children\&.
.PP
Referenced by DTSDVMListView::MoveChildUp()\&.
.SS "void DTSDVMListStore::RemoveChildReference (\fBDTSDVMListStore\fP *child)"

.PP
Definition at line 121 of file DTSListView\&.cpp\&.
.PP
References children, and GetChildIndex()\&.
.PP
Referenced by DTSDVMListView::Delete()\&.
.SS "void DTSDVMListStore::SetExpanded (boolexpanded = \fCtrue\fP)"

.PP
Definition at line 142 of file DTSListView\&.cpp\&.
.PP
References expanded\&.
.PP
Referenced by DTSDVMListView::SetExpanded(), and DTSTreeWindowEvent::SortParent()\&.
.SS "void DTSDVMListStore::SetTitle (const wxString &value)"

.PP
Definition at line 134 of file DTSListView\&.cpp\&.
.PP
References title\&.
.PP
Referenced by DTSDVMListView::SetValue()\&.
.SS "void DTSDVMListStore::SetXMLData (struct xml_node *xnode, const char *tattr)"

.PP
Definition at line 211 of file DTSListView\&.cpp\&.
.PP
References xml\&.
.PP
Referenced by DTS_C_API::dtsgui_treenodesetxml(), tree_newnode::handle_newtreenode(), and DTSDVMListView::SetXMLData()\&.
.SS "void DTSDVMListStore::SortChildren ()"

.PP
Definition at line 138 of file DTSListView\&.cpp\&.
.PP
References children, and cmp_title()\&.
.PP
Referenced by DTSDVMListView::SortChildren()\&.
.SH "Member Data Documentation"
.PP 
.SS "bool DTSDVMListStore::can_delete"

.PP
Definition at line 50 of file DTSListView\&.h\&.
.PP
Referenced by DTSDVMCtrl::AppendNode(), and DTSTreeWindowEvent::TreeEvent()\&.
.SS "bool DTSDVMListStore::can_edit"

.PP
Definition at line 48 of file DTSListView\&.h\&.
.PP
Referenced by DTSDVMCtrl::AppendNode(), and DTSTreeWindowEvent::TreeEvent()\&.
.SS "bool DTSDVMListStore::can_sort"

.PP
Definition at line 49 of file DTSListView\&.h\&.
.PP
Referenced by DTSDVMCtrl::AppendNode(), and DTSTreeWindowEvent::TreeEvent()\&.
.SS "std::vector<\fBDTSDVMListStore\fP*> DTSDVMListStore::children\fC [private]\fP"

.PP
Definition at line 57 of file DTSListView\&.h\&.
.PP
Referenced by Append(), GetChildCount(), GetChildIndex(), GetChildren(), GetContainers(), GetNthChild(), Insert(), MoveChildDown(), MoveChildUp(), RemoveChildReference(), SortChildren(), and ~DTSDVMListStore()\&.
.SS "void* DTSDVMListStore::data\fC [private]\fP"

.PP
Definition at line 65 of file DTSListView\&.h\&.
.PP
Referenced by ConfigPanel(), DTSDVMListStore(), GetUserData(), and ~DTSDVMListStore()\&.
.SS "bool DTSDVMListStore::expanded\fC [private]\fP"

.PP
Definition at line 64 of file DTSListView\&.h\&.
.PP
Referenced by GetContainers(), IsExpanded(), and SetExpanded()\&.
.SS "bool DTSDVMListStore::is_container\fC [private]\fP"

.PP
Definition at line 62 of file DTSListView\&.h\&.
.PP
Referenced by DTSDVMListStore(), GetContainers(), and IsContainer()\&.
.SS "int DTSDVMListStore::nodeid\fC [private]\fP"

.PP
Definition at line 66 of file DTSListView\&.h\&.
.PP
Referenced by DTSDVMListStore(), and GetNodeID()\&.
.SS "\fBdtsgui_treeviewpanel_cb\fP DTSDVMListStore::p_cb\fC [private]\fP"

.PP
Definition at line 58 of file DTSListView\&.h\&.
.PP
Referenced by ConfigPanel(), and DTSDVMListStore()\&.
.SS "\fBDTSDVMListStore\fP* DTSDVMListStore::parent\fC [private]\fP"

.PP
Definition at line 59 of file DTSListView\&.h\&.
.PP
Referenced by DTSDVMListStore(), GetParent(), and GetParentTitle()\&.
.SS "const char* DTSDVMListStore::tattr\fC [private]\fP"

.PP
Definition at line 61 of file DTSListView\&.h\&.
.PP
Referenced by DTSDVMListStore(), GetXMLData(), and ~DTSDVMListStore()\&.
.SS "wxString DTSDVMListStore::title\fC [private]\fP"

.PP
Definition at line 63 of file DTSListView\&.h\&.
.PP
Referenced by DTSDVMListStore(), GetTitle(), and SetTitle()\&.
.SS "struct xml_node* DTSDVMListStore::xml\fC [private]\fP"

.PP
Definition at line 60 of file DTSListView\&.h\&.
.PP
Referenced by DTSDVMListStore(), GetXMLData(), SetXMLData(), and ~DTSDVMListStore()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
