DTSDVMListStore
NAME
DTSDVMListStore -
SYNOPSIS
#include <DTSListView.h>
Public Member Functions
DTSDVMListStore (DTSDVMListStore *parent, bool is_container, const wxString &title, int nodeid=-1, dtsgui_treeviewpanel_cb p_cb=NULL, void *userdata=NULL)
~DTSDVMListStore ()
bool IsContainer () const
DTSDVMListStore * GetParent ()
const wxString GetParentTitle ()
size_t GetChildCount ()
void Append (DTSDVMListStore *child)
void Insert (DTSDVMListStore *child, size_t idx)
DTSDVMListStore * GetNthChild (size_t idx)
size_t GetChildIndex (DTSDVMListStore *child)
void RemoveChildReference (DTSDVMListStore *child)
const wxString GetTitle ()
void SetTitle (const wxString &value)
void SortChildren ()
void SetExpanded (bool expanded=true)
unsigned int GetChildren (wxDataViewItemArray &items)
unsigned int GetContainers (wxDataViewItemArray &items, bool exonly=false)
bool IsExpanded ()
bool MoveChildUp (size_t idx)
bool MoveChildDown (size_t idx)
void * GetUserData ()
int GetNodeID ()
void SetXMLData (struct xml_node *xnode, const char *tattr)
struct xml_node * GetXMLData (char **buff)
void ConfigPanel (dtsgui_pane p, dtsgui_treeview tw)
Static Public Member Functions
static bool cmp_title (DTSDVMListStore *c1, DTSDVMListStore *c2)
Public Attributes
bool can_edit
bool can_sort
bool can_delete
Private Attributes
std::vector< DTSDVMListStore * > children
dtsgui_treeviewpanel_cb p_cb
DTSDVMListStore * parent
struct xml_node * xml
const char * tattr
bool is_container
wxString title
bool expanded
void * data
int nodeid
Detailed Description
Definition at line 25 of file DTSListView.h.
Constructor & Destructor Documentation
DTSDVMListStore::DTSDVMListStore (DTSDVMListStore *parent, boolis_container, const wxString &title, intnodeid = -1, dtsgui_treeviewpanel_cbp_cb = NULL, void *userdata = NULL)
Definition at line 47 of file DTSListView.cpp.
References data, is_container, nodeid, p_cb, parent, tattr, title, and xml.
                                                                                                                                                            {
    xml = NULL;
    tattr = NULL;
    this->parent = parent;
    this->title = title;
    this->is_container = is_container;
    this->nodeid = nodeid;
    this->p_cb = p_cb;
    if (userdata && objref(userdata)) {
        this->data = userdata;
    } else {
        this->data = NULL;
    }
}
DTSDVMListStore::~DTSDVMListStore ()
Definition at line 62 of file DTSListView.cpp.
References children, data, tattr, and xml.
                                  {
    while (!children.empty()) {
        DTSDVMListStore* f_child = children.back();
        delete f_child;
        children.pop_back();
    }
    if (data) {
        objunref(data);
    }
    if (xml) {
        objunref(xml);
    }
    if (tattr) {
        free((void*)tattr);
    }
}
Member Function Documentation
void DTSDVMListStore::Append (DTSDVMListStore *child)
Definition at line 96 of file DTSListView.cpp.
References children.
Referenced by DTSDVMCtrl::AppendNode().
                                                   {
    children.push_back(child);
}
bool DTSDVMListStore::cmp_title (DTSDVMListStore *c1, DTSDVMListStore *c2) [static]
Definition at line 38 of file DTSListView.cpp.
References GetTitle().
Referenced by SortChildren().
                                                                       {
    wxString s1, s2;
    s1 = c1->GetTitle();
    s2 = c2->GetTitle();
    return (s1 < s2);
}
void DTSDVMListStore::ConfigPanel (dtsgui_panep, dtsgui_treeviewtw)
Definition at line 240 of file DTSListView.cpp.
References data, and p_cb.
Referenced by DTSTreeWindowEvent::TreeCallback().
                                                                   {
    if (!p_cb) {
        return;
    }
    p_cb(p, tw, this, data);
}
size_t DTSDVMListStore::GetChildCount ()
Definition at line 92 of file DTSListView.cpp.
References children.
Referenced by DTSDVMListView::GetChildCount().
                                      {
    return children.size();
}
size_t DTSDVMListStore::GetChildIndex (DTSDVMListStore *child)
Definition at line 118 of file DTSListView.cpp.
References children.
Referenced by DTSDVMListView::MoveChildDown(), DTSDVMListView::MoveChildUp(), and RemoveChildReference().
                                                            {
    size_t idx = 0, c_cnt;
    c_cnt = children.size();
    while ((idx < c_cnt) && (children[idx] != child)) {
        idx++;
    }
    return (children[idx] = child) ? idx : -1;
}
unsigned int DTSDVMListStore::GetChildren (wxDataViewItemArray &items)
Definition at line 154 of file DTSListView.cpp.
References children.
Referenced by DTSDVMListView::GetChildren().
                                                                    {
    unsigned int cnt;
    size_t acnt;
    acnt = children.size();
    for(cnt=0; cnt < acnt;cnt++) {
        items.Add(wxDataViewItem((void*)children[cnt]));
    }
    return cnt;
}
unsigned int DTSDVMListStore::GetContainers (wxDataViewItemArray &items, boolexonly = false)
Definition at line 165 of file DTSListView.cpp.
References children, expanded, and is_container.
Referenced by DTSDVMListView::GetContainers().
                                                                                   {
    unsigned int cnt;
    size_t acnt, ccnt = 0;
    wxString s;
    acnt = children.size();
    for(cnt=0; cnt < acnt;cnt++) {
        if (children[cnt]->is_container && (!exonly || (exonly && children[cnt]->expanded))) {
            items.Add(wxDataViewItem((void*)children[cnt]));
            ccnt++;
        }
    }
    return ccnt;
}
int DTSDVMListStore::GetNodeID ()
Definition at line 215 of file DTSListView.cpp.
References nodeid.
Referenced by DTS_C_API::dtsgui_treenodeid(), and DTSDVMListView::GetNodeID().
                               {
    return nodeid;
}
DTSDVMListStore * DTSDVMListStore::GetNthChild (size_tidx)
Definition at line 110 of file DTSListView.cpp.
References children.
Referenced by DTSDVMListView::GetNthChild().
                                                        {
    if (idx >= children.size()) {
        return NULL;
    }
    return children[idx];
}
DTSDVMListStore * DTSDVMListStore::GetParent ()
Definition at line 83 of file DTSListView.cpp.
References parent.
Referenced by DTSDVMListView::Delete(), DTSDVMListView::GetParent(), GetParentTitle(), DTSDVMListView::MoveChildDown(), and DTSDVMListView::MoveChildUp().
                                            {
    return parent;
}
const wxString DTSDVMListStore::GetParentTitle ()
Definition at line 87 of file DTSListView.cpp.
References GetParent(), GetTitle(), and parent.
Referenced by DTS_C_API::dtsgui_treenodeparent().
                                               {
    DTSDVMListStore *parent = this->GetParent();
    return (parent) ? parent->GetTitle() : '';
}
const wxString DTSDVMListStore::GetTitle ()
Definition at line 138 of file DTSListView.cpp.
References title.
Referenced by cmp_title(), GetParentTitle(), DTSDVMListView::GetTitle(), DTSDVMListView::GetValue(), DTSTreeWindowEvent::TreeCallback(), and DTSTreeWindowEvent::TreeEvent().
                                         {
    return (const wxString)title;
}
void * DTSDVMListStore::GetUserData (void)
Definition at line 208 of file DTSListView.cpp.
References data.
Referenced by DTS_C_API::dtsgui_treenodegetdata(), and DTSDVMListView::GetUserData().
                                   {
    if (data && objref(data)) {
        return data;
    }
    return NULL;
}
struct xml_node * DTSDVMListStore::GetXMLData (char **buff) [read]
Definition at line 228 of file DTSListView.cpp.
References tattr, and xml.
Referenced by DTSDVMListView::Delete(), DTS_C_API::dtsgui_treenodegetxml(), and DTSDVMListView::GetXMLData().
                                                        {
    struct xml_node *xn = NULL;
    if (xml && objref(xml)) {
        xn = xml;
    }
    if (buff && tattr) {
        *buff = (char*)objchar(tattr);
    }
    return xn;
}
void DTSDVMListStore::Insert (DTSDVMListStore *child, size_tidx)
Definition at line 100 of file DTSListView.cpp.
References children.
                                                               {
    std::vector<DTSDVMListStore*>::iterator iter = children.begin();
    if (idx >= children.size()) {
        return;
    }
    children.insert(iter+idx, child);
}
bool DTSDVMListStore::IsContainer () const
Definition at line 79 of file DTSListView.cpp.
References is_container.
Referenced by DTSDVMListView::IsContainer(), and DTSTreeWindowEvent::TreeEvent().
                                        {
    return is_container;
}
bool DTSDVMListStore::IsExpanded ()
Definition at line 180 of file DTSListView.cpp.
References expanded.
Referenced by DTSTreeWindowEvent::SortParent().
                                 {
    return expanded;
}
bool DTSDVMListStore::MoveChildDown (size_tidx)
Definition at line 196 of file DTSListView.cpp.
References children.
Referenced by DTSDVMListView::MoveChildDown().
                                              {
    DTSDVMListStore *tmp;
    if ((idx < 0) || (idx > children.size()-1)) {
        return false;
    }
    tmp = children[idx];
    children[idx]=children[idx+1];
    children[idx+1]=tmp;
    return true;
}
bool DTSDVMListStore::MoveChildUp (size_tidx)
Definition at line 184 of file DTSListView.cpp.
References children.
Referenced by DTSDVMListView::MoveChildUp().
                                            {
    DTSDVMListStore *tmp;
    if ((idx <= 0) || (idx > children.size())) {
        return false;
    }
    tmp = children[idx-1];
    children[idx-1]=children[idx];
    children[idx]=tmp;
    return true;
}
void DTSDVMListStore::RemoveChildReference (DTSDVMListStore *child)
Definition at line 129 of file DTSListView.cpp.
References children, and GetChildIndex().
Referenced by DTSDVMListView::Delete().
                                                                 {
    std::vector<DTSDVMListStore*>::iterator iter = children.begin();
    size_t idx;
    if ((idx = GetChildIndex(child)) >= 0) {
        children.erase(iter+idx);
    }
}
void DTSDVMListStore::SetExpanded (boolexpanded = true)
Definition at line 150 of file DTSListView.cpp.
References expanded.
Referenced by DTSDVMListView::SetExpanded(), and DTSTreeWindowEvent::SortParent().
                                               {
    this->expanded = expanded;
}
void DTSDVMListStore::SetTitle (const wxString &value)
Definition at line 142 of file DTSListView.cpp.
References title.
Referenced by DTSDVMListView::SetValue().
                                                    {
    title = value;
}
void DTSDVMListStore::SetXMLData (struct xml_node *xnode, const char *tattr)
Definition at line 219 of file DTSListView.cpp.
References xml.
Referenced by DTS_C_API::dtsgui_treenodesetxml(), tree_newnode::handle_newtreenode(), and DTSDVMListView::SetXMLData().
                                                                          {
    if (xnode && objref(xnode)) {
        this->xml = xnode;
    }
    if (tattr) {
        this->tattr = strdup(tattr);
    }
}
void DTSDVMListStore::SortChildren ()
Definition at line 146 of file DTSListView.cpp.
References children, and cmp_title().
Referenced by DTSDVMListView::SortChildren().
                                   {
    std::sort(children.begin(), children.end(), cmp_title);
}
Member Data Documentation
bool DTSDVMListStore::can_delete
Definition at line 50 of file DTSListView.h.
Referenced by DTSDVMCtrl::AppendNode(), and DTSTreeWindowEvent::TreeEvent().
bool DTSDVMListStore::can_edit
Definition at line 48 of file DTSListView.h.
Referenced by DTSDVMCtrl::AppendNode(), and DTSTreeWindowEvent::TreeEvent().
bool DTSDVMListStore::can_sort
Definition at line 49 of file DTSListView.h.
Referenced by DTSDVMCtrl::AppendNode(), and DTSTreeWindowEvent::TreeEvent().
std::vector<DTSDVMListStore*> DTSDVMListStore::children [private]
Definition at line 57 of file DTSListView.h.
Referenced by Append(), GetChildCount(), GetChildIndex(), GetChildren(), GetContainers(), GetNthChild(), Insert(), MoveChildDown(), MoveChildUp(), RemoveChildReference(), SortChildren(), and ~DTSDVMListStore().
void* DTSDVMListStore::data [private]
Definition at line 65 of file DTSListView.h.
Referenced by ConfigPanel(), DTSDVMListStore(), GetUserData(), and ~DTSDVMListStore().
bool DTSDVMListStore::expanded [private]
Definition at line 64 of file DTSListView.h.
Referenced by GetContainers(), IsExpanded(), and SetExpanded().
bool DTSDVMListStore::is_container [private]
Definition at line 62 of file DTSListView.h.
Referenced by DTSDVMListStore(), GetContainers(), and IsContainer().
int DTSDVMListStore::nodeid [private]
Definition at line 66 of file DTSListView.h.
Referenced by DTSDVMListStore(), and GetNodeID().
dtsgui_treeviewpanel_cb DTSDVMListStore::p_cb [private]
Definition at line 58 of file DTSListView.h.
Referenced by ConfigPanel(), and DTSDVMListStore().
DTSDVMListStore* DTSDVMListStore::parent [private]
Definition at line 59 of file DTSListView.h.
Referenced by DTSDVMListStore(), GetParent(), and GetParentTitle().
const char* DTSDVMListStore::tattr [private]
Definition at line 61 of file DTSListView.h.
Referenced by DTSDVMListStore(), GetXMLData(), and ~DTSDVMListStore().
wxString DTSDVMListStore::title [private]
Definition at line 63 of file DTSListView.h.
Referenced by DTSDVMListStore(), GetTitle(), and SetTitle().
struct xml_node* DTSDVMListStore::xml [private]
Definition at line 60 of file DTSListView.h.
Referenced by DTSDVMListStore(), GetXMLData(), SetXMLData(), and ~DTSDVMListStore().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.