.TH "src/DTSFrame.cpp" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/DTSFrame.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <wx/menu\&.h>\fP
.br
\fC#include <wx/msgdlg\&.h>\fP
.br
\fC#include <wx/gauge\&.h>\fP
.br
\fC#include <wx/progdlg\&.h>\fP
.br
\fC#include <wx/toolbar\&.h>\fP
.br
\fC#include <wx/filedlg\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'DTSPanel\&.h'\fP
.br
\fC#include 'evdata\&.h'\fP
.br
\fC#include 'DTSApp\&.h'\fP
.br
\fC#include 'DTSFrame\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
