DTSFrame
NAME
DTSFrame -
SYNOPSIS
#include <DTSFrame.h>
Inherits wxFrame.
Public Member Functions
DTSFrame (const wxString &title, const wxPoint &pos, const wxSize &size, class dtsgui *dtsgui)
~DTSFrame ()
wxMenuBar * GetMenuBar (void)
void CloseMenu (wxMenu *m, int type)
wxMenu * NewMenu (const wxString &name)
void SetAbout (wxMenu *m, const char *a_text)
bool Confirm (wxString text)
void Alert (wxString text)
class basic_auth * Passwd (const char *user, const char *passwd)
const char * FileDialog (const char *title, const char *path, const char *name, const char *filter, long style)
int StartProgress (const wxString &text, int maxval, int quit)
void EndProgress (void)
int UpdateProgress (int cval, const wxString &msg)
int IncProgress (int ival, const wxString &msg)
void SetWindow (wxWindow *window)
class dtsgui * GetDTSData (void)
virtual wxToolBar * OnCreateToolBar (long style, wxWindowID id, const wxString &name)
void SetupToolbar (dtsgui_toolbar_create cb, void *data)
DTSPanel * CreatePane (const wxString &name, const wxString &title, int butmask, enum panel_type type, void *udata)
DTSWindow * TextPanel (const wxString &title, const char *buf)
wxMenuItem * NewMenuItem (wxMenu *m, DTSObject *panel, int menuid, const wxString &hint)
wxMenuItem * NewMenuItem (wxMenu *m, int menuid, const wxString &name, const wxString &hint, int blank, dtsgui_dynpanel cb, void *data)
void SendDTSEvent (int eid, wxObject *evobj)
void SwitchWindow (wxCommandEvent &event)
void DynamicPanelEvent (wxCommandEvent &event)
void OnClose (wxCommandEvent &event)
void OnAbort (wxCloseEvent &event)
void OnAbout (wxCommandEvent &event)
Private Member Functions
void OnDTSEvent (wxCommandEvent &event)
Static Private Member Functions
static int pwevent (struct dtsgui *dtsgui, dtsgui_pane p, int type, int event, void *data)
Private Attributes
wxBoxSizer * sizer
wxWindow * blank
wxWindow * a_window
wxToolBar * toolbar
wxString about
wxMenuBar * menubar
class dtsgui * dtsgui
bool abortconfirm
wxGauge * pbar
wxProgressDialog * pdia
dtsgui_toolbar_create tbcb
void * tb_data
Detailed Description
Definition at line 31 of file DTSFrame.h.
Constructor & Destructor Documentation
DTSFrame::DTSFrame (const wxString &title, const wxPoint &pos, const wxSize &size, class dtsgui *dtsgui)
Definition at line 43 of file DTSFrame.cpp.
References a_window, abortconfirm, about, blank, dtsgui, menubar, OnAbort(), OnDTSEvent(), pbar, pdia, sizer, tb_data, and tbcb.
    : wxFrame(NULL, wxID_ANY, title, pos, size) {
    if (!dtsgui || !objref(dtsgui)) {
        return;
    }
    this->dtsgui = dtsgui;
    /*deleted on close*/
    menubar = new wxMenuBar;
    SetMenuBar(menubar);
    CreateStatusBar();
    tbcb = NULL;
    tb_data = NULL;
// pbar = new wxGauge(toolbar, wxID_ANY, 1000);
    pbar = NULL;
    pdia = NULL;
    about = wxEmptyString;
    /*deleted on close*/
    sizer = new wxBoxSizer(wxHORIZONTAL);
    this->SetSizer(sizer);
    SetMinSize(size);
    blank = new wxWindow(this, -1);
    sizer->Add(blank, 1, wxALL | wxEXPAND);
    a_window = blank;
    blank->Show(true);
    abortconfirm = true;
    Bind(wxEVT_CLOSE_WINDOW, &DTSFrame::OnAbort, this);
    Bind(DTS_APP_EVENT, &DTSFrame::OnDTSEvent, this);
    Show(true);
    Raise();
}
DTSFrame::~DTSFrame ()
Definition at line 86 of file DTSFrame.cpp.
References blank, and tb_data.
                    {
    objunref(dtsgui);
    if (tb_data) {
        objunref(tb_data);
    }
    delete blank;
}
Member Function Documentation
void DTSFrame::Alert (wxStringtext)
Definition at line 120 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_alert().
                                  {
    wxMessageDialog *alert;
    alert = new wxMessageDialog(NULL, text, wxT('Alert'),
                                  wxOK | wxICON_EXCLAMATION);
    alert->ShowModal();
    alert->Destroy();
}
void DTSFrame::CloseMenu (wxMenu *m, inttype)
Definition at line 353 of file DTSFrame.cpp.
References OnClose().
Referenced by DTS_C_API::dtsgui_close(), and DTS_C_API::dtsgui_exit().
                                            {
    switch (type) {
        case wxID_EXIT:
            m->Append(type, '&Quit', 'Quit And Exit');
            Bind(wxEVT_COMMAND_MENU_SELECTED, &DTSFrame::OnClose, this, wxID_EXIT);
            break;
        case wxID_SAVE:
            m->Append(type, 'E&xit', 'Save And Exit');
            Bind(wxEVT_COMMAND_MENU_SELECTED, &DTSFrame::OnClose, this, wxID_SAVE);
            break;
    }
}
bool DTSFrame::Confirm (wxStringtext)
Definition at line 104 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_confirm(), DTSTreeWindowEvent::MenuEvent(), OnAbort(), and OnClose().
                                    {
    wxMessageDialog *confirm;
    int res;
    confirm = new wxMessageDialog(NULL, text, wxT('Confirm'),
                                  wxYES_NO | wxNO_DEFAULT | wxICON_QUESTION);
    res = confirm->ShowModal();
    confirm->Destroy();
    if (res == wxID_YES) {
        return true;
    } else {
        return false;
    }
}
DTSPanel * DTSFrame::CreatePane (const wxString &name, const wxString &title, intbutmask, enum panel_typetype, void *udata)
Definition at line 375 of file DTSFrame.cpp.
References DTSPanel::SetTitle(), DTSObject::SetUserData(), wx_DTSPANEL_DIALOG, wx_DTSPANEL_PANEL, wx_DTSPANEL_SCROLLPANEL, wx_DTSPANEL_TAB, wx_DTSPANEL_TREE, wx_DTSPANEL_WINDOW, and wx_DTSPANEL_WIZARD.
Referenced by dtsgui_wizard::AddPage(), DTS_C_API::dtsgui_panel(), and Passwd().
                                                                                                                          {
    DTSPanel *dp = NULL;
    switch (type) {
        case wx_DTSPANEL_SCROLLPANEL:
            dp = new DTSScrollPanel(this, this, name, butmask);
            break;
        case wx_DTSPANEL_PANEL:
            dp = new DTSStaticPanel(this, this, name, butmask);
            break;
        case wx_DTSPANEL_WINDOW:
            dp = new DTSWindow(this);
            break;
        case wx_DTSPANEL_DIALOG:
            dp = new DTSDialog(this, name, butmask);
            break;
        case wx_DTSPANEL_WIZARD:
            dp = new DTSWizardWindow(name);
            break;
        case wx_DTSPANEL_TAB:
        case wx_DTSPANEL_TREE:
            break;
    }
    if (title.Len() > 0) {
        dp->SetTitle(title, true);
    }
    if (udata) {
        dp->SetUserData(udata);
    }
    return dp;
}
void DTSFrame::DynamicPanelEvent (wxCommandEvent &event)
Definition at line 272 of file DTSFrame.cpp.
References a_window, evdata::data, dynamic_panel::HasCallback(), dynamic_panel::IsBlank(), dynamic_panel::RunCallback(), SetWindow(), and dynamic_panel::w.
Referenced by NewMenuItem().
                                                      {
    class evdata *evdat;
    class dynamic_panel *p_dyn;
    wxWindow *w;
    if (!(evdat = (evdata *)event.m_callbackUserData)) {
        SetWindow(NULL);
        return;
    }
    if (!evdat->data || !(p_dyn = (class dynamic_panel*)evdat->data) || !p_dyn->HasCallback() ) {
        SetWindow(NULL);
        return;
    }
    if (*p_dyn == *a_window) {
        return;
    }
    if (p_dyn->IsBlank()) {
        SetWindow(NULL);
    }
    if ((w = p_dyn->RunCallback(dtsgui))) {
        SetWindow(w);
    }
}
void DTSFrame::EndProgress (void)
Definition at line 181 of file DTSFrame.cpp.
References pdia.
Referenced by dtsgui_curl::curl_progress_ctrl(), and DTS_C_API::dtsgui_progress_end().
                               {
    if (pdia) {
        pdia->Hide();
        delete pdia;
        pdia = NULL;
    }
/* if (pbar) {
        pbar->Hide();
    }*/
}
const char * DTSFrame::FileDialog (const char *title, const char *path, const char *name, const char *filter, longstyle)
Definition at line 408 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_fileopen(), and DTS_C_API::dtsgui_filesave().
                                                                                                                      {
    void *filename = NULL;
    wxFileDialog *fd;
    fd = new wxFileDialog(this, title, (path) ? path : '', (name) ? name : '', (filter) ? filter : wxFileSelectorDefaultWildcardStr, style);
    if (fd->ShowModal() != wxID_CANCEL) {
        filename = objchar(fd->GetPath().ToUTF8());
    }
    delete fd;
    return (const char*)filename;
}
class dtsgui * DTSFrame::GetDTSData (void)
Definition at line 307 of file DTSFrame.cpp.
References dtsgui.
Referenced by DTSTreeWindow::DTSTreeWindow(), and DTSPanelEvent::RunCallBack().
                                       {
    if (dtsgui && objref(dtsgui)) {
        return dtsgui;
    }
    return NULL;
}
wxMenuBar * DTSFrame::GetMenuBar (void)
Definition at line 349 of file DTSFrame.cpp.
References menubar.
                                {
    return menubar;
}
int DTSFrame::IncProgress (intival, const wxString &msg)
Definition at line 166 of file DTSFrame.cpp.
References pdia.
Referenced by DTS_C_API::dtsgui_progress_increment().
                                                        {
/* if (pbar) {
        pbar->SetValue(pbar->GetValue()+ival);
    }*/
    if (pdia) {
        if (pdia->Update(pdia->GetValue()+ival, text)) {
            return 1;
        } else {
            return 0;
        }
    } else {
        return 0;
    }
}
wxMenu * DTSFrame::NewMenu (const wxString &name)
Definition at line 366 of file DTSFrame.cpp.
References menubar.
Referenced by DTS_C_API::dtsgui_newmenu().
                                              {
    wxMenu *new_menu = NULL;
    new_menu = new wxMenu;
    menubar->Append(new_menu, name);
    return new_menu;
}
wxMenuItem * DTSFrame::NewMenuItem (wxMenu *m, DTSObject *panel, intmenuid, const wxString &hint)
Definition at line 435 of file DTSFrame.cpp.
References DTSObject::GetName(), DTSObject::GetPanel(), and SwitchWindow().
Referenced by DTS_C_API::dtsgui_newmenucb(), and DTS_C_API::dtsgui_newmenuitem().
                                                                                               {
    wxMenuItem *mi;
    wxWindow *w = NULL;
    wxObject *ev_data;
    wxString name = wxEmptyString;
    if (panel) {
        w = panel->GetPanel();
        name = panel->GetName();
    }
    ev_data = new evdata(w);
    mi = m->Append(menuid, hint, name);
    Bind(wxEVT_COMMAND_MENU_SELECTED, &DTSFrame::SwitchWindow, this, menuid, menuid, ev_data);
    return mi;
}
wxMenuItem * DTSFrame::NewMenuItem (wxMenu *m, intmenuid, const wxString &name, const wxString &hint, intblank, dtsgui_dynpanelcb, void *data)
Definition at line 453 of file DTSFrame.cpp.
References DynamicPanelEvent().
                                                                                                                                              {
    wxMenuItem *mi;
    wxObject *ev_data;
    class dynamic_panel *p_dyn;
    if (!(p_dyn = new dynamic_panel(name, blank, cb, data))) {
        return NULL;
    }
    ev_data = new evdata(p_dyn, 1);
    objunref(p_dyn);
    mi = m->Append(menuid, hint, name);
    Bind(wxEVT_COMMAND_MENU_SELECTED, &DTSFrame::DynamicPanelEvent, this, menuid, menuid, ev_data);
    return mi;
}
void DTSFrame::OnAbort (wxCloseEvent &event)
Definition at line 196 of file DTSFrame.cpp.
References abortconfirm, and Confirm().
Referenced by DTSFrame().
                                          {
    if (abortconfirm && !Confirm('Are You Sure You Want To Abort ?')) {
        event.Veto();
    } else {
        event.Skip(true);
    }
}
void DTSFrame::OnAbout (wxCommandEvent &event)
Definition at line 231 of file DTSFrame.cpp.
References about.
Referenced by SetAbout().
                                            {
    wxMessageBox(about, 'About', wxOK | wxICON_INFORMATION );
}
void DTSFrame::OnClose (wxCommandEvent &event)
Definition at line 204 of file DTSFrame.cpp.
References abortconfirm, and Confirm().
Referenced by CloseMenu().
                                            {
    bool confirm;
    int eid;
    eid=event.GetId();
    switch (eid) {
        case wxID_EXIT:
            confirm = Confirm('Quit Without Saving ?');
            break;
        case wxID_SAVE:
            confirm = Confirm('Save And Exit ?');
            break;
        default:
            confirm = true;
    }
    if (confirm) {
        abortconfirm = false;
        Close(true);
    } else {
        event.Skip();
    }
}
wxToolBar * DTSFrame::OnCreateToolBar (longstyle, wxWindowIDid, const wxString &name) [virtual]
Definition at line 314 of file DTSFrame.cpp.
References tb_data, and tbcb.
                                                                                    {
    wxToolBar *tb;
    if (tbcb) {
        objref(dtsgui);
        tb = (wxToolBar*)tbcb(dtsgui, this, style, id, name, tb_data);
        objunref(dtsgui);
    } else {
        tb = new wxToolBar(this, id, wxDefaultPosition, wxDefaultSize, style, name);
    }
    return tb;
}
void DTSFrame::OnDTSEvent (wxCommandEvent &event) [private]
Definition at line 192 of file DTSFrame.cpp.
Referenced by DTSFrame().
                                               {
    event.Skip(true);
}
class basic_auth * DTSFrame::Passwd (const char *user, const char *passwd)
Definition at line 495 of file DTSFrame.cpp.
References CreatePane(), DTSGUI_FORM_DATA_PTR, pwevent(), DTSDialog::RunDialog(), DTSPanel::TextBox(), wx_DTSPANEL_DIALOG, and wx_PANEL_BUTTON_ACTION.
Referenced by dtsgui_curl::CurlPasswd(), and DTS_C_API::dtsgui_pwdialog().
                                                                       {
    struct basic_auth *bauth;
    DTSDialog *pwbox;
    if (!(bauth = curl_newauth(user, passwd))) {
        return NULL;
    }
    pwbox = (DTSDialog*)CreatePane('Athentification', wxEmptyString, wx_PANEL_BUTTON_ACTION, wx_DTSPANEL_DIALOG, bauth);
    pwbox->TextBox('Username', 'uname', bauth->user, wxTE_LEFT | wxTE_PROCESS_ENTER, 1, NULL, DTSGUI_FORM_DATA_PTR);
    pwbox->TextBox('Password', 'pwd', bauth->passwd, wxTE_PASSWORD | wxTE_PROCESS_ENTER, 1, NULL, DTSGUI_FORM_DATA_PTR);
    pwbox->RunDialog(pwevent, NULL);
    return bauth;
}
int DTSFrame::pwevent (struct dtsgui *dtsgui, dtsgui_panep, inttype, intevent, void *data) [static], [private]
Definition at line 470 of file DTSFrame.cpp.
References DTSPanel::FindValue(), DTSObject::GetUserData(), and wx_PANEL_EVENT_BUTTON_YES.
Referenced by Passwd().
                                                                                           {
    struct basic_auth *auth;
    DTSDialog *dp = (DTSDialog*)p;
    if (event == wx_PANEL_EVENT_BUTTON_YES) {
        if (!(auth = (struct basic_auth*)dp->GetUserData())) {
            return 0;
        }
        if (auth->user) {
            free((void*)auth->user);
            auth->user = NULL;
        }
        if (auth->passwd) {
            memset((void*)auth->passwd, 0, strlen(auth->passwd));
            free((void*)auth->passwd);
            auth->passwd = NULL;
        }
        auth->user = dp->FindValue('uname');
        auth->passwd = dp->FindValue('pwd');
        objunref(auth);
    }
    return 1;
}
void DTSFrame::SendDTSEvent (inteid, wxObject *evobj)
Definition at line 300 of file DTSFrame.cpp.
Referenced by DTS_C_API::dtsgui_sendevent().
                                                    {
    wxCommandEvent event(DTS_APP_EVENT, eid);
    event.SetEventObject(evobj);
    event.ShouldPropagate();
    ProcessWindowEvent(event);
}
void DTSFrame::SetAbout (wxMenu *m, const char *a_text)
Definition at line 94 of file DTSFrame.cpp.
References about, and OnAbout().
Referenced by DTS_C_API::dtsgui_about().
                                                     {
    if (about.Len() > 0) {
        return;
    }
    m->Append(wxID_ABOUT);
    Bind(wxEVT_COMMAND_MENU_SELECTED, &DTSFrame::OnAbout, this, wxID_ABOUT);
    about = a_text;
}
void DTSFrame::SetupToolbar (dtsgui_toolbar_createcb, void *data)
Definition at line 328 of file DTSFrame.cpp.
References dtsgui::cb, pbar, tb_data, tbcb, and toolbar.
Referenced by DTS_C_API::dtsgui_setuptoolbar().
                                                                {
    tbcb = cb;
    if (tb_data) {
        objunref(tb_data);
        tb_data = NULL;
    }
    if (data && objref(data)) {
        tb_data = data;
    }
    toolbar = CreateToolBar();
    if (pbar) {
        toolbar->AddControl(pbar);
        pbar->Hide();
    }
    toolbar->Realize();
}
void DTSFrame::SetWindow (wxWindow *window)
Definition at line 235 of file DTSFrame.cpp.
References a_window, blank, dtsgui::SetStatusText(), and sizer.
Referenced by DTS_C_API::dtsgui_setwindow(), DynamicPanelEvent(), and SwitchWindow().
                                         {
    if (!window) {
        window = blank;
    }
    if (window == a_window) {
        return;
    }
    a_window->Show(false);
    sizer->Replace(a_window, window);
    if (window == blank) {
        dtsgui->SetStatusText();
    }
    window->Show(true);
    sizer->Layout();
    sizer->FitInside(this);
    a_window = window;
}
int DTSFrame::StartProgress (const wxString &text, intmaxval, intquit)
Definition at line 129 of file DTSFrame.cpp.
References pbar, and pdia.
Referenced by dtsgui_curl::curl_progress_function(), and DTS_C_API::dtsgui_progress_start().
                                                                      {
    int flags;
    if (!quit && pbar) {
        pbar->SetRange(maxval);
        pbar->Show();
        pbar->Pulse();
        return 1;
    } else {
        flags = wxPD_APP_MODAL | wxPD_AUTO_HIDE | wxPD_ELAPSED_TIME;
        if (quit) {
            flags |= wxPD_CAN_ABORT;
        }
        if ((pdia = new wxProgressDialog('Progress', text, maxval, NULL, flags))) {
            pdia->Show();
            pdia->Pulse();
            return 1;
        }
    }
    return 0;
}
void DTSFrame::SwitchWindow (wxCommandEvent &event)
Definition at line 257 of file DTSFrame.cpp.
References a_window, blank, evdata::data, and SetWindow().
Referenced by NewMenuItem().
                                                 {
    wxWindow *window;
    class evdata *evdat;
    evdat = (evdata*)event.m_callbackUserData;
    if (!evdat || (!(window = (wxWindow*)evdat->data))) {
        window = blank;
    }
    if (window != a_window) {
        SetWindow(window);
    }
}
DTSWindow * DTSFrame::TextPanel (const wxString &title, const char *buf)
Definition at line 421 of file DTSFrame.cpp.
References DTSPanel::AddItem(), and DTSObject::GetPanel().
Referenced by DTS_C_API::dtsgui_textpane().
                                                                     {
    DTSWindow *p;
    wxWindow *w;
    wxTextCtrl *tc;
    p = new DTSWindow(this, this, title);
    w = p->GetPanel();
    tc = new wxTextCtrl(w, -1, buf, wxDefaultPosition, wxDefaultSize,wxTE_MULTILINE | wxHSCROLL | wxTE_READONLY);
    p->AddItem(tc, wxGBPosition(0,0), wxGBSpan(10, 6), wxEXPAND|wxGROW, 0, 0);
    return p;
}
int DTSFrame::UpdateProgress (intcval, const wxString &msg)
Definition at line 151 of file DTSFrame.cpp.
References pdia.
Referenced by dtsgui_curl::curl_progress_function(), and DTS_C_API::dtsgui_progress_update().
                                                           {
/* if (pbar) {
        pbar->SetValue(cval);
    }*/
    if (pdia) {
        if (pdia->Update(cval, text)) {
            return 1;
        } else {
            return 0;
        }
    } else {
        return 0;
    }
}
Member Data Documentation
wxWindow* DTSFrame::a_window [private]
Definition at line 69 of file DTSFrame.h.
Referenced by DTSFrame(), DynamicPanelEvent(), SetWindow(), and SwitchWindow().
bool DTSFrame::abortconfirm [private]
Definition at line 74 of file DTSFrame.h.
Referenced by DTSFrame(), OnAbort(), and OnClose().
wxString DTSFrame::about [private]
Definition at line 71 of file DTSFrame.h.
Referenced by DTSFrame(), OnAbout(), and SetAbout().
wxWindow* DTSFrame::blank [private]
Definition at line 68 of file DTSFrame.h.
Referenced by DTSFrame(), SetWindow(), SwitchWindow(), and ~DTSFrame().
class dtsgui* DTSFrame::dtsgui [private]
Definition at line 73 of file DTSFrame.h.
Referenced by DTSFrame(), and GetDTSData().
wxMenuBar* DTSFrame::menubar [private]
Definition at line 72 of file DTSFrame.h.
Referenced by DTSFrame(), GetMenuBar(), and NewMenu().
wxGauge* DTSFrame::pbar [private]
Definition at line 75 of file DTSFrame.h.
Referenced by DTSFrame(), SetupToolbar(), and StartProgress().
wxProgressDialog* DTSFrame::pdia [private]
Definition at line 76 of file DTSFrame.h.
Referenced by DTSFrame(), EndProgress(), IncProgress(), StartProgress(), and UpdateProgress().
wxBoxSizer* DTSFrame::sizer [private]
Definition at line 67 of file DTSFrame.h.
Referenced by DTSFrame(), and SetWindow().
void* DTSFrame::tb_data [private]
Definition at line 78 of file DTSFrame.h.
Referenced by DTSFrame(), OnCreateToolBar(), SetupToolbar(), and ~DTSFrame().
dtsgui_toolbar_create DTSFrame::tbcb [private]
Definition at line 77 of file DTSFrame.h.
Referenced by DTSFrame(), OnCreateToolBar(), and SetupToolbar().
wxToolBar* DTSFrame::toolbar [private]
Definition at line 70 of file DTSFrame.h.
Referenced by SetupToolbar().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.