.TH "src/include/DTSFrame.h" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/DTSFrame.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/frame\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDTSFrame\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fBwxBoxSizer\fP \fBwxBoxSizer\fP"
.br
.ti -1c
.RI "typedef class \fBwxGauge\fP \fBwxGauge\fP"
.br
.ti -1c
.RI "typedef class \fBwxProgressDialog\fP \fBwxProgressDialog\fP"
.br
.ti -1c
.RI "typedef class \fBDTSPanel\fP \fBDTSPanel\fP"
.br
.ti -1c
.RI "typedef class \fBDTSObject\fP \fBDTSObject\fP"
.br
.ti -1c
.RI "typedef class \fBDTSWindow\fP \fBDTSWindow\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef class \fBDTSObject\fP \fBDTSObject\fP"

.PP
Definition at line 28 of file DTSFrame\&.h\&.
.SS "typedef class \fBDTSPanel\fP \fBDTSPanel\fP"

.PP
Definition at line 27 of file DTSFrame\&.h\&.
.SS "typedef class \fBDTSWindow\fP \fBDTSWindow\fP"

.PP
Definition at line 29 of file DTSFrame\&.h\&.
.SS "typedef class \fBwxBoxSizer\fP \fBwxBoxSizer\fP"

.PP
Definition at line 24 of file DTSFrame\&.h\&.
.SS "typedef class \fBwxGauge\fP \fBwxGauge\fP"

.PP
Definition at line 25 of file DTSFrame\&.h\&.
.SS "typedef class \fBwxProgressDialog\fP \fBwxProgressDialog\fP"

.PP
Definition at line 26 of file DTSFrame\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
