.TH "dtsgui" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtsgui \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSApp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTS_OJBREF_CLASS\fP (\fBdtsgui\fP)"
.br
.ti -1c
.RI "\fBdtsgui\fP (const char *title, const char *stat, struct \fBpoint\fP w_size, struct \fBpoint\fP w_pos, \fBdtsgui_configcb\fP confcallback_cb, void *userdata)"
.br
.ti -1c
.RI "int \fBSetupAPPFrame\fP (void)"
.br
.ti -1c
.RI "void * \fBGetUserData\fP (void)"
.br
.ti -1c
.RI "void \fBSetStatusText\fP (void)"
.br
.ti -1c
.RI "void \fBAppendTitle\fP (const char *text)"
.br
.ti -1c
.RI "class \fBDTSFrame\fP * \fBGetFrame\fP (void)"
.br
.ti -1c
.RI "void \fBShowToolbar\fP (bool show=true)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file DTSApp\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dtsgui::dtsgui (const char *title, const char *stat, struct \fBpoint\fPw_size, struct \fBpoint\fPw_pos, \fBdtsgui_configcb\fPconfcallback_cb, void *userdata)"

.PP
Definition at line 29 of file DTSApp\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void dtsgui::AppendTitle (const char *text)"

.PP
Definition at line 99 of file DTSApp\&.cpp\&.
.SS "dtsgui::DTS_OJBREF_CLASS (\fBdtsgui\fP)"

.SS "class \fBDTSFrame\fP * dtsgui::GetFrame (void)"

.PP
Definition at line 131 of file DTSApp\&.cpp\&.
.SS "void * dtsgui::GetUserData (void)"

.PP
Definition at line 79 of file DTSApp\&.cpp\&.
.SS "void dtsgui::SetStatusText (void)"

.PP
Definition at line 91 of file DTSApp\&.cpp\&.
.SS "int dtsgui::SetupAPPFrame (void)"

.PP
Definition at line 58 of file DTSApp\&.cpp\&.
.SS "void dtsgui::ShowToolbar (boolshow = \fCtrue\fP)"

.PP
Definition at line 123 of file DTSApp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
