.TH "dtsgui_wizard" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtsgui_wizard \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSWizard\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTS_OJBREF_CLASS\fP (\fBdtsgui_wizard\fP)"
.br
.ti -1c
.RI "\fBdtsgui_wizard\fP (class \fBdtsgui\fP *\fBdtsgui\fP, \fBwxWindow\fP *f, const wxString &title)"
.br
.ti -1c
.RI "\fBDTSWizardWindow\fP * \fBAddPage\fP (const char *title, struct xml_doc *xmldoc, void *userdata)"
.br
.ti -1c
.RI "int \fBRunWizard\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file DTSWizard\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dtsgui_wizard::dtsgui_wizard (class \fBdtsgui\fP *dtsgui, \fBwxWindow\fP *f, const wxString &title)"

.PP
Definition at line 30 of file DTSWizard\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDTSWizardWindow\fP * dtsgui_wizard::AddPage (const char *title, struct xml_doc *xmldoc, void *userdata)"

.PP
Definition at line 48 of file DTSWizard\&.cpp\&.
.SS "dtsgui_wizard::DTS_OJBREF_CLASS (\fBdtsgui_wizard\fP)"

.SS "int dtsgui_wizard::RunWizard ()"

.PP
Definition at line 81 of file DTSWizard\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
