dtsgui_curl
NAME
dtsgui_curl -
SYNOPSIS
#include <DTSApp.h>
Public Member Functions
DTS_OJBREF_CLASS (dtsgui_curl)
dtsgui_curl (class dtsgui *dtsgui)
void Close ()
DTSFrame * GetFrame ()
Static Private Member Functions
static struct basic_auth * CurlPasswd (const char *user, const char *passwd, void *data)
static void * curl_startprogress (void *data)
static void curl_progress_ctrl (void *data, int pause)
static int curl_progress_function (void *data, double dltotal, double dlnow, double ultotal, double ulnow)
Private Attributes
class DTSFrame * frame
int curl
Detailed Description
Definition at line 42 of file DTSApp.h.
Constructor & Destructor Documentation
dtsgui_curl::dtsgui_curl (class dtsgui *dtsgui)
Definition at line 141 of file DTSApp.cpp.
References curl, curl_progress_ctrl(), curl_progress_function(), curl_startprogress(), CurlPasswd(), frame, and dtsgui::GetFrame().
                                             {
    frame = dtsgui->GetFrame();
    curl = curlinit();
    curl_setprogress(curl_progress_function, curl_progress_ctrl, curl_startprogress, dtsgui);
    curl_setauth_cb(CurlPasswd, this);
}
Member Function Documentation
void dtsgui_curl::Close ()
Definition at line 154 of file DTSApp.cpp.
References curl.
                        {
    if (curl) {
        curlclose();
        curl = 0;
    }
}
void dtsgui_curl::curl_progress_ctrl (void *data, intpause) [static], [private]
Definition at line 194 of file DTSApp.cpp.
References DTSFrame::EndProgress(), curl_progress::GetFrame(), curl_progress::pause, and curl_progress::pd.
Referenced by dtsgui_curl().
                                                          {
    class curl_progress *cp = (class curl_progress*)data;
    DTSFrame *f = cp->GetFrame();
    switch(pause) {
        case 0:
            cp->pause = pause;
            break;
        case 1:
            f->EndProgress();
            cp->pause = pause;
            cp->pd = 0;
            break;
        case -1:
            if (cp->pd) {
                f->EndProgress();
            }
            objunref(cp);
            break;
    }
}
int dtsgui_curl::curl_progress_function (void *data, doubledltotal, doubledlnow, doubleultotal, doubleulnow) [static], [private]
Definition at line 168 of file DTSApp.cpp.
References curl_progress::GetFrame(), curl_progress::pause, curl_progress::pd, DTSFrame::StartProgress(), and DTSFrame::UpdateProgress().
Referenced by dtsgui_curl().
                                                                                                              {
    class curl_progress *cp = (class curl_progress*)data;
    DTSFrame *f;
    int val, tot, cur;
    if (!cp || cp->pause || !(f = cp->GetFrame())) {
        return 0;
    }
    tot = dltotal+ultotal;
    cur = ulnow+dlnow;
    val = (tot && cur) ? (1000/tot) * cur : 0;
    val = ceil(val);
    if (!cp->pd) {
        cp->pd = f->StartProgress('Web Transfer Progress', 1000, 1);
    };
    if (cp->pd && val && !f->UpdateProgress(val, wxEmptyString)) {
        return 1;
    }
    return 0;
}
void * dtsgui_curl::curl_startprogress (void *data) [static], [private]
Definition at line 162 of file DTSApp.cpp.
Referenced by dtsgui_curl().
                                                {
    class dtsgui_curl *dc = (class dtsgui_curl*)data;
    return new class curl_progress(dc);
}
struct basic_auth * dtsgui_curl::CurlPasswd (const char *user, const char *passwd, void *data) [static], [read], [private]
Definition at line 216 of file DTSApp.cpp.
References frame, and DTSFrame::Passwd().
Referenced by dtsgui_curl().
                                                                                           {
    class dtsgui_curl *dc = (class dtsgui_curl*)data;
    class DTSFrame *f = dc->frame;
    return f->Passwd(user, passwd);
}
dtsgui_curl::DTS_OJBREF_CLASS (dtsgui_curl)
DTSFrame * dtsgui_curl::GetFrame (void)
Definition at line 223 of file DTSApp.cpp.
References frame.
                                {
    return frame;
}
Member Data Documentation
int dtsgui_curl::curl [private]
Definition at line 54 of file DTSApp.h.
Referenced by Close(), dtsgui_curl(), DTSApp::OnInit(), and DTSApp::~DTSApp().
class DTSFrame* dtsgui_curl::frame [private]
Definition at line 53 of file DTSApp.h.
Referenced by CurlPasswd(), dtsgui_curl(), and GetFrame().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.