dtsgui
NAME
dtsgui -
SYNOPSIS
#include <DTSApp.h>
Public Member Functions
DTS_OJBREF_CLASS (dtsgui)
dtsgui (const char *title, const char *stat, struct point w_size, struct point w_pos, dtsgui_configcb confcallback_cb, void *userdata)
int SetupAPPFrame (void)
void * GetUserData (void)
void SetStatusText (void)
void AppendTitle (const char *text)
class DTSFrame * GetFrame (void)
void ShowToolbar (bool show=true)
Private Attributes
void * userdata
class DTSFrame * appframe
const char * title
const char * status
dtsgui_configcb cb
struct point wsize
struct point wpos
Detailed Description
Definition at line 22 of file DTSApp.h.
Constructor & Destructor Documentation
dtsgui::dtsgui (const char *title, const char *stat, struct pointw_size, struct pointw_pos, dtsgui_configcbconfcallback_cb, void *userdata)
Definition at line 35 of file DTSApp.cpp.
References cb, status, userdata, wpos, and wsize.
Member Function Documentation
void dtsgui::AppendTitle (const char *text)
Definition at line 105 of file DTSApp.cpp.
References appframe, and title.
Referenced by DTS_C_API::dtsgui_titleappend().
dtsgui::DTS_OJBREF_CLASS (dtsgui)
class DTSFrame * dtsgui::GetFrame (void)
Definition at line 137 of file DTSApp.cpp.
References appframe.
Referenced by dtsgui_wizard::AddPage(), DTS_C_API::dtsgui_about(), DTS_C_API::dtsgui_alert(), DTS_C_API::dtsgui_close(), DTS_C_API::dtsgui_confirm(), dtsgui_curl::dtsgui_curl(), DTS_C_API::dtsgui_exit(), DTS_C_API::dtsgui_fileopen(), DTS_C_API::dtsgui_filesave(), DTS_C_API::dtsgui_newmenu(), DTS_C_API::dtsgui_newmenucb(), DTS_C_API::dtsgui_newmenuitem(), DTS_C_API::dtsgui_newwizard(), DTS_C_API::dtsgui_panel(), DTS_C_API::dtsgui_progress_end(), DTS_C_API::dtsgui_progress_increment(), DTS_C_API::dtsgui_progress_start(), DTS_C_API::dtsgui_progress_update(), DTS_C_API::dtsgui_sendevent(), DTS_C_API::dtsgui_setuptoolbar(), DTS_C_API::dtsgui_setwindow(), DTS_C_API::dtsgui_tabwindow(), DTS_C_API::dtsgui_textpane(), and DTS_C_API::dtsgui_treewindow().
void * dtsgui::GetUserData (void)
Definition at line 85 of file DTSApp.cpp.
References userdata.
Referenced by DTS_C_API::dtsgui_userdata().
void dtsgui::SetStatusText (void)
Definition at line 97 of file DTSApp.cpp.
References appframe, and status.
Referenced by SetupAPPFrame(), and DTSFrame::SetWindow().
int dtsgui::SetupAPPFrame (void)
Definition at line 64 of file DTSApp.cpp.
References appframe, cb, SetStatusText(), title, userdata, wpos, wsize, point::x, and point::y.
Referenced by DTSApp::OnInit().
void dtsgui::ShowToolbar (boolshow = true)
Definition at line 129 of file DTSApp.cpp.
References appframe.
Referenced by DTS_C_API::dtsgui_set_toolbar().
Member Data Documentation
class DTSFrame* dtsgui::appframe [private]
Definition at line 34 of file DTSApp.h.
Referenced by AppendTitle(), GetFrame(), SetStatusText(), SetupAPPFrame(), and ShowToolbar().
dtsgui_configcb dtsgui::cb [private]
Definition at line 37 of file DTSApp.h.
Referenced by dtsgui(), DTSPanelEvent::OnCombo(), SetupAPPFrame(), and DTSFrame::SetupToolbar().
const char* dtsgui::status [private]
Definition at line 36 of file DTSApp.h.
Referenced by dtsgui(), and SetStatusText().
const char* dtsgui::title [private]
Definition at line 35 of file DTSApp.h.
Referenced by AppendTitle(), and SetupAPPFrame().
void* dtsgui::userdata [private]
Definition at line 33 of file DTSApp.h.
Referenced by dtsgui(), GetUserData(), and SetupAPPFrame().
struct point dtsgui::wpos [private]
Definition at line 39 of file DTSApp.h.
Referenced by dtsgui(), and SetupAPPFrame().
struct point dtsgui::wsize [private]
Definition at line 38 of file DTSApp.h.
Referenced by dtsgui(), and SetupAPPFrame().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.