.TH "dtsgui_curl" 3 "Thu Oct 10 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dtsgui_curl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSApp\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTS_OJBREF_CLASS\fP (\fBdtsgui_curl\fP)"
.br
.ti -1c
.RI "\fBdtsgui_curl\fP (class \fBdtsgui\fP *\fBdtsgui\fP)"
.br
.ti -1c
.RI "void \fBClose\fP ()"
.br
.ti -1c
.RI "\fBDTSFrame\fP * \fBGetFrame\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file DTSApp\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dtsgui_curl::dtsgui_curl (class \fBdtsgui\fP *dtsgui)"

.PP
Definition at line 141 of file DTSApp\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void dtsgui_curl::Close ()"

.PP
Definition at line 154 of file DTSApp\&.cpp\&.
.SS "dtsgui_curl::DTS_OJBREF_CLASS (\fBdtsgui_curl\fP)"

.SS "\fBDTSFrame\fP * dtsgui_curl::GetFrame (void)"

.PP
Definition at line 223 of file DTSApp\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
