dtsgui_wizard
NAME
dtsgui_wizard -
SYNOPSIS
#include <DTSWizard.h>
Public Member Functions
DTS_OJBREF_CLASS (dtsgui_wizard)
dtsgui_wizard (class dtsgui *dtsgui, wxWindow *f, const wxString &title)
DTSWizardWindow * AddPage (const char *title, struct xml_doc *xmldoc, void *userdata)
int RunWizard ()
Private Attributes
wxWizard * wiz
wxWizardPageSimple * start
class dtsgui * dtsgui
Detailed Description
Definition at line 26 of file DTSWizard.h.
Constructor & Destructor Documentation
dtsgui_wizard::dtsgui_wizard (class dtsgui *dtsgui, wxWindow *f, const wxString &title)
Definition at line 38 of file DTSWizard.cpp.
References start, and wiz.
                                                                                   {
    if (dgui && objref(dgui)) {
        dtsgui = dgui;
        wiz = new wxWizard(f, wxID_ANY, title, wxNullBitmap, wxDefaultPosition, wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER);
    }
    start = NULL;
}
Member Function Documentation
DTSWizardWindow * dtsgui_wizard::AddPage (const char *title, struct xml_doc *xmldoc, void *userdata)
Definition at line 56 of file DTSWizard.cpp.
References DTSFrame::CreatePane(), dtsgui::GetFrame(), DTSPanel::SetTitle(), DTSObject::SetXMLDoc(), start, wiz, and wx_DTSPANEL_WIZARD.
Referenced by DTS_C_API::dtsgui_wizard_addpage().
                                                                                                 {
    DTSWizardWindow *dww;
    wxWizardPageSimple *wp, *tmp;
    wxWizardPage *last;
    DTSFrame *f = dtsgui->GetFrame();
    dww = (DTSWizardWindow*)f->CreatePane(title, wxEmptyString, 0, wx_DTSPANEL_WIZARD, userdata);
    wp = dynamic_cast<wxWizardPageSimple *>(dww);
    wp->Create(wiz);
    if (title) {
        dww->SetTitle(title, true);
    }
    if (xmldoc) {
        dww->SetXMLDoc(xmldoc);
    }
    objlock(this);
    if (!start) {
        start = wp;
    } else {
        for(last = start; last->GetNext(); last=last->GetNext());
        tmp = dynamic_cast<wxWizardPageSimple*>(last);
        tmp->SetNext(wp);
        wp->SetPrev(tmp);
    }
    objunlock(this);
    return dww;
}
dtsgui_wizard::DTS_OJBREF_CLASS (dtsgui_wizard)
int dtsgui_wizard::RunWizard ()
Definition at line 89 of file DTSWizard.cpp.
References start, and wiz.
Referenced by DTS_C_API::dtsgui_runwizard().
                             {
    wiz->GetPageAreaSizer()->Add(start);
    wiz->Center();
    return wiz->RunWizard(start);
}
Member Data Documentation
class dtsgui* dtsgui_wizard::dtsgui [private]
Definition at line 35 of file DTSWizard.h.
wxWizardPageSimple* dtsgui_wizard::start [private]
Definition at line 34 of file DTSWizard.h.
Referenced by AddPage(), dtsgui_wizard(), and RunWizard().
wxWizard* dtsgui_wizard::wiz [private]
Definition at line 33 of file DTSWizard.h.
Referenced by AddPage(), dtsgui_wizard(), and RunWizard().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.