.TH "DTSObject" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSObject \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSPanel\&.h>\fP
.PP
Inherits wxWindow\&.
.PP
Inherited by \fBDTSPanel\fP, \fBDTSTabWindow\fP, and \fBDTSTreeWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSObject\fP (wxString=wxEmptyString)"
.br
.ti -1c
.RI "\fB~DTSObject\fP ()"
.br
.ti -1c
.RI "wxString \fBGetName\fP ()"
.br
.ti -1c
.RI "\fBwxWindow\fP * \fBGetPanel\fP ()"
.br
.ti -1c
.RI "\fBDTSFrame\fP * \fBGetFrame\fP ()"
.br
.ti -1c
.RI "void \fBEventHandler\fP (int eid, wxCommandEvent *event)"
.br
.ti -1c
.RI "struct bucket_list * \fBGetItems\fP (void)"
.br
.ti -1c
.RI "void \fBSetUserData\fP (void *data)"
.br
.ti -1c
.RI "void * \fBGetUserData\fP (void)"
.br
.ti -1c
.RI "void \fBSetXMLDoc\fP (struct xml_doc *\fBxmldoc\fP)"
.br
.ti -1c
.RI "struct xml_doc * \fBGetXMLDoc\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpanel_type\fP \fBtype\fP"
.br
.ti -1c
.RI "int \fBbuttons\fP [6]"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "void ** \fBrefobj\fP"
.br
.ti -1c
.RI "\fBDTSFrame\fP * \fBframe\fP"
.br
.ti -1c
.RI "wxString \fBstatus\fP"
.br
.ti -1c
.RI "\fBwxWindow\fP * \fBpanel\fP"
.br
.ti -1c
.RI "wxEvtHandler * \fBdtsevthandler\fP"
.br
.ti -1c
.RI "struct bucket_list * \fBfitems\fP"
.br
.ti -1c
.RI "void * \fBuserdata\fP"
.br
.ti -1c
.RI "struct xml_doc * \fBxmldoc\fP"
.br
.ti -1c
.RI "bool \fBbeenshown\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file DTSPanel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSObject::DTSObject (wxStringst = \fCwxEmptyString\fP)"

.PP
Definition at line 241 of file DTSPanel\&.cpp\&.
.PP
References beenshown, dtsevthandler, frame, panel, refobj, status, userdata, and xmldoc\&.
.SS "DTSObject::~DTSObject ()"

.PP
Definition at line 254 of file DTSPanel\&.cpp\&.
.PP
References dtsevthandler, refobj, userdata, and xmldoc\&.
.SH "Member Function Documentation"
.PP 
.SS "void DTSObject::EventHandler (inteid, wxCommandEvent *event)"

.PP
Definition at line 323 of file DTSPanel\&.cpp\&.
.PP
Referenced by DTSPanelEvent::OnButton()\&.
.SS "\fBDTSFrame\fP * DTSObject::GetFrame (void)"

.PP
Definition at line 286 of file DTSPanel\&.cpp\&.
.PP
References frame\&.
.PP
Referenced by DTSTreeWindow::CreatePane(), DTSTabWindow::CreateTab(), DTSTreeWindowEvent::MenuEvent(), and DTSPanelEvent::RunCallBack()\&.
.SS "struct bucket_list * DTSObject::GetItems (void)\fC [read]\fP"

.PP
Definition at line 316 of file DTSPanel\&.cpp\&.
.PP
References fitems\&.
.PP
Referenced by DTS_C_API::dtsgui_panel_items(), and DTSPanelEvent::OnCombo()\&.
.SS "wxString DTSObject::GetName ()"

.PP
Definition at line 272 of file DTSPanel\&.cpp\&.
.PP
References refobj, and status\&.
.PP
Referenced by DTSTabWindow::InsertTab(), and DTSFrame::NewMenuItem()\&.
.SS "\fBwxWindow\fP * DTSObject::GetPanel ()"

.PP
Definition at line 282 of file DTSPanel\&.cpp\&.
.PP
References panel\&.
.PP
Referenced by DTSTreeWindow::CreatePane(), DTSTabWindow::CreateTab(), DTSTreeWindow::DTSTreeWindow(), DTSTabWindow::InsertTab(), DTSFrame::NewMenuItem(), dynamic_panel::RunCallback(), DTSTreeWindow::SetWindow(), and DTSFrame::TextPanel()\&.
.SS "void * DTSObject::GetUserData (void)"

.PP
Definition at line 338 of file DTSPanel\&.cpp\&.
.PP
References refobj, and userdata\&.
.PP
Referenced by DTS_C_API::dtsgui_paneldata(), and DTSFrame::pwevent()\&.
.SS "struct xml_doc * DTSObject::GetXMLDoc (void)\fC [read]\fP"

.PP
Definition at line 305 of file DTSPanel\&.cpp\&.
.PP
References refobj, and xmldoc\&.
.PP
Referenced by DTS_C_API::dtsgui_panelxml(), and DTSPanel::GetNode()\&.
.SS "void DTSObject::SetUserData (void *data)"

.PP
Definition at line 326 of file DTSPanel\&.cpp\&.
.PP
References refobj, and userdata\&.
.PP
Referenced by DTSFrame::CreatePane(), and DTSTabWindow::CreateTab()\&.
.SS "void DTSObject::SetXMLDoc (struct xml_doc *xmldoc)"

.PP
Definition at line 290 of file DTSPanel\&.cpp\&.
.PP
References refobj, and xmldoc\&.
.PP
Referenced by dtsgui_wizard::AddPage(), DTSTreeWindow::CreatePane(), DTS_C_API::dtsgui_panel_setxml(), DTSTabPage::DTSTabPage(), and DTSTreeWindow::DTSTreeWindow()\&.
.SH "Member Data Documentation"
.PP 
.SS "bool DTSObject::beenshown\fC [protected]\fP"

.PP
Definition at line 80 of file DTSPanel\&.h\&.
.PP
Referenced by DTSObject(), DTSPanel::SetupWin(), DTSTreeWindow::Show(), DTSTabWindow::Show(), and DTSPanel::ShowPanel()\&.
.SS "int DTSObject::buttons[6]"

.PP
Definition at line 70 of file DTSPanel\&.h\&.
.PP
Referenced by DTSPanel::Buttons(), DTSDialog::DTSDialog(), DTSPanel::DTSPanel(), DTSPanelEvent::OnButton(), and DTSPanelEvent::OnDialog()\&.
.SS "wxEvtHandler* DTSObject::dtsevthandler\fC [protected]\fP"

.PP
Definition at line 76 of file DTSPanel\&.h\&.
.PP
Referenced by DTSPanel::Buttons(), DTSPanel::ComboBox(), DTSDialog::DTSDialog(), DTSObject(), DTSPanel::DTSPanel(), DTSScrollPanel::DTSScrollPanel(), DTSStaticPanel::DTSStaticPanel(), DTSTabWindow::DTSTabWindow(), DTSTreeWindow::DTSTreeWindow(), DTSTabPage::operator=(), DTSPanel::SetEventCallback(), DTSTabWindow::Show(), and ~DTSObject()\&.
.SS "struct bucket_list* DTSObject::fitems\fC [protected]\fP"

.PP
Definition at line 77 of file DTSPanel\&.h\&.
.PP
Referenced by DTSPanel::CheckBox(), DTSPanel::ComboBox(), DTSPanel::DTSPanel(), DTSPanel::FindItem(), GetItems(), DTSPanel::ListBox(), DTSPanel::Panel2Post(), DTSPanel::Panel2XML(), DTSPanel::TextBox(), DTSPanel::Update_XML(), and DTSPanel::~DTSPanel()\&.
.SS "\fBDTSFrame\fP* DTSObject::frame\fC [protected]\fP"

.PP
Definition at line 73 of file DTSPanel\&.h\&.
.PP
Referenced by DTSObject(), DTSPanel::DTSPanel(), DTSTabWindow::DTSTabWindow(), DTSTreeWindow::DTSTreeWindow(), GetFrame(), DTSTabPage::operator=(), DTSTreeWindow::Show(), DTSTabWindow::Show(), and DTSPanel::ShowPanel()\&.
.SS "\fBwxWindow\fP* DTSObject::panel\fC [protected]\fP"

.PP
Definition at line 75 of file DTSPanel\&.h\&.
.PP
Referenced by DTSPanel::Buttons(), DTSPanel::CheckBox(), DTSPanel::ComboBox(), DTSDialog::DTSDialog(), DTSObject(), DTSScrollPanel::DTSScrollPanel(), DTSStaticPanel::DTSStaticPanel(), DTSTabWindow::DTSTabWindow(), DTSTreeWindow::DTSTreeWindow(), DTSWindow::DTSWindow(), DTSWizardWindow::DTSWizardWindow(), GetPanel(), DTSTabWindow::InsertTab(), DTSPanel::ListBox(), DTSTabPage::operator=(), DTSDialog::RunDialog(), DTSPanel::SetupWin(), DTSWizardWindow::Show(), DTSPanel::ShowPanel(), DTSPanel::TextBox(), and DTSPanel::Title()\&.
.SS "void** DTSObject::refobj\fC [protected]\fP"

.PP
Definition at line 72 of file DTSPanel\&.h\&.
.PP
Referenced by DTSObject(), GetName(), GetUserData(), GetXMLDoc(), DTSTabWindow::InsertTab(), DTSTabPage::operator=(), DTSPanel::SetConfigCallback(), DTSPanel::SetStatus(), DTSPanel::SetupWin(), SetUserData(), SetXMLDoc(), ~DTSObject(), DTSPanel::~DTSPanel(), and DTSTabPage::~DTSTabPage()\&.
.SS "wxString DTSObject::status\fC [protected]\fP"

.PP
Definition at line 74 of file DTSPanel\&.h\&.
.PP
Referenced by DTSObject(), GetName(), DTSTabPage::operator=(), DTSPanel::SetStatus(), DTSPanel::SetupWin(), DTSTreeWindow::Show(), DTSTabWindow::Show(), and DTSPanel::ShowPanel()\&.
.SS "\fBpanel_type\fP DTSObject::type"

.PP
Definition at line 69 of file DTSPanel\&.h\&.
.PP
Referenced by DTSTreeWindow::CreatePane(), DTSDialog::DTSDialog(), DTSScrollPanel::DTSScrollPanel(), DTSStaticPanel::DTSStaticPanel(), DTSTabPage::DTSTabPage(), DTSTabWindow::DTSTabWindow(), DTSTreeWindow::DTSTreeWindow(), DTSWindow::DTSWindow(), DTSWizardWindow::DTSWizardWindow(), DTSPanelEvent::OnButton(), DTSPanel::SetupWin(), and DTSPanel::ShowPanel()\&.
.SS "void* DTSObject::userdata\fC [protected]\fP"

.PP
Definition at line 78 of file DTSPanel\&.h\&.
.PP
Referenced by DTSObject(), DTSTabWindow::DTSTabWindow(), DTSTreeWindow::DTSTreeWindow(), GetUserData(), DTSPanel::SetConfigCallback(), SetUserData(), ~DTSObject(), DTSTabWindow::~DTSTabWindow(), and DTSTreeWindow::~DTSTreeWindow()\&.
.SS "struct xml_doc* DTSObject::xmldoc\fC [protected]\fP"

.PP
Definition at line 79 of file DTSPanel\&.h\&.
.PP
Referenced by DTSTreeWindow::CreatePane(), DTSObject(), GetXMLDoc(), DTSTabPage::operator=(), DTSPanel::Panel2XML(), SetXMLDoc(), DTSPanel::Update_XML(), DTSTreeWindow::UpdateNodeXML(), and ~DTSObject()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
