.TH "src/include/DTSPanel.h" 3 "Thu Oct 10 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/DTSPanel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/event\&.h>\fP
.br
\fC#include <wx/window\&.h>\fP
.br
\fC#include <wx/gbsizer\&.h>\fP
.br
\fC#include <wx/textctrl\&.h>\fP
.br
\fC#include <wx/panel\&.h>\fP
.br
\fC#include <wx/scrolwin\&.h>\fP
.br
\fC#include <wx/wizard\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDTSPanelEvent\fP"
.br
.ti -1c
.RI "class \fBDTSObject\fP"
.br
.ti -1c
.RI "class \fBDTSPanel\fP"
.br
.ti -1c
.RI "class \fBDTSStaticPanel\fP"
.br
.ti -1c
.RI "class \fBDTSTextPanel\fP"
.br
.ti -1c
.RI "class \fBDTSScrollPanel\fP"
.br
.ti -1c
.RI "class \fBDTSTabPage\fP"
.br
.ti -1c
.RI "class \fBDTSWindow\fP"
.br
.ti -1c
.RI "class \fBDTSDialog\fP"
.br
.ti -1c
.RI "class \fBDTSWizardWindow\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fBDTSFrame\fP \fBDTSFrame\fP"
.br
.ti -1c
.RI "typedef class \fBDTSObject\fP \fBDTSObject\fP"
.br
.ti -1c
.RI "typedef class \fBwxStaticText\fP \fBwxStaticText\fP"
.br
.ti -1c
.RI "typedef class \fBwxBookCtrlBase\fP \fBwxBookCtrlBase\fP"
.br
.ti -1c
.RI "typedef class \fBwxDialog\fP \fBwxDialog\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef class \fBDTSFrame\fP \fBDTSFrame\fP"

.PP
Definition at line 30 of file DTSPanel\&.h\&.
.SS "typedef class \fBDTSObject\fP \fBDTSObject\fP"

.PP
Definition at line 31 of file DTSPanel\&.h\&.
.SS "typedef class \fBwxBookCtrlBase\fP \fBwxBookCtrlBase\fP"

.PP
Definition at line 33 of file DTSPanel\&.h\&.
.SS "typedef class \fBwxDialog\fP \fBwxDialog\fP"

.PP
Definition at line 34 of file DTSPanel\&.h\&.
.SS "typedef class \fBwxStaticText\fP \fBwxStaticText\fP"

.PP
Definition at line 32 of file DTSPanel\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
