.TH "src/DTSPanel.cpp" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/DTSPanel.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <wx/combobox\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include <wx/checkbox\&.h>\fP
.br
\fC#include <wx/button\&.h>\fP
.br
\fC#include <wx/notebook\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'DTSFrame\&.h'\fP
.br
\fC#include 'pitems\&.h'\fP
.br
\fC#include 'DTSPanel\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPADING\fP   10"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PADING   10"

.PP
Definition at line 33 of file DTSPanel\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
