.TH "src/DTSPanel.cpp" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/DTSPanel.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <wx/combobox\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include <wx/checkbox\&.h>\fP
.br
\fC#include <wx/button\&.h>\fP
.br
\fC#include <wx/notebook\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'DTSFrame\&.h'\fP
.br
\fC#include 'pitems\&.h'\fP
.br
\fC#include 'DTSPanel\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPADING\fP   10"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const int \fBdef_buttons\fP [6] = {wxID_FIRST, wxID_BACKWARD, wxID_FORWARD, wxID_LAST, wxID_APPLY, wxID_UNDO}"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PADING   10"

.PP
Definition at line 33 of file DTSPanel\&.cpp\&.
.PP
Referenced by DTSPanel::Buttons(), DTSPanel::CheckBox(), DTSPanel::ComboBox(), DTSPanel::ListBox(), DTSPanel::TextBox(), and DTSPanel::Title()\&.
.SH "Variable Documentation"
.PP 
.SS "const int def_buttons[6] = {wxID_FIRST, wxID_BACKWARD, wxID_FORWARD, wxID_LAST, wxID_APPLY, wxID_UNDO}\fC [static]\fP"

.PP
Definition at line 35 of file DTSPanel\&.cpp\&.
.PP
Referenced by DTSPanel::DTSPanel()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
