.TH "src/DTSPanel.cpp" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/DTSPanel.cpp \- 
.PP
Implementation of core panel classes and event handler\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <wx/combobox\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include <wx/checkbox\&.h>\fP
.br
\fC#include <wx/button\&.h>\fP
.br
\fC#include <wx/notebook\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'DTSFrame\&.h'\fP
.br
\fC#include 'pitems\&.h'\fP
.br
\fC#include 'DTSPanel\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPADING\fP   10"
.br
.RI "\fIBorder used when placing elements\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const int \fBdef_buttons\fP [6] = {wxID_FIRST, wxID_BACKWARD, wxID_FORWARD, wxID_LAST, wxID_APPLY, wxID_UNDO}"
.br
.RI "\fIArray mapping wxWidgets buttons to DTS Buttons\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of core panel classes and event handler\&. 


.PP
Definition in file \fBDTSPanel\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
