DTSPanelEvent
NAME
DTSPanelEvent -
SYNOPSIS
#include <DTSPanel.h>
Inherits wxEvtHandler.
Public Member Functions
DTSPanelEvent (DTSObject *win=NULL)
~DTSPanelEvent ()
void BindButton (wxWindow *win, int button)
void BindDTSEvent (DTSFrame *frame)
void BindCombo (wxWindow *win, int button)
void OnButton (wxCommandEvent &event)
void OnCombo (wxCommandEvent &event)
void OnDTSEvent (wxCommandEvent &event)
void SetCallback (event_callback evcb=NULL, void *userdata=NULL)
void OnDialog (wxCommandEvent &event)
Private Member Functions
int RunCallBack (int etype, int eid, void *cb_data)
Private Attributes
void ** refobj
void * data
event_callback evcb
DTSObject * parent
Detailed Description
Definition at line 36 of file DTSPanel.h.
Constructor & Destructor Documentation
DTSPanelEvent::DTSPanelEvent (DTSObject *win = NULL)
Definition at line 64 of file DTSPanel.cpp.
References data, evcb, parent, and refobj.
                                           {
    refobj = (void**)objalloc(sizeof(void*), NULL);
    *refobj = this;
    evcb = NULL;
    data = NULL;
    parent = win;
}
DTSPanelEvent::~DTSPanelEvent ()
Definition at line 72 of file DTSPanel.cpp.
References data, and refobj.
                              {
    objlock(refobj);
    if (data) {
        objunref(data);
        data = NULL;
    }
    objunlock(refobj);
    objunref(refobj);
}
Member Function Documentation
void DTSPanelEvent::BindButton (wxWindow *win, intbutton)
Definition at line 232 of file DTSPanel.cpp.
References OnButton().
Referenced by DTSPanel::Buttons().
                                                        {
    win->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &DTSPanelEvent::OnButton, this, button, button, NULL);
}
void DTSPanelEvent::BindCombo (wxWindow *win, intbutton)
Definition at line 236 of file DTSPanel.cpp.
References OnCombo().
Referenced by DTSPanel::ComboBox().
                                                     {
    win->Bind(wxEVT_COMMAND_TEXT_ENTER, &DTSPanelEvent::OnCombo, this, w_id, w_id, NULL);
    win->Bind(wxEVT_COMMAND_TEXT_UPDATED, &DTSPanelEvent::OnCombo, this, w_id, w_id, NULL);
}
void DTSPanelEvent::BindDTSEvent (DTSFrame *frame)
Definition at line 228 of file DTSPanel.cpp.
References OnDTSEvent().
Referenced by DTSPanel::DTSPanel(), and DTSTabPage::operator=().
                                                {
    frame->Bind(DTS_APP_EVENT, &DTSPanelEvent::OnDTSEvent, this);
}
void DTSPanelEvent::OnButton (wxCommandEvent &event)
Definition at line 123 of file DTSPanel.cpp.
References DTSObject::buttons, data, evcb, DTSObject::EventHandler(), parent, RunCallBack(), DTSObject::type, wx_DTSPANEL_DIALOG, and wx_PANEL_EVENT_BUTTON.
Referenced by BindButton(), and OnDialog().
                                                  {
    int eid, i;
    if (!parent) {
        event.Skip(true);
        return;
    }
    eid=event.GetId();
    /*convert wxbutton info to own id's and pass this on except for dialog*/
    for(i = 0; i < 6; i++) {
        if (parent->buttons[i] == eid) {
            eid = 1 << i;
            break;
        }
    }
    if (parent->type != wx_DTSPANEL_DIALOG) {
        event.SetId(eid);
    }
    /*maybe oneday there will be a default*/
    parent->EventHandler(eid, &event);
    if (evcb) {
        if (RunCallBack(wx_PANEL_EVENT_BUTTON, eid, data)) {
            event.Skip(true);
        }
    } else {
        event.Skip(true);
    }
}
void DTSPanelEvent::OnCombo (wxCommandEvent &event)
Definition at line 163 of file DTSPanel.cpp.
References dtsgui::cb, form_item::dtype, evcb, DTSObject::GetItems(), form_item::GetWidget(), parent, RunCallBack(), wx_PANEL_EVENT_COMBO_ENTER, and wx_PANEL_EVENT_COMBO_UPDATE.
Referenced by BindCombo().
                                                 {
    wxComboBox *cb;
    struct bucket_list *bl;
    struct bucket_loop *bloop;
    class form_item *fi;
    int eid, etype, dtype;
    if (!parent) {
        event.Skip(true);
        return;
    }
    bl = parent->GetItems();
    cb = (wxComboBox *)event.GetEventObject();
    etype = event.GetEventType();
    if (etype == wxEVT_COMMAND_TEXT_ENTER) {
        dtype = wx_PANEL_EVENT_COMBO_ENTER;
    } else if (etype == wxEVT_COMMAND_TEXT_UPDATED) {
        dtype = wx_PANEL_EVENT_COMBO_UPDATE;
    } else {
        dtype = 0;
    }
    bloop = init_bucket_loop(bl);
    while(bl && bloop && (fi = (class form_item *)next_bucket_loop(bloop))) {
        if (fi->GetWidget() == cb) {
            break;
        }
        objunref(fi);
        fi = NULL;
    }
    stop_bucket_loop(bloop);
    objunref(bl);
    if (fi) {
        eid=event.GetId();
        if (dtype && evcb) {
            if (RunCallBack(dtype, eid, fi)) {
                event.Skip(true);
            }
        }
        if (etype == wxEVT_COMMAND_TEXT_ENTER) {
            cb->Popup();
        }
        objunref(fi);
    } else {
        event.Skip(true);
    }
}
void DTSPanelEvent::OnDialog (wxCommandEvent &event)
Definition at line 156 of file DTSPanel.cpp.
References DTSObject::buttons, OnButton(), and parent.
Referenced by DTSDialog::DTSDialog(), DTSScrollPanel::DTSScrollPanel(), and DTSStaticPanel::DTSStaticPanel().
                                                  {
    /*translate enter into OK/Apply*/
    event.SetId(parent->buttons[4]);
    event.SetEventType(wxEVT_COMMAND_BUTTON_CLICKED);
    OnButton(event);
}
void DTSPanelEvent::OnDTSEvent (wxCommandEvent &event)
Definition at line 218 of file DTSPanel.cpp.
References data, evcb, RunCallBack(), and wx_PANEL_EVENT_DTS.
Referenced by BindDTSEvent().
                                                    {
    int eid;
    if (evcb) {
        eid=event.GetId();
        RunCallBack(wx_PANEL_EVENT_DTS, eid, data);
    }
    event.Skip(true);
}
int DTSPanelEvent::RunCallBack (intetype, inteid, void *cb_data) [private]
Definition at line 96 of file DTSPanel.cpp.
References evcb, DTSFrame::GetDTSData(), DTSObject::GetFrame(), and parent.
Referenced by OnButton(), OnCombo(), and OnDTSEvent().
                                                                {
    void *cbdata = NULL;
    DTSFrame *f;
    class dtsgui *dtsgui = NULL;
    int res;
    if (cb_data && objref(cb_data)) {
        cbdata = cb_data;
    }
    /*get app data*/
    if ((f = parent->GetFrame())) {
        dtsgui = f->GetDTSData();
    }
    /*pass fresh ref to callback*/
    res = evcb(dtsgui, (void *)parent, etype, eid, cbdata);
    if (dtsgui) {
        objunref(dtsgui);
    }
    if (cbdata) {
        objunref(cbdata);
    }
    return res;
}
void DTSPanelEvent::SetCallback (event_callbackevcb = NULL, void *userdata = NULL)
Definition at line 82 of file DTSPanel.cpp.
References data, evcb, and refobj.
Referenced by DTSPanel::SetEventCallback().
                                                                    {
    objlock(refobj);
    if (data) {
        objunref(data);
        data = NULL;
    }
    if (userdata && objref(userdata)) {
        data = userdata;
    }
    evcb = ev_cb;
    objunlock(refobj);
}
Member Data Documentation
void* DTSPanelEvent::data [private]
Definition at line 51 of file DTSPanel.h.
Referenced by DTSPanelEvent(), OnButton(), OnDTSEvent(), SetCallback(), and ~DTSPanelEvent().
event_callback DTSPanelEvent::evcb [private]
Definition at line 52 of file DTSPanel.h.
Referenced by DTSPanelEvent(), OnButton(), OnCombo(), OnDTSEvent(), RunCallBack(), and SetCallback().
DTSObject* DTSPanelEvent::parent [private]
Definition at line 53 of file DTSPanel.h.
Referenced by DTSPanelEvent(), OnButton(), OnCombo(), OnDialog(), and RunCallBack().
void** DTSPanelEvent::refobj [private]
Definition at line 49 of file DTSPanel.h.
Referenced by DTSPanelEvent(), SetCallback(), and ~DTSPanelEvent().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.