DTSPanel
NAME
DTSPanel -
SYNOPSIS
#include <DTSPanel.h>
Inherits DTSObject.
Inherited by DTSScrollPanel, DTSStaticPanel, DTSWindow, and DTSWizardWindow.
Public Member Functions
DTSPanel (DTSFrame *=NULL, wxString=wxEmptyString, int=0)
~DTSPanel ()
void TextBox (const char *, const char *, wxString=wxEmptyString, int flags=wxTE_LEFT, int rows=1, void *data=NULL, enum form_data_type dtype=DTSGUI_FORM_DATA_PTR)
void PasswdBox (const char *, const char *, wxString=wxEmptyString, int flags=wxTE_LEFT, void *data=NULL, enum form_data_type dtype=DTSGUI_FORM_DATA_PTR)
void CheckBox (const char *title, const char *name, int ischecked, const char *checkval, const char *uncheckval, void *data=NULL, enum form_data_type dtype=DTSGUI_FORM_DATA_PTR)
class form_item * ListBox (const char *title, const char *name, const char *value, void *data=NULL, enum form_data_type dtype=DTSGUI_FORM_DATA_PTR)
class form_item * ComboBox (const char *title, const char *name, const char *value, void *data=NULL, enum form_data_type dtype=DTSGUI_FORM_DATA_PTR)
void XMLTextBox (const char *, const char *, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr, int flags=wxTE_LEFT, int rows=1)
void XMLPasswdBox (const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr, int flags)
void XMLCheckBox (const char *title, const char *name, const char *checkval, const char *uncheckval, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
class form_item * XMLListBox (const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
class form_item * XMLComboBox (const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
void AddItem (wxWindow *item, const wxGBPosition pos, const wxGBSpan span=wxDefaultSpan, int flags=0, int border=0, int growrow=-1)
void SetEventCallback (event_callback evcb, void *userdata=NULL, bool useref=false)
void SetConfigCallback (dtsgui_configcb cb, void *userdata=NULL)
void Update_XML ()
struct xml_node * Panel2XML (const char *xpath, const char *node, const char *nodeval, const char *attrkey)
struct curl_post * Panel2Post ()
class xml_element * GetNode (const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
bool ShowPanel (bool=true)
void SetTitle (const wxString new_title, bool create=false)
void SetStatus (const wxString new_status)
class form_item * FindItem (const char *name)
const char * FindValue (const char *name)
Protected Member Functions
void Title (const char *title)
void SetSizerSize (wxSize, wxWindow *)
void SetupWin ()
void Buttons (void)
Protected Attributes
int button_mask
Static Private Member Functions
static int fitems_hash (const void *data, int key)
Private Attributes
wxStaticText * title
wxGridBagSizer * fgs
int g_row
dtsgui_configcb configcb
void * config_data
Additional Inherited Members
Detailed Description
Definition at line 83 of file DTSPanel.h.
Constructor & Destructor Documentation
DTSPanel::DTSPanel (DTSFrame *mainwin = NULL, wxStringstatusmsg = wxEmptyString, intbutmask = 0)
Definition at line 348 of file DTSPanel.cpp.
References DTSPanelEvent::BindDTSEvent(), button_mask, DTSObject::buttons, config_data, configcb, def_buttons, DTSObject::dtsevthandler, fgs, DTSObject::fitems, fitems_hash(), DTSObject::frame, and title.
    :DTSObject(statusmsg) {
    DTSPanelEvent *dtsevt;
    button_mask = butmask;
    config_data = NULL;
    configcb = NULL;
    dtsevthandler = NULL;
    title = NULL;
    fgs = NULL;
    frame = mainwin;
    memcpy(buttons, def_buttons, sizeof(def_buttons));;
    fitems = (struct bucket_list *)create_bucketlist(0, fitems_hash);
    dtsevt = new DTSPanelEvent(this);
    dtsevthandler = dtsevt;
    if (dtsevt && frame) {
        dtsevt->BindDTSEvent(frame);
    }
}
DTSPanel::~DTSPanel ()
Definition at line 369 of file DTSPanel.cpp.
References config_data, DTSObject::fitems, and DTSObject::refobj.
                    {
    objlock(refobj);
    if (fitems) {
        objunref(fitems);
        fitems = NULL;
    }
    if (config_data) {
        objunref(config_data);
        config_data = NULL;
    }
    objunlock(refobj);
}
Member Function Documentation
void DTSPanel::AddItem (wxWindow *item, const wxGBPositionpos, const wxGBSpanspan = wxDefaultSpan, intflags = 0, intborder = 0, intgrowrow = -1)
Definition at line 452 of file DTSPanel.cpp.
References fgs, and g_row.
Referenced by Buttons(), CheckBox(), ComboBox(), ListBox(), TextBox(), DTSFrame::TextPanel(), and Title().
                                                                                                                      {
    fgs->Add(item, pos, span, flags , border);
    if (growrow >= 0) {
        fgs->AddGrowableRow(g_row, growrow);
    }
}
void DTSPanel::Buttons (void) [protected]
Definition at line 724 of file DTSPanel.cpp.
References AddItem(), DTSPanelEvent::BindButton(), button_mask, DTSObject::buttons, DTSObject::dtsevthandler, fgs, g_row, PADING, and DTSObject::panel.
Referenced by ShowPanel().
                           {
    DTSPanelEvent *dtsevt = (DTSPanelEvent*)dtsevthandler;
    int i, b;
    if (!button_mask || !dtsevthandler) {
        return;
    }
    for(i = 0; i < 6; i++) {
        b = buttons[i];
        if (button_mask & (1 << i)) {
            wxButton *button = new wxButton(panel, b);
            dtsevt->BindButton(panel, b);
            AddItem(button, wxGBPosition(g_row, i), wxDefaultSpan, wxALIGN_BOTTOM | wxALL, PADING);
        }
    }
    fgs->AddGrowableRow(g_row, 0);
    g_row++;
}
void DTSPanel::CheckBox (const char *title, const char *name, intischecked, const char *checkval, const char *uncheckval, void *data = NULL, enum form_data_typedtype = DTSGUI_FORM_DATA_PTR)
Definition at line 608 of file DTSPanel.cpp.
References AddItem(), DTS_WIDGET_CHECKBOX, DTSGUI_FORM_DATA_XML, DTSObject::fitems, g_row, PADING, and DTSObject::panel.
Referenced by DTS_C_API::dtsgui_checkbox(), and XMLCheckBox().
                                                                                                                                                               {
    wxStaticText *text = new wxStaticText(panel, -1, title);
    wxCheckBox *cbox = new wxCheckBox(panel, -1, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxALIGN_RIGHT);
    class form_item *fi;
    AddItem(text, wxGBPosition(g_row, 0), wxGBSpan(1, 3), wxLEFT | wxRIGHT, PADING);
    AddItem(cbox, wxGBPosition(g_row, 3), wxGBSpan(1, 3), wxLEFT | wxRIGHT, PADING);
    g_row++;
    if ((dtype == DTSGUI_FORM_DATA_XML) && !data) {
        cbox->Disable();
    }
    cbox->SetValue((ischecked) ? true : false);
    fi = new form_item(cbox, DTS_WIDGET_CHECKBOX, name, checkval, uncheckval, data, dtype);
    addtobucket(fitems, fi);
    objunref(fi);
}
class form_item * DTSPanel::ComboBox (const char *title, const char *name, const char *value, void *data = NULL, enum form_data_typedtype = DTSGUI_FORM_DATA_PTR)
Definition at line 684 of file DTSPanel.cpp.
References AddItem(), DTSPanelEvent::BindCombo(), form_item::data, DTS_WIDGET_COMBOBOX, DTSObject::dtsevthandler, DTSGUI_FORM_DATA_XML, DTSObject::fitems, g_row, PADING, and DTSObject::panel.
Referenced by DTS_C_API::dtsgui_combobox(), and XMLComboBox().
                                                                                                                                 {
    class form_item *fi;
    DTSPanelEvent *dtsevt = (DTSPanelEvent*)dtsevthandler;
    wxStaticText *text = new wxStaticText(panel, -1, title);
    wxChoice *lbox = new wxComboBox(panel, -1, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0, NULL, wxTE_PROCESS_ENTER);
    AddItem(text, wxGBPosition(g_row, 0), wxGBSpan(1, 3), wxLEFT | wxRIGHT, PADING);
    AddItem(lbox, wxGBPosition(g_row, 3), wxGBSpan(1, 3), wxEXPAND | wxGROW | wxLEFT | wxRIGHT, PADING);
    g_row++;
    if (dtsevthandler) {
        dtsevt->BindCombo(panel, lbox->GetId());
    }
    if ((dtype == DTSGUI_FORM_DATA_XML) && !data) {
        lbox->Disable();
    }
    fi = new form_item(lbox, DTS_WIDGET_COMBOBOX, name, value, NULL, data, dtype);
    addtobucket(fitems, fi);
    return fi;
}
class form_item * DTSPanel::FindItem (const char *name)
Definition at line 882 of file DTSPanel.cpp.
References DTSObject::fitems.
Referenced by DTS_C_API::dtsgui_finditem(), and FindValue().
                                                    {
    return (class form_item*)bucket_list_find_key(fitems, (void*)name);
}
const char * DTSPanel::FindValue (const char *name)
Definition at line 886 of file DTSPanel.cpp.
References FindItem(), and form_item::GetValue().
Referenced by DTS_C_API::dtsgui_findvalue(), and DTSFrame::pwevent().
                                                {
    class form_item *fi;
    const char *val;
    if (!(fi = FindItem(name))) {
        return NULL;
    }
    val = fi->GetValue();
    objunref(fi);
    return val;
}
int DTSPanel::fitems_hash (const void *data, intkey) [static], [private]
Definition at line 49 of file DTSPanel.cpp.
References form_item::GetName().
Referenced by DTSPanel().
                                                   {
    int ret = 0;
    class form_item *fi = (class form_item *)data;
    const char *hashkey = (key) ? (const char *)data : fi->GetName();
    if (hashkey) {
        ret = jenhash(hashkey, strlen(hashkey), 0);
    } else {
        ret = jenhash(fi, sizeof(*fi), 0);
    }
    return(ret);
}
struct xml_element * DTSPanel::GetNode (const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr) [read]
Definition at line 496 of file DTSPanel.cpp.
References DTSObject::GetXMLDoc().
Referenced by XMLCheckBox(), XMLComboBox(), XMLListBox(), and XMLTextBox().
                                                                                                                                {
    class xml_element *xml = NULL;
    struct xml_doc *xd;
    struct xml_node *xn;
    const char *xpath;
    struct xml_search *xs;
    int len;
    if (!ppath || !(xd = GetXMLDoc())) {
        return NULL;
    }
    if (node) {
        len = strlen(ppath) + strlen(node) + 2;
        if (fval) {
            if (fattr) {
                len+= strlen(fattr) + strlen(fval)+8;
                xpath = (const char*)malloc(len);
                snprintf((char*)xpath, len, '%s/%s[@%s = '%s']', ppath, node, fattr, fval);
            } else {
                len+= strlen(fval)+8;
                xpath = (const char*)malloc(len);
                snprintf((char*)xpath, len, '%s/%s[. = '%s']', ppath, node, fval);
            }
        } else {
            xpath = (const char*)malloc(len);
            snprintf((char*)xpath, len, '%s/%s', ppath, node);
        }
    } else {
        len = strlen(ppath) + 1;
        if (fval) {
            if (fattr) {
                len+= strlen(fattr) + strlen(fval)+8;
                xpath = (const char*)malloc(len);
                snprintf((char*)xpath, len, '%s[@%s = '%s']', ppath, fattr, fval);
            } else {
                len+= strlen(fval)+8;
                xpath = (const char*)malloc(len);
                snprintf((char*)xpath, len, '%s[. = '%s']', ppath, fval);
            }
        } else {
            ALLOC_CONST(xpath, ppath);
        }
    }
    if (!(xs = xml_xpath(xd, xpath, attr))) {
        if (ppath && node) {
            const char *tval = (fval) ? fval : '';
            xml_createpath(xd, ppath);
            if ((xn = xml_addnode(xd, ppath, node, (fattr) ? '' : tval, fattr, (fattr) ? tval : NULL))) {
                xs = xml_xpath(xd, xpath, attr);
                objunref(xn);
            }
        }
    }
    if (!xs) {
        free((void*)xpath);
        return NULL;
    }
    if (!(xml = new xml_element(xpath, xs, attr))) {
        free((void*)xpath);
        objunref(xs);
    }
    objunref(xd);
    return xml;
}
class form_item * DTSPanel::ListBox (const char *title, const char *name, const char *value, void *data = NULL, enum form_data_typedtype = DTSGUI_FORM_DATA_PTR)
Definition at line 648 of file DTSPanel.cpp.
References AddItem(), DTS_WIDGET_LISTBOX, DTSGUI_FORM_DATA_XML, DTSObject::fitems, g_row, PADING, and DTSObject::panel.
Referenced by DTS_C_API::dtsgui_listbox(), and XMLListBox().
                                                                                                                                {
    class form_item *fi;
    wxStaticText *text = new wxStaticText(panel, -1, title);
    wxChoice *lbox = new wxComboBox(panel, -1, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0, NULL, wxCB_READONLY);
    AddItem(text, wxGBPosition(g_row, 0), wxGBSpan(1, 3), wxLEFT | wxRIGHT, PADING);
    AddItem(lbox, wxGBPosition(g_row, 3), wxGBSpan(1, 3), wxEXPAND | wxGROW | wxLEFT | wxRIGHT, PADING);
    g_row++;
    if ((dtype == DTSGUI_FORM_DATA_XML) && !data) {
        lbox->Disable();
    }
    fi = new form_item(lbox, DTS_WIDGET_LISTBOX, name, value, NULL, data, dtype);
    addtobucket(fitems, fi);
    return fi;
}
struct curl_post * DTSPanel::Panel2Post () [read]
Definition at line 841 of file DTSPanel.cpp.
References DTSObject::fitems, form_item::GetName(), form_item::GetValue(), and form_item::name.
Referenced by DTS_C_API::dtsgui_pane2post().
                                       {
    struct bucket_loop *bloop;
    struct curl_post *post;
    struct form_item *fi;
    const char *name;
    const char *val;
    if (!objref(fitems)) {
        return NULL;
    }
    if (!(bloop = init_bucket_loop(fitems))) {
        objunlock(fitems);
        return NULL;
    }
    if (!(post = curl_newpost())) {
        stop_bucket_loop(bloop);
        objunlock(fitems);
        return NULL;
    }
    while((fi = (struct form_item*)next_bucket_loop(bloop))) {
        if (!(name = fi->GetName())) {
            objunref(fi);
            continue;
        }
        val = fi->GetValue();
        if (val) {
            curl_postitem(post, name, val);
            free((void*)val);
        } else {
            curl_postitem(post, name, '');
        }
        objunref(fi);
    }
    stop_bucket_loop(bloop);
    objunref(fitems);
    return post;
}
struct xml_node * DTSPanel::Panel2XML (const char *xpath, const char *node, const char *nodeval, const char *attrkey) [read]
Definition at line 777 of file DTSPanel.cpp.
References DTSObject::fitems, form_item::GetName(), form_item::GetValue(), and DTSObject::xmldoc.
Referenced by DTS_C_API::dtsgui_panetoxml(), tab_newpane::handle_newtabpane(), and tree_newnode::handle_newtreenode().
                                                                                                                  {
    struct xml_node *xn;
    const char *val = NULL, *name, *aval = NULL;
    class form_item *fi;
    struct bucket_loop *bl;
    if (!xmldoc || !objref(xmldoc)) {
        return NULL;
    }
    objref(fitems);
    if (nodeval && (fi = (class form_item*)bucket_list_find_key(fitems, (void*)nodeval))) {
        val = fi->GetValue();
        objunref(fi);
        fi = NULL;
    }
    if (attrkey && (fi = (class form_item*)bucket_list_find_key(fitems, (void*)attrkey))) {
        aval = fi->GetValue();
        objunref(fi);
        fi = NULL;
    }
    xml_createpath(xmldoc, xpath);
    xn = xml_addnode(xmldoc, xpath, node, (val) ? val : '', attrkey, aval);
    if (val) {
        free((void*)val);
    }
    if (aval) {
        free((void*)aval);
    }
    if (!xn) {
        objunref(xmldoc);
        objunref(fitems);
        return NULL;
    }
    bl = init_bucket_loop(fitems);
    while(fitems && bl && (fi = (class form_item *)next_bucket_loop(bl))) {
        if (!(name = fi->GetName())) {
            objunref(fi);
            continue;
        }
        if (!(val = fi->GetValue())) {
            objunref(fi);
            continue;
        }
        if ((!nodeval || strcmp(name, nodeval)) && (!attrkey || strcmp(name, attrkey))) {
            xml_setattr(xmldoc, xn, name, val);
        }
        free((void*)val);
        objunref(fi);
    }
    stop_bucket_loop(bl);
    objunref(fitems);
    objunref(xmldoc);
    return xn;
}
void DTSPanel::PasswdBox (const char *title, const char *name, wxStringdefval = wxEmptyString, intflags = wxTE_LEFT, void *data = NULL, enum form_data_typedtype = DTSGUI_FORM_DATA_PTR)
Definition at line 600 of file DTSPanel.cpp.
References TextBox().
                                                                                                                         {
    TextBox(title, name, defval, flags | wxTE_PASSWORD | wxTE_PROCESS_ENTER, 1, data);
}
void DTSPanel::SetConfigCallback (dtsgui_configcbcb, void *userdata = NULL)
Definition at line 417 of file DTSPanel.cpp.
References config_data, configcb, DTSObject::refobj, and DTSObject::userdata.
Referenced by DTS_C_API::dtsgui_configcallback().
                                                                   {
    objlock(refobj);
    if (config_data) {
        objunref(config_data);
        config_data = NULL;
    }
    configcb = cb;
    if (userdata && objref(userdata)) {
        config_data = userdata;
    }
    objunlock(refobj);
}
void DTSPanel::SetEventCallback (event_callbackevcb, void *userdata = NULL, booluseref = false)
Definition at line 406 of file DTSPanel.cpp.
References DTSObject::dtsevthandler, and DTSPanelEvent::SetCallback().
Referenced by DTS_C_API::dtsgui_setevcallback(), and DTSDialog::RunDialog().
                                                                                {
    DTSPanelEvent *dtsevt = (DTSPanelEvent*)dtsevthandler;
    if (dtsevthandler) {
        dtsevt->SetCallback(evcb, userdata);
    }
    if (useref && userdata) {
        objunref(userdata);
    }
}
void DTSPanel::SetSizerSize (wxSizeminsize, wxWindow *parent) [protected]
Definition at line 382 of file DTSPanel.cpp.
References fgs.
Referenced by DTSWizardWindow::Show().
                                                            {
    if (parent) {
        fgs->FitInside(parent);
    }
    fgs->Layout();
}
void DTSPanel::SetStatus (const wxStringnew_status)
Definition at line 490 of file DTSPanel.cpp.
References DTSObject::refobj, and DTSObject::status.
Referenced by DTS_C_API::dtsgui_setstatus().
                                                  {
    objlock(refobj);
    status = new_status;
    objunlock(refobj);
}
void DTSPanel::SetTitle (const wxStringnew_title, boolcreate = false)
Definition at line 482 of file DTSPanel.cpp.
References Title(), and title.
Referenced by dtsgui_wizard::AddPage(), DTSFrame::CreatePane(), DTSTreeWindow::CreatePane(), DTS_C_API::dtsgui_settitle(), DTSTabPage::DTSTabPage(), DTSTabPage::operator=(), and DTSTreeWindow::SetPaneTitle().
                                                             {
    if (title) {
        title->SetLabel(new_title);
    } else if (create) {
        Title(new_title);
    }
}
void DTSPanel::SetupWin (void) [protected]
Definition at line 390 of file DTSPanel.cpp.
References DTSObject::beenshown, fgs, g_row, DTSObject::panel, DTSObject::refobj, DTSObject::status, DTSObject::type, and wx_DTSPANEL_TREE.
Referenced by DTSDialog::DTSDialog(), DTSScrollPanel::DTSScrollPanel(), DTSStaticPanel::DTSStaticPanel(), DTSWindow::DTSWindow(), and DTSWizardWindow::DTSWizardWindow().
                            {
    wxWindow *w = static_cast<wxWindow *>(this);
    if (panel && (type != wx_DTSPANEL_TREE)) {
        fgs = new wxGridBagSizer(9, 25);
        panel->SetSizer(fgs);
    }
    beenshown = false;
    g_row = 0;
    objlock(refobj);
    w->SetName(status);
    objunlock(refobj);
    w->Show(false);
}
bool DTSPanel::ShowPanel (boolshow = true)
Definition at line 432 of file DTSPanel.cpp.
References DTSObject::beenshown, Buttons(), fgs, DTSObject::frame, DTSObject::panel, DTSObject::status, DTSObject::type, wx_DTSPANEL_TAB, and wx_DTSPANEL_TREE.
Referenced by DTSTabPage::ConfigPane(), DTSStaticPanel::Show(), DTSScrollPanel::Show(), DTSWindow::Show(), DTSDialog::Show(), and DTSWizardWindow::Show().
                                  {
    if (show) {
        if (frame && (type != wx_DTSPANEL_TAB) && (type != wx_DTSPANEL_TREE)) {
            frame->SetStatusText(status);
        }
        if (!beenshown && panel && fgs) {
            Buttons();
            if (fgs->GetCols() >= 3) {
                fgs->AddGrowableCol(3, 1);
                fgs->AddGrowableCol(1, 1);
            }
            beenshown = true;
        }
    }
    return show;
}
void DTSPanel::TextBox (const char *title, const char *name, wxStringdefval = wxEmptyString, intflags = wxTE_LEFT, introws = 1, void *data = NULL, enum form_data_typedtype = DTSGUI_FORM_DATA_PTR)
Definition at line 567 of file DTSPanel.cpp.
References AddItem(), DTS_WIDGET_TEXTBOX, DTSGUI_FORM_DATA_XML, DTSObject::fitems, g_row, PADING, and DTSObject::panel.
Referenced by DTS_C_API::dtsgui_passwdbox(), DTS_C_API::dtsgui_textbox(), DTS_C_API::dtsgui_textbox_multi(), DTSFrame::Passwd(), PasswdBox(), and XMLTextBox().
                                                                                                                                      {
    wxStaticText *text = new wxStaticText(panel, -1, title);
    wxTextCtrl *tbox = new wxTextCtrl(panel, -1, defval, wxPoint(-1, -1), wxSize(-1, -1), flags);
    class form_item *fi;
    AddItem(text, wxGBPosition(g_row, 0), wxGBSpan(rows, 3), wxLEFT | wxRIGHT, PADING);
    AddItem(tbox, wxGBPosition(g_row, 3), wxGBSpan(rows,3), wxEXPAND | wxGROW | wxLEFT | wxRIGHT, PADING, (rows > 1) ? 1 : -1);
    g_row += rows;
    if ((dtype == DTSGUI_FORM_DATA_XML) && !data) {
        tbox->Disable();
    }
    fi = new form_item(tbox, DTS_WIDGET_TEXTBOX, name, NULL, NULL, data, dtype);
    addtobucket(fitems, fi);
    objunref(fi);
}
void DTSPanel::Title (const char *title) [protected]
Definition at line 460 of file DTSPanel.cpp.
References AddItem(), g_row, PADING, and DTSObject::panel.
Referenced by SetTitle().
                                      {
    wxFont font;
    wxStaticText *tit;
    if (this->title) {
        return;
    }
    tit = new wxStaticText(panel, -1, title);
    this->title = tit;
    font = tit->GetFont();
    font.SetPointSize(font.GetPointSize()+2);
    font.SetWeight(wxFONTWEIGHT_BOLD);
    tit->SetFont(font);
    AddItem(tit, wxGBPosition(g_row, 0), wxGBSpan(1, 6), wxALIGN_CENTER_HORIZONTAL | wxLEFT | wxRIGHT, PADING);
    g_row++;
}
void DTSPanel::Update_XML ()
Definition at line 746 of file DTSPanel.cpp.
References DTSObject::fitems, form_item::GetValue(), form_item::GetXMLData(), xml_element::Modify(), and DTSObject::xmldoc.
Referenced by DTS_C_API::dtsgui_xmlpanel_update(), DTSTreeWindowEvent::OnButton(), and DTSTabWindowEvent::OnButton().
                          {
    struct bucket_loop *bloop;
    class form_item *fi;
    class xml_element *xml;
    const char *value;
    if (!xmldoc) {
        return;
    }
    objref(fitems);
    bloop = init_bucket_loop(fitems);
    while (bloop && (fi = (class form_item*)next_bucket_loop(bloop))) {
        if (!(xml = fi->GetXMLData())) {
            objunref(fi);
            continue;
        }
        value = fi->GetValue();
        xml->Modify(xmldoc, value);
        objunref(xml);
        if (value) {
            free((void*)value);
        }
        objunref(fi);
    }
    stop_bucket_loop(bloop);
    objunref(fitems);
}
void DTSPanel::XMLCheckBox (const char *title, const char *name, const char *checkval, const char *uncheckval, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Definition at line 628 of file DTSPanel.cpp.
References CheckBox(), DTSGUI_FORM_DATA_XML, GetNode(), and xml_element::GetValue().
Referenced by DTS_C_API::dtsgui_xmlcheckbox().
                                                                                                                                                                                                        {
    struct xml_element *xml;
    int ischecked = 0;
    const char *value = NULL;
    if ((xml = GetNode(xpath, node, fattr, fval, attr))) {
        value = xml->GetValue();
    }
    if (value && checkval && !strcmp(value, checkval)) {
        ischecked = 1;
    }
    CheckBox(title, name, ischecked, checkval, uncheckval, xml, DTSGUI_FORM_DATA_XML);
    if (value) {
        free((void*)value);
    }
}
class form_item * DTSPanel::XMLComboBox (const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Definition at line 707 of file DTSPanel.cpp.
References ComboBox(), DTSGUI_FORM_DATA_XML, GetNode(), xml_element::GetValue(), and form_item::value.
Referenced by DTS_C_API::dtsgui_xmlcombobox().
                                                                                                                                                                      {
    const char *value = NULL;
    class xml_element *xml;
    struct form_item *fi;
    if ((xml = GetNode(xpath, node, fattr, fval, attr))) {
        value = xml->GetValue();
    }
    fi = ComboBox(title, name, value, xml, DTSGUI_FORM_DATA_XML);
    if (value) {
        free((void*)value);
    }
    return fi;
}
class form_item * DTSPanel::XMLListBox (const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr)
Definition at line 667 of file DTSPanel.cpp.
References DTSGUI_FORM_DATA_XML, GetNode(), xml_element::GetValue(), ListBox(), and form_item::value.
Referenced by DTS_C_API::dtsgui_xmllistbox().
                                                                                                                                                                     {
    const char *value = NULL;
    class xml_element *xml;
    struct form_item *fi;
    if ((xml = GetNode(xpath, node, fattr, fval, attr))) {
        value = xml->GetValue();
    }
    fi = ListBox(title, name, value, xml, DTSGUI_FORM_DATA_XML);
    if (value) {
        free((void*)value);
    }
    return fi;
}
void DTSPanel::XMLPasswdBox (const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr, intflags)
Definition at line 604 of file DTSPanel.cpp.
References XMLTextBox().
Referenced by DTS_C_API::dtsgui_xmlpasswdbox().
                                                                                                                                                                      {
    XMLTextBox(title, name, xpath, node, fattr, fval, attr, flags | wxTE_PASSWORD | wxTE_PROCESS_ENTER, 1);
}
void DTSPanel::XMLTextBox (const char *title, const char *name, const char *xpath, const char *node, const char *fattr, const char *fval, const char *attr, intflags = wxTE_LEFT, introws = 1)
Definition at line 585 of file DTSPanel.cpp.
References DTSGUI_FORM_DATA_XML, GetNode(), xml_element::GetValue(), and TextBox().
Referenced by DTS_C_API::dtsgui_xmltextbox(), DTS_C_API::dtsgui_xmltextbox_multi(), and XMLPasswdBox().
                                                                                                                                                                              {
    struct xml_element *xml;
    const char *value = NULL;
    if ((xml = GetNode(xpath, node, fattr, fval,attr))) {
        value = xml->GetValue();
    }
    TextBox(title, name, value, flags, rows, xml, DTSGUI_FORM_DATA_XML);
    if (value) {
        free((void*)value);
    }
}
Member Data Documentation
int DTSPanel::button_mask [protected]
Definition at line 114 of file DTSPanel.h.
Referenced by Buttons(), DTSDialog::DTSDialog(), DTSPanel(), DTSWizardWindow::DTSWizardWindow(), and DTSTabPage::operator=().
void* DTSPanel::config_data [private]
Definition at line 121 of file DTSPanel.h.
Referenced by DTSPanel(), SetConfigCallback(), and ~DTSPanel().
dtsgui_configcb DTSPanel::configcb [private]
Definition at line 120 of file DTSPanel.h.
Referenced by DTSPanel(), and SetConfigCallback().
wxGridBagSizer* DTSPanel::fgs [private]
Definition at line 118 of file DTSPanel.h.
Referenced by AddItem(), Buttons(), DTSPanel(), SetSizerSize(), SetupWin(), and ShowPanel().
int DTSPanel::g_row [private]
Definition at line 119 of file DTSPanel.h.
Referenced by AddItem(), Buttons(), CheckBox(), ComboBox(), ListBox(), SetupWin(), TextBox(), and Title().
wxStaticText* DTSPanel::title [private]
Definition at line 117 of file DTSPanel.h.
Referenced by DTSPanel(), and SetTitle().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.