DTSStaticPanel
NAME
DTSStaticPanel -
SYNOPSIS
#include <DTSPanel.h>
Inherits DTSPanel, and wxPanel.
Inherited by DTSDialog, and DTSTextPanel.
Public Member Functions
DTSStaticPanel (wxWindow *, DTSFrame *=NULL, wxString=wxEmptyString, int=0)
DTSStaticPanel ()
virtual bool Show (bool=true)
Additional Inherited Members
Detailed Description
Definition at line 124 of file DTSPanel.h.
Constructor & Destructor Documentation
DTSStaticPanel::DTSStaticPanel (wxWindow *parent, DTSFrame *frame = NULL, wxStringstatus = wxEmptyString, intbutmask = 0)
Definition at line 1012 of file DTSPanel.cpp.
References DTSObject::dtsevthandler, DTSPanelEvent::OnDialog(), DTSObject::panel, DTSPanel::SetupWin(), DTSObject::type, and wx_DTSPANEL_PANEL.
    :wxPanel(parent, wxID_ANY),
     DTSPanel(frame, status, butmask) {
    DTSPanelEvent *dtsevt = (DTSPanelEvent*)dtsevthandler;
    type = wx_DTSPANEL_PANEL;
    panel = dynamic_cast<wxPanel *>(this);
    panel->Bind(wxEVT_TEXT_ENTER, &DTSPanelEvent::OnDialog, dtsevt);
    SetupWin();
}
DTSStaticPanel::DTSStaticPanel ()
Definition at line 1022 of file DTSPanel.cpp.
References DTSObject::type, and wx_DTSPANEL_PANEL.
                               {
    type = wx_DTSPANEL_PANEL;
}
Member Function Documentation
bool DTSStaticPanel::Show (boolshow = true) [virtual]
Reimplemented in DTSDialog.
Definition at line 1026 of file DTSPanel.cpp.
References DTSPanel::ShowPanel().
                                   {
    ShowPanel(show);
    return wxPanel::Show(show);
}
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.