.TH "DTSScrollPanel" 3 "Thu Oct 10 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSScrollPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSPanel\&.h>\fP
.PP
Inherits \fBDTSPanel\fP, and wxScrolledWindow\&.
.PP
Inherited by \fBDTSTabPage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSScrollPanel\fP (\fBwxWindow\fP *, \fBDTSFrame\fP *=NULL, wxString=wxEmptyString, int=0)"
.br
.ti -1c
.RI "virtual bool \fBShow\fP (bool)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 136 of file DTSPanel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSScrollPanel::DTSScrollPanel (\fBwxWindow\fP *parent, \fBDTSFrame\fP *frame = \fCNULL\fP, wxStringstatus = \fCwxEmptyString\fP, intbutmask = \fC0\fP)"

.PP
Definition at line 886 of file DTSPanel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool DTSScrollPanel::Show (boolshow)\fC [virtual]\fP"

.PP
Reimplemented in \fBDTSTabPage\fP\&.
.PP
Definition at line 898 of file DTSPanel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
