.TH "DTSStaticPanel" 3 "Thu Oct 10 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSStaticPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSPanel\&.h>\fP
.PP
Inherits \fBDTSPanel\fP, and wxPanel\&.
.PP
Inherited by \fBDTSDialog\fP, and \fBDTSTextPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSStaticPanel\fP (\fBwxWindow\fP *, \fBDTSFrame\fP *=NULL, wxString=wxEmptyString, int=0)"
.br
.ti -1c
.RI "\fBDTSStaticPanel\fP ()"
.br
.ti -1c
.RI "virtual bool \fBShow\fP (bool=true)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 124 of file DTSPanel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSStaticPanel::DTSStaticPanel (\fBwxWindow\fP *parent, \fBDTSFrame\fP *frame = \fCNULL\fP, wxStringstatus = \fCwxEmptyString\fP, intbutmask = \fC0\fP)"

.PP
Definition at line 999 of file DTSPanel\&.cpp\&.
.SS "DTSStaticPanel::DTSStaticPanel ()"

.PP
Definition at line 1009 of file DTSPanel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool DTSStaticPanel::Show (boolshow = \fCtrue\fP)\fC [virtual]\fP"

.PP
Reimplemented in \fBDTSDialog\fP\&.
.PP
Definition at line 1013 of file DTSPanel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
