DTSTabPage
NAME
DTSTabPage -
SYNOPSIS
#include <DTSPanel.h>
Inherits DTSScrollPanel.
Public Member Functions
DTSTabPage (wxBookCtrlBase *, DTSFrame *=NULL, wxString=wxEmptyString, int=0, dtsgui_tabpanel_cb=NULL, void *=NULL, struct xml_doc *=NULL)
~DTSTabPage ()
void ConfigPane ()
virtual bool Show (bool)
DTSTabPage & operator= (const DTSTabPage &orig)
Private Attributes
dtsgui_tabpanel_cb cb
void * cdata
bool hasconfig
Additional Inherited Members
Detailed Description
Definition at line 142 of file DTSPanel.h.
Constructor & Destructor Documentation
DTSTabPage::DTSTabPage (wxBookCtrlBase *parent, DTSFrame *frame = NULL, wxStringstatus = wxEmptyString, intbutmask = 0, dtsgui_tabpanel_cbc_cb = NULL, void *c_data = NULL, struct xml_doc *xmldoc = NULL)
Definition at line 916 of file DTSPanel.cpp.
References cb, cdata, hasconfig, DTSPanel::SetTitle(), DTSObject::SetXMLDoc(), DTSObject::type, and wx_DTSPANEL_TAB.
    :wxScrolledWindow(parent, wxID_ANY),
    DTSScrollPanel(parent,frame, status, butmask) {
    type = wx_DTSPANEL_TAB;
    cb = c_cb;
    if (c_data && objref(c_data)) {
        cdata = c_data;
    } else {
        cdata = NULL;
    }
    if (xmldoc) {
        SetXMLDoc(xmldoc);
    }
    hasconfig = false;
    SetTitle(status, 1);
}
DTSTabPage::~DTSTabPage ()
Definition at line 933 of file DTSPanel.cpp.
References cdata, and DTSObject::refobj.
                        {
    objlock(refobj);
    if (cdata) {
        objunref(cdata);
    }
    objunlock(refobj);
}
Member Function Documentation
void DTSTabPage::ConfigPane ()
Definition at line 945 of file DTSPanel.cpp.
References cb, cdata, hasconfig, and DTSPanel::ShowPanel().
Referenced by DTSTabWindowEvent::PageChange(), and DTSTabWindow::Show().
                            {
    if (!hasconfig) {
        if (cb) {
            void *dat = NULL;
            if (cdata && objref(cdata)) {
                dat = cdata;
            }
            cb(this, dat);
            if (dat) {
                objunref(dat);
            }
        }
        hasconfig = true;
        ShowPanel();
    }
}
DTSTabPage & DTSTabPage::operator= (const DTSTabPage &orig)
Definition at line 962 of file DTSPanel.cpp.
References DTSPanelEvent::BindDTSEvent(), DTSPanel::button_mask, cb, cdata, DTSObject::dtsevthandler, DTSObject::frame, DTSObject::panel, DTSObject::refobj, DTSPanel::SetTitle(), DTSObject::status, and DTSObject::xmldoc.
                                                        {
    DTSPanelEvent *dtsevt = (DTSPanelEvent*)dtsevthandler;
    if (this == &orig) {
        return *this;
    }
    /*deadlock avoidance*/
    objlock(orig.refobj);
    while(!objtrylock(this->refobj)) {
        objunlock(orig.refobj);
#ifdef __WIN32
        Sleep(1);
#else
        usleep(1000);
#endif
        objlock(orig.refobj);
    }
    button_mask = orig.button_mask;
    if (cdata) {
        objunref(cdata);
        cdata = NULL;
    }
    if (orig.cdata && objref(orig.cdata)) {
        cdata = orig.cdata;
    }
    cb = orig.cb;
    if (xmldoc) {
        objunref(xmldoc);
        xmldoc = NULL;
    }
    if (orig.xmldoc && objref(orig.xmldoc)) {
        xmldoc = orig.xmldoc;
    } else {
        xmldoc = NULL;
    }
    status = orig.status;
    SetTitle(status);
    panel->SetName(status);
    frame = orig.frame;
    if (dtsevt && frame) {
        dtsevt->BindDTSEvent(frame);
    }
    objunlock(this->refobj);
    objunlock(orig.refobj);
    return *this;
}
bool DTSTabPage::Show (boolshow) [virtual]
Reimplemented from DTSScrollPanel.
Definition at line 941 of file DTSPanel.cpp.
                               {
    return wxScrolledWindow::Show(show);
}
Member Data Documentation
dtsgui_tabpanel_cb DTSTabPage::cb [private]
Definition at line 150 of file DTSPanel.h.
Referenced by ConfigPane(), DTSTabPage(), and operator=().
void* DTSTabPage::cdata [private]
Definition at line 151 of file DTSPanel.h.
Referenced by ConfigPane(), DTSTabPage(), operator=(), and ~DTSTabPage().
bool DTSTabPage::hasconfig [private]
Definition at line 152 of file DTSPanel.h.
Referenced by ConfigPane(), and DTSTabPage().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.