DTSTabWindowEvent
NAME
DTSTabWindowEvent -
SYNOPSIS
#include <DTSTreeWindow.h>
Inherits wxEvtHandler.
Public Member Functions
DTSTabWindowEvent (void *userdata=NULL, DTSTabWindow *win=NULL)
~DTSTabWindowEvent ()
void PageChange (wxBookCtrlEvent &event)
void PageChanged (wxBookCtrlEvent &event)
void RightMenu (wxCommandEvent &event)
void OnButton (wxCommandEvent &event)
Private Attributes
void * data
DTSTabWindow * tw
Detailed Description
Definition at line 136 of file DTSTreeWindow.h.
Constructor & Destructor Documentation
DTSTabWindowEvent::DTSTabWindowEvent (void *userdata = NULL, DTSTabWindow *win = NULL)
Definition at line 825 of file DTSTreeWindow.cpp.
References data, and tw.
                                                                      {
    if (userdata && objref(userdata)) {
        data = userdata;
    } else {
        data = NULL;
    }
    tw = win;
}
DTSTabWindowEvent::~DTSTabWindowEvent ()
Definition at line 834 of file DTSTreeWindow.cpp.
References data.
                                      {
    if (data) {
        objunref(data);
    }
}
Member Function Documentation
void DTSTabWindowEvent::OnButton (wxCommandEvent &event)
Definition at line 840 of file DTSTreeWindow.cpp.
References tw, DTSTabWindow::Undo(), DTSPanel::Update_XML(), wx_PANEL_EVENT_BUTTON_NO, and wx_PANEL_EVENT_BUTTON_YES.
Referenced by DTSTabWindow::Show().
                                                      {
    DTSTabPage *pane = dynamic_cast<DTSTabPage*>(tw->GetCurrentPage());
    int eid = event.GetId();
    int pg = tw->GetSelection();
    switch(eid) {
        case wx_PANEL_EVENT_BUTTON_YES:
            pane->Update_XML();
        /*no break here will reload tab*/
        case wx_PANEL_EVENT_BUTTON_NO:
            pg++;
            tw->Undo(pg);
            return;
        default:
            break;
    }
    event.Skip(true);
}
void DTSTabWindowEvent::PageChange (wxBookCtrlEvent &event)
Definition at line 864 of file DTSTreeWindow.cpp.
References DTSTabPage::ConfigPane(), and tw.
Referenced by DTSTabWindow::Show().
                                                         {
    wxWindow *w;
    DTSTabPage *tp;
    int p = event.GetSelection();
    if (p != wxNOT_FOUND) {
        w = tw->GetPage(p);
        tp = dynamic_cast<DTSTabPage*>(w);
        tp->ConfigPane();
    }
}
void DTSTabWindowEvent::PageChanged (wxBookCtrlEvent &event)
Definition at line 876 of file DTSTreeWindow.cpp.
References tw.
Referenced by DTSTabWindow::Show().
                                                          {
    wxWindow *w;
    int p = event.GetSelection();
    if (p != wxNOT_FOUND) {
        w = tw->GetPage(p);
        w->FitInside();
        w->Layout();
        w->Refresh();
    }
}
void DTSTabWindowEvent::RightMenu (wxCommandEvent &event)
Definition at line 860 of file DTSTreeWindow.cpp.
Referenced by DTSTabWindow::DTSTabWindow().
                                                       {
    printf('MENU\n');
}
Member Data Documentation
void* DTSTabWindowEvent::data [private]
Definition at line 145 of file DTSTreeWindow.h.
Referenced by DTSTabWindowEvent(), and ~DTSTabWindowEvent().
DTSTabWindow* DTSTabWindowEvent::tw [private]
Definition at line 146 of file DTSTreeWindow.h.
Referenced by DTSTabWindowEvent(), OnButton(), PageChange(), and PageChanged().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.