DTSTabWindow
NAME
DTSTabWindow -
SYNOPSIS
#include <DTSTreeWindow.h>
Inherits DTSObject, and wxNotebook.
Public Member Functions
DTSTabWindow (DTSFrame *frame=NULL, wxString stat_msg=wxEmptyString, void *u_data=NULL)
~DTSTabWindow ()
DTSTabPage * CreateTab (const wxString &name, int butmask=0, void *userdata=NULL, dtsgui_tabpanel_cb cb=NULL, void *cdata=NULL, struct xml_doc *xmldoc=NULL, bool addpage=true)
DTSTabPage * CreateTab (const wxString &name, int butmask, void *userdata, dtsgui_tabpanel_cb cb, void *cdata, struct xml_doc *xmldoc, int pos, int undo)
void InsertTab (DTSTabPage *panel, int pos, bool show=true, int undo=0)
void Undo (int pg)
bool Show (bool=true)
Additional Inherited Members
Detailed Description
Definition at line 149 of file DTSTreeWindow.h.
Constructor & Destructor Documentation
DTSTabWindow::DTSTabWindow (DTSFrame *frame = NULL, wxStringstat_msg = wxEmptyString, void *u_data = NULL)
Definition at line 888 of file DTSTreeWindow.cpp.
References DTSObject::dtsevthandler, DTSObject::frame, DTSObject::panel, DTSTabWindowEvent::RightMenu(), Show(), DTSObject::type, DTSObject::userdata, and wx_DTSPANEL_TAB.
    :wxNotebook((wxWindow*)frame, -1),
    DTSObject(stat_msg) {
    DTSTabWindowEvent *dtsevt;
    wxNotebook *nb = (wxNotebook*)this;
    panel = dynamic_cast<wxBookCtrlBase*>(this);
    type = wx_DTSPANEL_TAB;
    this->frame = frame;
    if (u_data && objref(u_data)) {
        userdata = u_data;
    }
    dtsevt = new DTSTabWindowEvent(userdata, this);
    dtsevthandler = dtsevt;
    nb->Bind(wxEVT_CONTEXT_MENU, &DTSTabWindowEvent::RightMenu, dtsevt);
    Show(false);
}
DTSTabWindow::~DTSTabWindow ()
Definition at line 912 of file DTSTreeWindow.cpp.
References DTSObject::userdata.
                            {
    if (userdata) {
        objunref(userdata);
    }
}
Member Function Documentation
DTSTabPage * DTSTabWindow::CreateTab (const wxString &name, intbutmask = 0, void *userdata = NULL, dtsgui_tabpanel_cbcb = NULL, void *cdata = NULL, struct xml_doc *xmldoc = NULL, booladdpage = true)
Definition at line 991 of file DTSTreeWindow.cpp.
References DTSObject::GetFrame(), DTSObject::GetPanel(), and DTSObject::SetUserData().
Referenced by CreateTab(), DTS_C_API::dtsgui_newtabpage(), DTS_C_API::dtsgui_tabpage_insert(), and tab_newpane::handle_newtabpane().
                                                                                                                                                               {
    DTSTabPage *dp;
    DTSFrame *f;
    wxBookCtrlBase *nb;
    f = GetFrame();
    nb = static_cast<wxBookCtrlBase*>(this);
    if (!(dp = new DTSTabPage(nb, f, name, butmask, cb, cdata, xmldoc))) {
        return NULL;
    }
    if (userdata) {
        dp->SetUserData(userdata);
    }
    if (addpage) {
        nb->AddPage(dp->GetPanel(), name);
    }
    return dp;
}
DTSTabPage * DTSTabWindow::CreateTab (const wxString &name, intbutmask, void *userdata, dtsgui_tabpanel_cbcb, void *cdata, struct xml_doc *xmldoc, intpos, intundo)
Definition at line 981 of file DTSTreeWindow.cpp.
References CreateTab(), and InsertTab().
                                                                                                                                                                    {
    DTSTabPage *dp;
    dp = CreateTab(name, butmask, userdata, cb, cdata, xmldoc, false);
    InsertTab(dp, pos, true, undo);
    return dp;
}
void DTSTabWindow::InsertTab (DTSTabPage *panel, intpos, boolshow = true, intundo = 0)
Definition at line 1014 of file DTSTreeWindow.cpp.
References DTSObject::GetName(), DTSObject::GetPanel(), DTSObject::panel, DTSObject::refobj, and Undo().
Referenced by CreateTab(), tab_newpane::handle_newtabpane(), and Undo().
                                                                           {
    wxBookCtrlBase *nb = dynamic_cast<wxBookCtrlBase*>(this);
    DTSObject *dp = static_cast<DTSObject*>(panel);
    wxWindow *w = panel->GetPanel();
    objlock(refobj);
    nb->InsertPage(pos, w, dp->GetName());
    objunlock(refobj);
    w->Show(true);
    if (sel) {
        SetSelection(pos);
    }
    if (undo) {
        Undo(undo);
    }
}
bool DTSTabWindow::Show (boolshow = true)
Definition at line 941 of file DTSTreeWindow.cpp.
References DTSObject::beenshown, DTSTabPage::ConfigPane(), DTSObject::dtsevthandler, DTSObject::frame, DTSTabWindowEvent::OnButton(), DTSTabWindowEvent::PageChange(), DTSTabWindowEvent::PageChanged(), and DTSObject::status.
Referenced by DTSTabWindow().
                                 {
    wxNotebook *nb = (wxNotebook*)this;
    DTSTabWindowEvent *dtsevt = (DTSTabWindowEvent*)dtsevthandler;
    wxWindow *w;
    int i, cnt;
    bool res;
#ifdef __WIN32
    DTSTabPage *tp;
#endif // __WIN32
    if (show && frame) {
        frame->SetStatusText(status);
    }
    res = wxNotebook::Show(show);
    if (!beenshown && show && res) {
        cnt = GetPageCount();
        for(i = 0; i < cnt;i++) {
            w = GetPage(i);
#ifdef __WIN32
            tp = dynamic_cast<DTSTabPage*>(w);
            tp->ConfigPane();
            w->Show(true);
            if (i) {
                w->Show(false);
            }
#else
            w->Show(true);
#endif // __WIN32
        }
        beenshown = true;
        nb->Bind(wxEVT_NOTEBOOK_PAGE_CHANGING, &DTSTabWindowEvent::PageChange, dtsevt);
        nb->Bind(wxEVT_NOTEBOOK_PAGE_CHANGED, &DTSTabWindowEvent::PageChanged, dtsevt);
        nb->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &DTSTabWindowEvent::OnButton, dtsevt);
    }
    return res;
}
void DTSTabWindow::Undo (intpg)
Definition at line 919 of file DTSTreeWindow.cpp.
References InsertTab().
Referenced by tab_newpane::handle_newtabpane(), InsertTab(), and DTSTabWindowEvent::OnButton().
                              {
    DTSTabPage *pane, *newp;
    int idx;
    if (pg == 0) {
        return;
    } else if (pg > 0) {
        idx = pg-1;
    } else {
        idx = GetPageCount() + pg;
    }
    pane = dynamic_cast<DTSTabPage*>(GetPage(idx));
    RemovePage(idx);
    newp = new DTSTabPage(this);
    *newp = *pane;
    delete pane;
    InsertTab(newp, idx);
}
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.