.TH "src/DTSTreeWindow.cpp" 3 "Thu Oct 10 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/DTSTreeWindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/menu\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'DTSFrame\&.h'\fP
.br
\fC#include 'DTSListView\&.h'\fP
.br
\fC#include 'DTSTreeWindow\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtreewinmenu\fP { \fBDTS_TREEWIN_MENU_SORT\fP = 127, \fBDTS_TREEWIN_MENU_MOVEUP\fP, \fBDTS_TREEWIN_MENU_MOVEDOWN\fP, \fBDTS_TREEWIN_MENU_DELETE\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBtreewinmenu\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIDTS_TREEWIN_MENU_SORT \fP\fP
.TP
\fB\fIDTS_TREEWIN_MENU_MOVEUP \fP\fP
.TP
\fB\fIDTS_TREEWIN_MENU_MOVEDOWN \fP\fP
.TP
\fB\fIDTS_TREEWIN_MENU_DELETE \fP\fP

.PP
Definition at line 27 of file DTSTreeWindow\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
