DTSTreeWindow
NAME
DTSTreeWindow -
SYNOPSIS
#include <DTSTreeWindow.h>
Inherits DTSObject, and wxSplitterWindow.
Public Member Functions
DTSTreeWindow (wxWindow *parent=NULL, DTSFrame *frame=NULL, dtsgui_tree_cb tree_cb=NULL, wxString stat_msg=wxEmptyString, int pos=30, void *u_data=NULL, struct xml_doc *xd=NULL)
~DTSTreeWindow ()
void ShowRMenu (bool cont, int cnt, bool first, bool last, bool c_sort, bool del)
bool Show (bool=true)
DTSDVMCtrl * GetTreeCtrl ()
void TreeResize ()
void SetTreePaneSize ()
DTSPanel * GetClientPane ()
void SetPaneTitle (const wxString value)
void Select (const wxDataViewItem &item)
wxWindow * SetWindow (DTSPanel *window, const wxDataViewItem &item)
dtsgui_treenode GetActiveNode ()
DTSScrollPanel * CreatePane (const wxString &name=wxEmptyString, int butmask=0, void *userdata=NULL, struct xml_doc *xmldoc=NULL)
DTSScrollPanel * CreatePane (const wxDataViewItem &node)
void UpdateNodeXML (const wxDataViewItem &node, const char *newname)
Private Attributes
wxScrolledWindow * t_pane
wxWindow * c_pane
DTSDVMCtrl * tree
DTSDVMListView * vm
DTSPanel * a_window
dtsgui_treenode a_node
class treemenu * rmenu
wxBoxSizer * treesizer
Additional Inherited Members
Detailed Description
Definition at line 108 of file DTSTreeWindow.h.
Constructor & Destructor Documentation
DTSTreeWindow::DTSTreeWindow (wxWindow *parent = NULL, DTSFrame *frame = NULL, dtsgui_tree_cbtree_cb = NULL, wxStringstat_msg = wxEmptyString, intpos = 30, void *u_data = NULL, struct xml_doc *xd = NULL)
Definition at line 544 of file DTSTreeWindow.cpp.
References a_window, DTSObject::dtsevthandler, DTSObject::frame, DTSFrame::GetDTSData(), DTSObject::GetPanel(), DTSTreeWindowEvent::MenuEvent(), DTSTreeWindowEvent::OnButton(), DTSObject::panel, rmenu, DTSObject::SetXMLDoc(), Show(), DTSTreeWindowEvent::SplitterEvent(), t_pane, tree, DTSTreeWindowEvent::TreeEvent(), treesizer, DTSObject::type, DTSObject::userdata, vm, and wx_DTSPANEL_TREE.
    :wxSplitterWindow(parent, -1, wxDefaultPosition, wxDefaultSize),
     DTSObject(stat_msg) {
    int w, h, p, psize;
    class dtsgui *udata;
    a_window = NULL;
    DTSTreeWindowEvent *dtsevt;
    wxSplitterWindow *sw = static_cast<wxSplitterWindow*>(this);
    wxBoxSizer *p_sizer = new wxBoxSizer(wxHORIZONTAL);
    treesizer = new wxBoxSizer(wxVERTICAL);
    wxDataViewItem root, root4;
    wxWindow *aw;
    rmenu = new treemenu();
    if (u_data && objref(u_data)) {
        userdata = u_data;
    } else {
        userdata = NULL;
    }
    this->frame = frame;
    if (xd) {
        SetXMLDoc(xd);
    }
    p_sizer->Add(sw, 1,wxEXPAND,0);
#ifdef __WIN32
    t_pane = new wxScrolledWindow(sw, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxVSCROLL);
#else
    t_pane = new wxScrolledWindow(sw, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxHSCROLL|wxVSCROLL);
#endif // _WIN32
    panel = static_cast<wxWindow *>(sw);
    a_window = new DTSWindow(panel, frame);
    a_window->type = wx_DTSPANEL_TREE;
    aw = a_window->GetPanel();
    SplitVertically(t_pane, aw);
    SetSashGravity(0.5);
    SetMinimumPaneSize(20);
    t_pane->SetSizer(treesizer);
#ifdef __WIN32
    t_pane->SetScrollRate(0, 10);
#else
    t_pane->SetScrollRate(10, 10);
#endif // _WIN32
    vm = new DTSDVMListView(1, true);
    tree = new DTSDVMCtrl(t_pane, wxID_ANY, vm, wxDefaultPosition, wxDefaultSize, wxDV_ROW_LINES|wxDV_NO_HEADER);
    udata = (frame) ? frame->GetDTSData() : NULL;
    dtsevt = new DTSTreeWindowEvent(userdata, tree_cb, udata, this);
    if (udata) {
        objunref(udata);
    }
    dtsevthandler = dtsevt;
    treesizer->Add(tree, 1,wxEXPAND,0);
    p_sizer->FitInside(parent);
    p_sizer->Layout();
    p_sizer->SetSizeHints(sw);
    parent->GetSize(&w, &h);
    p = (w * pos) / 100;
    SetSashPosition(p, true);
    treesizer->SetSizeHints(t_pane);
    treesizer->FitInside(t_pane);
    treesizer->Layout();
    tree->Bind(wxEVT_DATAVIEW_SELECTION_CHANGED, &DTSTreeWindowEvent::TreeEvent, dtsevt);
    tree->Bind(wxEVT_DATAVIEW_ITEM_EXPANDED, &DTSTreeWindowEvent::TreeEvent, dtsevt);
    tree->Bind(wxEVT_DATAVIEW_ITEM_CONTEXT_MENU, &DTSTreeWindowEvent::TreeEvent, dtsevt);
    tree->Bind(wxEVT_DATAVIEW_ITEM_EDITING_DONE, &DTSTreeWindowEvent::TreeEvent, dtsevt);
    tree->Bind(wxEVT_DATAVIEW_ITEM_START_EDITING, &DTSTreeWindowEvent::TreeEvent, dtsevt);
    frame->Bind(wxEVT_DATAVIEW_ITEM_BEGIN_DRAG, &DTSTreeWindowEvent::TreeEvent, dtsevt);
    tree->Bind(wxEVT_COMMAND_MENU_SELECTED, &DTSTreeWindowEvent::MenuEvent, dtsevt);
    sw->Bind(wxEVT_SPLITTER_SASH_POS_CHANGED, &DTSTreeWindowEvent::SplitterEvent, dtsevt);
    sw->Bind(wxEVT_COMMAND_BUTTON_CLICKED, &DTSTreeWindowEvent::OnButton, dtsevt);
    tree->EnableDragSource(wxDF_UNICODETEXT);
    tree->EnableDropTarget(wxDF_UNICODETEXT);
    Show(false);
/* root = tree->AppendContainer(wxDataViewItem(NULL), 'The Root');
    tree->AppendItem(root, 'Child E');
    tree->AppendContainer(root, 'Root2');
    tree->AppendItem(root, 'Child D');
    tree->AppendContainer(root, 'Root3');
    tree->AppendItem(root, 'Child C');
    root4 = tree->AppendContainer(root, 'Root4');
    tree->AppendItem(root, 'Child B');
    tree->AppendItem(root, 'Child A');
    tree->AppendItem(root4, 'Child E', true, true, true);
    tree->AppendItem(root4, 'Child D', true, true, true);
    tree->AppendItem(root4, 'Child C', true, true, true);
    tree->AppendItem(root4, 'Child B', true, true, true);
    tree->AppendItem(root4, 'Child A', true, true, true);*/
    psize = p - GetSashSize();
#ifdef _WIN32
    tree->GetColumn(0)->SetWidth(psize - wxSYS_VSCROLL_X);
#else
    tree->GetColumn(0)->SetMinWidth(psize);
#endif // _WIN32
}
DTSTreeWindow::~DTSTreeWindow ()
Definition at line 778 of file DTSTreeWindow.cpp.
References a_window, rmenu, t_pane, and DTSObject::userdata.
                              {
    delete t_pane;
    delete a_window;
    objunref(rmenu);
    if (userdata) {
        objunref(userdata);
    }
}
Member Function Documentation
DTSScrollPanel * DTSTreeWindow::CreatePane (const wxString &name = wxEmptyString, intbutmask = 0, void *userdata = NULL, struct xml_doc *xmldoc = NULL)
Definition at line 715 of file DTSTreeWindow.cpp.
References DTSObject::GetFrame(), DTSObject::GetPanel(), DTSPanel::SetTitle(), DTSObject::SetXMLDoc(), DTSObject::type, and wx_DTSPANEL_TREE.
Referenced by CreatePane(), DTS_C_API::dtsgui_treepane(), DTS_C_API::dtsgui_treepane_default(), and DTSTreeWindowEvent::TreeCallback().
                                                                                                                   {
    DTSScrollPanel *dp;
    wxWindow *parent;
    DTSFrame *f;
    parent = GetPanel();
    f = GetFrame();
    dp = new DTSScrollPanel(parent, f, name, butmask);
    dp->type = wx_DTSPANEL_TREE;
    if (name.Len() > 0) {
        dp->SetTitle(name, true);
    }
    if (xmldoc) {
        dp->SetXMLDoc(xmldoc);
    }
    return dp;
}
DTSScrollPanel * DTSTreeWindow::CreatePane (const wxDataViewItem &node)
Definition at line 736 of file DTSTreeWindow.cpp.
References CreatePane(), DTSDVMListView::GetNodeID(), DTSDVMListView::GetTitle(), vm, wx_PANEL_BUTTON_ACTION, and DTSObject::xmldoc.
                                                                    {
    DTSScrollPanel *p;
    int nodeid;
    wxString name;
    nodeid = vm->GetNodeID(node);
    if (nodeid == -1) {
        p = CreatePane();
    } else {
        name = vm->GetTitle(node);
        p = CreatePane(name, wx_PANEL_BUTTON_ACTION, NULL, xmldoc);
    }
    return p;
}
dtsgui_treenode DTSTreeWindow::GetActiveNode ()
Definition at line 683 of file DTSTreeWindow.cpp.
References a_node.
Referenced by DTSTreeWindowEvent::OnButton().
                                             {
    return a_node;
}
DTSPanel * DTSTreeWindow::GetClientPane ()
Definition at line 810 of file DTSTreeWindow.cpp.
References a_window.
Referenced by DTSTreeWindowEvent::OnButton().
                                       {
    return a_window;
}
DTSDVMCtrl * DTSTreeWindow::GetTreeCtrl ()
Definition at line 655 of file DTSTreeWindow.cpp.
References tree.
Referenced by DTS_C_API::dtsgui_treecont(), DTS_C_API::dtsgui_treeitem(), DTSTreeWindowEvent::DTSTreeWindowEvent(), and tree_newnode::handle_newtreenode().
                                       {
    return tree;
}
void DTSTreeWindow::Select (const wxDataViewItem &item)
Definition at line 814 of file DTSTreeWindow.cpp.
References DTSDVMListView::IsContainer(), tree, and vm.
Referenced by tree_newnode::handle_newtreenode(), DTSTreeWindowEvent::OnButton(), and Show().
                                                     {
    if (vm->IsContainer(item)) {
        tree->Expand(item);
    }
    tree->Select(item);
    wxDataViewEvent event(wxEVT_DATAVIEW_SELECTION_CHANGED, -1);
    event.SetItem(item);
    tree->ProcessWindowEvent(event);
}
void DTSTreeWindow::SetPaneTitle (const wxStringvalue)
Definition at line 673 of file DTSTreeWindow.cpp.
References a_window, DTSPanel::SetTitle(), and TreeResize().
Referenced by DTSTreeWindowEvent::TreeEvent().
                                                     {
    DTSPanel *p;
    if ((p = dynamic_cast<DTSPanel*>(a_window))) {
        p->SetTitle(value);
    }
    TreeResize();
}
void DTSTreeWindow::SetTreePaneSize ()
Definition at line 659 of file DTSTreeWindow.cpp.
References tree.
Referenced by DTSTreeWindowEvent::SplitterEvent().
                                    {
    int psize = GetSashPosition() - GetSashSize();
#ifdef _WIN32
        tree->GetColumn(0)->SetWidth(psize - wxSYS_VSCROLL_X);
#else
        tree->GetColumn(0)->SetMinWidth(psize);
#endif // _WIN32
}
wxWindow * DTSTreeWindow::SetWindow (DTSPanel *window, const wxDataViewItem &item)
Definition at line 687 of file DTSTreeWindow.cpp.
References a_node, a_window, and DTSObject::GetPanel().
Referenced by DTSTreeWindowEvent::TreeCallback().
                                                                               {
    DTSPanel *oldwin;
    wxWindow *nw, *cw;
    if (!window || (window == a_window)) {
        return NULL;
    }
    if ((oldwin = a_window)) {
        a_window->Show(false);
    }
    nw = window->GetPanel();
    cw = a_window->GetPanel();
    ReplaceWindow(cw, nw);
    a_window = window;
    a_node = item.GetID();
    nw->Show(true);
    nw->Layout();
    nw->FitInside();
    return oldwin;
}
bool DTSTreeWindow::Show (boolshow = true)
Definition at line 787 of file DTSTreeWindow.cpp.
References DTSObject::beenshown, DTSObject::frame, DTSDVMListView::GetRoot(), DTSDVMCtrl::GetStore(), Select(), DTSObject::status, tree, and TreeResize().
Referenced by DTSTreeWindow().
                                  {
    if (show) {
        TreeResize();
        if (!beenshown) {
            wxDataViewItem root;
            DTSDVMListStore *ds;
            DTSDVMListView *model;
            model = tree->GetStore();
            ds = model->GetRoot();
            root = wxDataViewItem(ds);
            Select(root);
            beenshown = true;
        }
        if (frame) {
            frame->SetStatusText(status);
        }
    }
    return wxSplitterWindow::Show(show);
}
void DTSTreeWindow::ShowRMenu (boolcont, intcnt, boolfirst, boollast, boolc_sort, booldel)
Definition at line 711 of file DTSTreeWindow.cpp.
References rmenu, treemenu::Show(), and tree.
Referenced by DTSTreeWindowEvent::TreeEvent().
                                                                                              {
    rmenu->Show(tree, cont, cnt, first, last, c_sort, del);
}
void DTSTreeWindow::TreeResize ()
Definition at line 668 of file DTSTreeWindow.cpp.
References tree.
Referenced by SetPaneTitle(), Show(), and DTSTreeWindowEvent::TreeEvent().
                               {
    tree->GetColumn(0)->SetHidden(true);
    tree->GetColumn(0)->SetHidden(false);
}
void DTSTreeWindow::UpdateNodeXML (const wxDataViewItem &node, const char *newname)
Definition at line 754 of file DTSTreeWindow.cpp.
References DTSDVMListView::GetXMLData(), vm, and DTSObject::xmldoc.
Referenced by DTS_C_API::dtsgui_nodesetxml(), and DTSTreeWindowEvent::TreeCallback().
                                                                                 {
    struct xml_node *xn;
    struct xml_doc *xd;
    char *buf;
    if (!xmldoc || !objref(xmldoc)) {
        return;
    }
    xd = xmldoc;
    if (!(xn = vm->GetXMLData(node, &buf))) {
        return;
    }
    if (buf) {
        xml_setattr(xd, xn, buf, newname);
        objunref(buf);
    } else {
        xml_modify(xd, xn, newname);
    }
    objunref(xn);
    objunref(xd);
}
Member Data Documentation
dtsgui_treenode DTSTreeWindow::a_node [private]
Definition at line 131 of file DTSTreeWindow.h.
Referenced by GetActiveNode(), and SetWindow().
DTSPanel* DTSTreeWindow::a_window [private]
Definition at line 130 of file DTSTreeWindow.h.
Referenced by DTSTreeWindow(), GetClientPane(), SetPaneTitle(), SetWindow(), and ~DTSTreeWindow().
wxWindow* DTSTreeWindow::c_pane [private]
Definition at line 127 of file DTSTreeWindow.h.
class treemenu* DTSTreeWindow::rmenu [private]
Definition at line 132 of file DTSTreeWindow.h.
Referenced by DTSTreeWindow(), ShowRMenu(), and ~DTSTreeWindow().
wxScrolledWindow* DTSTreeWindow::t_pane [private]
Definition at line 126 of file DTSTreeWindow.h.
Referenced by DTSTreeWindow(), and ~DTSTreeWindow().
DTSDVMCtrl* DTSTreeWindow::tree [private]
Definition at line 128 of file DTSTreeWindow.h.
Referenced by DTSTreeWindow(), GetTreeCtrl(), Select(), SetTreePaneSize(), Show(), ShowRMenu(), and TreeResize().
wxBoxSizer* DTSTreeWindow::treesizer [private]
Definition at line 133 of file DTSTreeWindow.h.
Referenced by DTSTreeWindow().
DTSDVMListView* DTSTreeWindow::vm [private]
Definition at line 129 of file DTSTreeWindow.h.
Referenced by CreatePane(), DTSTreeWindow(), Select(), and UpdateNodeXML().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.