.TH "DTSTabPage" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSTabPage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSPanel\&.h>\fP
.PP
Inherits \fBDTSScrollPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSTabPage\fP (\fBwxBookCtrlBase\fP *, \fBDTSFrame\fP *=NULL, wxString=wxEmptyString, int=0, \fBdtsgui_tabpanel_cb\fP=NULL, void *=NULL, struct xml_doc *=NULL)"
.br
.ti -1c
.RI "\fB~DTSTabPage\fP ()"
.br
.ti -1c
.RI "void \fBConfigPane\fP ()"
.br
.ti -1c
.RI "virtual bool \fBShow\fP (bool)"
.br
.ti -1c
.RI "\fBDTSTabPage\fP & \fBoperator=\fP (const \fBDTSTabPage\fP &orig)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 142 of file DTSPanel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSTabPage::DTSTabPage (\fBwxBookCtrlBase\fP *parent, \fBDTSFrame\fP *frame = \fCNULL\fP, wxStringstatus = \fCwxEmptyString\fP, intbutmask = \fC0\fP, \fBdtsgui_tabpanel_cb\fPc_cb = \fCNULL\fP, void *c_data = \fCNULL\fP, struct xml_doc *xmldoc = \fCNULL\fP)"

.PP
Definition at line 903 of file DTSPanel\&.cpp\&.
.SS "DTSTabPage::~DTSTabPage ()"

.PP
Definition at line 920 of file DTSPanel\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void DTSTabPage::ConfigPane ()"

.PP
Definition at line 932 of file DTSPanel\&.cpp\&.
.SS "\fBDTSTabPage\fP & DTSTabPage::operator= (const \fBDTSTabPage\fP &orig)"

.PP
Definition at line 949 of file DTSPanel\&.cpp\&.
.SS "bool DTSTabPage::Show (boolshow)\fC [virtual]\fP"

.PP
Reimplemented from \fBDTSScrollPanel\fP\&.
.PP
Definition at line 928 of file DTSPanel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
