.TH "DTSTabWindowEvent" 3 "Thu Oct 10 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSTabWindowEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSTreeWindow\&.h>\fP
.PP
Inherits wxEvtHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSTabWindowEvent\fP (void *userdata=NULL, \fBDTSTabWindow\fP *win=NULL)"
.br
.ti -1c
.RI "\fB~DTSTabWindowEvent\fP ()"
.br
.ti -1c
.RI "void \fBPageChange\fP (wxBookCtrlEvent &event)"
.br
.ti -1c
.RI "void \fBPageChanged\fP (wxBookCtrlEvent &event)"
.br
.ti -1c
.RI "void \fBRightMenu\fP (wxCommandEvent &event)"
.br
.ti -1c
.RI "void \fBOnButton\fP (wxCommandEvent &event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 136 of file DTSTreeWindow\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSTabWindowEvent::DTSTabWindowEvent (void *userdata = \fCNULL\fP, \fBDTSTabWindow\fP *win = \fCNULL\fP)"

.PP
Definition at line 811 of file DTSTreeWindow\&.cpp\&.
.SS "DTSTabWindowEvent::~DTSTabWindowEvent ()"

.PP
Definition at line 820 of file DTSTreeWindow\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void DTSTabWindowEvent::OnButton (wxCommandEvent &event)"

.PP
Definition at line 826 of file DTSTreeWindow\&.cpp\&.
.SS "void DTSTabWindowEvent::PageChange (wxBookCtrlEvent &event)"

.PP
Definition at line 850 of file DTSTreeWindow\&.cpp\&.
.SS "void DTSTabWindowEvent::PageChanged (wxBookCtrlEvent &event)"

.PP
Definition at line 862 of file DTSTreeWindow\&.cpp\&.
.SS "void DTSTabWindowEvent::RightMenu (wxCommandEvent &event)"

.PP
Definition at line 846 of file DTSTreeWindow\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
