.TH "src/DTSTreeWindow.cpp" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/DTSTreeWindow.cpp \- 
.PP
Implementation of Tree and Tab view and event handlers\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <wx/menu\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'DTSFrame\&.h'\fP
.br
\fC#include 'DTSListView\&.h'\fP
.br
\fC#include 'DTSTreeWindow\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtreewinmenu\fP { \fBDTS_TREEWIN_MENU_SORT\fP = 127, \fBDTS_TREEWIN_MENU_MOVEUP\fP, \fBDTS_TREEWIN_MENU_MOVEDOWN\fP, \fBDTS_TREEWIN_MENU_DELETE\fP }"
.br
.RI "\fIMenu id's for right click popup\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of Tree and Tab view and event handlers\&. 


.PP
Definition in file \fBDTSTreeWindow\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
