.TH "DTSTextPanel" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSTextPanel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSPanel\&.h>\fP
.PP
Inherits \fBDTSStaticPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSTextPanel\fP (\fBwxWindow\fP *, \fBDTSFrame\fP *=NULL, wxString=wxEmptyString)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 131 of file DTSPanel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSTextPanel::DTSTextPanel (\fBwxWindow\fP *parent, \fBDTSFrame\fP *frame = \fCNULL\fP, wxStringstatus = \fCwxEmptyString\fP)"

.PP
Definition at line 1018 of file DTSPanel\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
