.TH "src/include/DTSTreeWindow.h" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/DTSTreeWindow.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/dataview\&.h>\fP
.br
\fC#include <wx/splitter\&.h>\fP
.br
\fC#include <wx/notebook\&.h>\fP
.br
\fC#include 'DTSPanel\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtree_newnode\fP"
.br
.ti -1c
.RI "class \fBtab_newpane\fP"
.br
.ti -1c
.RI "class \fBtreemenu\fP"
.br
.ti -1c
.RI "class \fBDTSTreeWindowEvent\fP"
.br
.ti -1c
.RI "class \fBDTSTreeWindow\fP"
.br
.ti -1c
.RI "class \fBDTSTabWindowEvent\fP"
.br
.ti -1c
.RI "class \fBDTSTabWindow\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fBDTSTabWindow\fP \fBDTSTabWindow\fP"
.br
.ti -1c
.RI "typedef class \fBDTSTreeWindow\fP \fBDTSTreeWindow\fP"
.br
.ti -1c
.RI "typedef class \fBDTSDVMListView\fP \fBDTSDVMListView\fP"
.br
.ti -1c
.RI "typedef class \fBDTSDVMCtrl\fP \fBDTSDVMCtrl\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef class \fBDTSDVMCtrl\fP \fBDTSDVMCtrl\fP"

.PP
Definition at line 31 of file DTSTreeWindow\&.h\&.
.SS "typedef class \fBDTSDVMListView\fP \fBDTSDVMListView\fP"

.PP
Definition at line 30 of file DTSTreeWindow\&.h\&.
.SS "typedef class \fBDTSTabWindow\fP \fBDTSTabWindow\fP"

.PP
Definition at line 28 of file DTSTreeWindow\&.h\&.
.SS "typedef class \fBDTSTreeWindow\fP \fBDTSTreeWindow\fP"

.PP
Definition at line 29 of file DTSTreeWindow\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
