.TH "src/include/DTSWizard.h" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/DTSWizard.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdtsgui_wizard\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fBwxWizard\fP \fBwxWizard\fP"
.br
.ti -1c
.RI "typedef class \fBDTSWizardWindow\fP \fBDTSWizardWindow\fP"
.br
.ti -1c
.RI "typedef class \fBwxWizardPageSimple\fP \fBwxWizardPageSimple\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef class \fBDTSWizardWindow\fP \fBDTSWizardWindow\fP"

.PP
Definition at line 23 of file DTSWizard\&.h\&.
.SS "typedef class \fBwxWizard\fP \fBwxWizard\fP"

.PP
Definition at line 22 of file DTSWizard\&.h\&.
.SS "typedef class \fBwxWizardPageSimple\fP \fBwxWizardPageSimple\fP"

.PP
Definition at line 24 of file DTSWizard\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
