.TH "DTSWindow" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSPanel\&.h>\fP
.PP
Inherits \fBDTSPanel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSWindow\fP (\fBwxWindow\fP *, \fBDTSFrame\fP *=NULL, wxString=wxEmptyString)"
.br
.ti -1c
.RI "bool \fBShow\fP (bool=true)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 155 of file DTSPanel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSWindow::DTSWindow (\fBwxWindow\fP *parent, \fBDTSFrame\fP *frame = \fCNULL\fP, wxStringstatus = \fCwxEmptyString\fP)"

.PP
Definition at line 1035 of file DTSPanel\&.cpp\&.
.PP
References DTSObject::panel, DTSPanel::SetupWin(), DTSObject::type, and wx_DTSPANEL_WINDOW\&.
.PP
.nf
    :wxWindow(parent, -1),
     DTSPanel(frame, status) {
    type = wx_DTSPANEL_WINDOW;
    panel = dynamic_cast<wxWindow *>(this);
    SetupWin();
}
.fi
.SH "Member Function Documentation"
.PP 
.SS "bool DTSWindow::Show (boolshow = \fCtrue\fP)"

.PP
Definition at line 1043 of file DTSPanel\&.cpp\&.
.PP
References DTSPanel::ShowPanel()\&.
.PP
.nf
                              {
    ShowPanel(show);
    return wxWindow::Show(show);
}
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
