.TH "DTSWindow" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSPanel\&.h>\fP
.PP
Inherits \fBDTSPanel\fP, and wxWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSWindow\fP (\fBwxWindow\fP *, \fBDTSFrame\fP *=NULL, wxString=wxEmptyString)"
.br
.ti -1c
.RI "bool \fBShow\fP (bool=true)"
.br
.in -1c