.TH "DTSWizardWindow" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DTSWizardWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DTSPanel\&.h>\fP
.PP
Inherits \fBDTSPanel\fP, and wxWizardPageSimple\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDTSWizardWindow\fP (wxString=wxEmptyString)"
.br
.ti -1c
.RI "virtual bool \fBShow\fP (bool=true)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 172 of file DTSPanel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DTSWizardWindow::DTSWizardWindow (wxStringtitle = \fCwxEmptyString\fP)"

.PP
Definition at line 1090 of file DTSPanel\&.cpp\&.
.PP
References DTSPanel::button_mask, DTSObject::panel, DTSPanel::SetupWin(), DTSObject::type, and wx_DTSPANEL_WIZARD\&.
.SH "Member Function Documentation"
.PP 
.SS "bool DTSWizardWindow::Show (boolshow = \fCtrue\fP)\fC [virtual]\fP"

.PP
Definition at line 1097 of file DTSPanel\&.cpp\&.
.PP
References DTSObject::panel, DTSPanel::SetSizerSize(), and DTSPanel::ShowPanel()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
