DTSWizardWindow
NAME
DTSWizardWindow -
SYNOPSIS
#include <DTSPanel.h>
Inherits DTSPanel, and wxWizardPageSimple.
Public Member Functions
DTSWizardWindow (wxString=wxEmptyString)
virtual bool Show (bool=true)
Additional Inherited Members
Detailed Description
Definition at line 172 of file DTSPanel.h.
Constructor & Destructor Documentation
DTSWizardWindow::DTSWizardWindow (wxStringtitle = wxEmptyString)
Definition at line 1090 of file DTSPanel.cpp.
References DTSPanel::button_mask, DTSObject::panel, DTSPanel::SetupWin(), DTSObject::type, and wx_DTSPANEL_WIZARD.
Member Function Documentation
bool DTSWizardWindow::Show (boolshow = true) [virtual]
Definition at line 1097 of file DTSPanel.cpp.
References DTSObject::panel, DTSPanel::SetSizerSize(), and DTSPanel::ShowPanel().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.