DTSXMLComboBox
NAME
DTSXMLComboBox -
SYNOPSIS
#include <DTSXMLComboBox.h>
Inherits wxComboBox.
Public Member Functions
DTSXMLComboBox (wxWindow *parent, int id, wxString url, wxString xpath, struct curl_post *(*getpost)(const wxString &), size_t minlen)
~DTSXMLComboBox ()
bool HasXMLList ()
Private Member Functions
void HandleEvent (wxCommandEvent &event)
struct xml_doc * GetXMLDoc (const wxString &val, struct xml_node *xn)
struct curl_post * GetPostInfo (const wxString &val)
bool AppendXMLNodes (struct xml_doc *xmldoc)
void EmptyServerList ()
Private Attributes
int sflags
size_t minlen
wxString url
wxString xpath
struct curl_post *(* getpost )(const wxString &)
Detailed Description
Definition at line 27 of file DTSXMLComboBox.h.
Constructor & Destructor Documentation
DTSXMLComboBox::DTSXMLComboBox (wxWindow *parent, intid, wxStringurl, wxStringxpath, struct curl_post *(*)(const wxString &)getpost, size_tminlen)
Definition at line 34 of file DTSXMLComboBox.cpp.
References getpost, HandleEvent(), minlen, sflags, url, and xpath.
                                                                                                                                                  {
    sflags = 0;
    this->minlen = minlen;
    this->url = url;
    this->xpath = xpath;
    this->getpost = getpost;
    Create(parent, id, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0, NULL, wxTE_PROCESS_ENTER | wxCB_DROPDOWN);
    Append(wxEmptyString, (void*)NULL);
    Bind(wxEVT_TEXT_ENTER, &DTSXMLComboBox::HandleEvent, this);
    Bind(wxEVT_COMBOBOX, &DTSXMLComboBox::HandleEvent, this);
    Bind(wxEVT_COMBOBOX_DROPDOWN, &DTSXMLComboBox::HandleEvent, this);
    Bind(wxEVT_COMMAND_TEXT_UPDATED, &DTSXMLComboBox::HandleEvent, this);
}
DTSXMLComboBox::~DTSXMLComboBox ()
Definition at line 94 of file DTSXMLComboBox.cpp.
References EmptyServerList().
                                {
    EmptyServerList();
}
Member Function Documentation
bool DTSXMLComboBox::AppendXMLNodes (struct xml_doc *xmldoc) [private]
Definition at line 72 of file DTSXMLComboBox.cpp.
Referenced by HandleEvent().
                                                          {
    struct xml_search *xp;
    struct xml_node *xn;
    void *iter;
    xp = xml_xpath(xmldoc, xpath, NULL);
    if (!xp || !xml_nodecount(xp)) {
        if (xp) {
            objunref(xp);
        }
        objunref(xmldoc);
        return false;
    }
    for(xn = xml_getfirstnode(xp, &iter); xn; xn = xml_getnextnode(iter)) {
        Append(xn->value, xn);
    }
    objunref(iter);
    objunref(xp);
    objunref(xmldoc);
    return true;
}
void DTSXMLComboBox::EmptyServerList () [private]
Definition at line 162 of file DTSXMLComboBox.cpp.
Referenced by HandleEvent(), and ~DTSXMLComboBox().
                                     {
    void *data;
    int i, cnt;
    cnt = GetCount();
    for(i=0; i < cnt;i++) {
        if ((data = GetClientData(i))) {
            objunref(data);
            SetClientData(i, NULL);
        }
    }
    Clear();
}
struct curl_post* DTSXMLComboBox::GetPostInfo (const wxString &val) [read], [private]
struct xml_doc * DTSXMLComboBox::GetXMLDoc (const wxString &val, struct xml_node *xn) [read], [private]
Definition at line 51 of file DTSXMLComboBox.cpp.
References getpost.
Referenced by HandleEvent().
                                                                                  {
    struct xml_doc *xmldoc = NULL;
    struct curl_post *post;
    struct curlbuf *cbuf;
    if (getpost) {
        post = getpost(val);
    } else {
        return NULL;
    }
    if (!(cbuf = curl_posturl(url, NULL, post, NULL, NULL))) {
        return NULL;
    }
    xmldoc = curl_buf2xml(cbuf);
    objunref(cbuf);
    return xmldoc;
}
void DTSXMLComboBox::HandleEvent (wxCommandEvent &event) [private]
Definition at line 106 of file DTSXMLComboBox.cpp.
References AppendXMLNodes(), DTSAPPTB_SERVER_POP, DTSAPPTB_SERVER_SET, EmptyServerList(), GetXMLDoc(), minlen, and sflags.
Referenced by DTSXMLComboBox().
                                                      {
    struct xml_doc *xmldoc;
    wxString newval;
    int etype = event.GetEventType();
    wxString val;
    struct xml_node *xn = NULL;
    val = GetValue();
    if ((sflags & DTSAPPTB_SERVER_POP) && !(sflags & DTSAPPTB_SERVER_SET) && (etype == wxEVT_COMMAND_TEXT_UPDATED)) {
        sflags &= ~DTSAPPTB_SERVER_POP;
        event.Skip();
    } else if ((sflags & DTSAPPTB_SERVER_SET) && (etype == wxEVT_COMMAND_TEXT_UPDATED)) {
        sflags &= ~DTSAPPTB_SERVER_SET;
        event.Skip();
    } else if (!(sflags & DTSAPPTB_SERVER_POP) && !(sflags & DTSAPPTB_SERVER_SET) && (etype == wxEVT_COMBOBOX_DROPDOWN) && (val.Len() < minlen)) {
        sflags &= ~DTSAPPTB_SERVER_SET;
        EmptyServerList();
        Append(wxEmptyString, (void*)NULL);
        Dismiss();
        event.Skip();
    } else if (!(sflags & DTSAPPTB_SERVER_POP) && (etype == wxEVT_COMBOBOX_DROPDOWN) && (val.Len() >= minlen)) {
        Dismiss();
        EmptyServerList();
        sflags &= ~(DTSAPPTB_SERVER_SET | DTSAPPTB_SERVER_POP);
        if ((xmldoc = GetXMLDoc(val, xn))) {
            if (!AppendXMLNodes(xmldoc)) {
                Append(wxEmptyString, (void*)NULL);
                sflags &= ~(DTSAPPTB_SERVER_POP | DTSAPPTB_SERVER_SET);
            } else {
                sflags |= (DTSAPPTB_SERVER_POP | DTSAPPTB_SERVER_SET);
                event.Skip();
                Popup();
            }
        } else {
            Append(wxEmptyString, (void*)NULL);
            sflags &= ~(DTSAPPTB_SERVER_POP | DTSAPPTB_SERVER_SET);
        }
    } else if (!(sflags & DTSAPPTB_SERVER_POP) && (etype == wxEVT_COMBOBOX_DROPDOWN)) {
        EmptyServerList();
        Append(wxEmptyString, (void*)NULL);
        Dismiss();
    } else if ((sflags & DTSAPPTB_SERVER_POP) && etype == wxEVT_COMBOBOX) {
        /*Windows Barfs if you change the value*/
#ifdef __WIN332
        sflags |= (DTSAPPTB_SERVER_POP | DTSAPPTB_SERVER_SET);
#else
        sflags |= DTSAPPTB_SERVER_SET;
#endif // __WIN32
        event.Skip();
    } else if (etype != wxEVT_COMBOBOX_DROPDOWN) {
        event.Skip();
    }
}
bool DTSXMLComboBox::HasXMLList ()
Definition at line 98 of file DTSXMLComboBox.cpp.
References DTSAPPTB_SERVER_POP, and sflags.
Referenced by DTSAPPToolBar::HandleEvent().
                                {
    if (sflags & DTSAPPTB_SERVER_POP) {
        return true;
    } else {
        return false;
    }
}
Member Data Documentation
struct curl_post*(* DTSXMLComboBox::getpost)(const wxString &) [read], [private]
Definition at line 42 of file DTSXMLComboBox.h.
Referenced by DTSXMLComboBox(), and GetXMLDoc().
size_t DTSXMLComboBox::minlen [private]
Definition at line 39 of file DTSXMLComboBox.h.
Referenced by DTSXMLComboBox(), and HandleEvent().
int DTSXMLComboBox::sflags [private]
Definition at line 38 of file DTSXMLComboBox.h.
Referenced by DTSXMLComboBox(), HandleEvent(), and HasXMLList().
wxString DTSXMLComboBox::url [private]
Definition at line 40 of file DTSXMLComboBox.h.
Referenced by DTSXMLComboBox().
wxString DTSXMLComboBox::xpath [private]
Definition at line 41 of file DTSXMLComboBox.h.
Referenced by DTSXMLComboBox().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.