.TH "src/include/DTSXMLComboBox.h" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/DTSXMLComboBox.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDTSXMLComboBox\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBserver_state\fP { \fBDTSAPPTB_SERVER_POP\fP = 1 << 0, \fBDTSAPPTB_SERVER_SET\fP = 1 << 1 }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBserver_state\fP"

.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIDTSAPPTB_SERVER_POP \fP\fP
.TP
\fB\fIDTSAPPTB_SERVER_SET \fP\fP

.PP
Definition at line 22 of file DTSXMLComboBox\&.h\&.
.PP
.nf
                  {
    DTSAPPTB_SERVER_POP = 1 << 0,
    DTSAPPTB_SERVER_SET = 1 << 1
};
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
