.TH "src/include/evdata.h" 3 "Thu Oct 10 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/evdata.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdynamic_panel\fP"
.br
.ti -1c
.RI "class \fBevdata\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fBwxWindow\fP \fBwxWindow\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef class \fBwxWindow\fP \fBwxWindow\fP"

.PP
Definition at line 22 of file evdata\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
