.TH "form_data" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
form_data \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pitems\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBptr\fP"
.br
.ti -1c
.RI "class \fBxml_element\fP * \fBxml\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 38 of file pitems\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "void* form_data::ptr"

.PP
Definition at line 39 of file pitems\&.h\&.
.PP
Referenced by form_item::GetData()\&.
.SS "class \fBxml_element\fP* form_data::xml"

.PP
Definition at line 40 of file pitems\&.h\&.
.PP
Referenced by form_item::GetXMLData()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
