form_item
NAME
form_item -
SYNOPSIS
#include <pitems.h>
Public Member Functions
DTS_OJBREF_CLASS (form_item)
form_item (void *widget, enum widget_type type, const char *name, const char *value, const char *value2, void *data, enum form_data_type dtype)
class xml_element * GetXMLData ()
void * GetData ()
void Append (const char *text, const char *val)
void SetSelection (int i)
const char * GetName ()
const char * GetValue ()
void * GetWidget ()
void AppendXML (struct xml_doc *xmldoc, const char *xpath, const char *nattr, const char *vattr)
Private Attributes
enum widget_type type
const char * name
int idx
union form_data data
union widgets widget
enum form_data_type dtype
const char * value
const char * value2
Detailed Description
Definition at line 50 of file pitems.h.
Constructor & Destructor Documentation
form_item::form_item (void *widget, enum widget_typetype, const char *name, const char *value, const char *value2, void *data, enum form_data_typedtype)
Definition at line 89 of file pitems.cpp.
References data, dtype, idx, type, and widget.
                                                                                                                                                        {
    this->widget.p = widget;
    this->type = type;
    this->data.ptr = data;
    this->dtype = dtype;
    ALLOC_CONST(this->name, name);
    if (value) {
        ALLOC_CONST(this->value, value);
    }
    if (value2) {
        ALLOC_CONST(this->value2, value2);
    }
    this->idx = -1;
}
Member Function Documentation
void form_item::Append (const char *text, const char *val)
Definition at line 155 of file pitems.cpp.
References DTS_WIDGET_COMBOBOX, DTS_WIDGET_LISTBOX, idx, widgets::l, SetSelection(), type, value, and widget.
Referenced by AppendXML(), and DTS_C_API::dtsgui_listbox_add().
                                                        {
    int i;
    switch(type) {
        case DTS_WIDGET_COMBOBOX:
        case DTS_WIDGET_LISTBOX:
            break;
        default:
            return;
    }
    i = widget.l->Append(text, (val) ? (void*)strdup(val) : NULL);
    if ((idx == -1) && value && val && !strcmp(value, val)) {
        idx = i;
        SetSelection(idx);
    } else if (i == 0) {
        SetSelection(0);
    }
}
void form_item::AppendXML (struct xml_doc *xmldoc, const char *xpath, const char *nattr, const char *vattr)
Definition at line 225 of file pitems.cpp.
References Append(), name, and value.
Referenced by DTS_C_API::dtsgui_listbox_addxml().
                                                                                                         {
    struct xml_search *xs;
    struct xml_node *xn;
    void *iter;
    const char *name, *value;
    if (!(xs = xml_xpath(xmldoc, xpath, nattr))) {
        return;
    }
    for(xn = xml_getfirstnode(xs, &iter); xn ; xn = xml_getnextnode(iter)) {
        name = (nattr) ? xml_getattr(xn, nattr) : xn->value;
        value = (vattr) ? xml_getattr(xn, vattr) : xn->value;
        Append(name, value);
        objunref(xn);
    }
    objunref(xs);
    if (iter) {
        objunref(iter);
    }
}
form_item::DTS_OJBREF_CLASS (form_item)
void * form_item::GetData ()
Definition at line 144 of file pitems.cpp.
References data, and form_data::ptr.
Referenced by DTS_C_API::dtsgui_item_data().
                         {
    void *fp = NULL;
    objlock(this);
    if (data.ptr && objref(data.ptr)) {
        fp = data.ptr;
    }
    objunlock(this);
    return fp;
}
const char * form_item::GetName ()
Definition at line 188 of file pitems.cpp.
References name.
Referenced by DTS_C_API::dtsgui_item_name(), DTSPanel::fitems_hash(), DTSPanel::Panel2Post(), and DTSPanel::Panel2XML().
                               {
    return name;
}
const char * form_item::GetValue ()
Definition at line 192 of file pitems.cpp.
References widgets::c, DTS_WIDGET_CHECKBOX, DTS_WIDGET_COMBOBOX, DTS_WIDGET_LISTBOX, DTS_WIDGET_TEXTBOX, widgets::l, widgets::t, type, value, value2, and widget.
Referenced by DTS_C_API::dtsgui_item_value(), DTSPanel::FindValue(), DTSPanel::Panel2Post(), DTSPanel::Panel2XML(), and DTSPanel::Update_XML().
                                {
    const char *val = NULL;
    void *tmp;
    switch(type) {
        case DTS_WIDGET_TEXTBOX:
            val = strdup(widget.t->GetValue().ToUTF8());
            break;
        case DTS_WIDGET_LISTBOX:
        case DTS_WIDGET_COMBOBOX:
            int pos;
            pos = widget.l->GetSelection();
            if ((pos != wxNOT_FOUND) && widget.l->HasClientData() && (tmp = widget.l->GetClientData(pos))) {
                val = strdup((char*)tmp);
            } else {
                val = strdup(widget.l->GetValue().ToUTF8());
            }
            break;
        case DTS_WIDGET_CHECKBOX:
            if (widget.c->IsChecked()) {
                val = (value) ? strdup(value) : NULL;
            } else {
                val = (value2) ? strdup(value2) : NULL;
            }
            break;
    }
    return val;
}
void * form_item::GetWidget ()
Definition at line 221 of file pitems.cpp.
References widgets::p, and widget.
Referenced by DTSPanelEvent::OnCombo().
                           {
    return widget.p;
}
class xml_element * form_item::GetXMLData ()
Definition at line 134 of file pitems.cpp.
References data, DTSGUI_FORM_DATA_XML, dtype, and form_data::xml.
Referenced by DTSPanel::Update_XML().
                                         {
    class xml_element *ret = NULL;
    objlock(this);
    if ((dtype == DTSGUI_FORM_DATA_XML) && data.xml && objref(data.xml)) {
        ret = data.xml;
    }
    objunlock(this);
    return ret;
}
void form_item::SetSelection (inti)
Definition at line 176 of file pitems.cpp.
References DTS_WIDGET_COMBOBOX, DTS_WIDGET_LISTBOX, widgets::l, type, and widget.
Referenced by Append(), and DTS_C_API::dtsgui_listbox_set().
                                  {
    switch(type) {
        case DTS_WIDGET_COMBOBOX:
        case DTS_WIDGET_LISTBOX:
            break;
        default:
            return;
    }
    widget.l->SetSelection(i);
}
Member Data Documentation
union form_data form_item::data [private]
Definition at line 66 of file pitems.h.
Referenced by DTSPanel::ComboBox(), form_item(), GetData(), and GetXMLData().
enum form_data_type form_item::dtype [private]
Definition at line 68 of file pitems.h.
Referenced by form_item(), GetXMLData(), and DTSPanelEvent::OnCombo().
int form_item::idx [private]
Definition at line 65 of file pitems.h.
Referenced by Append(), and form_item().
const char* form_item::name [private]
Definition at line 64 of file pitems.h.
Referenced by AppendXML(), GetName(), network_tos(), DTSPanel::Panel2Post(), pbxconf_default(), and pbxconf_trunk().
enum widget_type form_item::type [private]
Definition at line 63 of file pitems.h.
Referenced by Append(), form_item(), GetValue(), and SetSelection().
const char* form_item::value [private]
Definition at line 69 of file pitems.h.
Referenced by Append(), AppendXML(), GetValue(), pbxconf_default(), pbxconf_trunk(), DTSPanel::XMLComboBox(), and DTSPanel::XMLListBox().
const char* form_item::value2 [private]
Definition at line 70 of file pitems.h.
Referenced by GetValue().
union widgets form_item::widget [private]
Definition at line 67 of file pitems.h.
Referenced by Append(), form_item(), GetValue(), GetWidget(), and SetSelection().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.