.TH "iface_cdata" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iface_cdata \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file interface\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* iface_cdata::name"

.PP
Definition at line 32 of file interface\&.c\&.
.PP
Referenced by free_iface_cdata(), get_iface_cdata(), handle_updatetabpane(), and network_iface_pane_cb()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
