.TH "app/interface.c" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/interface.c \- 
.PP
Interface configuration panel\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'private\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBnew_iface_data\fP"
.br
.RI "\fIStructure containing treeview and xmldoc for creating new tab\&. \fP"
.ti -1c
.RI "struct \fBiface_cdata\fP"
.br
.RI "\fIPretty pointless structure holding interface name\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBfree_iface_cdata\fP (void *data)"
.br
.RI "\fIRelase references held by structure before free\&. \fP"
.ti -1c
.RI "struct \fBiface_cdata\fP * \fBget_iface_cdata\fP (const char *val)"
.br
.RI "\fIAllocate new \fBiface_cdata\fP structure\&. \fP"
.ti -1c
.RI "void \fBfree_newiface_data\fP (void *data)"
.br
.RI "\fIRelease references held by structure before free\&. \fP"
.ti -1c
.RI "struct \fBnew_iface_data\fP * \fBget_newiface_data\fP (\fBdtsgui_tabview\fP tv, struct xml_doc *xmldoc)"
.br
.RI "\fIAllocate and return a \fBnew_iface_data\fP structure\&. \fP"
.ti -1c
.RI "void \fBhandle_newxmltabpane\fP (struct xml_doc *xmldoc, struct xml_node *xn, void *tdata, void **cdata, int *last)"
.br
.RI "\fIConfigure panel configuration data\&. \fP"
.ti -1c
.RI "int \fBhandle_updatetabpane\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, \fBdtsgui_pane\fP p, int type, int event, void *data)"
.br
.RI "\fIEvent handler callback that will only check the interface name and pass handling to default handler\&. \fP"
.ti -1c
.RI "void \fBnetwork_iface_pane_cb\fP (\fBdtsgui_pane\fP p, void *data)"
.br
.RI "\fICallback called to configure a interface pane\&. \fP"
.ti -1c
.RI "void \fBnetwork_iface_new_pane_cb\fP (\fBdtsgui_pane\fP p, void *data)"
.br
.RI "\fICallback called for the 'New' interface pane\&. \fP"
.ti -1c
.RI "\fBdtsgui_pane\fP \fBiface_config\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.RI "\fICallback called when the interface configuration link is selected\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Interface configuration panel\&. 


.PP
Definition in file \fBinterface\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
