.TH "listitem" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listitem \- 
.PP
Name value pair sturucture\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <private\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.RI "\fIName of the pair\&. \fP"
.ti -1c
.RI "const char * \fBvalue\fP"
.br
.RI "\fIValue of the pair\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Name value pair sturucture\&. 

This is used to create a static array to to populate listbox\&. 
.PP
Definition at line 89 of file private\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* listitem::name"

.PP
Name of the pair\&. 
.PP
Definition at line 91 of file private\&.h\&.
.PP
Referenced by wizz_exten()\&.
.SS "const char* listitem::value"

.PP
Value of the pair\&. 
.PP
Definition at line 93 of file private\&.h\&.
.PP
Referenced by wizz_exten()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
