app/netconfig.c
NAME
app/netconfig.c -
SYNOPSIS
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <limits.h>
#include 'dtsgui.h'
#include 'private.h'
Functions
void network_config_dns_domain_server_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void customer_info (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_config (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_config_dns (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_config_dns_dyn (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_config_dns_serv (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_config_dns_zone (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_config_dns_host (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_config_dns_host_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_config_dns_domain_node (dtsgui_treeview tv, dtsgui_treenode tn, struct xml_node *xn, void *data)
void network_config_dns_domain (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_config_dns_domain_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_config_dns_domain_server (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_iface_pane (dtsgui_pane p, const char *xpre, const char *iface)
void network_iface (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_iface_new_pane (dtsgui_pane p, void *data)
void network_newiface (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_wifi (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_newwifi (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_wan (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_newwan (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_route (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_newroute (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_modem (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_modem_adv (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_modem_ana (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_adsl_link (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_adsl_link_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_adsl_user (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_adsl_user_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_tos (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_tos_new (dtsgui_pane p, dtsgui_treeview self, dtsgui_treenode node, void *data)
void network_tree_setup (dtsgui_treeview tree, struct xml_doc *xmldoc)
dtsgui_pane advanced_config (struct dtsgui *dtsgui, const char *title, void *data)
Variables
static const char * protocols [] = {'TCP', 'UDP', 'GRE', 'ESP', 'AH', 'OSPF', 'ALL'}
Function Documentation
dtsgui_pane advanced_config (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 740 of file netconfig.c.
References app_getxmldoc(), app_data::datadir, dtsgui_alert(), dtsgui_treewindow(), dtsgui_userdata(), and network_tree_setup().
Referenced by config_menu().
void customer_info (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 32 of file netconfig.c.
References wizz_custinfo().
Referenced by network_tree_setup().
void network_adsl_link (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 446 of file netconfig.c.
References dtsgui_listbox_addxml(), dtsgui_panelxml(), dtsgui_treenodegetxml(), dtsgui_xmllistbox(), and dtsgui_xmltextbox().
Referenced by network_adsl_link_new(), and network_tree_setup().
void network_adsl_link_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 479 of file netconfig.c.
References DTS_NODE_NETWORK_ADSL_LINK, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_listbox(), dtsgui_listbox_addxml(), dtsgui_newxmltreenode(), dtsgui_panelxml(), dtsgui_textbox(), and network_adsl_link().
Referenced by network_tree_setup().
void network_adsl_user (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 504 of file netconfig.c.
References dtsgui_treenodegetxml(), and dtsgui_xmltextbox().
Referenced by network_adsl_user_new(), and network_tree_setup().
void network_adsl_user_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 513 of file netconfig.c.
References DTS_NODE_NETWORK_ADSL_USER, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), dtsgui_textbox(), and network_adsl_user().
Referenced by network_tree_setup().
void network_config (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 37 of file netconfig.c.
References dtsgui_item_value(), dtsgui_listbox_add(), dtsgui_listbox_addxml(), dtsgui_panelxml(), dtsgui_xmllistbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
void network_config_dns (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 76 of file netconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
void network_config_dns_domain (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 138 of file netconfig.c.
References dtsgui_treenodegetxml(), dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by network_config_dns_domain_new(), and network_tree_setup().
void network_config_dns_domain_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 151 of file netconfig.c.
References DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN, DTS_TREE_NEW_NODE_CONTAINER, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_checkbox(), dtsgui_newxmltreenode(), dtsgui_textbox(), network_config_dns_domain(), and network_config_dns_domain_node().
Referenced by network_tree_setup().
void network_config_dns_domain_node (dtsgui_treeviewtv, dtsgui_treenodetn, struct xml_node *xn, void *data)
Definition at line 134 of file netconfig.c.
References DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER_NEW, dtsgui_treecont(), and network_config_dns_domain_server_new().
Referenced by network_config_dns_domain_new().
void network_config_dns_domain_server (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 163 of file netconfig.c.
References dtsgui_treenodegetdata(), dtsgui_treenodegetxml(), and dtsgui_xmltextbox().
Referenced by network_config_dns_domain_server_new().
void network_config_dns_domain_server_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 177 of file netconfig.c.
References DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), dtsgui_textbox(), dtsgui_treenodeparent(), and network_config_dns_domain_server().
Referenced by network_config_dns_domain_node().
void network_config_dns_dyn (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 89 of file netconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
void network_config_dns_host (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 115 of file netconfig.c.
References dtsgui_treenodegetxml(), and dtsgui_xmltextbox().
Referenced by network_config_dns_host_new(), and network_tree_setup().
void network_config_dns_host_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 125 of file netconfig.c.
References DTS_NODE_NETWORK_CONFIG_DNS_HOST, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), dtsgui_textbox(), and network_config_dns_host().
Referenced by network_tree_setup().
void network_config_dns_serv (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 97 of file netconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
void network_config_dns_zone (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 107 of file netconfig.c.
References dtsgui_xmltextbox().
Referenced by network_tree_setup().
void network_iface (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 213 of file netconfig.c.
References dtsgui_treenodegetxml(), and network_iface_pane().
Referenced by network_newiface(), and network_tree_setup().
void network_iface_new_pane (dtsgui_panep, void *data)
Definition at line 222 of file netconfig.c.
References dtsgui_textbox().
Referenced by network_iface_new_pane_cb(), and network_newiface().
void network_iface_pane (dtsgui_panep, const char *xpre, const char *iface)
Definition at line 201 of file netconfig.c.
References dtsgui_xmltextbox().
Referenced by network_iface(), and network_iface_pane_cb().
void network_modem (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 372 of file netconfig.c.
References dtsgui_listbox_add(), dtsgui_xmllistbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
void network_modem_adv (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 390 of file netconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
void network_modem_ana (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 401 of file netconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), and dtsgui_xmltextbox().
Referenced by network_tree_setup().
void network_newiface (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 235 of file netconfig.c.
References DTS_NODE_NETWORK_IFACE, DTS_TREE_NEW_NODE_CONTAINER, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), network_iface(), and network_iface_new_pane().
Referenced by network_tree_setup().
void network_newroute (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 359 of file netconfig.c.
References DTS_NODE_NETWORK_ROUTE, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), dtsgui_textbox(), and network_route().
Referenced by network_tree_setup().
void network_newwan (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 333 of file netconfig.c.
References DTS_NODE_NETWORK_WAN, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_newxmltreenode(), dtsgui_textbox(), and network_wan().
Referenced by network_tree_setup().
void network_newwifi (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 277 of file netconfig.c.
References DTS_NODE_NETWORK_WIFI, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_SORT, dtsgui_listbox(), dtsgui_listbox_add(), dtsgui_listbox_addxml(), dtsgui_listbox_set(), dtsgui_newxmltreenode(), dtsgui_panelxml(), dtsgui_textbox(), and network_wifi().
Referenced by network_tree_setup().
void network_route (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 349 of file netconfig.c.
References dtsgui_treenodegetxml(), and dtsgui_xmltextbox().
Referenced by network_newroute(), and network_tree_setup().
void network_tos (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 524 of file netconfig.c.
References dtsgui_listbox_add(), dtsgui_treenodegetxml(), dtsgui_xmllistbox(), dtsgui_xmltextbox(), form_item::name, and protocols.
Referenced by network_tos_new(), and network_tree_setup().
void network_tos_new (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 565 of file netconfig.c.
References DTS_NODE_NETWORK_TOS, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, dtsgui_listbox(), dtsgui_listbox_add(), dtsgui_newxmltreenode(), dtsgui_textbox(), network_tos(), and protocols.
Referenced by network_tree_setup().
void network_tree_setup (dtsgui_treeviewtree, struct xml_doc *xmldoc)
Definition at line 602 of file netconfig.c.
References customer_info(), DTS_NODE_CUSTOMER, DTS_NODE_NETWORK_ADSL_LINK, DTS_NODE_NETWORK_ADSL_LINK_NEW, DTS_NODE_NETWORK_ADSL_USER, DTS_NODE_NETWORK_ADSL_USER_NEW, DTS_NODE_NETWORK_CONFIG, DTS_NODE_NETWORK_CONFIG_DNS, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_NEW, DTS_NODE_NETWORK_CONFIG_DNS_DYN, DTS_NODE_NETWORK_CONFIG_DNS_HOST, DTS_NODE_NETWORK_CONFIG_DNS_HOST_NEW, DTS_NODE_NETWORK_CONFIG_DNS_SERV, DTS_NODE_NETWORK_CONFIG_DNS_ZONE, DTS_NODE_NETWORK_IFACE, DTS_NODE_NETWORK_IFACE_NEW, DTS_NODE_NETWORK_MODEM, DTS_NODE_NETWORK_MODEM_ADV, DTS_NODE_NETWORK_MODEM_ANA, DTS_NODE_NETWORK_ROUTE_NEW, DTS_NODE_NETWORK_TOS, DTS_NODE_NETWORK_TOS_NEW, DTS_NODE_NETWORK_WAN, DTS_NODE_NETWORK_WAN_NEW, DTS_NODE_NETWORK_WIFI, DTS_NODE_NETWORK_WIFI_NEW, dtsgui_treecont(), dtsgui_treeitem(), dtsgui_treenodesetxml(), network_adsl_link(), network_adsl_link_new(), network_adsl_user(), network_adsl_user_new(), network_config(), network_config_dns(), network_config_dns_domain(), network_config_dns_domain_new(), network_config_dns_dyn(), network_config_dns_host(), network_config_dns_host_new(), network_config_dns_serv(), network_config_dns_zone(), network_iface(), network_modem(), network_modem_adv(), network_modem_ana(), network_newiface(), network_newroute(), network_newwan(), network_newwifi(), network_route(), network_tos(), network_tos_new(), network_wan(), and network_wifi().
Referenced by advanced_config().
void network_wan (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 320 of file netconfig.c.
References dtsgui_treenodegetxml(), and dtsgui_xmltextbox().
Referenced by network_newwan(), and network_tree_setup().
void network_wifi (dtsgui_panep, dtsgui_treeviewself, dtsgui_treenodenode, void *data)
Definition at line 245 of file netconfig.c.
References dtsgui_listbox_add(), dtsgui_treenodegetxml(), dtsgui_xmlcombobox(), and dtsgui_xmltextbox().
Referenced by network_newwifi(), and network_tree_setup().
Variable Documentation
const char* protocols[] = {'TCP', 'UDP', 'GRE', 'ESP', 'AH', 'OSPF', 'ALL'} [static]
Definition at line 30 of file netconfig.c.
Referenced by network_tos(), and network_tos_new().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.