.TH "app/netconfig.c" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/netconfig.c \- 
.PP
Advanced configuration panel\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'private\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBnetwork_config_dns_domain_server_new\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (New Hosted Domain Server) \fP"
.ti -1c
.RI "void \fBcustomer_info\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (Customer Info) \fP"
.ti -1c
.RI "void \fBnetwork_config\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (Network Configuration) \fP"
.ti -1c
.RI "void \fBnetwork_config_dns\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (DNS Configuration) \fP"
.ti -1c
.RI "void \fBnetwork_config_dns_dyn\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (Dynamic DNS) \fP"
.ti -1c
.RI "void \fBnetwork_config_dns_serv\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (DNS Server) \fP"
.ti -1c
.RI "void \fBnetwork_config_dns_zone\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (DNS Zone Defaults) \fP"
.ti -1c
.RI "void \fBnetwork_config_dns_host\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (DNS Hosts) \fP"
.ti -1c
.RI "void \fBnetwork_config_dns_host_new\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (New DNS Host) \fP"
.ti -1c
.RI "void \fBnetwork_config_dns_domain_node\fP (\fBdtsgui_treeview\fP tv, \fBdtsgui_treenode\fP tn, struct xml_node *xn, void *data)"
.br
.RI "\fIAdd a container for servers to newly added domain\&. \fP"
.ti -1c
.RI "void \fBnetwork_config_dns_domain\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (Hosted Domain) \fP"
.ti -1c
.RI "void \fBnetwork_config_dns_domain_new\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (New Hosted Domain) \fP"
.ti -1c
.RI "void \fBnetwork_config_dns_domain_server\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (Hosted Domain Server) \fP"
.ti -1c
.RI "void \fBnetwork_iface_pane\fP (\fBdtsgui_pane\fP p, const char *xpre, const char *iface)"
.br
.RI "\fINetwork interface stub shared with interface config\&. \fP"
.ti -1c
.RI "void \fBnetwork_iface\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (Network Interface) \fP"
.ti -1c
.RI "void \fBnetwork_iface_new_pane\fP (\fBdtsgui_pane\fP p)"
.br
.RI "\fINetwork interface stub shared with interface config\&. \fP"
.ti -1c
.RI "void \fBnetwork_newiface\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (New Network Interface) \fP"
.ti -1c
.RI "void \fBnetwork_wifi\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (WiFi Interface) \fP"
.ti -1c
.RI "void \fBnetwork_newwifi\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (New WiFi Interface) \fP"
.ti -1c
.RI "void \fBnetwork_wan\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (WAN Route) \fP"
.ti -1c
.RI "void \fBnetwork_newwan\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (New Wan Route) \fP"
.ti -1c
.RI "void \fBnetwork_route\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (Static Route) \fP"
.ti -1c
.RI "void \fBnetwork_newroute\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (New Static Route) \fP"
.ti -1c
.RI "void \fBnetwork_modem\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (Modem Config) \fP"
.ti -1c
.RI "void \fBnetwork_modem_adv\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (Advanced Modem Config) \fP"
.ti -1c
.RI "void \fBnetwork_modem_ana\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (Analogue Modem Config) \fP"
.ti -1c
.RI "void \fBnetwork_adsl_link\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (DSL Links) \fP"
.ti -1c
.RI "void \fBnetwork_adsl_link_new\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (New DSL Link) \fP"
.ti -1c
.RI "void \fBnetwork_adsl_user\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (DSL User) \fP"
.ti -1c
.RI "void \fBnetwork_adsl_user_new\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (New DSL User) \fP"
.ti -1c
.RI "void \fBnetwork_tos\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (TOS Config) \fP"
.ti -1c
.RI "void \fBnetwork_tos_new\fP (\fBdtsgui_pane\fP p, \fBdtsgui_treeview\fP self, \fBdtsgui_treenode\fP node, void *data)"
.br
.RI "\fITree pane configuration call back (New TOS Config) \fP"
.ti -1c
.RI "void \fBnetwork_tree_setup\fP (\fBdtsgui_treeview\fP tree, struct xml_doc *xmldoc)"
.br
.RI "\fIConfigure the networking noded on the tree\&. \fP"
.ti -1c
.RI "\fBdtsgui_pane\fP \fBadvanced_config\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.RI "\fIAdvanced configuration menu callback\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const char * \fBprotocols\fP [] = {'TCP', 'UDP', 'GRE', 'ESP', 'AH', 'OSPF', 'ALL'}"
.br
.RI "\fIArray of network protocols\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Advanced configuration panel\&. 


.PP
Definition in file \fBnetconfig\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
