.TH "new_iface_data" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
new_iface_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdtsgui_tabview\fP \fBtv\fP"
.br
.ti -1c
.RI "struct xml_doc * \fBxmldoc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file interface\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBdtsgui_tabview\fP new_iface_data::tv"

.PP
Definition at line 27 of file interface\&.c\&.
.PP
Referenced by get_newiface_data(), and network_iface_new_pane_cb()\&.
.SS "struct xml_doc* new_iface_data::xmldoc"

.PP
Definition at line 28 of file interface\&.c\&.
.PP
Referenced by free_newiface_data(), get_newiface_data(), and network_iface_new_pane_cb()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
