.TH "new_iface_data" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
new_iface_data \- 
.PP
Structure containing treeview and xmldoc for creating new tab\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdtsgui_tabview\fP \fBtv\fP"
.br
.RI "\fITabview to add new tab too\&. \fP"
.ti -1c
.RI "struct xml_doc * \fBxmldoc\fP"
.br
.RI "\fIXML Document to insert new node into\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Structure containing treeview and xmldoc for creating new tab\&. 
.PP
Definition at line 37 of file interface\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBdtsgui_tabview\fP new_iface_data::tv"

.PP
Tabview to add new tab too\&. 
.PP
Definition at line 39 of file interface\&.c\&.
.PP
Referenced by get_newiface_data(), and network_iface_new_pane_cb()\&.
.SS "struct xml_doc* new_iface_data::xmldoc"

.PP
XML Document to insert new node into\&. 
.PP
Definition at line 41 of file interface\&.c\&.
.PP
Referenced by free_newiface_data(), get_newiface_data(), and network_iface_new_pane_cb()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
