.TH "app/pbxconfig.c" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/pbxconfig.c \- 
.PP
PBX Configuration panel\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'private\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpbxconf_trunk\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for tunk panel\&. \fP"
.ti -1c
.RI "void \fBpbxconf_topts\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for trunk options panel\&. \fP"
.ti -1c
.RI "void \fBpbxconf_misdn\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for mISDN panel\&. \fP"
.ti -1c
.RI "void \fBpbxconf_e1\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for E1/T1 panel\&. \fP"
.ti -1c
.RI "void \fBpbxconf_mfcr2\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for MFC/R2 panel\&. \fP"
.ti -1c
.RI "void \fBpbxconf_global\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for global settings panel\&. \fP"
.ti -1c
.RI "void \fBpbxconf_acd\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for ACD options panel\&. \fP"
.ti -1c
.RI "void \fBpbxconf_default\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for extension default panel\&. \fP"
.ti -1c
.RI "void \fBpbxconf_location\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for location panel\&. \fP"
.ti -1c
.RI "void \fBpbxconf_incoming\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for incoming panel\&. \fP"
.ti -1c
.RI "void \fBpbxconf_numplan\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for number plan panel\&. \fP"
.ti -1c
.RI "void \fBpbxconf_autoadd\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.RI "\fIConfiguration callback for auto add panel\&. \fP"
.ti -1c
.RI "\fBdtsgui_pane\fP \fBpbx_settings\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.RI "\fIConfigure and return the PBX configuration tab view\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
PBX Configuration panel\&. 


.PP
Definition in file \fBpbxconfig\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
