.TH "app/pbxconfig.c" 3 "Thu Oct 10 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/pbxconfig.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'private\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpbxconf_trunk\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "void \fBpbxconf_topts\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "void \fBpbxconf_misdn\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "void \fBpbxconf_e1\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "void \fBpbxconf_mfcr2\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "void \fBpbxconf_global\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "void \fBpbxconf_acd\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "void \fBpbxconf_default\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "void \fBpbxconf_location\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "void \fBpbxconf_incoming\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "void \fBpbxconf_numplan\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "void \fBpbxconf_autoadd\fP (\fBdtsgui_pane\fP pg, void *data)"
.br
.ti -1c
.RI "\fBdtsgui_pane\fP \fBpbx_settings\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBdtsgui_pane\fP pbx_settings (struct \fBdtsgui\fP *dtsgui, const char *title, void *data)"

.PP
Definition at line 325 of file pbxconfig\&.c\&.
.PP
References app_getxmldoc(), dtsgui_newtabpage(), dtsgui_tabwindow(), pbxconf_acd(), pbxconf_autoadd(), pbxconf_default(), pbxconf_e1(), pbxconf_global(), pbxconf_incoming(), pbxconf_location(), pbxconf_mfcr2(), pbxconf_misdn(), pbxconf_numplan(), pbxconf_topts(), pbxconf_trunk(), and wx_PANEL_BUTTON_ACTION\&.
.PP
Referenced by config_menu()\&.
.SS "void pbxconf_acd (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 214 of file pbxconfig\&.c\&.
.PP
References dtsgui_xmltextbox()\&.
.PP
Referenced by pbx_settings()\&.
.SS "void pbxconf_autoadd (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 315 of file pbxconfig\&.c\&.
.PP
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox()\&.
.PP
Referenced by pbx_settings()\&.
.SS "void pbxconf_default (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 220 of file pbxconfig\&.c\&.
.PP
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), dtsgui_xmltextbox(), form_item::name, and form_item::value\&.
.PP
Referenced by pbx_settings()\&.
.SS "void pbxconf_e1 (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 134 of file pbxconfig\&.c\&.
.PP
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), and dtsgui_xmllistbox()\&.
.PP
Referenced by pbx_settings()\&.
.SS "void pbxconf_global (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 195 of file pbxconfig\&.c\&.
.PP
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), dtsgui_xmlpasswdbox(), and dtsgui_xmltextbox()\&.
.PP
Referenced by pbx_settings()\&.
.SS "void pbxconf_incoming (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 279 of file pbxconfig\&.c\&.
.PP
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), and dtsgui_xmllistbox()\&.
.PP
Referenced by pbx_settings()\&.
.SS "void pbxconf_location (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 268 of file pbxconfig\&.c\&.
.PP
References dtsgui_xmltextbox()\&.
.PP
Referenced by pbx_settings()\&.
.SS "void pbxconf_mfcr2 (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 161 of file pbxconfig\&.c\&.
.PP
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), and dtsgui_xmltextbox()\&.
.PP
Referenced by pbx_settings()\&.
.SS "void pbxconf_misdn (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 121 of file pbxconfig\&.c\&.
.PP
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox()\&.
.PP
Referenced by pbx_settings()\&.
.SS "void pbxconf_numplan (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 301 of file pbxconfig\&.c\&.
.PP
References dtsgui_xmltextbox()\&.
.PP
Referenced by pbx_settings()\&.
.SS "void pbxconf_topts (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 107 of file pbxconfig\&.c\&.
.PP
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox()\&.
.PP
Referenced by pbx_settings()\&.
.SS "void pbxconf_trunk (\fBdtsgui_pane\fPpg, void *data)"

.PP
Definition at line 25 of file pbxconfig\&.c\&.
.PP
References dtsgui_listbox_add(), dtsgui_xmllistbox(), dtsgui_xmltextbox(), form_item::name, and form_item::value\&.
.PP
Referenced by pbx_settings()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
