app/pbxconfig.c
NAME
app/pbxconfig.c -
SYNOPSIS
#include <unistd.h>
#include 'dtsgui.h'
#include 'private.h'
Functions
void pbxconf_trunk (dtsgui_pane pg, void *data)
void pbxconf_topts (dtsgui_pane pg, void *data)
void pbxconf_misdn (dtsgui_pane pg, void *data)
void pbxconf_e1 (dtsgui_pane pg, void *data)
void pbxconf_mfcr2 (dtsgui_pane pg, void *data)
void pbxconf_global (dtsgui_pane pg, void *data)
void pbxconf_acd (dtsgui_pane pg, void *data)
void pbxconf_default (dtsgui_pane pg, void *data)
void pbxconf_location (dtsgui_pane pg, void *data)
void pbxconf_incoming (dtsgui_pane pg, void *data)
void pbxconf_numplan (dtsgui_pane pg, void *data)
void pbxconf_autoadd (dtsgui_pane pg, void *data)
dtsgui_pane pbx_settings (struct dtsgui *dtsgui, const char *title, void *data)
Function Documentation
dtsgui_pane pbx_settings (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 325 of file pbxconfig.c.
References app_getxmldoc(), dtsgui_newtabpage(), dtsgui_tabwindow(), pbxconf_acd(), pbxconf_autoadd(), pbxconf_default(), pbxconf_e1(), pbxconf_global(), pbxconf_incoming(), pbxconf_location(), pbxconf_mfcr2(), pbxconf_misdn(), pbxconf_numplan(), pbxconf_topts(), pbxconf_trunk(), and wx_PANEL_BUTTON_ACTION.
Referenced by config_menu().
void pbxconf_acd (dtsgui_panepg, void *data)
Definition at line 214 of file pbxconfig.c.
References dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_autoadd (dtsgui_panepg, void *data)
Definition at line 315 of file pbxconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_default (dtsgui_panepg, void *data)
Definition at line 220 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), dtsgui_xmltextbox(), form_item::name, and form_item::value.
Referenced by pbx_settings().
void pbxconf_e1 (dtsgui_panepg, void *data)
Definition at line 134 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), and dtsgui_xmllistbox().
Referenced by pbx_settings().
void pbxconf_global (dtsgui_panepg, void *data)
Definition at line 195 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), dtsgui_xmlpasswdbox(), and dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_incoming (dtsgui_panepg, void *data)
Definition at line 279 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), and dtsgui_xmllistbox().
Referenced by pbx_settings().
void pbxconf_location (dtsgui_panepg, void *data)
Definition at line 268 of file pbxconfig.c.
References dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_mfcr2 (dtsgui_panepg, void *data)
Definition at line 161 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmlcheckbox(), dtsgui_xmllistbox(), and dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_misdn (dtsgui_panepg, void *data)
Definition at line 121 of file pbxconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_numplan (dtsgui_panepg, void *data)
Definition at line 301 of file pbxconfig.c.
References dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_topts (dtsgui_panepg, void *data)
Definition at line 107 of file pbxconfig.c.
References dtsgui_xmlcheckbox(), and dtsgui_xmltextbox().
Referenced by pbx_settings().
void pbxconf_trunk (dtsgui_panepg, void *data)
Definition at line 25 of file pbxconfig.c.
References dtsgui_listbox_add(), dtsgui_xmllistbox(), dtsgui_xmltextbox(), form_item::name, and form_item::value.
Referenced by pbx_settings().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.