.TH "src/pitems.cpp" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/pitems.cpp \- 
.PP
Implementation of Panel Items\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <wx/combobox\&.h>\fP
.br
\fC#include <wx/checkbox\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'pitems\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Implementation of Panel Items\&. 


.PP
Definition in file \fBpitems\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
