.TH "src/include/pitems.h" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include/pitems.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBxml_element\fP"
.br
.ti -1c
.RI "union \fBform_data\fP"
.br
.ti -1c
.RI "union \fBwidgets\fP"
.br
.ti -1c
.RI "class \fBform_item\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef class \fBwxComboBox\fP \fBwxComboBox\fP"
.br
.ti -1c
.RI "typedef class \fBwxCheckBox\fP \fBwxCheckBox\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef class \fBwxCheckBox\fP \fBwxCheckBox\fP"

.PP
Definition at line 24 of file pitems\&.h\&.
.SS "typedef class \fBwxComboBox\fP \fBwxComboBox\fP"

.PP
Definition at line 23 of file pitems\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
