.TH "point" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
point \- 
.PP
A simple data structure to store a coordinate\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dtsgui\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.RI "\fIX axis\&. \fP"
.ti -1c
.RI "int \fBy\fP"
.br
.RI "\fIY axis\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A simple data structure to store a coordinate\&. 
.PP
Definition at line 181 of file dtsgui\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int point::x"

.PP
X axis\&. 
.PP
Definition at line 183 of file dtsgui\&.h\&.
.PP
Referenced by dtsgui::SetupAPPFrame()\&.
.SS "int point::y"

.PP
Y axis\&. 
.PP
Definition at line 185 of file dtsgui\&.h\&.
.PP
Referenced by dtsgui::SetupAPPFrame()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
