app/private.h
NAME
app/private.h -
SYNOPSIS
Classes
struct app_data
struct listitem
Macros
#define DATA_DIR '/usr/share/dtsguiapp'
Enumerations
enum node_id { DTS_NODE_CUSTOMER, DTS_NODE_NETWORK_CONFIG, DTS_NODE_NETWORK_CONFIG_DNS, DTS_NODE_NETWORK_CONFIG_DNS_DYN, DTS_NODE_NETWORK_CONFIG_DNS_SERV, DTS_NODE_NETWORK_CONFIG_DNS_ZONE, DTS_NODE_NETWORK_CONFIG_DNS_HOST_NEW, DTS_NODE_NETWORK_CONFIG_DNS_HOST, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_NEW, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER_NEW, DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER, DTS_NODE_NETWORK_IFACE_NEW, DTS_NODE_NETWORK_IFACE, DTS_NODE_NETWORK_WIFI_NEW, DTS_NODE_NETWORK_WIFI, DTS_NODE_NETWORK_WAN_NEW, DTS_NODE_NETWORK_WAN, DTS_NODE_NETWORK_ROUTE_NEW, DTS_NODE_NETWORK_ROUTE, DTS_NODE_NETWORK_MODEM, DTS_NODE_NETWORK_MODEM_ADV, DTS_NODE_NETWORK_MODEM_ANA, DTS_NODE_NETWORK_ADSL_LINK_NEW, DTS_NODE_NETWORK_ADSL_LINK, DTS_NODE_NETWORK_ADSL_USER_NEW, DTS_NODE_NETWORK_ADSL_USER, DTS_NODE_NETWORK_TOS_NEW, DTS_NODE_NETWORK_TOS }
Functions
struct xml_doc * app_getxmldoc (struct dtsgui *dtsgui)
void * app_toolbar (struct dtsgui *dtsgui, void *pw, long style, int id, const char *name, void *data)
dtsgui_pane reconfig_wizard (struct dtsgui *dtsgui, const char *title, void *data)
dtsgui_pane editsys_wizard (struct dtsgui *dtsgui, const char *title, void *data)
dtsgui_pane newsys_wizard (struct dtsgui *dtsgui, const char *title, void *data)
void wizz_custinfo (dtsgui_pane *pg)
dtsgui_pane pbx_settings (struct dtsgui *dtsgui, const char *title, void *data)
void test_menu (struct dtsgui *dtsgui, dtsgui_menu menu, const char *url)
dtsgui_pane advanced_config (struct dtsgui *dtsgui, const char *title, void *data)
void network_iface_pane (dtsgui_pane p, const char *xpre, const char *iface)
void network_iface_new_pane (dtsgui_pane p, void *data)
dtsgui_pane iface_config (struct dtsgui *dtsgui, const char *title, void *data)
dtsgui_pane open_config (struct dtsgui *dtsgui, const char *title, void *data)
dtsgui_pane save_config (struct dtsgui *dtsgui, const char *title, void *data)
dtsgui_pane export_config (struct dtsgui *dtsgui, const char *title, void *data)
dtsgui_pane view_config_conf (struct dtsgui *dtsgui, const char *title, void *data)
dtsgui_pane view_config_xml (struct dtsgui *dtsgui, const char *title, void *data)
void config_menu (struct dtsgui *dtsgui)
Macro Definition Documentation
#define DATA_DIR '/usr/share/dtsguiapp'
Definition at line 24 of file private.h.
Referenced by main().
Enumeration Type Documentation
enum node_id
Enumerator:
DTS_NODE_CUSTOMER
DTS_NODE_NETWORK_CONFIG
DTS_NODE_NETWORK_CONFIG_DNS
DTS_NODE_NETWORK_CONFIG_DNS_DYN
DTS_NODE_NETWORK_CONFIG_DNS_SERV
DTS_NODE_NETWORK_CONFIG_DNS_ZONE
DTS_NODE_NETWORK_CONFIG_DNS_HOST_NEW
DTS_NODE_NETWORK_CONFIG_DNS_HOST
DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_NEW
DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN
DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER_NEW
DTS_NODE_NETWORK_CONFIG_DNS_DOMAIN_SERVER
DTS_NODE_NETWORK_IFACE_NEW
DTS_NODE_NETWORK_IFACE
DTS_NODE_NETWORK_WIFI_NEW
DTS_NODE_NETWORK_WIFI
DTS_NODE_NETWORK_WAN_NEW
DTS_NODE_NETWORK_WAN
DTS_NODE_NETWORK_ROUTE_NEW
DTS_NODE_NETWORK_ROUTE
DTS_NODE_NETWORK_MODEM
DTS_NODE_NETWORK_MODEM_ADV
DTS_NODE_NETWORK_MODEM_ANA
DTS_NODE_NETWORK_ADSL_LINK_NEW
DTS_NODE_NETWORK_ADSL_LINK
DTS_NODE_NETWORK_ADSL_USER_NEW
DTS_NODE_NETWORK_ADSL_USER
DTS_NODE_NETWORK_TOS_NEW
DTS_NODE_NETWORK_TOS
Definition at line 27 of file private.h.
Function Documentation
dtsgui_pane advanced_config (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 740 of file netconfig.c.
References app_getxmldoc(), app_data::datadir, dtsgui_alert(), dtsgui_treewindow(), dtsgui_userdata(), and network_tree_setup().
Referenced by config_menu().
void* app_toolbar (struct dtsgui *dtsgui, void *pw, longstyle, intid, const char *name, void *data)
Definition at line 111 of file toolbar.cpp.
Referenced by guiconfig_cb().
void config_menu (struct dtsgui *dtsgui)
Definition at line 189 of file config.c.
References advanced_config(), app_data::cfg_menu, dtsgui_menuenable(), dtsgui_menusep(), dtsgui_newmenu(), dtsgui_newmenucb(), dtsgui_userdata(), export_config(), iface_config(), pbx_settings(), reconfig_wizard(), save_config(), view_config_conf(), and view_config_xml().
Referenced by guiconfig_cb().
dtsgui_pane export_config (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 150 of file config.c.
References app_getxmldoc(), app_data::datadir, dtsgui_alert(), dtsgui_filesave(), and dtsgui_userdata().
Referenced by config_menu().
dtsgui_pane iface_config (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 145 of file interface.c.
References app_getxmldoc(), dtsgui_newtabpage(), dtsgui_tabwindow(), get_iface_cdata(), get_newiface_data(), network_iface_new_pane_cb(), network_iface_pane_cb(), and wx_PANEL_BUTTON_ACTION.
Referenced by config_menu().
void network_iface_new_pane (dtsgui_panep, void *data)
Definition at line 222 of file netconfig.c.
References dtsgui_textbox().
Referenced by network_iface_new_pane_cb(), and network_newiface().
void network_iface_pane (dtsgui_panep, const char *xpre, const char *iface)
Definition at line 201 of file netconfig.c.
References dtsgui_xmltextbox().
Referenced by network_iface(), and network_iface_pane_cb().
dtsgui_pane open_config (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 27 of file config.c.
References app_data::c_open, app_data::cfg_menu, dtsgui_alert(), dtsgui_fileopen(), dtsgui_menuenable(), dtsgui_menuitemenable(), dtsgui_sendevent(), dtsgui_set_toolbar(), dtsgui_titleappend(), dtsgui_userdata(), app_data::e_wiz, app_data::n_wiz, and app_data::xmldoc.
Referenced by file_menu().
dtsgui_pane pbx_settings (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 325 of file pbxconfig.c.
References app_getxmldoc(), dtsgui_newtabpage(), dtsgui_tabwindow(), pbxconf_acd(), pbxconf_autoadd(), pbxconf_default(), pbxconf_e1(), pbxconf_global(), pbxconf_incoming(), pbxconf_location(), pbxconf_mfcr2(), pbxconf_misdn(), pbxconf_numplan(), pbxconf_topts(), pbxconf_trunk(), and wx_PANEL_BUTTON_ACTION.
Referenced by config_menu().
dtsgui_pane save_config (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 69 of file config.c.
References app_data::c_open, app_data::cfg_menu, dtsgui_menuenable(), dtsgui_menuitemenable(), dtsgui_set_toolbar(), dtsgui_titleappend(), dtsgui_userdata(), app_data::e_wiz, app_data::n_wiz, and app_data::xmldoc.
Referenced by config_menu().
void test_menu (struct dtsgui *dtsgui, dtsgui_menumenu, const char *url)
Definition at line 94 of file testing.c.
References dtsgui_newmenuitem(), dtsgui_panel(), dtsgui_setevcallback(), handle_test(), testpanel(), and wx_PANEL_BUTTON_ALL.
Referenced by help_menu().
dtsgui_pane view_config_conf (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 112 of file config.c.
References app_getxmldoc(), app_data::datadir, dtsgui_alert(), dtsgui_textpane(), and dtsgui_userdata().
Referenced by config_menu().
dtsgui_pane view_config_xml (struct dtsgui *dtsgui, const char *title, void *data)
Definition at line 94 of file config.c.
References app_getxmldoc(), and dtsgui_textpane().
Referenced by config_menu().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.