app/testing.c
NAME
app/testing.c -
SYNOPSIS
#include <unistd.h>
#include 'dtsgui.h'
#include 'private.h'
Functions
void post_items (struct dtsgui *dtsgui, dtsgui_pane p)
int handle_test (struct dtsgui *dtsgui, dtsgui_pane p, int type, int event, void *data)
void testpanel (dtsgui_pane p)
void test_menu (struct dtsgui *dtsgui, dtsgui_menu menu, const char *url)
Function Documentation
int handle_test (struct dtsgui *dtsgui, dtsgui_panep, inttype, intevent, void *data)
Definition at line 44 of file testing.c.
References dtsgui_alert(), post_items(), wx_PANEL_EVENT_BUTTON, wx_PANEL_EVENT_BUTTON_BACK, wx_PANEL_EVENT_BUTTON_FIRST, wx_PANEL_EVENT_BUTTON_FWD, wx_PANEL_EVENT_BUTTON_LAST, wx_PANEL_EVENT_BUTTON_NO, and wx_PANEL_EVENT_BUTTON_YES.
Referenced by test_menu().
void post_items (struct dtsgui *dtsgui, dtsgui_panep)
Definition at line 25 of file testing.c.
References dtsgui_alert(), dtsgui_pane2post(), and dtsgui_paneldata().
Referenced by handle_test().
void test_menu (struct dtsgui *dtsgui, dtsgui_menumenu, const char *url)
Definition at line 94 of file testing.c.
References dtsgui_newmenuitem(), dtsgui_panel(), dtsgui_setevcallback(), handle_test(), testpanel(), and wx_PANEL_BUTTON_ALL.
Referenced by help_menu().
void testpanel (dtsgui_panep)
Definition at line 72 of file testing.c.
References dtsgui_checkbox(), dtsgui_combobox(), dtsgui_listbox(), dtsgui_listbox_add(), dtsgui_textbox(), and dtsgui_textbox_multi().
Referenced by test_menu().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.