.TH "app/testing.c" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/testing.c \- 
.PP
Test panel\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'private\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpost_items\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, \fBdtsgui_pane\fP p)"
.br
.RI "\fICreate a curl post object and submit to url\&. \fP"
.ti -1c
.RI "int \fBhandle_test\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, \fBdtsgui_pane\fP p, int type, int event, void *data)"
.br
.RI "\fIpanel event handler\&. \fP"
.ti -1c
.RI "void \fBtestpanel\fP (\fBdtsgui_pane\fP p)"
.br
.RI "\fIConfigure a panel with test elements\&. \fP"
.ti -1c
.RI "void \fBtest_menu\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, \fBdtsgui_menu\fP menu, const char *url)"
.br
.RI "\fIAdd test option to menu\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Test panel\&. 


.PP
Definition in file \fBtesting\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
