.TH "app/testing.c" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/testing.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'private\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBpost_items\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, \fBdtsgui_pane\fP p)"
.br
.ti -1c
.RI "int \fBhandle_test\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, \fBdtsgui_pane\fP p, int type, int event, void *data)"
.br
.ti -1c
.RI "void \fBtestpanel\fP (\fBdtsgui_pane\fP p)"
.br
.ti -1c
.RI "void \fBtest_menu\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, \fBdtsgui_menu\fP menu, const char *url)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int handle_test (struct \fBdtsgui\fP *dtsgui, \fBdtsgui_pane\fPp, inttype, intevent, void *data)"

.PP
Definition at line 44 of file testing\&.c\&.
.SS "void post_items (struct \fBdtsgui\fP *dtsgui, \fBdtsgui_pane\fPp)"

.PP
Definition at line 25 of file testing\&.c\&.
.SS "void test_menu (struct \fBdtsgui\fP *dtsgui, \fBdtsgui_menu\fPmenu, const char *url)"

.PP
Definition at line 94 of file testing\&.c\&.
.SS "void testpanel (\fBdtsgui_pane\fPp)"

.PP
Definition at line 72 of file testing\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
