.TH "todo" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.IP "\fBGroup \fBC-API-Menus\fP \fP" 1c
Define and implement Exit/Quit events  
.IP "\fBGroup \fBC-API-Panel\fP \fP" 1c
Emit and allow panels to manage a event when a new panel is requested to allow saving the displayed panel\&.  
.IP "\fBGroup \fBC-API-Panel-Elements\fP \fP" 1c
Add a JSON API  
.IP "\fBGroup \fBC-API-Panel-Elements-XML\fP \fP" 1c
Adding functions to work from a search path will be better than the current interface that alloacates a new search for each element\&.  
.IP "\fBGroup \fBC-API-Panel-Tab\fP \fP" 1c
Implement a right click action to allow for deletion via a confirmation dialog\&.  
.IP "\fBGroup \fBC-API-Panel-Tree\fP \fP" 1c
Allow for the deletion of branch/container/folder nodes\&.  
.IP "\fBGroup \fBC-API-Progress\fP \fP" 1c
Allow multiple instances of progress dialog not only the single interface at present\&.  
.IP "\fBGroup \fBC-API-Wizard\fP \fP" 1c
Add a hashed list to the wizard class storing the panels to no longer need to keep a array of panels\&. 
.PP

