.TH "app/toolbar.cpp" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/toolbar.cpp \- 
.PP
Application toolbar\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <wx/toolbar\&.h>\fP
.br
\fC#include <wx/combobox\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'private\&.h'\fP
.br
\fC#include 'DTSXMLComboBox\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDTSAPPToolBar\fP"
.br
.RI "\fIApplication toolbar class\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__DTS_C_API\fP"
.br
.RI "\fIAllow access to the C API from C++\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBapp_toolbar\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, void *pw, long style, int id, const char *name, void *data)"
.br
.RI "\fICallback called when the toolbar is to be created\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Application toolbar\&. 


.PP
Definition in file \fBtoolbar\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
