.TH "app/toolbar.cpp" 3 "Wed Oct 9 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/toolbar.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <wx/toolbar\&.h>\fP
.br
\fC#include <wx/combobox\&.h>\fP
.br
\fC#include <wx/stattext\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'private\&.h'\fP
.br
\fC#include 'DTSXMLComboBox\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDTSAPPToolBar\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__DTS_C_API\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBapp_toolbar\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, void *pw, long style, int id, const char *name, void *data)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __DTS_C_API"

.PP
Definition at line 19 of file toolbar\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "void* app_toolbar (struct \fBdtsgui\fP *dtsgui, void *pw, longstyle, intid, const char *name, void *data)"

.PP
Definition at line 111 of file toolbar\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
