tree_newnode
NAME
tree_newnode -
SYNOPSIS
#include <DTSTreeWindow.h>
Public Member Functions
DTS_OJBREF_CLASS (tree_newnode)
tree_newnode (dtsgui_treeview tree, dtsgui_treenode tn, const char *xpath, const char *node, const char *vitem, const char *tattr, int nid, int flags, dtsgui_xmltreenode_cb node_cb, void *data, dtsgui_treeviewpanel_cb p_cb)
Static Public Member Functions
static int handle_newtreenode_cb (class dtsgui *dtsgui, dtsgui_pane p, int type, int event, void *data)
Private Member Functions
int handle_newtreenode (class dtsgui *dtsgui, DTSPanel *dp)
Private Attributes
void * data
dtsgui_treeview tv
dtsgui_treenode tn
dtsgui_xmltreenode_cb node_cb
dtsgui_treeviewpanel_cb p_cb
const char * xpath
const char * node
const char * vitem
const char * tattr
int type
int flags
Detailed Description
Definition at line 33 of file DTSTreeWindow.h.
Constructor & Destructor Documentation
tree_newnode::tree_newnode (dtsgui_treeviewtree, dtsgui_treenodetn, const char *xpath, const char *node, const char *vitem, const char *tattr, intnid, intflags, dtsgui_xmltreenode_cbnode_cb, void *data, dtsgui_treeviewpanel_cbp_cb)
Definition at line 52 of file DTSTreeWindow.cpp.
References data, flags, node_cb, p_cb, tn, tv, and type.
Referenced by DTS_C_API::dtsgui_newxmltreenode().
Member Function Documentation
tree_newnode::DTS_OJBREF_CLASS (tree_newnode)
int tree_newnode::handle_newtreenode (class dtsgui *dtsgui, DTSPanel *dp) [private]
Definition at line 89 of file DTSTreeWindow.cpp.
References DTSDVMCtrl::AppendContainer(), DTSDVMCtrl::AppendItem(), data, DTS_TREE_NEW_NODE_CONTAINER, DTS_TREE_NEW_NODE_DELETE, DTS_TREE_NEW_NODE_EDIT, DTS_TREE_NEW_NODE_SORT, flags, DTSTreeWindow::GetTreeCtrl(), node, node_cb, p_cb, DTSPanel::Panel2XML(), DTSTreeWindow::Select(), DTSDVMListStore::SetXMLData(), tattr, tn, tv, type, vitem, and xpath.
Referenced by handle_newtreenode_cb().
int tree_newnode::handle_newtreenode_cb (class dtsgui *dtsgui, dtsgui_panep, inttype, intevent, void *data) [static]
Definition at line 71 of file DTSTreeWindow.cpp.
References handle_newtreenode(), wx_PANEL_EVENT_BUTTON, and wx_PANEL_EVENT_BUTTON_YES.
Referenced by DTS_C_API::dtsgui_newxmltreenode().
Member Data Documentation
void* tree_newnode::data [private]
Definition at line 41 of file DTSTreeWindow.h.
Referenced by handle_newtreenode(), and tree_newnode().
int tree_newnode::flags [private]
Definition at line 51 of file DTSTreeWindow.h.
Referenced by handle_newtreenode(), and tree_newnode().
const char* tree_newnode::node [private]
Definition at line 47 of file DTSTreeWindow.h.
Referenced by handle_newtreenode().
dtsgui_xmltreenode_cb tree_newnode::node_cb [private]
Definition at line 44 of file DTSTreeWindow.h.
Referenced by handle_newtreenode(), and tree_newnode().
dtsgui_treeviewpanel_cb tree_newnode::p_cb [private]
Definition at line 45 of file DTSTreeWindow.h.
Referenced by handle_newtreenode(), and tree_newnode().
const char* tree_newnode::tattr [private]
Definition at line 49 of file DTSTreeWindow.h.
Referenced by handle_newtreenode().
dtsgui_treenode tree_newnode::tn [private]
Definition at line 43 of file DTSTreeWindow.h.
Referenced by handle_newtreenode(), and tree_newnode().
dtsgui_treeview tree_newnode::tv [private]
Definition at line 42 of file DTSTreeWindow.h.
Referenced by handle_newtreenode(), and tree_newnode().
int tree_newnode::type [private]
Definition at line 50 of file DTSTreeWindow.h.
Referenced by handle_newtreenode(), and tree_newnode().
const char* tree_newnode::vitem [private]
Definition at line 48 of file DTSTreeWindow.h.
Referenced by handle_newtreenode().
const char* tree_newnode::xpath [private]
Definition at line 46 of file DTSTreeWindow.h.
Referenced by handle_newtreenode().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.