.TH "widgets" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
widgets \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pitems\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wxTextCtrl * \fBt\fP"
.br
.ti -1c
.RI "\fBwxComboBox\fP * \fBl\fP"
.br
.ti -1c
.RI "\fBwxCheckBox\fP * \fBc\fP"
.br
.ti -1c
.RI "void * \fBp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file pitems\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBwxCheckBox\fP* widgets::c"

.PP
Definition at line 46 of file pitems\&.h\&.
.PP
Referenced by form_item::GetValue()\&.
.SS "\fBwxComboBox\fP* widgets::l"

.PP
Definition at line 45 of file pitems\&.h\&.
.PP
Referenced by form_item::Append(), form_item::GetValue(), and form_item::SetSelection()\&.
.SS "void* widgets::p"

.PP
Definition at line 47 of file pitems\&.h\&.
.PP
Referenced by form_item::GetWidget()\&.
.SS "wxTextCtrl* widgets::t"

.PP
Definition at line 44 of file pitems\&.h\&.
.PP
Referenced by form_item::GetValue()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
