.TH "app/wizard.c" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/wizard.c \- 
.PP
Wizard Interface\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'private\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBset_temp_xml\fP (struct xml_doc *xmldoc)"
.br
.ti -1c
.RI "static void \fBrem_temp_xml\fP (struct xml_doc *xmldoc)"
.br
.ti -1c
.RI "void \fBwizz_custinfo\fP (\fBdtsgui_pane\fP *pg)"
.br
.ti -1c
.RI "void \fBwizz_netinfo\fP (\fBdtsgui_pane\fP pg)"
.br
.ti -1c
.RI "void \fBwizz_dyndns\fP (\fBdtsgui_pane\fP pg)"
.br
.ti -1c
.RI "void \fBwizz_dnsinfo\fP (\fBdtsgui_pane\fP pg)"
.br
.ti -1c
.RI "void \fBwizz_x509\fP (\fBdtsgui_pane\fP pg)"
.br
.ti -1c
.RI "void \fBwizz_samba\fP (\fBdtsgui_pane\fP pg)"
.br
.ti -1c
.RI "void \fBwizz_network\fP (\fBdtsgui_pane\fP pg)"
.br
.ti -1c
.RI "void \fBwizz_exten\fP (\fBdtsgui_pane\fP pg)"
.br
.ti -1c
.RI "void \fBwizz_location\fP (\fBdtsgui_pane\fP pg)"
.br
.ti -1c
.RI "void \fBwizz_acd\fP (\fBdtsgui_pane\fP pg)"
.br
.ti -1c
.RI "void \fBwizz_trunk\fP (\fBdtsgui_pane\fP pg)"
.br
.ti -1c
.RI "void \fBwizz_voip\fP (\fBdtsgui_pane\fP pg)"
.br
.ti -1c
.RI "static int \fBsystem_wizard\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, void *data, const char *filename, struct xml_doc *xmldoc, int save)"
.br
.ti -1c
.RI "\fBdtsgui_pane\fP \fBnewsys_wizard\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.ti -1c
.RI "\fBdtsgui_pane\fP \fBeditsys_wizard\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.ti -1c
.RI "\fBdtsgui_pane\fP \fBreconfig_wizard\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, const char *title, void *data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wizard Interface\&. 


.PP
Definition in file \fBwizard\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
