.TH "app/wxforms.c" 3 "Fri Oct 11 2013" "Version 0.00" "DTS Application wxWidgets GUI Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/wxforms.c \- 
.PP
Main application file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include 'dtsgui\&.h'\fP
.br
\fC#include 'private\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBxml_config\fP (struct xml_doc *xmldoc)"
.br
.ti -1c
.RI "struct xml_doc * \fBapp_getxmldoc\fP (struct \fBdtsgui\fP *\fBdtsgui\fP)"
.br
.ti -1c
.RI "void \fBfile_menu\fP (struct \fBdtsgui\fP *\fBdtsgui\fP)"
.br
.ti -1c
.RI "void \fBhelp_menu\fP (struct \fBdtsgui\fP *\fBdtsgui\fP)"
.br
.ti -1c
.RI "int \fBguiconfig_cb\fP (struct \fBdtsgui\fP *\fBdtsgui\fP, void *data)"
.br
.ti -1c
.RI "void \fBfree_appdata\fP (void *data)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main application file\&. 


.PP
Definition in file \fBwxforms\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code\&.
