xml_element
NAME
xml_element -
SYNOPSIS
#include <pitems.h>
Public Member Functions
DTS_OJBREF_CLASS (xml_element)
xml_element (const char *xp, struct xml_search *xs, const char *xa)
void Modify (struct xml_doc *xmldoc, const char *value)
const char * GetValue ()
Private Attributes
struct xml_search * xsearch
const char * xpath
const char * attr
Detailed Description
Definition at line 26 of file pitems.h.
Constructor & Destructor Documentation
xml_element::xml_element (const char *xp, struct xml_search *xs, const char *xa)
Definition at line 38 of file pitems.cpp.
References attr, xpath, and xsearch.
Member Function Documentation
xml_element::DTS_OJBREF_CLASS (xml_element)
const char * xml_element::GetValue ()
Definition at line 59 of file pitems.cpp.
References attr, and xsearch.
Referenced by DTSPanel::XMLCheckBox(), DTSPanel::XMLComboBox(), DTSPanel::XMLListBox(), and DTSPanel::XMLTextBox().
void xml_element::Modify (struct xml_doc *xmldoc, const char *value)
Definition at line 46 of file pitems.cpp.
References attr, and xsearch.
Referenced by DTSPanel::Update_XML().
Member Data Documentation
const char* xml_element::attr [private]
Definition at line 35 of file pitems.h.
Referenced by GetValue(), Modify(), and xml_element().
const char* xml_element::xpath [private]
Definition at line 34 of file pitems.h.
Referenced by xml_element().
struct xml_search* xml_element::xsearch [private]
Definition at line 33 of file pitems.h.
Referenced by GetValue(), Modify(), and xml_element().
Author
Generated automatically by Doxygen for DTS Application wxWidgets GUI Library from the source code.